### ISSUE TITLE
fastlane - undefined method `upload_edit_apk'

### ISSUE THREAD

**Issue by francisfernando** [fastlane/fastlane#10116]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[06:38:08]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[06:38:10]: -------------------------------------------------
[06:38:10]: --- Step: Verifying required fastlane version ---
[06:38:10]: -------------------------------------------------
[06:38:10]: Your fastlane version 2.54.0 matches the minimum requirement of 2.38.1  ✅
[06:38:10]: ------------------------------
[06:38:10]: --- Step: default_platform ---
[06:38:10]: ------------------------------
[06:38:10]: Driving the lane 'android alpha' 🚀
[06:38:10]: --------------------
[06:38:10]: --- Step: gradle ---
[06:38:10]: --------------------
[06:38:10]: $ /home/ubuntu/hrfid-thermistor/gradlew assembleRelease -p .
[06:38:12]: ▸ google-services plugin could not detect any version for com.google.android.gms or com.google.firebase, default version: 9.0.0 will be used.
[06:38:12]: ▸ please apply google-services plugin at the bottom of the build file.
[06:38:12]: ▸ Incremental java compilation is an incubating feature.
[06:38:13]: ▸ :app:preBuild UP-TO-DATE
[06:38:13]: ▸ :app:preReleaseBuild UP-TO-DATE
[06:38:13]: ▸ :app:checkReleaseManifest
[06:38:13]: ▸ :app:preDebugBuild UP-TO-DATE
[06:38:13]: ▸ :app:prepareComAndroidSupportAnimatedVectorDrawable2500Library
[06:38:13]: ▸ :app:prepareComAndroidSupportAppcompatV72500Library
[06:38:13]: ▸ :app:prepareComAndroidSupportConstraintConstraintLayout100Alpha4Library
[06:38:13]: ▸ :app:prepareComAndroidSupportDesign2500Library
[06:38:13]: ▸ :app:prepareComAndroidSupportRecyclerviewV72500Library
[06:38:13]: ▸ :app:prepareComAndroidSupportSupportCompat2500Library
[06:38:13]: ▸ :app:prepareComAndroidSupportSupportCoreUi2500Library
[06:38:13]: ▸ :app:prepareComAndroidSupportSupportCoreUtils2500Library
[06:38:13]: ▸ :app:prepareComAndroidSupportSupportFragment2500Library
[06:38:13]: ▸ :app:prepareComAndroidSupportSupportMediaCompat2500Library
[06:38:13]: ▸ :app:prepareComAndroidSupportSupportV42500Library
[06:38:13]: ▸ :app:prepareComAndroidSupportSupportVectorDrawable2500Library
[06:38:13]: ▸ :app:prepareComAndroidSupportTransition2500Library
[06:38:13]: ▸ :app:prepareComCrashlyticsSdkAndroidAnswers1313Library
[06:38:13]: ▸ :app:prepareComCrashlyticsSdkAndroidBeta125Library
[06:38:13]: ▸ :app:prepareComCrashlyticsSdkAndroidCrashlytics268Library
[06:38:13]: ▸ :app:prepareComCrashlyticsSdkAndroidCrashlyticsCore2317Library
[06:38:13]: ▸ :app:prepareComGoogleAndroidGmsPlayServicesBasement1001Library
[06:38:13]: ▸ :app:prepareComGoogleAndroidGmsPlayServicesTasks1001Library
[06:38:13]: ▸ :app:prepareComGoogleFirebaseFirebaseAnalytics1001Library
[06:38:13]: ▸ :app:prepareComGoogleFirebaseFirebaseAnalyticsImpl1001Library
[06:38:14]: ▸ :app:prepareComGoogleFirebaseFirebaseCommon1001Library
[06:38:14]: ▸ :app:prepareComGoogleFirebaseFirebaseCore1001Library
[06:38:14]: ▸ :app:prepareComGoogleFirebaseFirebaseIid1001Library
[06:38:14]: ▸ :app:prepareComGoogleFirebaseFirebaseMessaging1001Library
[06:38:14]: ▸ :app:prepareIoFabricSdkAndroidFabric1317Library
[06:38:14]: ▸ :app:prepareIoReactivexRxandroid110Library
[06:38:14]: ▸ :thermodosdk:preBuild UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:extractProguardFiles
[06:38:14]: ▸ :thermodosdk:preReleaseBuild
[06:38:14]: ▸ :thermodosdk:checkReleaseManifest
[06:38:14]: ▸ :thermodosdk:prepareReleaseDependencies
[06:38:14]: ▸ :thermodosdk:compileReleaseAidl UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:compileReleaseNdk UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:compileLint UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:copyReleaseLint UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:mergeReleaseShaders UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:compileReleaseShaders UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:generateReleaseAssets UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:mergeReleaseAssets UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:mergeReleaseProguardFiles UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:packageReleaseRenderscript UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:compileReleaseRenderscript UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:generateReleaseResValues UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:generateReleaseResources UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:packageReleaseResources UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:processReleaseManifest UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:generateReleaseBuildConfig UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:processReleaseResources UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:generateReleaseSources UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:javaPreCompileRelease
[06:38:14]: ▸ :thermodosdk:compileReleaseJavaWithJavac UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:processReleaseJavaRes UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:transformClassesAndResourcesWithProguardForRelease UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:mergeReleaseJniLibFolders UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:transformNativeLibsWithMergeJniLibsForRelease UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:transformNativeLibsWithStripDebugSymbolForRelease UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:transformNativeLibsWithSyncJniLibsForRelease UP-TO-DATE
[06:38:14]: ▸ :thermodosdk:bundleRelease UP-TO-DATE
[06:38:14]: ▸ :app:prepareReleaseDependencies
[06:38:14]: ▸ :app:compileReleaseAidl UP-TO-DATE
[06:38:14]: ▸ :app:compileReleaseRenderscript UP-TO-DATE
[06:38:14]: ▸ :app:generateReleaseBuildConfig UP-TO-DATE
[06:38:14]: ▸ :app:mergeReleaseShaders UP-TO-DATE
[06:38:14]: ▸ :app:compileReleaseShaders UP-TO-DATE
[06:38:14]: ▸ :app:generateReleaseAssets UP-TO-DATE
[06:38:14]: ▸ :app:mergeReleaseAssets UP-TO-DATE
[06:38:14]: ▸ :app:processReleaseGoogleServices
[06:38:14]: ▸ Parsing json file: /home/ubuntu/hrfid-thermistor/app/google-services.json
[06:38:14]: ▸ :app:processReleaseManifest UP-TO-DATE
[06:38:14]: ▸ :app:fabricGenerateResourcesRelease
[06:38:14]: ▸ :app:generateReleaseResValues UP-TO-DATE
[06:38:14]: ▸ :app:generateReleaseResources
[06:38:16]: ▸ :app:mergeReleaseResources
[06:38:17]: ▸ :app:processReleaseResources
[06:38:17]: ▸ :app:generateReleaseSources
[06:38:17]: ▸ :app:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
[06:38:17]: ▸ :app:javaPreCompileRelease
[06:38:17]: ▸ :app:compileReleaseJavaWithJavac UP-TO-DATE
[06:38:17]: ▸ :app:compileReleaseNdk UP-TO-DATE
[06:38:17]: ▸ :app:compileReleaseSources UP-TO-DATE
[06:38:28]: ▸ :app:lintVitalRelease
[06:39:01]: ▸ :app:transformClassesWithDexForRelease
[06:39:01]: ▸ :app:mergeReleaseJniLibFolders
[06:39:01]: ▸ :app:transformNativeLibsWithMergeJniLibsForRelease
[06:39:01]: ▸ :app:transformNativeLibsWithStripDebugSymbolForRelease
[06:39:01]: ▸ :app:processReleaseJavaRes UP-TO-DATE
[06:39:01]: ▸ :app:transformResourcesWithMergeJavaResForRelease
[06:39:01]: ▸ :app:validateSigningRelease
[06:39:05]: ▸ :app:packageRelease
[06:39:05]: ▸ :app:assembleRelease
[06:39:05]: ▸ :thermodosdk:compileReleaseSources UP-TO-DATE
[06:39:05]: ▸ :thermodosdk:assembleRelease UP-TO-DATE
[06:39:05]: ▸ BUILD SUCCESSFUL
[06:39:05]: ▸ Total time: 54.334 secs
[06:39:05]: --------------------
[06:39:05]: --- Step: supply ---
[06:39:05]: --------------------

+-------------------------+---------------------------------------------------------------------+
|                                   Summary for supply 2.54.0                                   |
+-------------------------+---------------------------------------------------------------------+
| track                   | alpha                                                               |
| apk                     | /home/ubuntu/hrfid-thermistor/app/build/outputs/apk/app-release.apk |
| package_name            | com.healthrfid.temperatureapp                                       |
| json_key                | ./GooglePlayAndroidDeveloper-81a5770f5344.json                      |
| skip_upload_apk         | false                                                               |
| skip_upload_metadata    | false                                                               |
| skip_upload_images      | false                                                               |
| skip_upload_screenshots | false                                                               |
| validate_only           | false                                                               |
| check_superseded_tracks | false                                                               |
+-------------------------+---------------------------------------------------------------------+

[06:39:06]: Preparing apk at path '/home/ubuntu/hrfid-thermistor/app/build/outputs/apk/app-release.apk' for upload...
[06:39:07]: Sending crash report...
[06:39:07]: The stack trace is sanitized so no personal information is sent.
[06:39:07]: To see what we are sending, look here: /home/ubuntu/.fastlane/latest_crash.json
[06:39:07]: Learn more at https://github.com/fastlane/fastlane#crash-reporting
[06:39:07]: You can disable crash reporting by adding `opt_out_crash_reporting` at the top of your Fastfile
+-----------------------------+-------------------------------------------------------------------------+
|                                             Lane Context                                              |
+-----------------------------+-------------------------------------------------------------------------+
| DEFAULT_PLATFORM            | android                                                                 |
| PLATFORM_NAME               | android                                                                 |
| LANE_NAME                   | android alpha                                                           |
| GRADLE_BUILD_TYPE           | Release                                                                 |
| GRADLE_ALL_APK_OUTPUT_PATHS | ["/home/ubuntu/hrfid-thermistor/app/build/outputs/apk/app-release.apk"] |
| GRADLE_APK_OUTPUT_PATH      | /home/ubuntu/hrfid-thermistor/app/build/outputs/apk/app-release.apk     |
+-----------------------------+-------------------------------------------------------------------------+
[06:39:07]: undefined method `upload_edit_apk' for #<Google::Apis::AndroidpublisherV2::AndroidPublisherService:0x007fc77bd49e60>

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | gradle                              | 54          |
| 💥   | supply                              | 0           |
+------+-------------------------------------+-------------+

[06:39:07]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/supply/lib/supply/client.rb:214:in `block in upload_apk': [!] undefined method `upload_edit_apk' for #<Google::Apis::AndroidpublisherV2::AndroidPublisherService:0x007fc77bd49e60> (NoMethodError)
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/supply/lib/supply/client.rb:367:in `call_google_api'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/supply/lib/supply/client.rb:213:in `upload_apk'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/supply/lib/supply/uploader.rb:139:in `upload_binary_data'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/supply/lib/supply/uploader.rb:113:in `block in upload_binaries'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/supply/lib/supply/uploader.rb:112:in `each'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/supply/lib/supply/uploader.rb:112:in `upload_binaries'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/supply/lib/supply/uploader.rb:26:in `perform_upload'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/fastlane/lib/fastlane/actions/supply.rb:21:in `run'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:26:in `block (2 levels) in parsing_binding'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/gems/fastlane-2.54.0/bin/fastlane:20:in `<top (required)>'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/bin/fastlane:23:in `load'
	from /opt/circleci/.rvm/gems/ruby-2.2.6/bin/fastlane:23:in `<main>'

**Comment by bangonkali** [comment]
I encounter the same issue.

**Comment by minhtc** [comment]
I've pushed a pull request to fix this issue:
#10120

**Comment by mpirri** [comment]
We just merged @minhtc 's fix for this issue and will be doing a new _fastlane_ release shortly with this fix to `supply`.  Thanks for you patience and sorry for the inconvenience!  🚀

**Comment by francisfernando** [comment]
Thanks for the reply. I will wait for the new release thanks

**Comment by NathanWalker** [comment]
@mpirri It looks like 2.54.0 included the fix mentioned? however 2.54.0 appears to still have this error?
Or is the next release after 2.54.0 going to contain the fix for this?
Thank you for attention to this blocker for many folks right now.

**Comment by mpirri** [comment]
@NathanWalker It will be in the release AFTER 2.54.0. We will release that in a few hours time.  Thanks so much for your patience!

**Comment by maxkomarychev** [comment]
It looks like this is related but I am getting this:

```
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.54.1/supply/lib/supply/client.rb:214:in `block in upload_apk': [!] undefined method `upload_apk' for #<Google::Apis::AndroidpublisherV2::AndroidPublisherService:0x007fbfd3eb23d8> (NoMethodError)
```

with latest 2.54.1

**Comment by skulawik** [comment]
Same here:
```
/var/lib/gems/2.3.0/gems/fastlane-2.54.1/supply/lib/supply/client.rb:214:in `block in upload_apk': [!] undefined method `upload_apk' for #<Google::Apis::AndroidpublisherV2::AndroidPublisherService:0x0000000401db88> (NoMethodError)
Did you mean?  upload_edit_apk
               upload_path
```

**Comment by thiemo--bleeken** [comment]
same for me. could you please double check?

**Comment by francisfernando** [comment]
Hi All 
I will closed this issue is already resolved from my last build. Thanks fastlane support.
