### ISSUE TITLE
Scheme Unity-iPhone is not currently configured for the test action

### ISSUE THREAD

**Issue by FelixDYS** [fastlane/fastlane#10413]
### New Issue Checklist

- [Y ] Updated fastlane to the latest version
- [Y] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [Y] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [Y] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
 xcodebuild: error: Scheme Unity-iPhone is not currently configured for the test action.
##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]
This is a project from Unity4.6, When I scan , output this error

[16:02:09]: Found simulator "iPhone 5s (10.1)"
[16:02:09]: It's not recommended to set the `destination` value directly
[16:02:09]: Instead use the other options available in `fastlane scan --help`
[16:02:09]: Using your value 'platform=iOS,id=f469f184a4d270ff25daee222d0c9d3b2688c052' for now
[16:02:09]: because I trust you know what you're doing...

+------------------------+--------------------------------------+
|                    Summary for scan 2.59.0                    |
+------------------------+--------------------------------------+
| project                | ./Unity-iPhone.xcodeproj             |
| scheme                 | Unity-iPhone                         |
| derived_data_path      | /Users/imac03_mineloader/Library/De  |
|                        | veloper/Xcode/DerivedData/Unity-iPh  |
|                        | one-endlcoaduefhuedrvofkmfhlhefv     |
| clean                  | false                                |
| skip_build             | false                                |
| output_directory       | ./fastlane/test_output               |
| output_types           | html,junit                           |
| buildlog_path          | ~/Library/Logs/scan                  |
| include_simulator_logs | false                                |
| open_report            | false                                |
| skip_slack             | false                                |
| slack_only_on_failure  | false                                |
| use_clang_report_name  | false                                |
| fail_build             | true                                 |
| xcode_path             | /Applications/Xcode.app              |
+------------------------+--------------------------------------+

[16:02:09]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme Unity-iPhone -project ./Unity-iPhone.xcodeproj -destination 'platform=iOS,id=f469f184a4d270ff25daee222d0c9d3b2688c052' -derivedDataPath '/Users/imac03_mineloader/Library/Developer/Xcode/DerivedData/Unity-iPhone-endlcoaduefhuedrvofkmfhlhefv' build test | tee '/Users/imac03_mineloader/Library/Logs/scan/sirius-Unity-iPhone.log' | xcpretty  --report html --output '/Users/imac03_mineloader/Desktop/Sirius/buildToolProject/com.xijigame.yysg/fastlane/test_output/report.html' --report junit --output '/Users/imac03_mineloader/Desktop/Sirius/buildToolProject/com.xijigame.yysg/fastlane/test_output/report.junit' --report junit --output '/var/folders/2w/x79n4ttn63ldtyvz91nl_gvm0000gn/T/junit_report20170926-11349-1tu6l8'
[16:02:09]: ▸ Loading...
[16:02:10]: ▸ 2017-09-26 16:02:10.240 xcodebuild[11389:129027] WARNING: Failed to load plugin at path: "/Applications/Unity/Unity.app/Contents/PlaybackEngines/iossupport/Tools/OSX/Unity4XC.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Applications/Unity/Unity.app/Contents/PlaybackEngines/iossupport/Tools/OSX/Unity4XC.xcplugin/Contents/MacOS/Unity4XC): no suitable image found.  Did find:
[16:02:10]: ▸ /Applications/Unity/Unity.app/Contents/PlaybackEngines/iossupport/Tools/OSX/Unity4XC.xcplugin/Contents/MacOS/Unity4XC: code signing blocked mmap() of '/Applications/Unity/Unity.app/Contents/PlaybackEngines/iossupport/Tools/OSX/Unity4XC.xcplugin/Contents/MacOS/Unity4XC'" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Applications/Unity/Unity.app/Contents/PlaybackEngines/iossupport/Tools/OSX/Unity4XC.xcplugin/Contents/MacOS/Unity4XC, NSDebugDescription=dlopen_preflight(/Applications/Unity/Unity.app/Contents/PlaybackEngines/iossupport/Tools/OSX/Unity4XC.xcplugin/Contents/MacOS/Unity4XC): no suitable image found.  Did find:
[16:02:10]: ▸ /Applications/Unity/Unity.app/Contents/PlaybackEngines/iossupport/Tools/OSX/Unity4XC.xcplugin/Contents/MacOS/Unity4XC: code signing blocked mmap() of '/Applications/Unity/Unity.app/Contents/PlaybackEngines/iossupport/Tools/OSX/Unity4XC.xcplugin/Contents/MacOS/Unity4XC', NSBundlePath=/Applications/Unity/Unity.app/Contents/PlaybackEngines/iossupport/Tools/OSX/Unity4XC.xcplugin, NSLocalizedDescription=The bundle “Unity4XC” couldn’t be loaded because it is damaged or missing necessary resources.}
[16:02:10]: ▸ xcodebuild: error: Scheme Unity-iPhone is not currently configured for the test action.

**Comment by codefei** [comment]
type in terminal:
`export FORK_XCODE_WRITING=true`
I got the same error and solved by refer (https://github.com/CocoaPods/CocoaPods/issues/5938)

**Comment by FelixDYS** [comment]
@codefei ，sir，Thank you very much for your solution。I have a holiday time ，so my reply is late

**Comment by kd8ssq** [comment]
I tried using the suggestion made by @codefei but I'm still getting the same errors when trying to run snapshot
