### ISSUE TITLE
Fastlane 2.62.1 added manual signing to export plist

### ISSUE THREAD

**Issue by lbrownell-gpsw** [fastlane/fastlane#10685]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Builds of one of our apps started failing trying to export an ipa. The last success was with 2.62.0; the first failure was with 2.62.1.  The obvious difference is in the export plist; see below
##### Complete output when running fastlane, including the stack trace and command used
Not the complete output, but here's the summary for gym (edited to remove names):
```
+----------------------------------------------------------+------------------------------------------------------------------------------+
|                                                         Summary for gym 2.62.1                                                          |
+----------------------------------------------------------+------------------------------------------------------------------------------+
| clean                                                    | true                                                                         |
| project                                                  | ./MyApp/MyApp.xcodeproj                                                      |
| scheme                                                   | MyApp                                                                        |
| archive_path                                             | MyApp-AppStore.xcarchive                                                     |
| sdk                                                      | iphoneos                                                                     |
| output_name                                              | MyApp-AppStore                                                               |
| output_directory                                         | ..                                                                           |
| configuration                                            | Release                                                                      |
| xcargs                                                   | -allowProvisioningUpdates GCC_PREPROCESSOR_DEFINITIONS='$(inherited) BETA=1' |
| buildlog_path                                            | .                                                                            |
| include_bitcode                                          | false                                                                        |
| export_method                                            | app-store                                                                    |
| export_team_id                                           | xxxxxxxxxx                                                                   |
| export_xcargs                                            | -allowProvisioningUpdates                                                    |
| export_options.provisioningProfiles.com.MyCompany.MyApp  | MyApp AppStore                                                               |
| destination                                              | generic/platform=iOS                                                         |
| build_path                                               | /Users/builder-mobile/Library/Developer/Xcode/Archives/2017-10-24            |
| silent                                                   | false                                                                        |
| skip_package_ipa                                         | false                                                                        |
| skip_profile_detection                                   | false                                                                        |
| xcode_path                                               | /Applications/Xcode9.app                                                     |
+----------------------------------------------------------+------------------------------------------------------------------------------+
```
(Note that `export_options.provisioningProfiles.com.MyCompany.MyApp` isn't something specified in the options I specify in the Fastfile. Fastlane is generating that, and ignoring another target's provisioning profile; see at the end.)

And here is the before and after version of the export plist (bundle id, app name and teamID edited):
Before (2.62.0):
```
 ▸ -----------------------------------------
 ▸ {
 ▸   "provisioningProfiles": {
 ▸     "com.mycompany.app": "OurApp"
 ▸   },
 ▸   "method": "app-store",
 ▸   "uploadBitcode": false,
 ▸   "teamID": "xxxxxxxxxx"
 ▸ }
 ▸ -----------------------------------------
```
After (2.62.1):
``` 
 ▸ -----------------------------------------
 ▸ {
 ▸   "provisioningProfiles": {
 ▸     "com.mycompany.app": "OurApp"
 ▸   },
 ▸   "method": "app-store",
 ▸   "uploadBitcode": false,
 ▸   "signingStyle": "manual",
 ▸   "teamID": "xxxxxxxxxx"
 ▸ }
 ▸ -----------------------------------------
```
As mentioned above, there is an additional target, a widget, whose provisioning profile isn't listed.  I'm guessing if it was, it might work with manual signing (that's another Fastlane bug). But it was working defaulting to automatic signing, so, can we not randomly switch it to manual?

Working around the problem now by locking down to 2.62.0.

**Comment by vascome** [comment]
I have similar issue.
Everything works fine with 2.62.0 and starts failing with 2.62.1. 

ERROR [2017-10-25 20:53:19.95]: There seems to be a mismatch between your provided `export_method` in gym
ERROR [2017-10-25 20:53:19.95]: and the selected provisioning profiles. You passed the following options:
WARN [2017-10-25 20:53:19.95]:   export_method:      app-store
WARN [2017-10-25 20:53:19.95]:   Bundle identifier:  io.***.app
WARN [2017-10-25 20:53:19.95]:   Profile name:       match Development io.***.app
WARN [2017-10-25 20:53:19.95]:   Profile type:       development

I fixed it by follow change in Fastfile
-    match(type: "development",
+    match(type: "appstore",

Hard to say, probably it's my fault , and it worked just because all certs and profiles was installed on machine, and signingStyle was not manual (not sure if this property was before) . So once it becomes "manual" build starts failing. Not sure if it's your case.

**Comment by lbrownell-gpsw** [comment]
@vascome Similar, but not the same.  You're using match, I'm not (I do use sigh, however), and as you can see, appstore is and was explicitly stated in my export plist.  I'm sure I could restructure my Fastfile to make it work again, but...er...why?

The similarity is that 2.62.1 changed signing in export to manual when that's not helpful.  And now that I'm back on 2.62.0, pretty sure that first item they tout in .1 is it:
```
2.62.1 Improvements
- Support manual signingStyle (#10508) via Aleksey Anisov
```

**Comment by lanebrain** [comment]
Same issue here - don't use match, but do use sigh.  I pinned version to 2.62.0 for now to be able to submit and things are fine.  Have not had the time to help debug the issue.

**Comment by MartijnSchoemaker** [comment]
Same issue! Is this going to be fixed?

**Comment by MartijnSchoemaker** [comment]
I didn't downgrade to previous versions before, but I want to do this now. How can I do this? I installed fastlane with homebrew.

**Comment by MartijnSchoemaker** [comment]
I manually changed 'signingStyle' to 'automatic' in the plist and exporting is working correctly then. 
So I added this in my gym command:

```
export_options: {
                signingStyle: "automatic"
        }
```

But when I run fastlane the signingStyle of generated plist is still 'manual'. I don't want this... Did I do anything wrong or is this een issue in fastlane?!

**Comment by ohayon** [comment]
Hey @MartijnSchoemaker - could you share the output from your terminal?

**Comment by MartijnSchoemaker** [comment]
What part do you need to answer this question? I don't want to paste my whole output because of security. Paths, env vars, etc.

**Comment by MartijnSchoemaker** [comment]
Some parts that are useful I think:

+--------------------------------------+--------------------------------------+
|                           Summary for gym 2.63.0                            |
+--------------------------------------+--------------------------------------+
| workspace                            | wehkamp.xcworkspace                  |
| configuration                        | DebugDistribution                    |
| scheme                               | wehkamp                              |
| silent                               | true                                 |
| output_name                          | wehkamp                              |
| export_team_id                       | 8V375A94TK                           |
| export_xcargs                        | -allowProvisioningUpdates            |
| export_options.signingStyle          | automatic                            |
| export_method                        | ad-hoc                               |
| destination                          | generic/platform=iOS                 |
| build_path                           | /Users/monitor/Library/Developer/Xc  |
|                                      | ode/Archives/2017-11-02              |
| clean                                | false                                |
| skip_package_ipa                     | false                                |
| buildlog_path                        | ~/Library/Logs/gym                   |
| skip_profile_detection               | false                                |
| xcode_path                           | /Applications/Xcode.app              |
+--------------------------------------+--------------------------------------+

[15:21:04]: Generated plist file with the following values:
[15:21:04]: ▸ -----------------------------------------
[15:21:04]: ▸ {
[15:21:04]: ▸   "signingStyle": "manual",
[15:21:04]: ▸   "provisioningProfiles": {
[15:21:04]: ▸     "nl.wehkamp.PDD5388SwipeBetweenPDP": "nl.wehkamp.PDD5388SwipeBetweenPDP AdHoc"
[15:21:04]: ▸   },
[15:21:04]: ▸   "method": "ad-hoc",
[15:21:04]: ▸   "teamID": "8V375A94TK"
[15:21:04]: ▸ }
[15:21:04]: ▸ -----------------------------------------

**Comment by lbrownell-gpsw** [comment]
@ohayon LMK if there's anything I can provide as well.

**Comment by vorobievalex** [comment]
This problem blocked apps release for us. We use automated signing and sigh>gym>pilot without match.
Yet sticked to 2.62.0, but this will fail with next Apple API update. Is there anything else I can provide?

Some analyses:
- sigh downloads Xcode managed profile.
- https://github.com/fastlane/fastlane/pull/10508/files sets signingStyle = 'manual'
- xcodebuild fails with 

> Provisioning profile \"XC iOS: com.***\" is Xcode managed, but signing settings require a manually managed profile.

**Comment by vorobievalex** [comment]
The problem above worked around by removing the use of sigh and replacing it with 'export_xcargs "-allowProvisioningUpdates"' for profiles update.

**Comment by lbrownell-gpsw** [comment]
@vorobievalex Thanks, I'll give that a try.

**Comment by biolinh** [comment]
Hi all,
I got a same  error with code signing.

- My Fastlane file:

```
desc "Deploy a new version to the hockey"
lane :upload_hockey do
unlock_keychain(path: "login.keychain", password: KEYCHAIN_PASSWORD)
sh "fastlane fastlane-credentials add --username '" + ENV["FASTLANE_USER"] + "' --password '" + KEYCHAIN_PASSWORD + "'"
match(force: false, type: "adhoc" )

sh "pod install"
sh "sed -i '' 's/ProvisioningStyle = Automatic;/ProvisioningStyle = Manual;/' '#{ENV["PROJECT_DIR"]}'/360.xcodeproj/project.pbxproj"

increment_build_number(build_number: BUILD_NUMBER)
xcclean(scheme: "360")

PROVISIONING_PROFILE_SPECIFIER='match AdHoc ' + ENV["BUNDLE_IDENTIFIER"]
gym(scheme: "360", codesigning_identity: CODE_SIGN_IDENTITY,  workspace: "360.xcworkspace", configuration: "Jenkins", derived_data_path: "./build",
    xcargs: "DEVELOPMENT_TEAM=" + ENV["TEAM_ID"] +" " "PROVISIONING_PROFILE_SPECIFIER='#{PROVISIONING_PROFILE_SPECIFIER}'"+" " "PRODUCT_BUNDLE_IDENTIFIER=" + BUNDLE_ID
    )
hockey(
api_token: 'xxxxxxxxxxxx',
ipa: './build/360.ipa'
)
sh "fastlane fastlane-credentials remove --username $FASTLANE_USER"
end
```

I got the error:

```
[33m▸�[0m �[39;1mSigning�[0m /Users/jenkins/Library/Developer/Xcode/DerivedData/360-agcktrxjiuzpueaynyyhoctfiaja/Build/Intermediates.noindex/ArchiveIntermediates/360/InstallationBuildProductsLocation/Applications/360.app
** ARCHIVE FAILED **

The following build commands failed:
CodeSign /Users/jenkins/Library/Developer/Xcode/DerivedData/360-agcktrxjiuzpueaynyyhoctfiaja/Build/Intermediates.noindex/ArchiveIntermediates/360/InstallationBuildProductsLocation/Applications360.app
(1 failure)
[14:45:32]: �[31mExit status: 65�[0m

+---------------+-------------------------+
| �[32m�[33mBuild environment�[0m |
+---------------+-------------------------+
| xcode_path | /Applications/Xcode.app |
| gym_version | 2.68.2 |
| export_method | app-store |
| sdk | iPhoneOS11.2.sdk |
+---------------+-------------------------+

[14:45:32]: ▸ �[35m (7fa6ed04-ea94-496c-a4e9-e66be8feccd8)�[0m
[14:45:32]: ▸ �[35m /usr/bin/codesign --force --sign A22EDB7245B8CBB7CB5A2ED61ED7B980873C17E6 --entitlements /Users/jenkins/Library/Developer/Xcode/DerivedData/360-agcktrxjiuzpueaynyyhoctfiaja/Build/Intermediates.noindex/ArchiveIntermediates/360/IntermediateBuildFilesPath/360.build/Release-iphoneos/360.build/360.app.xcent --timestamp=none /Users/jenkins/Library/Developer/Xcode/DerivedData/360-agcktrxjiuzpueaynyyhoctfiaja/Build/Intermediates.noindex/ArchiveIntermediates/360/InstallationBuildProductsLocation/Applications/360.app�[0m
[14:45:32]: ▸ �[35m/Users/jenkins/Library/Developer/Xcode/DerivedData/360-agcktrxjiuzpueaynyyhoctfiaja/Build/Intermediates.noindex/ArchiveIntermediates/360/InstallationBuildProductsLocation/Applications/360.app: unknown error -1=ffffffffffffffff�[0m
[14:45:32]: ▸ �[35mCommand /usr/bin/codesign failed with exit code 1�[0m
[14:45:32]:
[14:45:32]: �[31m⬆️ Check out the few lines of raw xcodebuild output above for potential hints on how to solve this error�[0m
[14:45:32]: �[33m📋 For the complete and more detailed error log, check the full log at:�[0m
[14:45:32]: �[33m📋 /Users/jenkins/Library/Logs/gym/360-360.log�[0m
[14:45:32]:
Then I run the command again in terminal:

/usr/bin/codesign --force --sign A22EDB7245B8CBB7CB5A2ED61ED7B980873C17E6 --entitlements /Users/jenkins/Library/Developer/Xcode/DerivedData/360-agcktrxjiuzpueaynyyhoctfiaja/Build/Intermediates.noindex/ArchiveIntermediates/360/IntermediateBuildFilesPath/360.build/Release-iphoneos/360.build/360.app.xcent --timestamp=none /Users/jenkins/Library/Developer/Xcode/DerivedData/360-agcktrxjiuzpueaynyyhoctfiaja/Build/Intermediates.noindex/ArchiveIntermediates/360/InstallationBuildProductsLocation/Applications/360.app�
**it popups a message to require input password to allow add the certificate.

```
After I run the command, I can build successful. But the problem is that:

I must build many apps with corresponding certificate, I unable to import manually like that.
If I must do manually it lost the powerful feature of Fastlane.**
[15:30:15]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[15:30:17]: Generating fastlane environment output, this might take a few seconds...

🚫 fastlane environment 🚫

**Comment by ohayon** [comment]
Hey everyone, we released some changes to this code yesterday. Could you all update fastlane and try running this again to see if the code signing will work a bit better and get you back up and running? 🚀

**Comment by biolinh** [comment]
Hi @ohayon,

I have just update the latest Fastlane but the error is still remaining.
`[18:17:21]: ▸ [35m/Users/jenkins/Library/Developer/Xcode/DerivedData/JMango360-bmoxcuvzmgnulwbfxrcqcqgjrook/Build/Intermediates/ArchiveIntermediates/JMango360/InstallationBuildProductsLocation/Applications/JMango360.app: unknown error -1=ffffffffffffffff[0m
[18:17:21]: ▸ [35mCommand /usr/bin/codesign failed with exit code 1[0m
[18:17:21]:`

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                        | Mac OS X 10.13.1 (17B1003)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.68.2  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.13.4       |
| io-console                | 0.4.5        |
</details>


*generated on:* **2017-12-07**
</details>

**Comment by ohayon** [comment]
Hey @biolinh, the exit code looks like it was mangled in your last comment. Any chanc eyou could share some more of your output?

**Comment by biolinh** [comment]
Hi @ohayon,

open the raw  log, I can get anything more:

`    
Signing Identity:     "iPhone Distribution: XXXYYYZZZ BV (XXXXXXX)"
Provisioning Profile: "match AppStore nl.deltastar.deltastar"
                      (d53ad046-qwertyuiokjhngbfvdcsdfgn)

    /usr/bin/codesign --force --sign 123456780POIUYTREWQ --entitlements /Users/jenkins/Library/Developer/Xcode/DerivedData/360-bmoxcuvzmgnulwbfxrcqcqgjrook/Build/Intermediates.noindex/ArchiveIntermediates/360/IntermediateBuildFilesPath/360.build/Release-iphoneos/360.build/360.app.xcent --timestamp=none /Users/jenkins/Library/Developer/Xcode/DerivedData/360-bmoxcuvzmgnulwbfxrcqcqgjrook/Build/Intermediates.noindex/ArchiveIntermediates/360/InstallationBuildProductsLocation/Applications/360.app
/Users/jenkins/Library/Developer/Xcode/DerivedData/360-bmoxcuvzmgnulwbfxrcqcqgjrook/Build/Intermediates.noindex/ArchiveIntermediates/360/InstallationBuildProductsLocation/Applications/360.app: unknown error -1=ffffffffffffffff
Command /usr/bin/codesign failed with exit code 1` 

My OS 10.13.1, Xcode 8.2.1.

Thanks

**Comment by biolinh** [comment]
Hi @ohayon,

After work around I found the specific error, then I create a new issues for this.
Please help me to look up it.
https://github.com/fastlane/fastlane/issues/11155
Thanks.

**Comment by lbrownell-gpsw** [comment]
(much time passes...)

Thanks @vorobievalex, the combination of removing sigh and adding 'export_xcargs "-allowProvisioningUpdates"' worked for me too.

That said...still seems to be peculiarly broken.
