### ISSUE TITLE
Certificate not installed when already installed in other keychain

### ISSUE THREAD

**Issue by YvesDelcoigne** [fastlane/fastlane#11659]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm implementing the fastlane match action to use in our build script for Xamarin iOS builds (using terminal commands). When the certificate is not installed on the machine, this works correctly. However, if the certificate is already installed in another keychain, the certificate is not installed in the provided keychain. This is problematic: for each build, a new keychain is created and the certificate added; the keychain is removed when the build is completed. If multiple builds need the same certificate, the latter build will fail if the first build removed its keychain.

The main issue is this error: security: SecKeychainItemImport: The specified item already exists in the keychain.
It thinks the certificate is already installed in the keychain, while it isn't.

##### Complete output when running fastlane, including the stack trace and command used

[08:48:24]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
INFO [2018-01-23 08:48:24.37]: Successfully loaded 'xx/Matchfile' 📄

+------------+--------------------------------------+
|    Detected Values from './fastlane/Matchfile'    |
+------------+--------------------------------------+
| git_url    | ssh://git@bitbucket.org/xx  |
|            | /xx                     |
| git_branch | xx                          |
| readonly   | true                                 |
| username   | xx              |
+------------+--------------------------------------+

+-----------------------+--------------------------------------+
|                   Summary for match 2.78.0                   |
+-----------------------+--------------------------------------+
| verbose               | true                                 |
| keychain_name         | xamarin_test.keychain               |
| app_identifier        | ["xx  |
|                       | "]                                   |
| keychain_password     | ********                             |
| type                  | enterprise                           |
| git_url               | ssh://git@bitbucket.org/xx  |
|                       | /xx                    |
| git_branch            | xx                          |
| username              | xx              |
| readonly              | true                                 |
| force                 | false                                |
| skip_confirmation     | false                                |
| shallow_clone         | false                                |
| clone_branch_directly | false                                |
| force_for_new_devices | false                                |
| skip_docs             | false                                |
| platform              | ios                                  |
+-----------------------+--------------------------------------+

INFO [2018-01-23 08:48:24.39]: Cloning remote git repo...
INFO [2018-01-23 08:48:24.39]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2018-01-23 08:48:24.39]: $ GIT_TERMINAL_PROMPT=0 git clone 'ssh://git@bitbucket.org/xx/xx
' '/var/folders/z1/_5prbhms5s5gdjc7pmq_2xpc0000gs/T/d20180123-18491-drbbgk'
INFO [2018-01-23 08:48:24.42]: ▸ Cloning into '/var/folders/z1/_5prbhms5s5gdjc7pmq_2xpc0000gs/T/d20180123-18491-drbbgk'...
INFO [2018-01-23 08:48:26.84]: ▸ remote: Counting objects: 4020, done.
INFO [2018-01-23 08:48:27.98]: ▸ remote: Compressing objects: 100% (2993/2993), done.
INFO [2018-01-23 08:48:32.59]: ▸ remote: Total 4020 (delta 260), reused 0 (delta 0)
INFO [2018-01-23 08:48:32.59]: ▸ Receiving objects: 100% (4020/4020), 23.92 MiB | 5.19 MiB/s, done.
INFO [2018-01-23 08:48:32.61]: ▸ Resolving deltas: 100% (353/353), done.
INFO [2018-01-23 08:48:32.65]: $ git branch --list origin/xx --no-color -r
INFO [2018-01-23 08:48:32.66]: ▸ origin/xx
INFO [2018-01-23 08:48:32.66]: Checking out branch xx...
INFO [2018-01-23 08:48:32.66]: $ git checkout xx
INFO [2018-01-23 08:48:32.70]: ▸ Branch xx set up to track remote branch xx from origin.
INFO [2018-01-23 08:48:32.70]: ▸ Switched to a new branch 'xx'
INFO [2018-01-23 08:48:32.77]: 🔓  Decrypted '3648BL3N34.cer'
INFO [2018-01-23 08:48:32.83]: 🔓  Decrypted 'MJ3RCTVR2N.cer'
INFO [2018-01-23 08:48:32.95]: 🔓  Decrypted 'UFP6VF5LDV.cer'
INFO [2018-01-23 08:48:33.03]: 🔓  Decrypted '3648BL3N34.p12'
INFO [2018-01-23 08:48:33.08]: 🔓  Decrypted 'MJ3RCTVR2N.p12'
INFO [2018-01-23 08:48:33.14]: 🔓  Decrypted 'UFP6VF5LDV.p12'
INFO [2018-01-23 08:48:36.76]: 🔓  Successfully decrypted certificates repo
INFO [2018-01-23 08:48:36.76]: Installing certificate...
INFO [2018-01-23 08:48:36.76]: $ security list-keychains -d user
INFO [2018-01-23 08:48:36.80]: ▸     "/Users/yves/Library/Keychains/login.keychain-db"
INFO [2018-01-23 08:48:36.80]: ▸     "/Users/yves/Library/Keychains/xamarin_test.keychain-db"
INFO [2018-01-23 08:48:36.80]: $ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' /Users/yves/Library/Keychains/login.keychain-db
INFO [2018-01-23 08:48:36.87]: ▸ keychain: "/Users/yves/Library/Keychains/login.keychain-db"
INFO [2018-01-23 08:48:36.87]: ▸ version: 512
DEBUG [2018-01-23 08:48:37.14]: Certificate 'MJ3RCTVR2N.cer' is already installed on this machine
INFO [2018-01-23 08:48:37.14]: $ security import /var/folders/z1/_5prbhms5s5gdjc7pmq_2xpc0000gs/T/d20180123-18491-drbbgk/certs/enterprise/MJ3RCTVR2N.p12 -k '/Users/yves/Library/Keychains/xamarin_test2.keychain-db' -P '' -T /usr/bin/codesign -T /usr/bin/security
security: SecKeychainItemImport: The specified item already exists in the keychain.
INFO [2018-01-23 08:48:37.27]: $ security set-key-partition-list -S apple-tool:,apple: -k xamarin /Users/yves/Library/Keychains/xamarin_test2.keychain-db
INFO [2018-01-23 08:48:37.35]: ▸ keychain: "/Users/yves/Library/Keychains/xamarin_test2.keychain-db"
INFO [2018-01-23 08:48:37.37]: $ openssl x509 -inform der -in /var/folders/z1/_5prbhms5s5gdjc7pmq_2xpc0000gs/T/d20180123-18491-drbbgk/certs/enterprise/MJ3RCTVR2N.cer -subject -dates -noout &
INFO [2018-01-23 08:48:37.40]: ▸ subject= /UID=xx/CN=xx/OU=xx/O=xx/C=US
INFO [2018-01-23 08:48:37.40]: ▸ notBefore=Oct 14 12:04:05 2015 GMT
INFO [2018-01-23 08:48:37.40]: ▸ notAfter=Oct 13 12:04:05 2018 GMT

+-------------------+-------------------------------------------+
|                     Installed Certificate                     |
+-------------------+-------------------------------------------+
| User ID           | xx                                |
| Common Name       | xx |
| Organisation Unit | xx                                |
| Organisation      | xx                      |
| Country           | US                                        |
| Start Datetime    | Oct 14 12:04:05 2015 GMT                  |
| End Datetime      | Oct 13 12:04:05 2018 GMT                  |
+-------------------+-------------------------------------------+

INFO [2018-01-23 08:48:37.41]: Installing provisioning profile...

+---------------------+------------------------+------------------------+
|                    Installed Provisioning Profile                     |
+---------------------+------------------------+------------------------+
| Parameter           | Environment Variable   | Value                  |
+---------------------+------------------------+------------------------+
| App Identifier      |                        | xx  |
|                     |                        | xx           |
| Type                |                        | enterprise             |
| Platform            |                        | ios                    |
| Profile UUID        | xx  | xx  |
|                     | xx  | xx        |
|                     | xx                |                        |
| Profile Name        | xx  | match InHouse          |
|                     | xx  | xx  |
|                     | xx   | xx           |

INFO [2018-01-23 08:48:37.62]: All required keys, certificates and provisioning profiles are installed 🙌
ERROR [2018-01-23 08:48:37.67]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.2                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.2 (17C88)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.78.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.60.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.14.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.0.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2018-01-23**
</details>

**Comment by YvesDelcoigne** [comment]
Some more information gathered: apparently, with every try, there is a private key that is installed in the correct keychain, but nothing more.

**Comment by YvesDelcoigne** [comment]
Pinging this issue again. 

I've performed all commands that are outputted by using the verbose flag manually, but with my manually created p12 file. This works as expected (p12 is installed in new keychain, even if it is already available in another keychain).

**Comment by KrauseFx** [comment]
Can you tell us how we can reproduce the issue to work on a fix?

**Comment by DelcoigneYves** [comment]
Certainly!

Steps to reproduce:
- Make sure the certificate you want to install is not installed in any certificate
- Create and unlock a new keychain (temp1.keychain). Either manually or using fastlane run create_keychain.
- Run (in my case) "fastlane match enterprise" with temp1.keychain as keychain name, an app identifier you can choose, and the necessary extra parameters (git url, keychain password, login email). The certificate will be installed.
-  Create and unlock a second keychain (temp2.keychain).
- Run the same "fastlane match" command as before, but replace the temp1.keychain parameter with temp2.keychain. The certificate is NOT imported in the requested keychain, only a private key is imported.

**Comment by elitalon** [comment]
FWIW we also have this very same issue in our team. It seems that `match` does not use the value passed on `MATCH_KEYCHAIN_NAME` (or `keychain_name`) when verifying the certificates installed locally:

```
INFO [2018-03-05 10:54:02.25]: $ security list-keychains -d user
INFO [2018-03-05 10:54:02.27]: ▸     "/Users/elitalon/Library/Keychains/login.keychain-db"
INFO [2018-03-05 10:54:02.27]: ▸     "/Users/elitalon/Library/Keychains/ios.keychain-db"
INFO [2018-03-05 10:54:02.27]: $ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' /Users/elitalon/Library/Keychains/login.keychain-db
INFO [2018-03-05 10:54:02.31]: …
DEBUG [2018-03-05 10:54:02.50]: Certificate '352G4S6BDE.cer' is already installed on this machine
```

It does use it however when adding the associated private key:

```
INFO [2018-03-05 10:54:02.50]: $ security import /var/folders/sd/p17d_g8s5dv6h8hfm181hltm0000gn/T/d20180305-16703-15jp918/certs/development/352G4S6BDE.p12 -k '/Users/elitalon/Library/Keychains/ios.keychain-db' -P '' -T /usr/bin/codesign -T /usr/bin/security
security: SecKeychainItemImport: The specified item already exists in the keychain.
INFO [2018-03-05 10:54:02.58]: $ security set-key-partition-list -S apple-tool:,apple: -k EBKITCEA4 /Users/elitalon/Library/Keychains/ios.keychain-db
```

The thing that puzzles us is the output from  `security`: _"The specified item already exists in the keychain"_. It notices that the key is indeed there, because it's in `login.keychain-db`, but it installs a duplicated version of it in `ios.keychain-db` anyway.

**Comment by YvesDelcoigne** [comment]
Preliminary tests indicate that this issue should be solved, will confirm after further tests!

**Comment by acecilia** [comment]
Using 2.92.1. The issue is still not resolved. 

1 - When using match, I have the certificate and private key in a customCreated-locked keychain (not in login keychain). 
2 - During gym, I am asked access to the locked keychain, and I reject it, and fastlane fails.
3 - When removing the certificate and key from the custom keychain and running the lane again, the certificate and key are added to the login keychain and all works.

**Comment by joshdholtz** [comment]
@YvesDelcoigne @acecilia @elitalon I just made PR #12413 which should fix this 💪 Can you test this out when you get a chance to see if this works for you?

## To Test This Change
Add the following to your Gemfile and then run `bundle install`
```rb
gem 'fastlane', :git => 'https://github.com/fastlane/fastlane.git', :branch => 'joshdholtz-match-only-check-cert-installed-in-given-keychain'
```

**Comment by YvesDelcoigne** [comment]
Hi @joshdholtz 
Thanks for your efforts! While my issue was not fixed with your PR, it is fixed now by upgrading my build machine to High Sierra.

**Comment by elitalon** [comment]
@joshdholtz Sorry for the delayed answer. I tried with a few projects and I'm pretty sure the issue is fixed: there are no more duplicated keys.

We do get some duplicated keys from time to time, but that's probably because we have projects still building with older versions of fastlane (we lock all gems per project with `bundle --deployment`).

Thanks a lot for your efforts!
