### ISSUE TITLE
Fastlane init itunes connect option.

### ISSUE THREAD

**Issue by Remyoman** [fastlane/fastlane#1199]
Since one of the latest version (0.15.2) the auto detect feature does it's thing and tells you the app identifier will be created for Itunes Connect and the Apple Developer Portal. Is there a way to not create it in iTunes Connect, since the help doesn't mention it?
The app I am adding fastlane to will probably not get published under the same iTunes Connect account, therefore I would like to disable this action.

**Comment by ohwutup** [comment]
hey @Remyoman, thanks for submitting the issue, i have a fix for this in the works currently. I will update and close this issue as soon as i merge it and you should be able to proceed without making the app in the dev portal and itc

**Comment by Remyoman** [comment]
@ohwutup Thank you, for the time being I downgraded and did the setup with 1.51.0. I assume this is related to issue#1167, as it is a similar situation.

**Comment by ohwutup** [comment]
exactly!

**Comment by ohwutup** [comment]
hey @Remyoman just fixed this here https://github.com/fastlane/fastlane/releases/tag/1.54.0, going to close this for now, please open new issues as they arise! :octopus:

**Comment by allewun** [comment]
@ohwutup the latest `fastlane init` still seems to force you into iTunes Connect. Is this the intended behavior?

```
$ fastlane init

...

Your Apple ID (e.g. fastlane@krausefx.com): XXX@YYY.ZZZ
[18:21:48]: Verifying if app is available on the Apple Developer Portal and iTunes Connect...
[18:21:48]: Starting login with user 'XXX@YYY.ZZZ'
Multiple teams found on the Developer Portal, please enter the number of the team you want to use:
1) XXXXXXXX "MyCompany" (In-House)
2) YYYYYYYY "MyCompany Labs" (Company/Organization)
1

+----------------+----------------------------------------------+
|                        Detected Values                        |
+----------------+----------------------------------------------+
| Apple ID       | XXX@YYY.ZZZ                                  |
| App Name       | AppName                                      |
| App Identifier | com.mycompany.AppName                        |
| Workspace      | /Users/allen/AppName.xcworkspace             |
+----------------+----------------------------------------------+

[18:22:10]: This app identifier doesn't exist on iTunes Connect yet, it will be created for you
Please confirm the above values (y/n)
App Identifier (com.krausefx.app): █
```

**Comment by ohwutup** [comment]
That is not intended, I believe one of two things are happening. I will look into this shortly. Thanks for raising the issue!

**Comment by ohwutup** [comment]
Hi all! This should be fixed with the most recent releases of fastlane- I am going to close the issue for now, but please reopen it if you run into more problems! Thanks! :octopus:

**Comment by rpowelll** [comment]
I'm still encountering this issue on the latest version of fastlane, 1.80.0 as of writing this.

**Comment by TKBurner** [comment]
Hi @rpowelll! Great to hear from you! Can you send over the full output when you run 'fastlane init' also can you send the output for fastlane -v.

Thanks!

**Comment by tadija** [comment]
Hello, I'm having similar problem, my output from `fastlane init` is reported in Issue #4236.

**Comment by siemensikkema** [comment]
I have the same issue on 1.88.0.

**Comment by TKBurner** [comment]
@siemensikkema Thanks for reaching out. You can enter any address not associated with an ITC account and not sync the metadata. Let me know how it goes!

**Comment by siemensikkema** [comment]
While that seems like a good workaround, provided one has access to such an account, my hack of choice was to temporarily comment out the relevant part in the setup script ;)

**Comment by TKBurner** [comment]
@siemensikkema Thanks for following up. Sorry I meant literally any email address!

**Comment by Jerrot** [comment]
@TKBurner We still *want* fastlane to use our Apple IDs to deal with the developer portal. :)
I'd like to see an option though to skip the iTunes Connect part in "fastlane init" completely. 

In my case, my Apple ID is part of an In-House team (Enterprise) in the developer portal, but on iTunes Connect, it's only part of two other teams - which are not related at all to the in house team. Still I'm forced to select one of them (or if there only was one, it would be auto-selected).
So I don't want fastlane to create an app into one of those iTunes Connect teams at all. 

@siemensikkema thanks for that hack idea. ;)

**Comment by katunch** [comment]
Hi 
I'm struggling with the same issue. I have an Apple ID which is a part of an enterprise account. So no iTunes Connect is available. I'm forced to do the `fastlane init` by hand and create the files manually. 

It would be a great feature to skip the iTunes Connect setup for enterprise Apps.

**Comment by TKBurner** [comment]
@katunch Thanks for the feedback. We'll leave this open as a feature request 👍
