### ISSUE TITLE
Could not find app with app identifier 'com.bundle.id' in your iTunes Connect account (apple_id@domain.com - Team: XXXXXX)

### ISSUE THREAD

**Issue by vincedev** [fastlane/fastlane#12055]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

`fastlane` deliver fails to find my app on ITC, although bundle ID, team iD, etc are correct.
Can someone give me advices on how to debug this issue please ?

Same command works for the iOS version of the app, although the bundle ID end is different.
Both apps are on ITC, Mac app isn't released yet and I hoped to use fast lane to upload all the associated metadata.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
$ bundle exec fastlane mac deliver_metadata
[[✔] 🚀
[15:44:31]: Driving the lane 'mac deliver_metadata' 🚀
[15:44:31]: ----------------------------------------------------------
[15:44:31]: --- Step: Switch to mac deliver_appstore_metadata lane ---
[15:44:31]: ----------------------------------------------------------
[15:44:31]: Cruising over to lane 'mac deliver_appstore_metadata' 🚖
[15:44:31]: ----------------------------------
[15:44:31]: --- Step: get_info_plist_value ---
[15:44:31]: ----------------------------------
[15:44:31]: -----------------------------------------------------------------------
[15:44:31]: --- Step: cd .. && sh scripts/export_appstore_metadata.sh macOS 1.0 ---
[15:44:31]: -----------------------------------------------------------------------
[15:44:31]: $ cd .. && sh scripts/export_appstore_metadata.sh macOS 1.0
[15:44:31]: ▸ Not found export app_mac_app_store
[15:44:31]: ----------------------------------
[15:44:31]: --- Step: get_info_plist_value ---
[15:44:31]: ----------------------------------
[15:44:31]: ---------------------
[15:44:31]: --- Step: deliver ---
[15:44:31]: ---------------------
[15:44:31]: Login to iTunes Connect (apple_id@domain.com)
[15:44:34]: Login successful
[15:44:35]: --------------------------
[15:44:35]: --- Step: notification ---
[15:44:35]: --------------------------
+-----------------------------------+----------------------+
|                       Lane Context                       |
+-----------------------------------+----------------------+
| PLATFORM_NAME                     | mac                  |
| LANE_NAME                         | mac deliver_metadata |
| GET_INFO_PLIST_VALUE_CUSTOM_VALUE | 1.0                  |
+-----------------------------------+----------------------+
[15:44:35]: Could not find app with app identifier 'com.bundle.id' in your iTunes Connect account (apple_id@domain.com - Team: XXXXXX)

+------+-----------------------------------------------------------+-------------+
|                                fastlane summary                                |
+------+-----------------------------------------------------------+-------------+
| Step | Action                                                    | Time (in s) |
+------+-----------------------------------------------------------+-------------+
| 1    | Switch to mac deliver_appstore_metadata lane              | 0           |
| 2    | get_info_plist_value                                      | 0           |
| 3    | cd .. && sh scripts/export_appstore_metadata.sh macOS 1.0 | 0           |
| 4    | get_info_plist_value                                      | 0           |
| 💥   | deliver                                                   | 3           |
| 6    | notification                                              | 0           |
+------+-----------------------------------------------------------+-------------+

[15:44:35]: fastlane finished with errors

[!] Could not find app with app identifier 'com.bundle.id' in your iTunes Connect account (apple_id@domain.com - Team: XXXXXX)
  </pre>
</details>

### Environment

<details>
  <pre>
### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.3 (17D102)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.85.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.6        |
| rake                      | 12.3.0       |
| CFPropertyList            | 2.3.6        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| cork                      | 0.3.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| fuzzy_match               | 2.0.4        |
| cocoapods-core            | 1.4.0        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.4        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| cocoapods                 | 1.4.0        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.14.0       |
| faraday-http-cache        | 1.3.1        |
| git                       | 1.3.0        |
| kramdown                  | 1.16.2       |
| no_proxy_fix              | 0.1.2        |
| sawyer                    | 0.8.1        |
| octokit                   | 4.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| danger                    | 5.5.10       |
| thor                      | 0.20.0       |
| danger-swiftlint          | 0.13.1       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.60.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>
  </pre>
</details>

**Comment by vincedev** [comment]
I tested with another Mac app that waits to be published for the first time, and I had the same issue.   
Looks like it's related to Mac apps, no problem with any other iOS app.

**Comment by vincedev** [comment]
Hi!

Does anyone can/did try to reproduce this ?

**Comment by joshdholtz** [comment]
@vincedev Hey 👋 Can you provide me with a sample of what your `Fastfile` looks like?

**Comment by vincedev** [comment]
Hi @joshdholtz, sure, here is an excerpt :

```ruby
platform :mac do
  ### PUBLIC macOS LANES ###
  desc "Upload app metadata to iTunes Connect"
  lane :deliver_metadata do |options|
    deliver_appstore_metadata()
  end
end

private_lane :deliver_appstore_metadata do |options|
  deliver(
    app_version: version_number,
    skip_screenshots: true,
    automatic_release: false,
    phased_release: true,
    metadata_path: "./fastlane/metadata_#{ENV["TARGET"].downcase}"
  )
end

def version_number
  "#{get_info_plist_value(path: ENV['PLIST'], key: 'CFBundleShortVersionString')}"
end
```

Our `AppFile` looks like this :

```ruby
itc_team_id "XXXXXX"

for_platform :mac do
  app_identifier "com.bundle.id"
end
```

We have double checked team ID and app identifier, and they are both correct.

**Comment by joshdholtz** [comment]
@vincedev Good-ish news! I can recreate the issue 😝 Bad news, we have this issue 😉 Looking into this right now!

**Comment by joshdholtz** [comment]
@vincedev Hey! Quick fix... add `platform: 'osx'` into your `deliver` options 🙃 

It looks like `deliver` is detecting the platform incorrectly. I will be making a PR to fix this. Sorry about the issues! ❤️

**Comment by joshdholtz** [comment]
Last comment... Looks like `gym` isn't building the `.pkg` file  correctly 😢 Now looking into that

**Comment by vincedev** [comment]
@joshdholtz Thank you for your response, adding the parameter does indeed make deliver work as expected 👍.

Looking forward to a fastlane update ! Thanks again.

**Comment by joshdholtz** [comment]
@vincedev Did `deliver` actually upload a new version for you?! I couldn't get `gym` to build a `.pkg` file, only a `.app`. Does `gym` build a `.pkg` for you?

**Comment by vincedev** [comment]
I didn't try this actually, I'm using deliver only to upload the app's metadatas to ITC.

**Comment by vincedev** [comment]
But this time deliver didn't complain about my app identifier, so I guess it's all good.

**Comment by joshdholtz** [comment]
@vincedev Oh interesting! That should work then.

I discovered during this that `gym` doesn't actually build a `.pkg` for uploading so I got that "solved " right now 😝 I need to make the code prettier now but soon you will **actually** be able to call `gym` on a Mac app again 🙃 

How are you packing your Mac app right now? Would you be able to test my code change for me when I got it ready?

**Comment by vincedev** [comment]
> How are you packing your Mac app right now?

I have been using Xcode to archive and upload the app on ITC, but I suppose Xcode is doing a `.pkg` out the archive with the app ?

> Would you be able to test my code change for me when I got it ready?

Sure, tell me how to do the test though :)

**Comment by joshdholtz** [comment]
@vincedev I have a PR here - https://github.com/fastlane/fastlane/pull/12195

1. Change your `Gemfile` to be 
    ```rb
    gem 'fastlane', git: 'https://github.com/fastlane/fastlane.git', branch: 'joshdholtz-make-gym-mac-again'
    ````
2. Run `bundle install` to pull down my specific branch
3. Configure `gym` like...
   ```rb
   gym(
     export_method: 'app-store',

     # Our new Mac signing/packaging options
     mac_app_distribution_cert_name: '3rd Party Mac Developer Application: Something LLC (ABC1234XYZ)',
     mac_app_installer_cert_name: '3rd Party Mac Developer Installer: Something LLC (ABC1234XYZ)'
   )
   ```

This _should_ be all you need to do. You can get those names of the certs from `Keychain Access`. Let me know if you have any questions or issues! ❤️

**Comment by vincedev** [comment]
Hi @joshdholtz 

After switching to your branch and tried, I got the following error :

```
[...]
[11:23:04]: undefined method `confg' for Gym:Module
Did you mean?  config
               config=

[...]

[11:23:04]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

[...]

bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/2.4.0/bin/fastlane)
NoMethodError: [!] undefined method `confg' for Gym:Module
Did you mean?  config
               config=
Did you mean?  config
               config=
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/gym/lib/gym/runner.rb:198:in `build_mac_pkg'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/gym/lib/gym/runner.rb:39:in `run'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/gym/lib/gym/manager.rb:19:in `work'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/actions/build_ios_app.rb:65:in `run'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/runner.rb:231:in `chdir'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
  Fastfile:146:in `block in parsing_binding'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
  Fastfile:106:in `block in parsing_binding'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
  Fastfile:67:in `block (2 levels) in parsing_binding'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/lane_manager.rb:57:in `cruise_lane'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/fastlane/lib/fastlane/cli_tools_distributor.rb:107:in `take_off'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-a86b541f61c9/bin/fastlane:20:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/bin/fastlane:22:in `load'
  /usr/local/lib/ruby/gems/2.4.0/bin/fastlane:22:in `<top (required)>'
```

And we called `gym` this way :

```
gym(
    scheme: ENV["SCHEME"],
    export_method: "app-store",
    export_options: { compileBitcode: false },
    mac_app_distribution_cert_name: '3rd Party Mac Developer Application: MyComp (XXXXXX)',
    mac_app_installer_cert_name: '3rd Party Mac Developer Installer: MyComp (XXXXXX)',
    clean: true
 )
```

**Comment by vincedev** [comment]
I also tried again `deliver`, this time without specifying the `platform` parameter, I got the same error as previously.

**Comment by joshdholtz** [comment]
@vincedev OMG, I have no idea how that happened 😱 How embarrassing... I just pushed a fix. Can you try again whenever you get a chance? 😊

**Comment by vincedev** [comment]
Hi @joshdholtz, sorry for being this late, still getting the error though :/

**Comment by joshdholtz** [comment]
@vincedev Ahhhh, looks like I made the change locally but forgot to push 😱 I swear I know what I'm doing 🙃 NOW.... the fix should be there - https://github.com/fastlane/fastlane/pull/12195/commits/5f6ba6caef7b2316597d07f54c4608f289a8130f

**Comment by vincedev** [comment]
Hi @joshdholtz . Yes this time it's there and I think we made progress.
Still getting an error but a different one :

```
[13:53:58]: undefined local variable or method `plist_file' for #<Gym::Runner:0x007fc836cae3c8>
Did you mean?  plist_path
```

Here is the stack :

```
bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/2.4.0/bin/fastlane)
NameError: [!] undefined local variable or method `plist_file' for #<Gym::Runner:0x007fc836cae3c8>
Did you mean?  plist_path
Did you mean?  plist_path
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/gym/lib/gym/runner.rb:212:in `build_mac_pkg'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/gym/lib/gym/runner.rb:39:in `run'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/gym/lib/gym/manager.rb:19:in `work'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/actions/build_ios_app.rb:65:in `run'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/runner.rb:231:in `chdir'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
  Fastfile:146:in `block in parsing_binding'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
  Fastfile:106:in `block in parsing_binding'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
  Fastfile:67:in `block (2 levels) in parsing_binding'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/lane_manager.rb:57:in `cruise_lane'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
  /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/fastlane/lib/fastlane/cli_tools_distributor.rb:107:in `take_off'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-5f6ba6caef7b/bin/fastlane:20:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/bin/fastlane:22:in `load'
  /usr/local/lib/ruby/gems/2.4.0/bin/fastlane:22:in `<top (required)>'
```

**Comment by joshdholtz** [comment]
@vincedev Ah yes! I did mean that 😊 I pushed a fix but this will still probably error out since it won't it looks like its not finding your plist file from your project settings properly 😔

**Comment by vincedev** [comment]
@joshdholtz you are welcome, no problem.

BTW, I just retried and it now looks like `gym` can't find the `Info.plist` file, although I did put its path in the environment.

```
[14:40:44]: Cannot find Info.plist file for project at 'App macOS/Supporting Files/Info.plist'

[...]

bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/2.4.0/bin/fastlane)
FastlaneCore::Interface::FastlaneCrash: [!] Cannot find Info.plist file for project at 'App macOS/Supporting Files/Info.plist'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-bd4c3444f250/fastlane_core/lib/fastlane_core/ui/interface.rb:121:in `crash!'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-bd4c3444f250/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-bd4c3444f250/gym/lib/gym/runner.rb:212:in `build_mac_pkg'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-bd4c3444f250/gym/lib/gym/runner.rb:39:in `run'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-bd4c3444f250/gym/lib/gym/manager.rb:19:in `work'
  /Users/vince/.bundle/ruby/2.4.0/fastlane-bd4c3444f250/fastlane/lib/fastlane/actions/build_ios_app.rb:65:in `run'
[...]
```

The plist file in fact is a level lower deep in the hierarchy in `App macOS/App macOS/Supporting Files/Info.plist` (the path specified in the environment)

**Comment by joshdholtz** [comment]
@vincedev Ahhh, weird! I will look into 😊 Thanks again! My project found the plist find but I also have the most basic macOS project possible 😛

**Comment by vincedev** [comment]
Hi @joshdholtz , did you made any progress on this ? I'm ready to test if you need.

**Comment by joshdholtz** [comment]
@vincedev Ah no, I did not yet but I want to 😊 I will look at sometime this week 💪

**Comment by iOSDeveloperL** [comment]
I'm getting the same error. tried adding `platform: "ios"` but that doesn't help.

**Comment by franco640** [comment]
Currently using fastlane-2.97.0 and I'm using the terminal command "fastlane deliver init" but I am currently getting the "Could not find app with app identifier" . I'm trying to get the metadata from a Mac App not iOS app. I get the following in your iTunes Connect account (******* - Team: 108936). I am admin and the bundle id is correct from the iTunes connect.  Please note that I am not uploading a build as i'm doing this through application loader. All I require is that I want to upload the Localisation txt for all the apps that I will be uploading.  Any help would be greatly appreciated. P.S I tried this with iOS app and works fine.
