### ISSUE TITLE
Gym finish with error - exit code 65

### ISSUE THREAD

**Issue by palusik86** [fastlane/fastlane#12135]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have error "Exit status 65", nothing special, I always was able to find reason of error, but not this time. No error in logs from xcodebuild/gym. Running gym almost always fails, 1 on 10/20 builds are success. 
Last line in gym log is: 
<details>
<pre>
`Touch build/App\ Name.DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/App\ Name/BuildProductsPath/Release-iphoneos/App\ Name.app.dSYM
    cd /Users/pawel/Documents/Projects/Project
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/(User)/.rvm/gems/ruby-2.4.0/bin:/Users/(User)/.rvm/gems/ruby-2.4.0@global/bin:/Users/(User)/.rvm/rubies/ruby-2.4.0/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/(User)/.rvm/bin"
    /usr/bin/touch -c /Users/(User)/Documents/Projects/Project/build/App\
Name.DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/App\ Name/BuildProductsPath/Release-iphoneos/App\ Name.app.dSYM`
</pre>
</details>

Lasts part of output from lane:

<details>
  <pre>▸ Running script 'Run Script'
▸ Running script '[CP] Embed Pods Frameworks'
▸ Running script '[CP] Copy Pods Resources'
▸ Running script 'SafeDK'
▸ Copying build/Appname.DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/Appname/BuildProductsPath/Release-iphoneos/Appname NSE.appex
▸ Running script 'Carthage'
▸ Touching Appname.app
▸ Signing build/Appname.DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/Appname/InstallationBuildProductsLocation/Applications/Appname.app
▸ Touching Appname.app.dSYM
** ARCHIVE FAILED **
ERROR [2018-03-22 13:01:56.80]: Exit status: 65
INFO [2018-03-22 13:01:56.81]: 
WARN [2018-03-22 13:01:56.81]: Maybe the error shown is caused by using the wrong version of Xcode
WARN [2018-03-22 13:01:56.81]: Found multiple versions of Xcode in '/Applications/'
WARN [2018-03-22 13:01:56.81]: Make sure you selected the right version for your project
WARN [2018-03-22 13:01:56.82]: This build process was executed using '/Applications/Xcode.app'
WARN [2018-03-22 13:01:56.82]: If you want to update your Xcode path, either
INFO [2018-03-22 13:01:56.82]: 
INFO [2018-03-22 13:01:56.82]: - Specify the Xcode version in your Fastfile
INFO [2018-03-22 13:01:56.82]: ▸ xcversion(version: "8.1") # Selects Xcode 8.1.0
INFO [2018-03-22 13:01:56.82]: 
INFO [2018-03-22 13:01:56.82]: - Specify an absolute path to your Xcode installation in your Fastfile
INFO [2018-03-22 13:01:56.82]: ▸ xcode_select "/Applications/Xcode8.app"
INFO [2018-03-22 13:01:56.82]: 
INFO [2018-03-22 13:01:56.82]: - Manually update the path using
INFO [2018-03-22 13:01:56.82]: ▸ sudo xcode-select -s /Applications/Xcode.app
INFO [2018-03-22 13:01:56.82]: </pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.13.3 (17D47)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0e  16 Feb 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

fastlane_version "2.60"
# Custom functions
require "./loaders.rb"
require "./filters.rb"
# This is the minimum version number required.
import "./Match"
import "./Tools"
import "./Metrics"
# Imports above

# FASTLANE JOBS

default_platform :ios

platform :ios do

  desc "Run metrics for app. @options: appname - name of app to run"
  lane :metrics do |options|
    appname = options[:appname]
    scheme = filter_by_scheme_name(appname).first
    isOclint = scheme["isOclint"]
    isSwiftlint = scheme["isSwiftlint"]
    isCarthage = scheme["isCarthage"]
  	isCocoapods = scheme["isCocoapods"]

    make(isCarthage: isCarthage,
  		   isCocoapods: isCocoapods)

    run_metrics(scheme: scheme,
    			 isOclint: isOclint,
            	        isSwiftlint: isSwiftlint)
  end
  desc "Release for internal tests using fabric. @options: appname - name of app to build"
  lane :fabric do |options|
  	
  	appname = options[:appname]
  	config = load_config()
  	scheme = filter_by_scheme_name(appname).first
  	scheme_name = scheme["scheme"]
  	workspace_name = scheme["xcworkspace"]
  	xcproj_name = scheme["xcproj"]
  	default_config = config["default_config"]
  	crashlytics_path = config["crashlytics_path"]
  	isCarthage = scheme["isCarthage"]
  	isCocoapods = scheme["isCocoapods"]

  	make(isCarthage: isCarthage,
  		 isCocoapods: isCocoapods)

  	# download_profiles_read_only - dsiabled for now

  	run_fabric(scheme: scheme_name,
  			   config: default_config,
  			   xcworkspace: workspace_name,
  			   xcproj: xcproj_name,
  			   crashlytics_path: crashlytics_path)
  end

  desc "Build app lane. @options: appname - name of app to build"
  lane :build do |options|

  	  appname = options[:appname]
  	  config = load_config()
  	  scheme = filter_by_scheme_name(appname).first
  	  scheme_name = scheme["scheme"]
  	  workspace_name = scheme["xcworkspace"]
  	  isCarthage = scheme["isCarthage"]
  	  isCocoapods = scheme["isCocoapods"]
  	  default_config = config["default_config"]
  	  clean = true
  	  export = "ad-hoc"

	  make(isCarthage: isCarthage,
	  	   isCocoapods: isCocoapods)
      # download_profiles_read_only - dsiabled for now
      run_build(export: export,
      			workspace: workspace_name,
      			scheme: scheme_name,
      			config: default_config,
      			clean: true)
  end

  desc "Test on app. @options: appname - name of app to test"

  lane :test do |options|
  	appname = options[:appname]
  	scheme = filter_by_scheme_name(appname).first
  	isCarthage = scheme["isCarthage"]
  	isCocoapods = scheme["isCocoapods"]
  	isTestable = scheme["unit_tests"]

  	if isTestable == true
	  	make(isCarthage: isCarthage,
	 		 isCocoapods: isCocoapods)
		run_test(scheme: scheme)
  	end
  end

  # PRIVATE lanes

  private_lane :run_fabric do |options|

    scheme_name = options[:scheme]
    config =  options[:config]
    build_number = number_of_commits
    project_name = options[:xcproj]
    workspace_name = options[:xcworkspace]
    crashlytics_path = options[:crashlytics_path]
    export = "ad-hoc"
    version_number = get_version_number(xcodeproj: "#{project_name}.xcodeproj")
    git_tag = "CI/v#{version_number}/##{build_number}"

    m_build_number = "Build number: #{build_number}"
    m_build_branch = "Branch: #{git_branch}"
    m_build_commit = "Commit: #{last_git_commit[:abbreviated_commit_hash]}"
    # m_groups = ENV["CRASHLYTICS_GROUPS"]
    # m_comments = ENV["CRASHLYTICS_NOTES"]
    m_groups = "developers"
    m_comments = "Fastlane test of Fabric upload"
    
    message = [
      m_build_number,
      m_build_branch,
      m_build_commit,
      "GIT TAG: #{git_tag}",
      "Groups: #{m_groups}",
      "Release Notes: #{m_comments}"
    ]
    .join("\n")

    increment_build_number(
       build_number: build_number,
       xcodeproj: "#{project_name}.xcodeproj")

	  run_build(export: export,
	  		      workspace: workspace_name,
	  		      scheme: scheme_name,
	  		      config: config)

    crashlytics(
         crashlytics_path: "#{crashlytics_path}",
         api_token: "token",
         build_secret: "secret",
         notes: "#{message}",
         groups: m_groups)

    if !git_tag_exists(tag: git_tag)
        add_git_tag(tag: git_tag)
        push_git_tags
    end

    notifier(message: message,
             success: true)
  end

  desc "Runs all the tests"
  private_lane :run_test do |options|

  schemes = options[:scheme]
	devices = load_devices()
	schemeName = scheme["scheme"]
	scan(
	    scheme: "#{schemeName}Tests",
	    code_coverage: true,
	    clean: true,
	    skip_build: false,
	    devices: devices,
	    output_style: "basic",
	    derived_data_path: "./build/#{schemeName}.DerivedData",
	    output_directory: "./build/#{schemeName}.reports/")
  end

  # Fastlane cycles

  before_all do
      unlock_keychain(path: "login.keychain-db",
                      add_to_search_list: :replace,
                      password: "Password")
      sh("rm -rf /build")
  end

  after_all do |lane|
  	  appname = ENV["APPNAME"]
           notifier(message: "CI build for #{appname} completed",
            success: true)
  end

  # Error handling

  error do |lane, exception, options|
      message = [
      "Exception: #{exception}",
      "Options: #{options}",
      "On Lane: #{lane}"
      ]
      .join("\n")

    notifier(message: message,
             success: false)
  end
end

desc "Build lane"
  lane :run_build do |options|

      export = options[:export]
      workspace = options[:workspace]
      scheme = options[:scheme]
      config = options[:config]

      if options[:clean] == true
	      run_clean(scheme: scheme,
	                xcworkspace: workspace)
      end

      gym(workspace: "#{workspace}.xcworkspace",
          scheme: scheme,
          configuration: config,
          include_bitcode: false,
          export_method: export,
          clean: true,
          xcpretty_report_json: "./compile_commands.json",
          derived_data_path: "./build/#{scheme}.DerivedData",
          output_name: "#{scheme}.ipa")
  end

  private_lane :run_clean do |options|
        workspace = options[:xcworkspace]
        scheme = options[:scheme]

        xcclean(workspace: "#{workspace}.xcworkspace",
                scheme: scheme)

        clear_derived_data
  end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.86.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                   | Version      |
| --------------------- | ------------ |
| did_you_mean          | 1.1.2        |
| slack-notifier        | 2.3.2        |
| atomos                | 0.1.2        |
| claide                | 1.0.2        |
| colored2              | 3.1.2        |
| nanaimo               | 0.2.3        |
| xcodeproj             | 1.5.6        |
| multipart-post        | 2.0.0        |
| word_wrap             | 1.0.0        |
| public_suffix         | 2.0.5        |
| tty-screen            | 0.6.4        |
| tty-cursor            | 0.5.0        |
| tty-spinner           | 0.8.0        |
| babosa                | 1.0.2        |
| colored               | 1.2          |
| commander-fastlane    | 4.4.6        |
| unf                   | 0.1.4        |
| domain_name           | 0.5.20170404 |
| http-cookie           | 1.0.3        |
| faraday-cookie_jar    | 0.0.6        |
| gh_inspector          | 1.1.3        |
| mini_magick           | 4.5.1        |
| multi_xml             | 0.6.0        |
| rubyzip               | 1.2.1        |
| security              | 0.1.3        |
| naturally             | 2.1.0        |
| simctl                | 1.6.2        |
| declarative-option    | 0.1.0        |
| representable         | 3.0.4        |
| mime-types-data       | 3.2016.0521  |
| mime-types            | 3.1          |
| httpclient            | 2.8.3        |
| google-api-client     | 0.13.6       |
| openssl               | 2.0.4        |
| highline              | 1.7.10       |
| io-console            | 0.4.6        |
| excon                 | 0.61.0       |
| CFPropertyList        | 2.3.6        |
| mini_portile2         | 2.3.0        |
| nokogiri              | 1.8.2        |
| plist                 | 3.4.0        |
| faraday               | 0.14.0       |
| faraday_middleware    | 0.12.2       |
| os                    | 0.9.6        |
| googleauth            | 0.6.2        |
| signet                | 0.8.1        |
| fastimage             | 2.1.1        |
| json                  | 2.1.0        |
| bundler               | 1.16.0       |
| terminal-table        | 1.8.0        |
| unicode-display_width | 1.3.0        |
</details>

*generated on:* **2018-03-22**
</details></pre>
</details>

**Comment by ladislas** [comment]
same exit code issue here.

In my case it's complaining about not finding the right scheme... used to work last week. Haven't touche my fastfile, only updated fastlane to the latest version.

**Comment by palusik86** [comment]
So there is some issue then, or gym was change somehow.

**Comment by joshdholtz** [comment]
@palusik86 What was the exact terminal command you were using that was working?

@tootsweet @ladislas Are your issues fixed with the latest version (2.88.0)? If not, can you try making sure your schemes are marked as “Shared” and see if that helps?

**Comment by palusik86** [comment]
This is output from gym:
`set -o pipefail && xcodebuild -workspace workspace.xcworkspace -scheme Appl\ Name\  -configuration Release -destination 'generic/platform=iOS' -archivePath /Users/(User)/Library/Developer/Xcode/Archives/2018-04-01/App\ Name\ 2018-04-01\ 11.15.26.xcarchive -derivedDataPath './build/App Name Scores.DerivedData' clean archive | tee /Users/(User)/Library/Logs/gym/App\ Name\ -App\ Name.log | xcpretty  --report json-compilation-database --output  ./compile_commands.json`

This is the last line in log (I was mistaken, ipa file is not valid):
`Touch build/App\ Name.DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/App\ Name/BuildProductsPath/Release-iphoneos/App\ Name.app.dSYM
    cd /Users/pawel/Documents/Projects/Project
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/(User)/.rvm/gems/ruby-2.4.0/bin:/Users/(User)/.rvm/gems/ruby-2.4.0@global/bin:/Users/(User)/.rvm/rubies/ruby-2.4.0/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/(User)/.rvm/bin"
    /usr/bin/touch -c /Users/(User)/Documents/Projects/Project/build/App\
Name.DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/App\ Name/BuildProductsPath/Release-iphoneos/App\ Name.app.dSYM`

**Comment by tootsweet** [comment]
Hello,

Updating doesn't fix it.
The "Shared" option maked it work on both versions (2.86.2 and 2.89.0).

**Comment by palusik86** [comment]
I should add here, that all common mistakes/issue is know for me (like shared scheme). Double checked everything that I'm aware of.

**Comment by joshdholtz** [comment]
@palusik86 Can your lane with `--verbose` and paste the whole output from start to finish? Its hard to see what is all going on with only snippets 🙃

**Comment by joshdholtz** [comment]
@tootsweet So just to clarify, things _are_ working for you now?

**Comment by palusik86** [comment]
@joshdholtz 
Here you go:

<details>
https://paste.ofcode.org/L2LZCyTHhGKMvrKdNY49jk
</details>

**Comment by tootsweet** [comment]
@joshdholtz / Yes it does

**Comment by joshdholtz** [comment]
@palusik86 It looks this _may_ be an issue with generating the dSYM with your derived data? Reasons being that the "Archived failed" error is happening right having "Touching .dSYM". Maybe try one or multiple of these solutions?
1) Make sure you `derived_data_path` is correct
2) Look at this issue - https://github.com/fastlane/fastlane/issues/6456#issuecomment-254888665 (This error occurred with some faulty PNGs that weren't getting crushed properly or something)
3) Maybe try switching over the standard/default derived data path if you can
4) Try turning creating a dSYM off completely in the build settings and see if things success 😬

**Comment by joshdholtz** [comment]
Closing this since no activity 🙃

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ninjazoete** [comment]
I have exactly same issue here. I have been trying to finish GYM action for 2 days and exact same problem happenes. It exits with 65 code when touching .dSYM file.

Fastlane 2.99.0
