### ISSUE TITLE
Unable to upload ipa to Appaloosa store

### ISSUE THREAD

**Issue by pcl-ext** [fastlane/fastlane#1331]
![screen shot 2016-02-17 at 16 00 56](https://cloud.githubusercontent.com/assets/17179351/13113584/ebc00fb6-d58f-11e5-8971-45cb921eceb6.png)

I think that the problem is that in the file appaloosa.rb you are using the V1 of the API but the API is in V2 now and they don't use API V1 anymore

**Comment by ohwutup** [comment]
thanks for opening this issue, @pcl-ext! we are about to merge a PR from @benoittgt for some appaloosa changes. follow this PR for updates! https://github.com/fastlane/fastlane/pull/1366

**Comment by benoittgt** [comment]
Thanks @pcl-ext for the feedback. It should be fixed with the updated version.

**Comment by pberanger** [comment]
@benoittgt : Just tested to upload an ipa with appaloosa an same issue again 

![image](https://cloud.githubusercontent.com/assets/866266/14645915/dae0c25a-0657-11e6-9a7b-95577d146425.png)

**Comment by benoittgt** [comment]
@pberanger thanks for the report. We will take a look.

**Comment by benoittgt** [comment]
@pberanger Could you attach the crash report ?

**Comment by pberanger** [comment]
@benoittgt : Voilà !

[sentry_579eaad191d67a7418c19ac4690419dd.json.zip](https://github.com/fastlane/fastlane/files/226300/sentry_579eaad191d67a7418c19ac4690419dd.json.zip)

**Comment by TKBurner** [comment]
@benoittgt Thanks for working on this. Let me know if you need anything on our end 👍

**Comment by benoittgt** [comment]
@TKBurner @pberanger it seems this error happen when server returns an HTTPForbidden and the fastlane action try to parse the failure answer. I've updated the code to get a better feedback when this happen. Also fix an error with SSL. Tested on production and it's work. 

Thanks a lot for reporting this issue.

**Comment by TKBurner** [comment]
Hi @benoittgt! Thanks for following up. I'll make sure we get some eyes on your pull request. Thanks!

**Comment by pcl-ext** [comment]
@benoittgt Thanks ! I'm using your fork with your recent modifications. But still having an error while trying to upload to Appaloosa : 

![capture d ecran 2016-04-29 a 09 59 19](https://cloud.githubusercontent.com/assets/17179351/14910837/3b2c8090-0df1-11e6-8f6a-9fd81ede277d.png)

My API token and store ID are OK, so I don't really understand where this error comes from.

**Comment by benoittgt** [comment]
@pcl-ext can you join the support on our frontpage with intercom ?

**Comment by pcl-ext** [comment]
@benoittgt Yes, I will do it now

**Comment by benoittgt** [comment]
@vpolouchkine I think this issue can be close. The problem was related to credentials given to Fastlane not fastlane itself. 

Thanks in advance.

**Comment by TKBurner** [comment]
@benoittgt Thanks for keeping us updated and being part of our ecosystem 👍 Hope you have a wonderful weekend!
