### ISSUE TITLE
[Regression] Breaking change when importing a new cert in 2.113.0, worked in 2.112.0

### ISSUE THREAD

**Issue by nemui** [fastlane/fastlane#14039]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
There is an error message when importing a new certificate:
```
Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
Check if you supplied the correct `keychain_password` for keychain: `/Users/dmitry/Library/Keychains/fastlane.keychain-db`

[17:59:19]: 
[17:59:19]: Please look at the following docs to see how to set a keychain password:
[17:59:19]:  - https://docs.fastlane.tools/actions/sync_code_signing
[17:59:19]:  - https://docs.fastlane.tools/actions/get_certificates
```

This leads to build failures in CI because of the UI permission popup.
Keychain password in supplied in the Match file, as per details below.

##### Command executed

```
fastlane certificates
```
^ this installs certificates for various build types
##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>:fastlane dmitry$ fastlane certificates
[09:51:41]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[09:51:43]: ----------------------------------------
[09:51:43]: --- Step: Verifying fastlane version ---
[09:51:43]: ----------------------------------------
[09:51:43]: Your fastlane version 2.113.0 matches the minimum requirement of 2.44.1  ✅
[09:51:43]: ------------------------------
[09:51:43]: --- Step: default_platform ---
[09:51:43]: ------------------------------
[09:51:43]: Driving the lane 'certificates' 🚀
[09:51:43]: -----------------------------
[09:51:43]: --- Step: delete_keychain ---
[09:51:43]: -----------------------------
[09:51:43]: -----------------------------
[09:51:43]: --- Step: create_keychain ---
[09:51:43]: -----------------------------
[09:51:43]: $ security list-keychains -d user
[09:51:43]: ▸ "/Users/dmitry/Library/Keychains/login.keychain-db"
[09:51:43]: -------------------
[09:51:43]: --- Step: match ---
[09:51:43]: -------------------
WARNING: You are running Ruby 2.2.4, which has reached end-of-life and is no longer supported by Ruby Core.
The Google Cloud API clients work best on supported versions of Ruby. It is strongly recommended that you upgrade to Ruby 2.4 or later.
See https://www.ruby-lang.org/en/downloads/branches/ for more info on the Ruby maintenance schedule.
To suppress this message, set the GOOGLE_CLOUD_SUPPRESS_RUBY_WARNINGS environment variable.
[09:51:43]: Successfully loaded '/Users/dmitry/Documents/development/fastlane/fastlane/Matchfile' 📄

+-------------------+--------------------------------------+
|       Detected Values from './fastlane/Matchfile'        |
+-------------------+--------------------------------------+
| git_url           | REDUCTED                       |
| type              | development                          |
| readonly          | true                                 |
| keychain_name     | fastlane.keychain                    |
| keychain_password | temppassword                         |
+-------------------+--------------------------------------+

+-----------------------+--------------------------------------+
|                  Summary for match 2.113.0                   |
+-----------------------+--------------------------------------+
| type                  | development                          |
| readonly              | true                                 |
| app_identifier        | ["REDUCTED"]                 |
| username              | REDUCTED      |
| storage_mode          | git                                  |
| git_url               | REDUCTED                       |
| git_branch            | master                               |
| shallow_clone         | false                                |
| clone_branch_directly | false                                |
| keychain_name         | fastlane.keychain                    |
| keychain_password     | ********                             |
| force                 | false                                |
| force_for_new_devices | false                                |
| skip_confirmation     | false                                |
| skip_docs             | false                                |
| platform              | ios                                  |
| verbose               | false                                |
+-----------------------+--------------------------------------+

[09:51:43]: Cloning remote git repo...
[09:51:43]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[09:51:44]: 🔓  Successfully decrypted certificates repo
[09:51:44]: Installing certificate...
[09:51:44]: There are no local code signing identities found.
You can run `security find-identity -v -p codesigning fastlane.keychain` to get this output.
This Stack Overflow thread has more information: https://stackoverflow.com/q/35390072/774.
(Check in Keychain Access for an expired WWDR certificate: https://stackoverflow.com/a/35409835/774 has more info.)
[09:51:45]: 
[09:51:45]: Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
Check if you supplied the correct `keychain_password` for keychain: `/Users/dmitry/Library/Keychains/fastlane.keychain-db`

[09:51:45]: 
[09:51:45]: Please look at the following docs to see how to set a keychain password:
[09:51:45]:  - https://docs.fastlane.tools/actions/sync_code_signing
[09:51:45]:  - https://docs.fastlane.tools/actions/get_certificates

+-------------------+-------------------------------------------+
|                     Installed Certificate                     |
+-------------------+-------------------------------------------+
| User ID           | H78U838C7X                                |
| Common Name       | iPhone Developer: Jenkins CI (H24NQR3297) |
| Organisation Unit | REDUCTED                                |
| Organisation      | REDUCTED                         |
| Country           | US                                        |
| Start Datetime    | 2018-07-24 08:13:16 UTC                   |
| End Datetime      | 2019-07-24 08:13:16 UTC                   |
+-------------------+-------------------------------------------+

[09:51:45]: Installing provisioning profile...

+---------------------+------------------------+------------------------+
|                    Installed Provisioning Profile                     |
+---------------------+------------------------+------------------------+
| Parameter           | Environment Variable   | Value                  |
+---------------------+------------------------+------------------------+
| App Identifier      |                        | REDUCTED       |
| Type                |                        | development            |
| Platform            |                        | ios                    |
| Profile UUID        | sigh_ REDUCTED  | edae9a4e-d550-492a-9b  |
|                     | _development           | d5-1ff7d94b39cf        |
| Profile Name        | sigh_ REDUCTED  | match Development      |
|                     | _development_profile-  | REDUCTED       |
|                     | name                   | 1532420603             |
| Profile Path        | sigh_ REDUCTED  | /Users/dmitry/Library  |
|                     | _development_profile-  | /MobileDevice/Provisi  |
|                     | path                   | oning                  |
|                     |                        | Profiles/edae9a4e-d55  |
|                     |                        | 0-492a-9bd5-1ff7d94b3  |
|                     |                        | 9cf.mobileprovision    |
| Development Team ID | sigh_ REDUCTED  | 8P6Q66W4FV             |
|                     | _development_team-id   |                        |
+---------------------+------------------------+------------------------+

[09:51:45]: All required keys, certificates and provisioning profiles are installed 🙌</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.18.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.44.1"

before_all do
  update_fastlane
  ENV["keychain"] = "fastlane.keychain"
end

default_platform :ios

def ensure_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
  create_keychain(
    name: name,
    password: 'temppassword',
    unlock: true,
    timeout: false
  )
end

lane :certificates do
  ensure_temp_keychain(ENV["keychain"])
  match
  match(type: "appstore")
  match(app_identifier: "REDUCTED.*", type: "enterprise", git_branch: "PAW5F92N29")
  match(type: "adhoc")
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "REDUCTED" # the bundle identifier of your app
package_name "REDUCTED"   # the bundle identifier of your app

apple_id "REDUCTED" # Your Apple ID

json_key_file "REDUCTED.json"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.113.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| jwt                       | 1.5.6        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2019-01-09**
</details>
<details><summary><b>Match file</b></summary>
```
git_url("REDUCTED")

type("development")
readonly("true")

keychain_name(ENV["keychain"])
keychain_password("temppassword")
```
</details>
</pre>
</details>

**Comment by joshdholtz** [comment]
@nemui Looking into right now for you!

**Comment by joshdholtz** [comment]
@nemui Huh, I have no idea how it was building okay before but not building okay now then 😱 I might have to do some more digging to see if I can reproduce. Are you able to go back down to `2.112.0` to see if that still works fine for you and use that for now?

@appplemac Ah kk! I will also look into that setup as well 😊 I will let you know if there is anything else I need!

**Comment by castus** [comment]
We have also experienced this issue. We are building using Bitrise and it works very well for 2.112 but every build that was run on 2.113 was broken because of that Keychain issue.

**Comment by joshdholtz** [comment]
@castus Is the same thing happening to you where you are prompted for a keychain password when building?

**Comment by nemui** [comment]
@joshdholtz I have reverted to ```2.112.0``` for now, it works fine 👍

**Comment by castus** [comment]
We are creating keychain like that:

```
create_keychain(
    name: KEYCHAIN_NAME,
    password: CERTIFICATE_PASSWORD,
    default_keychain: false,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: true
  )
```

and then import the certificate to it, like that:
```
  import_certificate(
    keychain_name: KEYCHAIN_NAME,
    keychain_password: CERTIFICATE_PASSWORD,
    certificate_path: "#{WORK_DIR}/#{IOS_CERTIFICATES_DIR_NAME}/#{CERTIFICATE_NAME}",
    certificate_password: CERTIFICATE_PASSWORD,
    log_output: false
  )
```

And immediately after that we have an error from the issue's description. I don't know in which state is UI of the OS, because I'm building using Bitrise's machines.

**Comment by nemui** [comment]
@joshdholtz When running ```2.112.0``` with ```--verbose```, I can see the following output

```
$ security set-key-partition-list -S apple-tool:,apple: -k temppassword /Users/dmitry/Library/Keychains/fastlane.keychain-db
security: SecItemCopyMatching: The specified item could not be found in the keychain.
``` 
Looks like I have an issue here, although it doesn't seem to affect building process.

In ```2.113.0``` ```set-key-partition-list``` command is modified:

```
$ security set-key-partition-list -S apple-tool:,apple: -l 'Imported Private Key' -k temppassword /Users/dmitry/Library/Keychains/fastlane.keychain-db &> /dev/null
ERROR [2019-01-09 15:10:32.14]: 
ERROR [2019-01-09 15:10:32.14]: Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
Check if you supplied the correct `keychain_password` for keychain: `/Users/dmitry/Library/Keychains/fastlane.keychain-db`
```

**Comment by joshdholtz** [comment]
My guess here is the `-l 'Imported Private Key'` might be a bit too strong here. We added that because this command could take a really long time for users with a long list off signing identities (like up to a minute) but this might not be working properly.

If I create a branch to test this out, would you be able to specify my branch in a `Gemfile` (I'll give you what to put in three) to test it out? (If I'm not able to reproduce nicely on my side)

**Comment by nemui** [comment]
Yep!

**Comment by trentbb** [comment]
Experiencing the same issue here. Builds are not working 2.113.0 update

**Comment by CodeMonkeyPrime** [comment]
FWIW: We are having this issue as well on 2.113.0.  We're running on Travis and I have what appears to be the exact same two steps as posted by castus here: https://github.com/fastlane/fastlane/issues/14039#issuecomment-452729338

and we are seeing identical keychain warning/error messages and our builds are hanging when the keychain is first accessed (in this case, by Carthage copy frameworks step).

**Comment by joshdholtz** [comment]
I'm gunna see if I can get a branch out there for anybody to test in a few hours if anybody is willing to 😬 I'd like to get this fixed today if possible and working for as many people here as possible 💪

**Comment by BelfDev** [comment]
Same issue when running on CircleCI

**Comment by trentbb** [comment]
@joshdholtz Yes, using CircleCI. I'm able to get my builds to work for now by using 2.112.0

**Comment by marcomorain** [comment]
I'm getting the same on a Travis project 👍

**Comment by joshdholtz** [comment]
@marcomorain What's up? 😉 Long time no talk! I'm working on fixing/testing right now with a sample project of mine on Circle

**Comment by joshdholtz** [comment]
Okay, team! Let's give this a shot 😬 If I could get a few volunteers to replace `gem "fastlane"` in their `Gemfile` with the contents I have below and then run either `bundle install` or `bundle update fastlane` that would be great appreciated 🙏

```rb
source "https://rubygems.org"
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "joshdholtz-match-import-error-fix"
```

I _thiiiiiiinnnnnkkkkkk_ this will work but I'll still be 🤞🤞🤞🤞🤞🤞🤞🤞🤞🤞

**Comment by edcastparesh** [comment]
I'm getting the same on a Bitrise project

**Comment by ZionChang** [comment]
+1

**Comment by nemui** [comment]
@joshdholtz I have tested your branch and it seems to be working 🎆  
No ```Could not configure imported keychain item``` warning, local builds are fine.
Testing on Jenkins will take time, as we do not usually use bundler there, but so far your change looks good to me 👍

**Comment by joshdholtz** [comment]
@johnyorke Thanks for giving that a go! I made another change just now. Do you mind running `bundle update fastlane` and trying it again? 😇

**Comment by johnyorke** [comment]
@joshdholtz Sorry....still not working. Same output as above.

I should add that I'm adding a new keychain.
```
    sync_code_signing(
    type: 'appstore',
    git_url: 'git@github.com:**********/ios-certificates.git',
    username: 'ios@**********.com',
    keychain_name: KEYCHAIN_NAME,
    keychain_password: KEYCHAIN_PASSWORD
    )
```

**Comment by romk1n** [comment]
same issue on our end

**Comment by nemui** [comment]
@joshdholtz I have tried your branch on our CI setup around an hour ago - worked without issues.

**Comment by joshdholtz** [comment]
@nemui Woot! That's good news 😊

@johnyorke Did your setup work in version `2.112.0`?

**Comment by johnyorke** [comment]
@joshdholtz I can’t actually verify that as this is my first deployment to CircleCI. I worked through all the errors up to this point, then arrived at this one and saw there was a new issue where people were having the same problem. 

Perhaps I’m not the best person to contribute as I didn’t have a guaranteed working version before this issue came up.

**Comment by phatmann** [comment]
Going back to 2.112.0 worked for me. I did not try the branch yet.

**Comment by shangardezi** [comment]
Same issue for me.

**Comment by nekrich** [comment]
@joshdholtz , tried the updated branch. Got same error.
```
[10:47:55]: Installing certificate...
[10:48:04]:
[10:48:04]: Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
Check if you supplied the correct `keychain_password` for keychain: `/Users/nekrich/Library/Keychains/login.keychain-db`
security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
[10:48:04]:
[10:48:04]: Please look at the following docs to see how to set a keychain password:
[10:48:04]:  - https://docs.fastlane.tools/actions/sync_code_signing
[10:48:04]:  - https://docs.fastlane.tools/actions/get_certificates
```

**Comment by DTown** [comment]
Had the same problem. Downgrade to 2.112.0 helped to solve the problem.
- Slave/Build Client has Mac Mojave 10.14.2
- Currently an older Ruby Version of 2.3.7
- Xcode 10.1

**Comment by nemui** [comment]
@joshdholtz Tried the latest version of your branch, commit e71f892, on my Jenkins setup. Worked without any issues 👍

**Comment by joshdholtz** [comment]
@nekrich Was your fastlane setup working with `2.112.0` and then started breaking in `2.113.0`?

**Comment by nekrich** [comment]
@joshdholtz , I think that @DTown is right in some way. match produces an error in logs only and lane successfully completes. On my mac certificate and private key are already in the Keychain, so maybe that's why match doesn't throw (but only shows) an error.

**Comment by mthakuri** [comment]
For those who are facing this issue on travis, please use Fastlane v2.112.0 in your `.travis.yml` file e.g. `gem install fastlane --version 2.112.0`. When you don't mention the version in yml file, then travis install the latest Fastlane(v2.113.0) which has keychain issue.

**Comment by racer1988** [comment]
@joshdholtz just tested on ‘2.114.0’ but the issue is still there

Running ‘match’ readonly from the fastfile gives the same error plus a new info:

‘’’
[10:32:34]: Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
Check if you supplied the correct `keychain_password` for keychain: `/Users/x/Library/Keychains/login.keychain-db`
security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
[10:32:34]:
[10:32:34]: Please look at the following docs to see how to set a keychain password:
[10:32:34]:  - https://docs.fastlane.tools/actions/sync_code_signing
[10:32:34]:  - https://docs.fastlane.tools/actions/get_certificates
‘’’

**Comment by Deub27** [comment]
> @joshdholtz just tested on ‘2.114.0’ but the issue is still there
> 
> Running ‘match’ readonly from the fastfile gives the same error plus a new info:
> 
> ‘’’
> [10:32:34]: Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
> Check if you supplied the correct `keychain_password` for keychain: `/Users/x/Library/Keychains/login.keychain-db`
> security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
> [10:32:34]:
> [10:32:34]: Please look at the following docs to see how to set a keychain password:
> [10:32:34]: - https://docs.fastlane.tools/actions/sync_code_signing
> [10:32:34]: - https://docs.fastlane.tools/actions/get_certificates
> ‘’’

Hi, I have got still the issue with 2.114 version

**Comment by DTown** [comment]
> Just cut a release for version `2.114.0` which should have a fix for this 🙏 Closing this but feel free to comment and mention me if there are still some other issues around this

Hmm, updated to 2.114.0 , still having the problem 

```
[10:42:42]: 🔓  Successfully decrypted certificates repo
[10:42:42]: Verifying that the certificate and profile are still valid on the Dev Portal...
[10:42:46]: Installing certificate...
security: SecKeychainItemImport: The specified item already exists in the keychain.
[⠋] Setting key partition list... (this can take a minute if there are a lot of keys installed) [10:42:46]:
[10:42:46]: Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
Check if you supplied the correct `keychain_password` for keychain: `/Users/XXX/Library/Keychains/login.keychain-db`
security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
[10:42:46]:
[10:42:46]: Please look at the following docs to see how to set a keychain password:
[10:42:46]:  - https://docs.fastlane.tools/actions/sync_code_signing
[10:42:46]:  - https://docs.fastlane.tools/actions/get_certificates
[✔] Setting key partition list... (this can take a minute if there are a lot of keys installed)
```

**Comment by romk1n** [comment]
I can also confirm the issue still persists running locally on my machine```[12:11:42]: Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
Check if you supplied the correct `keychain_password` for keychain: `/Users/roman/Library/Keychains/login.keychain-db`
security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
[12:11:42]:
[12:11:42]: Please look at the following docs to see how to set a keychain password:
[12:11:42]:  - https://docs.fastlane.tools/actions/sync_code_signing
[12:11:42]:  - https://docs.fastlane.tools/actions/get_certificates```

**Comment by joshdholtz** [comment]
@Deub27 @DTown @romk1n Question about what not working is here 🙃

1) Are you getting the UI popup when you are trying to sign an app with `gym`/`build_ios_app`?
2) Or are you only seeing this output message above that has the error `security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.`?

### History
- Before `2.112.0` and earlier, this error was still happening but the message was just not being captured.
- `2.113.0` introduced a change show this to the user because this happens if `MATCH_KEYCHAIN_PASSWORD` is not set. `match` needs `MATCH_KEYCHAIN_PASSWORD` to call `security set-key-partition-list` to prevent the UI popup when signing
- **However**, `2.113.0` was a bit too aggressive/open with when it showed this error so it would sometimes show this error when another error was actually happening
- **Also**, `2.113.0` may have not been calling `security set-key-partition-list` properly which is why some users experience the UI popup which blocked signing the first time using a certificate while signing with `gym`
- **Now**, in `2.114.0`, we will only show the message you have seen above when we receive an error of `SecKeychainItemSetAccessWithPassword` which means that `MATCH_KEYCHAIN_PASSWORD` is probably not being set.

### Summary
1. If you set `MATCH_KEYCHAIN_PASSWORD` to be what the password of your keychain is (which is your login credentials for the login keychain), this error should no longer happen
2. Hopefully you also don't receive the blocking UI popup while signing 🤞

**Comment by nekrich** [comment]
What if in the case when keychain password is not provided show a warning instead of the error?

Smth like this:
```ruby
is_security_partion_enabled = Helper.backticks('security -h | grep set-key-partition-list', print: false).length > 0
if  is_security_partion_enabled && keychain_password.to_s.empty?
  UI.important("Keychain could present a blocking pop-up asking for the keychain password to grant permissions for /usr/bin/codesign to use the new identity to codesign the app..")
  UI.important("If you want to avoid blocking pop-up pass a `keychain_password ` parameter")
elsif is_security_partion_enabled
  # do the stuff
end
```

At least people will stop worrying about red text any more.

**Comment by romk1n** [comment]
@joshdholtz there is no popup, but the keys are already in the keychain, so it's just goes through. the keychain is unlocked on my machine so I don't want to provide any MATCH_KEYCHAIN_PASSWORD since it use to work with no issues for a few years. is there a way you can check if keychain is unlocked and have a slightly better logic ?

**Comment by phatmann** [comment]
When using `setup_circle_ci`, `MATCH_KEYCHAIN_PASSWORD` is set to a blank string. Will this count as being "set"?

**Comment by joshdholtz** [comment]
@phatmann Yup, that should cover you on CirclCi 😊 That is what I tested last week and its working for me 💪

**Comment by nemui** [comment]
Fixed in 2.114.0 (#14056)

**Comment by dogeri28** [comment]
i am still having this issue, when locally and also when i run build in bitrise

**Comment by dogeri28** [comment]
still having this issue in version 2.114.0

**Comment by racer1988** [comment]
@nemui could I ask why this was closed?
 @joshdholtz reopened it after merging #14056 because the change is not fixing this issue

**Comment by nemui** [comment]
@racer1988 After @joshdholtz re-opened it and posted https://github.com/fastlane/fastlane/issues/14039#issuecomment-455159133, there was no activity for 5 days. This and the fact that the fix did work for me.

**Comment by racer1988** [comment]
Ok. I understand.
I ask because imho this [two points](https://github.com/fastlane/fastlane/issues/14039#issuecomment-455171243):

> So I think what we will do here is look into doing two things:
> 
> 1. Lower the message into something less loud - like `UI.important`
> 2. Attempt to check if the cert was already installed because that message is probably not needed then

are extremely valid in the original posting of the issue

**Comment by nemui** [comment]
These would be nice to have, I agree.
But it doesn't actually cause build failures, as far as I understand? It's just an extra error message.
I'll leave the decision on whether to re-open this issue or create a new one with @joshdholtz.

**Comment by dogeri28** [comment]
i set this MATCH_KEYCHAIN_PASSWORD in the env variable and also confirmed the password of the keychain by locking and unlocking the keychain. result: No success as its causing the CI builds to fail meaning there is an underlying issue with match import keychain credentials / certs

**Comment by joshdholtz** [comment]
I'm going to reopen this even because though `2.114.0` shouldn't cause anybody failures now (that weren't there before because `security` commands that we executing are the same as we were back in `2.112.0), the errors that are showing might be showing up falsely or showing too strongly still - the points that were pointed out here https://github.com/fastlane/fastlane/issues/14039#issuecomment-456842291

**If anybody is having further issues**, I would appreciate an explanation of what the issue _actually_ is that you are experiencing since there are multiple things that have happened here 🙃
1. Are you seeing the UI popup when code signing?
2. Is setting the `MATCH_KEYCHAIN_PASSWORD` not preventing the error from showing?
3. Is CI (circle and travis failing) even when still using `setup_circle_ci` and `setup_travis_ci`?

Thanks! 🚀

**Comment by joshdholtz** [comment]
Got a PR up for these improvements now!! 💪

**Comment by kono-paku** [comment]
@joshdholtz
Hello,
Is thie pull request going to release on 2.116.0?
By the way, this issue occurs on delvelopment only.

```
fastlane match development (x)
fastlane match appstore (o)
```

I am using the 2.115.0.
I wonder that I am the only one who shows the this issue.

**Comment by geraldeersteling** [comment]
I'm on `2.115.0` and still seeing the issue, both on development and in the appstore.
As for @joshdholtz's questions:

> 1. Are you seeing the UI popup when code signing?
I'm not getting any UI popup at all.  
I _had_ one when I first had to install the certificate (that was a _long_ while ago), but suddenly this issue appeared and I never had a popup since.

> 2. Is setting the `MATCH_KEYCHAIN_PASSWORD` not preventing the error from showing?
Still got it :/  
Next to this, I also run fastlane through GitLab's pipelines (not Circle CI like much of the others here). I'm not keen of providing the password through variables.  
Moreover I have several runners (different machines) set up, which all have their own login credentials...having to provide them all is kind of tedious.

**Comment by phatmann** [comment]
I am also still seeing the error when running locally on my machine. But the match command actually succeeds.

```
Setting key partition list... (this can take a minute if there are a lot of keys installed) [10:02:50]:
[10:02:50]: Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
Check if you supplied the correct `keychain_password` for keychain: `/Users/tony/Library/Keychains/login.keychain-db`
security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
[10:02:50]:
[10:02:50]: Please look at the following docs to see how to set a keychain password:
[10:02:50]:  - https://docs.fastlane.tools/actions/sync_code_signing
[10:02:50]:  - https://docs.fastlane.tools/actions/get_certificates
[✔] Setting key partition list... (this can take a minute if there are a lot of keys installed)
[⠋] Setting key partition list... (this can take a minute if there are a lot of keys installed) [10:02:50]:
[10:02:50]: Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
Check if you supplied the correct `keychain_password` for keychain: `/Users/tony/Library/Keychains/login.keychain-db`
security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
[10:02:50]:
[10:02:50]: Please look at the following docs to see how to set a keychain password:
[10:02:50]:  - https://docs.fastlane.tools/actions/sync_code_signing
[10:02:50]:  - https://docs.fastlane.tools/actions/get_certificates
```

**Comment by joshdholtz** [comment]
Popping a new release this morning which should have a fix for these!

**Comment by geraldeersteling** [comment]
Neat, tried it again and the error is gone for now!

I am a happy fastlaner again, thanks @joshdholtz 🎉

**Comment by kono-paku** [comment]
@joshdholtz
It works, fine! Thank you for fixing the issue.

I have another problem on creating a provisioning profile in development mode. 
Is there something I missed?
I am very newbie on IOS deployment process.
```
WARN [2019-02-07 19:39:45.02]: Creating new provisioning profile for 'com.test.app.exam' with name 'match Development com.test.app.exam' for 'ios' platform
ERROR [2019-02-07 19:39:46.55]: An error occurred while verifying your certificates and profiles with the Apple Developer Portal.
ERROR [2019-02-07 19:39:46.55]: If you already have your certificates stored in git, you can run `fastlane match` in readonly mode
ERROR [2019-02-07 19:39:46.55]: to just install the certificates and profiles without accessing the Dev Portal.
ERROR [2019-02-07 19:39:46.55]: To do so, just pass `readonly: true` to your match call.

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/spaceship/lib/spaceship/client.rb:708:in `parse_response': [!] Apple provided the following error info: (Spaceship::UnexpectedResponse)
	There were errors in the data supplied. Please correct and re-submit.
	There are no current IOS devices on this team matching the provided device IDs.
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/spaceship/lib/spaceship/portal/portal_client.rb:688:in `create_provisioning_profile!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:297:in `block in create!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/spaceship/lib/spaceship/client.rb:619:in `with_retry'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:296:in `create!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/sigh/lib/sigh/runner.rb:135:in `create_profile!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/sigh/lib/sigh/runner.rb:40:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/sigh/lib/sigh/manager.rb:8:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/match/lib/match/generator.rb:76:in `generate_provisioning_profile'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/match/lib/match/runner.rb:248:in `fetch_provisioning_profile'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/match/lib/match/runner.rb:98:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/match/lib/match/runner.rb:97:in `loop'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/match/lib/match/runner.rb:97:in `block in run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/match/lib/match/runner.rb:96:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/match/lib/match/runner.rb:96:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/match/lib/match/commands_generator.rb:66:in `block (3 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/match/lib/match/commands_generator.rb:172:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/match/lib/match/commands_generator.rb:24:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/cli_tools_distributor.rb:105:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

**Comment by kono-paku** [comment]
@joshdholtz 
Could you check whether it is neccessary to register the device on Apple Developer site?
I have resolved the above issue by registering the device on Apple Developer official one.

**Comment by webmasterdragon** [comment]
Same issue on my React Native ios platform:
```
fastlane installation at path:
/Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/bin/fastlane
-----------------------------
fastlane 2.116.1
```

```
[03:06:50]: No code signing identity found and can not create a new one because you enabled `readonly`

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying fastlane  | 0           |
|      | version             |             |
| 2    | match               | 61          |
| 💥   | match               | 46          |
+------+---------------------+-------------+

[03:06:50]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  [Regression] Breaking change when importing a new cert in 2.113.0, worked in 2.112.0
    https://github.com/fastlane/fastlane/issues/14039 [closed] 68 💬
    3 weeks ago

➡️  Scan ignores max_concurrent_simulators
    https://github.com/fastlane/fastlane/issues/13388 [closed] 3 💬
    26 Dec 2018

➡️  Match Install Errors
    https://github.com/fastlane/fastlane/issues/12421 [closed] 16 💬
    06 Oct 2018

and 17 more at: https://github.com/fastlane/fastlane/search?q=No%20code%20signing%20identity%20found%20and%20can%20not%20create%20a%20new%20one%20because%20you%20enabled%20%60readonly%60&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] No code signing identity found and can not create a new one because you enabled `readonly` (FastlaneCore::Interface::FastlaneCrash)
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/match/lib/match/runner.rb:164:in `fetch_certificate'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/match/lib/match/runner.rb:92:in `run'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/actions/sync_code_signing.rb:12:in `run'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
        from Fastfile:8:in `block (2 levels) in parsing_binding'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        from /Users/sbc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/bin/fastlane:23:in `<top (required)>'
        from /Users/sbc/.fastlane/bin/bundle/bin/fastlane:22:in `load'
        from /Users/sbc/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

**Comment by saltwat5r** [comment]
In my case the problem was caused by new Mac OS feature called **Full Disk Access**.
I use iTerm in everyday work, but I didn't grant **Full Disk Access** for it. In Mac Os Terminal `fastlane certificates` works as expected and when I've grant **Full Disk Access** for iTerm then it also starts working. 🎉

**Comment by fvvliet** [comment]
@saltwat5r  great tip !! Thanks

**Comment by checkerap** [comment]
Adding a device UDID on Apple Developer fixed it for me
