### ISSUE TITLE
Fastlane match isn't prompting me for my keychain password

### ISSUE THREAD

**Issue by KidkArolis** [fastlane/fastlane#14196]
I'm using fastlane 2.115.0.

When I run `fastlane match appstore` and enter the various details, eventually I get:

```
[13:26:19]: Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
Check if you supplied the correct `keychain_password` for keychain: `/Users/karolis/Library/Keychains/login.keychain-db`
security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
[13:26:19]:
[13:26:19]: Please look at the following docs to see how to set a keychain password:
[13:26:19]:  - https://docs.fastlane.tools/actions/sync_code_signing
[13:26:19]:  - https://docs.fastlane.tools/actions/get_certificates
```

Am I doing something wrong?

It never asked me for my keychain password. And _I do not want to_ put the password into the `-p` flag in the terminal, I shouldn't need to be doing that.

Note, if I do put my password into `-p`, it all works. But this seems like a bug / regression? It should prompt me for password in a MacOS dialogue?

**Comment by KidkArolis** [comment]
With 2.112.0, it's not actually even asking for a password and it's not erroring and everything seems to work fine.

**Comment by KidkArolis** [comment]
Furthermore:

with 2.115.0 when I run my build lane, it errors because of that same error as above: "Could not configure imported keychain item"

with 2.112.0 when I build, it prompts me for my keychain password using MacOS dialog and that all works

**Comment by joshdholtz** [comment]
This looks to be similar to #14039 which is fixed in #14175! I will be popping a new release this morning which should have a fix for this 🤞

**Comment by wayferer** [comment]
Am on version `2.117.1` and am still experiencing this issue.

**Comment by fvvliet** [comment]
Same problem here with v2.120.0

**Comment by duhuynh8435** [comment]
same issue on fastlane-2.123.0

**Comment by joshdholtz** [comment]
My apologies on this! Will take to the team about removing auto locking and what can be done instead. I will also make sure this issue gets bumped and handled ❤️
