### ISSUE TITLE
[Swift] Latest Testflight build number returns 0

### ISSUE THREAD

**Issue by pkallu** [fastlane/fastlane#14910]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
This is a duplicate of #13678, which was locked, and unable to open by me.

I am using swift version of fastlane
``` 
  let buildNumber = latestTestflightBuildNumber(appIdentifier: config.appIdentifier, username: config.userName, version: version)
       println(message: "VERSION NUMBER: \(version), BUILD NUMBER: \(buildNumber)")
       incrementBuildNumber(buildNumber: "\(1 + buildNumber)", xcodeproj: ProjectSetting.project)
``` 

Output:
 VERSION NUMBER: 4.2, BUILD NUMBER: 0

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
 Output:
 VERSION NUMBER: 4.2, BUILD NUMBER: 0
 </pre>
</details>

### Environment

<details>
  <pre> ### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.4                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.rbenv/versions/2.5.1/bin/fastlane        |
| Host                        | Mac OS X 10.14.4 (18E226)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

 </pre>
</details>

**Comment by janpio** [comment]
Please add your environment information - the original issue mentioned it was fixed.
Please also add the output you are getting as the issue template asks for.

**Comment by pkallu** [comment]
Added environment details and output that i am getting from fastlane

**Comment by pkallu** [comment]
Hi 

I have tested it using the latest fastlane. I still dont get the latest testflight build number. 

This is the data from Testflight
Latest upload for version 4.1 is build: 1563814785

Fastlane output
VERSION NUMBER: 4.1, BUILD NUMBER: 0
