### ISSUE TITLE
get_version_number doesn't work for build setting variables that use curly braces

### ISSUE THREAD

**Issue by christhegrand** [fastlane/fastlane#15194]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
If the version number for an Xcode project is a build setting variable that uses curly braces, get_version_number returns the literal string instead of the interpolated variable. For instance, if you have a variable called MARKETING_VERSION that stores the app's version number, and you access it with ```${MARKETING_VERSION}```, Fastlane returns ```${MARKETING_VERSION}``` instead of the value of the MARKETING_VERSION variable.

##### Command executed

The problem was with this line in our Fastfile: 
```version_number = get_version_number(xcodeproj: 'Bagel.xcodeproj', target: scheme)```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> Doesn't matter in this scenario </pre>
</details>

### Environment

<details>
  <pre> <summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| CFPropertyList            | 3.0.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.0.1        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| tty-screen                | 0.7.0        |
| faraday                   | 0.15.4       |
| json                      | 2.2.0        |
| io-console                | 0.4.5        |
| excon                     | 0.66.0       |
| rubyzip                   | 1.2.3        |
| libxml-ruby               | 2.9.0        |
| plist                     | 3.5.0        |
| atomos                    | 0.1.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| claide                    | 1.0.3        |
| google-cloud-env          | 1.2.0        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| unicode-display_width     | 1.6.0        |
| addressable               | 2.6.0        |
| os                        | 1.0.1        |
| psych                     | 2.1.0.1      |
| retriable                 | 3.1.2        |
| mime-types                | 3.2.2        |
| mime-types-data           | 3.2019.0331  |
| fastlane-plugin-sentry    | 1.5.0        |
| fastlane-plugin-appcenter | 1.2.0        | </pre>
</details>

**Comment by janpio** [comment]
That should already be fixed in the current release: https://github.com/fastlane/fastlane/pull/15139 Are you using the current fastlane version?

**Comment by christhegrand** [comment]
Yes, I'm still seeing this on Fastlane 2.129.0. I have a Fastfile that has everything in our build lane commented out but these lines:

```     
scheme = build_env == "Production" ? "Twobird" : "Twobird #{build_env}"
version_number = get_version_number(xcodeproj: 'Bagel.xcodeproj', target: scheme)
puts version_number
```

```
Chriss-iMac:ios bundle exec fastlane staging
[✔] 🚀 
+---------------------------+---------+---------------------------------------------+
|                                   Used plugins                                    |
+---------------------------+---------+---------------------------------------------+
| Plugin                    | Version | Action                                      |
+---------------------------+---------+---------------------------------------------+
| fastlane-plugin-sentry    | 1.5.0   | sentry_upload_dsym sentry_upload_sourcemap  |
|                           |         | sentry_finalize_release sentry_upload_file  |
|                           |         | sentry_create_release                       |
| fastlane-plugin-appcenter | 1.1.1   | appcenter_upload                            |
+---------------------------+---------+---------------------------------------------+

[15:35:28]: ------------------------------
[15:35:28]: --- Step: default_platform ---
[15:35:28]: ------------------------------
[15:35:28]: Driving the lane 'ios staging' 🚀
[15:35:28]: -------------------------------------------------
[15:35:28]: --- Step: Switch to ios build_and_submit lane ---
[15:35:28]: -------------------------------------------------
[15:35:28]: Cruising over to lane 'ios build_and_submit' 🚖
[15:35:28]: --------------------------------
[15:35:28]: --- Step: get_version_number ---
[15:35:28]: --------------------------------
[15:35:28]: ${MARKETING_VERSION}
[15:35:28]: Cruising back to lane 'ios staging' 🚘

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | default_platform                    | 0           |
| 2    | Switch to ios build_and_submit lane | 0           |
| 3    | get_version_number                  | 0           |
+------+-------------------------------------+-------------+

[15:35:28]: fastlane.tools finished successfully 🎉
Chriss-iMac:ios bundle exec fastlane --version
fastlane installation at path:
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/bin/fastlane
-----------------------------
[✔] 🚀 
fastlane 2.129.0
```

**Comment by christhegrand** [comment]
I think https://github.com/fastlane/fastlane/pull/15139 only works for variables that are using parentheses, not variables that are using curly braces.

**Comment by janpio** [comment]
Hey @florentmorin, you did a great job on #15139 - can you maybe want to take a shot at this as well?

**Comment by florentmorin** [comment]
@janpio Yes, with pleasure 😄 
I will do that this week.

**Comment by florentmorin** [comment]
OK. Just created the branch on my fork...

**Comment by florentmorin** [comment]
Hey! Seems to be OK. Just check my PR specified in this discuss. 😄
