### ISSUE TITLE
CHANGE_CONFIGURATION permission not granted

### ISSUE THREAD

**Issue by Raymond1337** [fastlane/fastlane#15321]
- [X] Updated fastlane to the latest version
- [X] I read the Contribution Guidelines
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)
- [X] I've redone the setup process

### Question Subject
Tool: Fastlane / Sceengrab
What setup changes do i need to make, to get screengrab running / permissions granted in a test environment?

#### Question Description
Expected behavior: Screengrab is usable if configured as the documentation states.

The debug/AndroidManifest.xml has 
```
    <!-- Allows changing locales -->
    <uses-permission android:name="android.permission.CHANGE_CONFIGURATION" />
```
The build.gradle has:
```
debug {
            ndkConfig.abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86_64'
            sourceSets {
                debug {
                    jniDebuggable true
                    debuggable true
                    manifest.srcFile 'src/debug/AndroidManifest.xml'
                }
            }
        }
```
Error message:
```
"Security exception: Package [Package name] has not requested permission android.permission.CHANGE_CONFIGURATION" 
Exit status: 255
```

Code might be messed up beyond all recognition, since i already tried mutible solutions.
Fastlane env:
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.6 (18G95)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |
| Xcode Version               |                                                                |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Build and take screenshots"
  lane :screenshots do
    gradle(
      task:"clean"
    )
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
  	  properties: {
    		//Sensitive data
    		},
      build_type: 'AndroidTest' # Screenshots are done in AndroidTest
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("[Pakage name]") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.66.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.4        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| json                      | 2.2.0        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-09-17**
</details>

**Comment by rickclephas** [comment]
How are you starting your tests?
When your tests are started from fastlane/screengrab this permissions should be granted before the tests are run.

**Comment by Raymond1337** [comment]
I'm starting them via 'fastlane screengrab'

I tried: 
Grant them via adb.
Grant them before the actual tests start. (In App)
Removing the necessity to have those permissions by having just one language.
Using 
```
    @Rule
    public GrantPermissionRule mRuntimePermissionRule = GrantPermissionRule.grant(Manifest.permission.CHANGE_CONFIGURATION);
```

**Comment by rickclephas** [comment]
Could you post your output from `fastlane screengrab`?

I can reproduce this if the `android.permission.CHANGE_CONFIGURATION` permission is missing from the apk file.
Though this can only happen when `aapt` isn't found else screengrab will verify the apk file before running the permission commands.

**Comment by Raymond1337** [comment]
OK, it seems this is the Problem, the aapt can't be found:
```
[13:34:40]: The `aapt` command could not be found on your system, so your app APK could not be validated
```
But it is in the right location and i already reinstalled the SDK package and added the PATH variables.

I also had issues with the adb PATH entrys.

**Comment by rickclephas** [comment]
Try setting the `ANDROID_HOME` environment variable to your Android SDK folder.
That should fix the `aapt` command could not be found error.

**Comment by Raymond1337** [comment]
My PATHs did not have the build-tools path. The SDK path was already present.

```
export ANDROID_HOME=~/Library/Android/sdk/
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/tools:$PATH
```
Thanks for your help and quick responses.

**Comment by Raymond1337** [comment]
But i still have an issue with the detection of permissions:
```
[!] The needed permission(s) android.permission.READ_EXTERNAL_STORAGE, android.permission.WRITE_EXTERNAL_STORAGE, android.permission.CHANGE_CONFIGURATION could not be found in your app APK
```
All Permissions in my debug/AndroidManifest.xml:
```
    <uses-permission android:name="android.permission.CAMERA" />

    <!-- Allows unlocking your device and activating its screen so UI tests can succeed -->
    <uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>

    <!-- Allows for storing and retrieving screenshots -->
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

    <!-- Allows changing locales -->
    <uses-permission android:name="android.permission.CHANGE_CONFIGURATION"
        tools:ignore="ProtectedPermissions" />
```
Unfortunately 0 similar search results for this issue.

**Comment by rickclephas** [comment]
Are you building the debug apk before running the fastlane command?

Try running the following
```
./gradlew assembleDebug assembleAndroidTest
```

**Comment by Raymond1337** [comment]
OK, i can't recall what i've done exactly, but i removed the signing out of this lane and checked the AndroidManifest.xml path on the build.gradle which is and was 'src/debug/AndroidManifest.xml' since https://github.com/fastlane/fastlane/issues/12770 fixed it by having the same AndroidManifest.xml in the androidTest folder.

I built it.
Now it installs both apks and cancels with:
```
[15:45:15]: Granting the permission necessary to change locales on the device
[15:45:15]: $ /Users/me/Library/Android/sdk/platform-tools/adb -s FA7C61A01112 shell pm grant [com.package.name] android.permission.CHANGE_CONFIGURATION
[15:45:15]: ▸ Security exception: Package [com.package.name]  has not requested permission android.permission.CHANGE_CONFIGURATION
```
But the statement in the AndroidManifest.xml is an explicit request right?

**Comment by rickclephas** [comment]
So the waring about the `aapt` command is now gone and the apps get installed but you are still getting the security exception?

**Comment by Raymond1337** [comment]
Yes.

```
$ fastlane screengrab
[✔] 🚀 
[10:28:30]: fastlane detected a Gemfile in the current directory
[10:28:30]: however it seems like you don't use `bundle exec`
[10:28:30]: to launch fastlane faster, please use
[10:28:30]: 
[10:28:30]: $ bundle exec fastlane screengrab
[10:28:30]: 
[10:28:30]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[10:28:31]: Successfully loaded '/Users/me/appName-android/fastlane/Screengrabfile' 📄

+----------------------------+-----------------------------------------------------------------------------------------------------------+
|                                            Detected Values from './fastlane/Screengrabfile'                                            |
+----------------------------+-----------------------------------------------------------------------------------------------------------+
| app_package_name           | [com.package.name]                                                                                     |
| use_tests_in_packages      | ["[com.package.name]"]                                                                                 |
| app_apk_path               | /Users/me/appName-android/app/build/outputs/apk/flavorF/debug/app-flavorF-debug.apk                         |
| tests_apk_path             | /Users/me/appName-android/app/build/outputs/apk/androidTest/flavorF/debug/app-flavorF-debug-androidTest.apk |
| locales                    | ["en-US", "de-DE"]                                                                                        |
| clear_previous_screenshots | true                                                                                                      |
+----------------------------+-----------------------------------------------------------------------------------------------------------+


+-----------------------------+-----------------------------------------------------------------------------------------------------------+
|                                                     Summary for screengrab 2.131.0                                                      |
+-----------------------------+-----------------------------------------------------------------------------------------------------------+
| tests_package_name          | [com.package.name.test]                                                                                |
| android_home                | /Users/me/Library/Android/sdk/                                                                       |
| locales                     | ["en-US", "de-DE"]                                                                                        |
| clear_previous_screenshots  | true                                                                                                      |
| output_directory            | fastlane/metadata/android                                                                                 |
| skip_open_summary           | false                                                                                                     |
| app_package_name            | [com.package.name]                                                                                     |
| use_tests_in_packages       | ["[com.package.name]"]                                                                                 |
| test_instrumentation_runner | android.support.test.runner.AndroidJUnitRunner                                                            |
| ending_locale               | en-US                                                                                                     |
| app_apk_path                | /Users/me/appName-android/app/build/outputs/apk/flavorF/debug/app-flavorF-debug.apk                         |
| tests_apk_path              | /Users/me/appName-android/app/build/outputs/apk/androidTest/flavorF/debug/app-FlavorF-debug-androidTest.apk |
| device_type                 | phone                                                                                                     |
| exit_on_test_failure        | true                                                                                                      |
| reinstall_app               | false                                                                                                     |
+-----------------------------+-----------------------------------------------------------------------------------------------------------+

[10:28:31]: Clearing phoneScreenshots within fastlane/metadata/android
[10:28:31]: $ /Users/me/Library/Android/sdk/platform-tools/adb devices -l
[10:28:31]: ▸ List of devices attached
[10:28:31]: ▸ FA7C61A01112           device usb:338690048X product:walleye model:Pixel_2 device:walleye transport_id:1
[10:28:31]: $ /Users/me/Library/Android/sdk/platform-tools/adb -s FA7C61A01112 shell echo \$EXTERNAL_STORAGE
[10:28:31]: ▸ /sdcard
[10:28:31]: Cleaning screenshots on device
ls: /sdcard/[com.package.name]/screengrab: No such file or directory
[10:28:31]: Exit status: 1
ls: /data/data/[com.package.name]/app_screengrab: Permission denied
[10:28:31]: Exit status: 1
[10:28:31]: Validating app APK
[10:28:31]: $ /Users/me/Library/Android/sdk/build-tools/28.0.3/aapt dump permissions /Users/me/appName-android/app/build/outputs/apk/flavorF/debug/app-flavorF-debug.apk
[10:28:31]: ▸ package: [com.package.flavorAppName]
[10:28:31]: ▸ uses-permission: name='android.permission.CAMERA'
[10:28:31]: ▸ uses-permission: name='android.permission.DISABLE_KEYGUARD'
[10:28:31]: ▸ uses-permission: name='android.permission.WAKE_LOCK'
[10:28:31]: ▸ uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
[10:28:31]: ▸ uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
[10:28:31]: ▸ uses-permission: name='android.permission.CHANGE_CONFIGURATION'
[10:28:31]: ▸ uses-permission: name='android.permission.INTERNET'
[10:28:31]: ▸ uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
[10:28:31]: ▸ uses-permission: name='com.google.android.c2dm.permission.RECEIVE'
[10:28:31]: ▸ uses-permission: name='com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE'
[10:28:31]: Installing app APK
[10:28:31]: $ /Users/me/Library/Android/sdk/platform-tools/adb -s FA7C61A01112 install -t -r /Users/me/appName-android/app/build/outputs/apk/flavorF/debug/app-flavorF-debug.apk
[10:28:31]: ▸ Performing Streamed Install
[10:28:35]: ▸ Success
[10:28:35]: Installing tests APK
[10:28:35]: $ /Users/me/Library/Android/sdk/platform-tools/adb -s FA7C61A01112 install -t -r /Users/me/appName-android/app/build/outputs/apk/androidTest/flavorF/debug/app-flavorF-debug-androidTest.apk
[10:28:35]: ▸ Performing Streamed Install
[10:28:36]: ▸ Success
[10:28:36]: Granting the permission necessary to change locales on the device
[10:28:36]: $ /Users/me/Library/Android/sdk/platform-tools/adb -s FA7C61A01112 shell pm grant [com.package.name] android.permission.CHANGE_CONFIGURATION
[10:28:36]: ▸ Security exception: Package [com.package.name] has not requested permission android.permission.CHANGE_CONFIGURATION
[10:28:36]: ▸ java.lang.SecurityException: Package [com.package.name] has not requested permission android.permission.CHANGE_CONFIGURATION
[10:28:36]: ▸ 	at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:379)
[10:28:36]: ▸ 	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1404)
[10:28:36]: ▸ 	at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerService.java:89)
[10:28:36]: ▸ 	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.grantRuntimePermission(PermissionManagerService.java:2093)
[10:28:36]: ▸ 	at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:5411)
[10:28:36]: ▸ 	at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1730)
[10:28:36]: ▸ 	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:217)
[10:28:36]: ▸ 	at android.os.ShellCommand.exec(ShellCommand.java:103)
[10:28:36]: ▸ 	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21336)
[10:28:36]: ▸ 	at android.os.Binder.shellCommand(Binder.java:634)
[10:28:36]: ▸ 	at android.os.Binder.onTransact(Binder.java:532)
[10:28:36]: ▸ 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2821)
[10:28:36]: ▸ 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3856)
[10:28:36]: ▸ 	at android.os.Binder.execTransact(Binder.java:731)
Security exception: Package [com.package.name] has not requested permission android.permission.CHANGE_CONFIGURATION

java.lang.SecurityException: Package [com.package.name] has not requested permission android.permission.CHANGE_CONFIGURATION
	at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:379)
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1404)
	at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerService.java:89)
	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.grantRuntimePermission(PermissionManagerService.java:2093)
	at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:5411)
	at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1730)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:217)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21336)
	at android.os.Binder.shellCommand(Binder.java:634)
	at android.os.Binder.onTransact(Binder.java:532)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2821)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3856)
	at android.os.Binder.execTransact(Binder.java:731)
[10:28:36]: Exit status: 255

[!] Exit status: 255

```

The same for `bundle exec fastlane screengrab` if it maters.
While censoring i stumbled upon [10:28:31]: ▸ package: [com.package.**flavorAppName**] instead of [com.package.**name**] ,this should be package name contacted by adb, so there is nothing wrong with it? Just in case i'll double check the config files.

**Comment by rickclephas** [comment]
I see you are using app flavors.
My guess is that your apk has a different package name.
Screengrab needs the package name of your debug app. In your case:
```
/Users/me/appName-android/app/build/outputs/apk/flavorF/debug/app-flavorF-debug.apk
```

You can check the package name of your apk file with:
```
aapt dump badging <path-to-apk> | grep package:\ name
```

**Comment by Raymond1337** [comment]
Thank you so very much.
Using the 'flavorAppName' in the screengrab configuration file instead of the general package name does the trick.
I guess I misread it or skipped the manual, or whatever, but now the error is gone.
Tank you :)
