### ISSUE TITLE
[Regression][Supply] Rollout to production to 100% is failing

### ISSUE THREAD

**Issue by emarc-m** [fastlane/fastlane#15645]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version:`2.135.2`
- Last working version: `2.132.0`

### Regression Description

Hi @joshdholtz, I've updated to the latest `fastlane (2.135.2)` and suddenly publishing to `production` with a rollout percentage of `1.0` is failing with the following error message:
```json
{
  "build": {
    "display_name": "***REDACTED***",
    "distribution_platform_pretty_name": "Google Play",
    "build_info": {
      "pr_number": null,
      "date": "2019-11-13 11:18:54 -0800",
      "build": null
    }
  },
  "error": "Google Api Error: validateAppMessageRolloutFractionOutOfRange: Rollout user fraction must be greater than 0.0 and less than 1.0 - Rollout user fraction must be greater than 0.0 and less than 1.0"
}
```
##### Command executed

```ruby
upload_to_play_store(
  package_name: application_id,
  apk_paths: apks,
  json_key: (FASTLANE_DIR + channel.json_key_path).to_s,
  skip_upload_metadata: true,
  skip_upload_changelogs: true,
  skip_upload_images: true,
  skip_upload_screenshots: true,
  track: 'production', 
  rollout: '1',
  validate_only: true,
  mapping_paths: mapping_file * 4,
)
```
Note: Changed `track`, `rollout`, and `validate_only` to actual value being passed.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[11:19:55]: ----------------------------------
[11:19:55]: --- Step: upload_to_play_store ---
[11:19:55]: ----------------------------------
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------+
|                                                                   Summary for supply 2.135.2                                                                    |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------+
| package_name            | REDACTED                                                                                                                              |
| apk_paths               | ["REDACTED"]                                                                                                                          |
| json_key                | REDACTED                                                                                                                              |
| skip_upload_metadata    | true                                                                                                                                  |
| skip_upload_changelogs  | true                                                                                                                                  |
| skip_upload_images      | true                                                                                                                                  |
| skip_upload_screenshots | true                                                                                                                                  |
| track                   | production                                                                                                                            |
| rollout                 | 1                                                                                                                                     |
| validate_only           | true                                                                                                                                  |
| mapping_paths           | ["REDACTED"]                                                                                                                          |
| skip_upload_apk         | false                                                                                                                                 |
| skip_upload_aab         | false                                                                                                                                 |
| check_superseded_tracks | false                                                                                                                                 |
| timeout                 | 300                                                                                                                                   |
| deactivate_on_promote   | true                                                                                                                                  |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------+
[11:19:56]: REDACTED
[11:20:11]: REDACTED
[11:20:11]: REDACTED
[11:20:18]: REDACTED
[11:20:18]: REDACTED
[11:20:23]: REDACTED
[11:20:23]: REDACTED
[11:20:29]: REDACTED
[11:20:40]: Updating track 'production'...
[11:20:40]: Wrote distribution report to /Users/******/Library/Logs/upload_report.json.
[11:20:40]: {
  "build": {
    "display_name": "REDACTED",
    "distribution_platform_pretty_name": "Google Play",
    "build_info": {
      "pr_number": null,
      "date": "2019-11-13 11:18:54 -0800",
      "build": null
    }
  },
  "error": "Google Api Error: validateAppMessageRolloutFractionOutOfRange: Rollout user fraction must be greater than 0.0 and less than 1.0 - Rollout user fraction must be greater than 0.0 and less than 1.0"
}
[11:20:40]: Google Api Error: validateAppMessageRolloutFractionOutOfRange: Rollout user fraction must be greater than 0.0 and less than 1.0 - Rollout user fraction must be greater than 0.0 and less than 1.0
+------+----------------------+-------------+
|             fastlane summary              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | default_platform     | 0           |
| 2    | is_ci                | 0           |
| 3    | gradle               | 1           |
| 4    | gradle               | 59          |
| 💥   | upload_to_play_store | 45          |
+------+----------------------+-------------+
  </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                         |
| --------------------------- | ------------------------------------------------------------- |
| OS                          | 10.15.1                                                       |
| Ruby                        | 2.4.6                                                         |
| Bundler?                    | true                                                          |
| Git                         | git version 2.21.0 (Apple Git-122.2)                          |
| Installation Source         | REDACTED                                                      |
| Host                        | Mac OS X 10.15.1 (19B88)                                      |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.6/lib                                  |
| OpenSSL Version             | OpenSSL 1.1.1b  26 Feb 2019                                   |
| Is contained                | false                                                         |
| Is homebrew                 | false                                                         |
| Is installed via Fabric.app | false                                                         |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                   |
| Xcode Version               | 11.2.1                                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.135.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                             | Version | Update-Status |
| ---------------------------------- | ------- | ------------- |
| fastlane-plugin-aws_s3             | 1.6.1   | ✅ Up-To-Date  |
| fastlane-plugin-versioning_android | 0.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-waldo              | 1.3.0   | ✅ Up-To-Date  |
| fastlane-plugin-changelog          | 0.15.0  | ✅ Up-To-Date  |
| fastlane-plugin-slack_upload       | 0.1.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                | Version      |
| ---------------------------------- | ------------ |
| did_you_mean                       | 1.1.0        |
| executable-hooks                   | 1.6.0        |
| bundler-unload                     | 1.0.2        |
| rubygems-bundler                   | 1.4.5        |
| bundler                            | 2.0.2        |
| CFPropertyList                     | 3.0.1        |
| concurrent-ruby                    | 1.1.5        |
| i18n                               | 1.7.0        |
| minitest                           | 5.13.0       |
| thread_safe                        | 0.3.6        |
| tzinfo                             | 1.2.5        |
| activesupport                      | 5.2.3        |
| public_suffix                      | 2.0.5        |
| addressable                        | 2.7.0        |
| rubyzip                            | 1.3.0        |
| apktools                           | 0.7.3        |
| ast                                | 2.4.0        |
| atomos                             | 0.1.3        |
| aws-eventstream                    | 1.0.3        |
| aws-sigv4                          | 1.1.0        |
| jmespath                           | 1.4.0        |
| aws-sdk-core                       | 2.11.396     |
| aws-sdk-resources                  | 2.11.396     |
| aws-sdk                            | 2.11.396     |
| babosa                             | 1.0.3        |
| claide                             | 1.0.3        |
| colored2                           | 3.1.2        |
| cork                               | 0.3.0        |
| nap                                | 1.1.0        |
| open4                              | 1.3.4        |
| claide-plugins                     | 0.9.2        |
| colored                            | 1.2          |
| highline                           | 1.7.10       |
| commander-fastlane                 | 4.4.6        |
| multipart-post                     | 2.1.1        |
| faraday                            | 0.17.0       |
| faraday-http-cache                 | 2.0.0        |
| git                                | 1.5.0        |
| kramdown                           | 2.1.0        |
| kramdown-parser-gfm                | 1.1.0        |
| no_proxy_fix                       | 0.1.2        |
| sawyer                             | 0.8.2        |
| octokit                            | 4.14.0       |
| unicode-display_width              | 1.6.0        |
| terminal-table                     | 1.8.0        |
| danger                             | 6.0.9        |
| jaro_winkler                       | 1.5.3        |
| parallel                           | 1.17.0       |
| parser                             | 2.6.3.0      |
| rainbow                            | 3.0.0        |
| ruby-progressbar                   | 1.10.1       |
| rubocop                            | 0.73.0       |
| danger-rubocop                     | 0.6.1        |
| declarative                        | 0.0.10       |
| declarative-option                 | 0.1.0        |
| digest-crc                         | 0.4.1        |
| unf_ext                            | 0.0.7.6      |
| unf                                | 0.1.4        |
| domain_name                        | 0.5.20190701 |
| dotenv                             | 2.7.5        |
| emoji_regex                        | 1.0.1        |
| excon                              | 0.68.0       |
| http-cookie                        | 1.0.3        |
| faraday-cookie_jar                 | 0.0.6        |
| faraday_middleware                 | 0.13.1       |
| fastimage                          | 2.1.7        |
| gh_inspector                       | 1.1.3        |
| jwt                                | 2.1.0        |
| memoist                            | 0.16.1       |
| multi_json                         | 1.14.1       |
| os                                 | 1.0.1        |
| signet                             | 0.12.0       |
| googleauth                         | 0.6.7        |
| httpclient                         | 2.8.3        |
| mime-types-data                    | 3.2019.1009  |
| mime-types                         | 3.3          |
| uber                               | 0.1.0        |
| representable                      | 3.0.4        |
| retriable                          | 3.1.2        |
| google-api-client                  | 0.23.9       |
| google-cloud-env                   | 1.3.0        |
| google-cloud-core                  | 1.4.1        |
| google-cloud-storage               | 1.16.0       |
| json                               | 2.2.0        |
| mini_magick                        | 4.9.5        |
| multi_xml                          | 0.6.0        |
| plist                              | 3.5.0        |
| security                           | 0.1.3        |
| naturally                          | 2.2.0        |
| simctl                             | 1.6.6        |
| slack-notifier                     | 2.3.2        |
| terminal-notifier                  | 2.0.0        |
| tty-screen                         | 0.7.0        |
| tty-cursor                         | 0.7.0        |
| tty-spinner                        | 0.9.1        |
| word_wrap                          | 1.0.0        |
| nanaimo                            | 0.2.6        |
| xcodeproj                          | 1.13.0       |
| rouge                              | 2.0.7        |
| xcpretty                           | 0.3.0        |
| xcpretty-travis-formatter          | 1.0.0        |
| fastlane-plugin-aws_s3             | 1.6.1        |
| fastlane-plugin-changelog          | 0.15.0       |
| gli                                | 2.19.0       |
| hashie                             | 4.0.0        |
| websocket-extensions               | 0.1.4        |
| websocket-driver                   | 0.7.1        |
| slack-ruby-client                  | 0.14.4       |
| fastlane-plugin-slack_upload       | 0.1.0        |
| fastlane-plugin-versioning_android | 0.1.0        |
| fastlane-plugin-waldo              | 1.3.0        |
| hashdiff                           | 1.0.0        |
| optimist                           | 3.0.0        |
| web_translate_it                   | 2.4.8        |
</details>

*generated on:* **2019-11-13**
</details>

Note: Removed `fastlane files` section. Kindly let me know if issue is missing required details. Thank you.

**Comment by joshdholtz** [comment]
@emarc-m Have you tried on `2.136.0`? I just released that and it fixed some things. I'm _pretty sure_ this is fixed on that one 🤞

**Comment by emarc-m** [comment]
Hi @joshdholtz thank you for the response. I tried updating to `2.136.0` but unfortunately I'm still getting the same error.

```
+-------------------------+----------------------------------------------------------------------------------------------------------------+
|                                                        Summary for supply 2.136.0                                                        |
+-------------------------+----------------------------------------------------------------------------------------------------------------+
| package_name            | REDACTED                                                                                                       |
| apk_paths               | [REDACTED]                                                                                                     |
| json_key                | REDACTED                                                                                                       |
| skip_upload_metadata    | true                                                                                                           |
| skip_upload_changelogs  | true                                                                                                           |
| skip_upload_images      | true                                                                                                           |
| skip_upload_screenshots | true                                                                                                           |
| track                   | production                                                                                                     |
| rollout                 | 1                                                                                                              |
| validate_only           | true                                                                                                           |
| mapping_paths           | [REDACTED]                                                                                                     |
| release_status          | completed                                                                                                      |
| skip_upload_apk         | false                                                                                                          |
| skip_upload_aab         | false                                                                                                          |
| check_superseded_tracks | false                                                                                                          |
| timeout                 | 300                                                                                                            |
| deactivate_on_promote   | true                                                                                                           |
+-------------------------+----------------------------------------------------------------------------------------------------------------+
```

output:

```
[15:01:26]: {
  "build": {
    "display_name": "REDACTED",
    "distribution_platform_pretty_name": "Google Play",
    "build_info": {
      "pr_number": null,
      "date": "2019-11-15 14:59:36 -0800",
      "build": null
    }
  },
  "error": "Google Api Error: validateAppMessageRolloutFractionOutOfRange: Rollout user fraction must be greater than 0.0 and less than 1.0 - Rollout user fraction must be greater than 0.0 and less than 1.0"
}
```

**Comment by joshdholtz** [comment]
@emarc-m Ohhhhhh, I think I see what is going on here! I should be able to fix this now 😊

**Comment by joshdholtz** [comment]
@emarc-m This would would have worked for you if you didn't specify any value for `rollout` at all but its erroring out because of the `1` value for `rollout`. We should have caught this so I'm making a fix for this now 😇 Thanks for the patience and the help ❤️

**Comment by emarc-m** [comment]
Hi @joshdholtz thank you for looking into it. 

I tried removing the`rollout` parameter into supply  and ran into the error being described in https://github.com/fastlane/fastlane/issues/15646
```
+-------------------------+----------------------------------------------------------------------------------------------------+
|                                                  Summary for supply 2.136.0                                                  |
+-------------------------+----------------------------------------------------------------------------------------------------+
| package_name            | REDACTED                                                                                           |
| apk_paths               | [REDACTED]                                                                                         |
| json_key                | REDACTED                                                                                           |
| skip_upload_metadata    | true                                                                                               |
| skip_upload_changelogs  | true                                                                                               |
| skip_upload_images      | true                                                                                               |
| skip_upload_screenshots | true                                                                                               |
| track                   | production                                                                                         |
| validate_only           | true                                                                                               |
| mapping_paths           | [REDACTED]                                                                                         |
| release_status          | completed                                                                                          |
| skip_upload_apk         | false                                                                                              |
| skip_upload_aab         | false                                                                                              |
| check_superseded_tracks | false                                                                                              |
| timeout                 | 300                                                                                                |
| deactivate_on_promote   | true                                                                                               |
+-------------------------+----------------------------------------------------------------------------------------------------+
```

```json
{
  "build": {
    "display_name": "REDACTED",
    "distribution_platform_pretty_name": "Google Play",
    "build_info": {
      "pr_number": null,
      "date": "2019-11-16 11:48:06 -0800",
      "build": null
    }
  },
  "error": "You currently have an active edit"
}
```

**Comment by joshdholtz** [comment]
Thanks for trying!! I’ll look into this some more then 😇

**Comment by emarc-m** [comment]
Thanks as well and kindly let me know where I could be of assistance. 😃
