### ISSUE TITLE
Visual Studio 2019: Limit of requests to iTunes Connect is reached

### ISSUE THREAD

**Issue by CoveTechnologyAus** [fastlane/fastlane#15649]
### New Issue Checklist

- [Y ] Updated fastlane to the latest version
- [Y ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [Y ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [Y ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Installed Visual Studio 2019 Mac and Fast Lane and Xcode 11.2
Attempt to add my Apple Developer Account to Visual Studio 2019 and receive the following message:

Failed to synchronize [DEVELOPER ACCOUNT] account with Apple Developer Portal
Limit of requests to iTunes Connect is reached.

### Environment
MacOS Catalina

fastlane env
[15:03:35]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.1                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122.2)        |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.15.1 (19B88)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.6        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.17.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| google-api-client         | 0.9.28       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 2.1.0        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.1       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.9.5        |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.6        |
| naturally                 | 2.2.0        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 2.0.7        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| simctl                    | 1.6.6        |
| slack-notifier            | 2.3.2        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 2.0.0        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-cursor                | 0.7.0        |
| tty-screen                | 0.7.0        |
| tty-screen                | 0.5.0        |
| tty-spinner               | 0.9.1        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.13.0       |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

**Comment by jhermsen** [comment]
Same issue here.
Related issue on MS developer community portal: https://developercommunity.visualstudio.com/content/problem/817521/xamarin-fastlane-there-was-an-error-while-syncing.html

**Comment by janpio** [comment]
I am confused. How is fastlane connected to Visual Studio 2019?

**Comment by laibulle** [comment]
It seems to be a Microsoft issue. According to MS, it should be fixed  in **Visual Studio 2019 version 16.3.10 and Visual Studio for Mac version 8.3.9**. As a closed source IDE, we do not know how VS interact with Fastlane so maybe this issue should be closed. Moreover, every things work perfectly fine with Fastlane CLI.

Best regards

**Comment by janpio** [comment]
Thanks for that input @laibulle. I am pretty much wondering why people think this is caused by fastlane in the first place.

**Comment by ulipde** [comment]
Just installed 8.3.9 build 2 and the problem vanished and a new one arises. Automatic provisioning is still not working.

<img width="953" alt="Bildschirmfoto 2019-11-18 um 22 46 53" src="https://user-images.githubusercontent.com/57921561/69097270-826f0300-0a56-11ea-8463-71bad9af2d34.png">

**Comment by janpio** [comment]
@ulipde What is fastlane's involvement there?

**Comment by ulipde** [comment]
I may be wrong here. It's invoked by VS.

**Comment by laibulle** [comment]
@ulipde It is a Microsoft issue, they failed to fix the problem quickly but creating issues in Fastlane repo won't help anybody I think.

regards

**Comment by janpio** [comment]
I am still confused what gives you the impression this might be caused by fastlane? If there is something Microsoft tells you that this comes from fastlane, we should know and ask them to fix it.

**Comment by ulipde** [comment]
As you may have noticed I revoked my questions because the issue is in fact VS related. The automatic provisioning in the VS for Mac is incorporating fast lane for that. Fast lane invokes the apple two factor authentication here in the first step. After that it's failing. Don't know in which part of the pipeline it's failing. May be the Microsoft people are using it wrong in the moment. Thats why  the tried to fix it. I feel Apple changed something with iTunes Connect a few days ago.

**Comment by ulipde** [comment]
https://developercommunity.visualstudio.com/content/problem/817364/apple-developer-account-limit-of-requests-to-itune.html

**Comment by janpio** [comment]
Thanks for the context @ulipde. If you in contact with someone from Microsoft, tell them they are very much welcome to open an issue here as well. If they reach out, we can also open a more direct channel of commuincation to us. I am reachable via piotrowski@gmail.com.

**Comment by truekxmexico** [comment]
Update your Visual Studio to 8.3.10.2 and its fixed!!!

**Comment by alexthekid07** [comment]
It doesn't seem fixed on the preview version of VS 2019
