### ISSUE TITLE
[Regression] Frameit text is small

### ISSUE THREAD

**Issue by EmilioPelaez** [fastlane/fastlane#16365]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I was using `frameit` to frame my screenshots and when I was on version 2.136.0 it was working great.

I updated fastlane to 2.146.0 to be able to use the new device frames and now all the text is really small. The area where the text would be rendered didn't change, only the text size. **I tracked down the issue to version 2.139.0**. Using version 2.138.0 doesn't cause this issue.

This is my Framefile.json
<details>
  <pre>{
  "default": {
    "title": {
      "color": "#FFFFFF",
      "font": "./fonts/Font.ttc"
    },
    "background": "./background.png",
    "font_scale_factor": 0.25,
    "padding": "5%",
    "stack_title": true
  },

  "data": [
    {
      "filter": "0_Countdowns",
      "background": "./background-red.jpg"
    },
    {
      "filter": "1_DarkMode",
      "background": "./background-darkgray.jpg"
    },
    {
      "filter": "2_Images",
      "background": "./background-green.jpg",
      "title_below_image": true
    },
    {
      "filter": "3_Share",
      "background": "./background-purple.jpg",
      "title_below_image": true
    }
  ]
}
</pre>
</details>

I've I've played around with `font_scale_factor` and `padding` and also tried removing `stack_title`, as well as the custom font. Neither of these changes worked.

I also tried reinstalling `imagemagick` to make sure it was the latest version, but that didn't make a difference.

I'm attaching two images of how the output used to look and how it does now. I'm also attaching a folder with the required files to reproduce this. 

[screenshots.zip](https://github.com/fastlane/fastlane/files/4522009/screenshots.zip)

![Previous Output](https://user-images.githubusercontent.com/140234/80090538-f65e8b80-855f-11ea-9e87-86f78520a2db.jpg)
![iPhone 8-1_DarkMode_framed](https://user-images.githubusercontent.com/140234/80090634-1aba6800-8560-11ea-83ca-65a3ebe439aa.png)

##### Command executed
`fastlane frameit`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>$fastlane frameit
[✔] 🚀 
[12:39:26]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[12:39:27]: Using device frames version 'latest'
[⠏] Framing screenshot './en-US/iPhone 8-1_DarkMode.png' composite: invalid profile length `/var/folders/l7/268fs7bx3hb_9xpfmq_jhjy40000gn/T/mini_magick20200423-41545-1o7v9yv.png' @ warning/png.c/MagickPNGWarningHandler/1748.
[⠹] Framing screenshot './en-US/iPhone 8-1_DarkMode.png' convert: invalid profile length `/var/folders/l7/268fs7bx3hb_9xpfmq_jhjy40000gn/T/mini_magick20200423-41545-1t0n13v.png' @ warning/png.c/MagickPNGWarningHandler/1748.
[✔] Framing screenshot './en-US/iPhone 8-1_DarkMode.png' 
[12:39:32]: Added frame: '/Users/emiliopelaez/Desktop/screenshots/en-US/iPhone 8-1_DarkMode_framed.png' </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.4                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.2 (Apple Git-127)          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.3/bin/fastlane         |
| Host                        | Mac OS X 10.15.4 (19E287)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.4.1                                      |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build app, test, create screenshots and upload to AppStore"
  lane :release do
    build_app(scheme: "Countdown", output_directory: "./build")
    run_tests(skip_build: true)
    capture_screenshots
    frame_screenshots
    upload_to_app_store(force: true)
  end
end

platform :ios do
  desc "Build App"
  lane :build do
    build_app(scheme: "Countdown", output_directory: "./build")
  end
 end
 
 platform :ios do
  desc "Run Tests"
  lane :test do
    run_tests
  end
end

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots
    frame_screenshots
  end
end

platform :ios do
  desc "Upload App to AppStore"
  lane :upload do
    upload_to_app_store
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("identifier") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.146.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.17.3       |
| etc                       | 1.0.1        |
| forwardable               | 1.2.0        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.301.0      |
| aws-sigv4                 | 1.1.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.94.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.63.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.5.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.73.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.0       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-04-23**
</details>

**Comment by StuSchwartz** [comment]
I am seeing the same issue with version 2.146.1

**Comment by thecoolwinter** [comment]
I'm getting the same bug in 2.148.1 as well.

**Comment by emovla** [comment]
Me too, in 2.148.1

**Comment by zakiso** [comment]
Me too , in 2.148.1

**Comment by bbccd** [comment]
Same here - also seeing it in 2.149.1.

**Comment by davidrothera** [comment]
Bumping this, also seeing it in the latest RC

**Comment by bbccd** [comment]
Just installed the new 2.152.0 yesterday and tried again - it appears the issue with too small text is now solved; it may have turned into the opposite now (too large), though. But I only tried iPad devices, so try carefully (probably be prepared to role back to 2.138 - the last version that didn’t have that issue before).

**Comment by TonyStarkBy** [comment]
v2.158.0 - Same here.

Install v2.138: `sudo gem install fastlane:2.138`
Use it: `fastlane _2.138.0_ frameit`

**Comment by rogerluan** [comment]
Looks like this is still an issue, I'd like to keep this issue open as it seems to be affecting too many people 😥

**Comment by EmilioPelaez** [comment]
It's still happening in 2.168.0

**Comment by davlhd** [comment]
For me too with 2.169.0.

**Comment by p8** [comment]
I had some luck with changing the `padding` and `title_min_height`:
```
  "data": [
    {
      "filter": "iPad Pro (12.9-inch) (3rd generation)",
      "padding": "3%x8%",
      "interline_spacing": 30,
      "font_size": 130,
      "title_min_height": "15%"
    },
    {
      "filter": "iPhone 6 Plus",
      "padding": "3%x8%",
      "interline_spacing": 30,
      "font_size": 130,
      "title_min_height": "20%"
    }
]
```
