### ISSUE TITLE
Fastlane Pilot Distribute Clears TestFlight Data

### ISSUE THREAD

**Issue by Blackjacx** [fastlane/fastlane#16394]
### Issue Description
I use the command line version of pilot (see below) to notify testers about already uploaded builds.

The command figures out the latest version - build number - combination and adds the specified tester groups to this build.

Since some weeks this command wipes out the data which can be specified via `beta_app_review_info` parameter (specifically the contact information) when this is executed in the context of a lane and not via command line. We never specified this since it is already set in TestFlight. Suddenly pilot started wiping this data if not provided.

I expect that this data stays untouched when it is not provided in pilot.

### Command executed
```shell
fastlane pilot distribute -q <itc_team_id> --distribute_external "true" --notify_external_testers "true" --demo_account_required "false" -a <bundle_id> -g <tester_groups> -w <changelog>
```

### Complete output when running fastlane, including the stack trace and command used
```shell
[15:26:56]: ▸ ➡️  Spaceship::UnexpectedResponse: [!] Missing required information to submit for external testing - Missing requied data.
[15:26:56]: ▸ https://github.com/fastlane/fastlane/issues/16294 [closed] 26 💬
[15:26:56]: ▸ a day ago
[15:26:56]: ▸ 🔗  You can ⌘ + double-click on links to open them directly in your browser.
[15:26:56]: ▸ bundler: failed to load command: fastlane (/Users/stherold/.gem/bin/fastlane)
[15:26:56]: ▸ Spaceship::UnexpectedResponse: [!] Missing required information to submit for external testing - Missing requied data.
[15:26:56]: ▸ /Users/stherold/.gem/gems/fastlane-2.146.1/spaceship/lib/spaceship/connect_api/client.rb:134:in `handle_response'
[15:26:56]: ▸ /Users/stherold/.gem/gems/fastlane-2.146.1/spaceship/lib/spaceship/connect_api/client.rb:96:in `post'
[15:26:56]: ▸ /Users/stherold/.gem/gems/fastlane-2.146.1/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:105:in `post_beta_app_review_submissions'
[15:26:56]: ▸ /Users/stherold/.gem/gems/fastlane-2.146.1/spaceship/lib/spaceship/connect_api/models/build.rb:159:in `post_beta_app_review_submission'
[15:26:56]: ▸ /Users/stherold/.gem/gems/fastlane-2.146.1/pilot/lib/pilot/build_manager.rb:349:in `distribute_build'
[15:26:56]: ▸ /Users/stherold/.gem/gems/fastlane-2.146.1/pilot/lib/pilot/build_manager.rb:173:in `distribute'
[15:26:56]: ▸ /Users/stherold/.gem/gems/fastlane-2.146.1/pilot/lib/pilot/commands_generator.rb:78:in `block (2 levels) in run'
[15:26:56]: ▸ /Users/stherold/.gem/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
[15:26:56]: ▸ /Users/stherold/.gem/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
[15:26:56]: ▸ /Users/stherold/.gem/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
[15:26:56]: ▸ /Users/stherold/.gem/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
[15:26:56]: ▸ /Users/stherold/.gem/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
[15:26:56]: ▸ /Users/stherold/.gem/gems/fastlane-2.146.1/pilot/lib/pilot/commands_generator.rb:166:in `run'
[15:26:56]: ▸ /Users/stherold/.gem/gems/fastlane-2.146.1/pilot/lib/pilot/commands_generator.rb:18:in `start'
[15:26:56]: ▸ /Users/stherold/.gem/gems/fastlane-2.146.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
[15:26:56]: ▸ /Users/stherold/.gem/gems/fastlane-2.146.1/bin/fastlane:23:in `<top (required)>'
[15:26:56]: ▸ /Users/stherold/.gem/bin/fastlane:23:in `load'
[15:26:56]: ▸ /Users/stherold/.gem/bin/fastlane:23:in `<top (required)>'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.4                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.26.2                                             |
| Installation Source         | ~/.gem/bin/fastlane                                            |
| Host                        | Mac OS X 10.15.4 (19E287)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.4.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile attached**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.146.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-changelog | 0.15.0  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.1.4        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.6        |
| i18n                      | 0.9.5        |
| minitest                  | 5.14.0       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.7        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.0        |
| algoliasearch             | 1.27.1       |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.302.0      |
| aws-sigv4                 | 1.1.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.94.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.63.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| cork                      | 0.3.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| fuzzy_match               | 2.0.4        |
| netrc                     | 0.11.0       |
| ffi                       | 1.12.2       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.3.1        |
| cocoapods-core            | 1.9.1        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.3.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| cocoapods-trunk           | 1.4.1        |
| cocoapods-try             | 1.2.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| cocoapods                 | 1.9.1        |
| coderay                   | 1.1.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| faraday-http-cache        | 2.2.0        |
| rchardet                  | 1.8.0        |
| git                       | 1.6.0        |
| rexml                     | 3.2.4        |
| kramdown                  | 2.2.1        |
| kramdown-parser-gfm       | 1.1.0        |
| no_proxy_fix              | 0.1.2        |
| sawyer                    | 0.8.2        |
| octokit                   | 4.18.0       |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| danger                    | 7.0.0        |
| danger-plugin-api         | 1.0.0        |
| danger-changelog          | 0.6.0        |
| danger-commit_lint        | 0.0.7        |
| thor                      | 0.20.3       |
| danger-swiftlint          | 0.24.2       |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.73.0       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.12.0       |
| mini_mime                 | 1.0.2        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| digest-crc                | 0.5.1        |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.0       |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| xcresult                  | 0.2.0        |
| xcov                      | 1.7.2        |
| danger-xcov               | 0.4.1        |
| fastlane-plugin-changelog | 0.15.0       |
| method_source             | 1.0.0        |
| pry                       | 0.13.1       |
</details>

*generated on:* **2020-04-28**
</details>

**Comment by Blackjacx** [comment]
Already fixed by https://github.com/fastlane/fastlane/pull/16314

**Comment by ajaykn** [comment]
@Blackjacx I am still facing the issue when using via command line.
`fastlane pilot upload -u xxx -a xxxx -q xxxxx -g xxxxx`

The fix #16314 solves only when we pass `beta_app_review_info` with values.
But we don't have to pass every time we distribute the build.

And the code here is checking 
`# If demo_account_required is a parameter, it should added into beta_app_review_info`
https://github.com/fastlane/fastlane/blob/master/pilot/lib/pilot/build_manager.rb#L219

which means we always tries to update beta_app_review_info with 
` 
{
    "demoAccountRequired": false
}`

And I have verified the behaviour by hitting the `betaAppReviewDetails` patch call and it resets if other values in `attributes` doesn't exists

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/40024974/80880032-ad35d680-8cd9-11ea-9df0-1a1d4be10a81.png">

**Comment by Blackjacx** [comment]
Okay @ajaykn , I closed this since we have to upload the data and now that I specify everything it just works. But you're maybe right. I ask you to have a look on  https://github.com/fastlane/fastlane/issues/16294#issuecomment-613866125 and https://github.com/fastlane/fastlane/issues/16294#issuecomment-613872740. It might be possible that Apple changed the way it works. Now you may have to specif that data each time you upload a build.

**Comment by ajaykn** [comment]
Thanks @Blackjacx, Glad your scenario doesn't fall into same case as mine. I don't have to pass beta info every time.

As part of fastlane, below are the high level steps.
1. first build is uploaded
2. wait for the build to be processed by apple
3. update beta review info
4. Submit for review

Now as part of 3rd step, you are correct, Apple might have changed its behaviour and so it's resetting the beta info, which needs to fixed by fastlane aligning to latest apple behaviour.
And so 4th step is failing with valid error `Missing required fields`.

I will see if some one replies in another thread, else will create a new issue :) Thanks.

**Comment by Blackjacx** [comment]
Why don't you just specify your beta review info as environment varaible in the fastlane/.env file? Fastlane picks that up automatically and the error is gone. Plus you can be sure you always have the correct data up there for each distribution. I like this new approach much more. The is how it needs  to be set in `fastlane/.env`:

```
PILOT_BETA_APP_REVIEW_INFO='{
  "contact_email": "team@company.com",
  "contact_first_name": "John",
  "contact_last_name": "Doe",
  "contact_phone": "+123456789
  "demo_account_name": "+1234567890",
  "demo_account_password": "123456"
}'
```

You can try to just leave out the demo-account related fields if not needed. I didn't try that but it should just work.

If you run your distribution on a CI you can specify the same environment variable there in the environment section. Again fastlane will just pick up the data and work as expected.

**Comment by ajaykn** [comment]
Yeah, since we don’t have this info every time we distribute, we updated by fetching the existing beta review info and passing it again.

Thanks for ur points again.

**Comment by rogerluan** [comment]
> Why don't you just specify your beta review info as environment varaible in the fastlane/.env file? Fastlane picks that up automatically and the error is gone. Plus you can be sure you always have the correct data up there for each distribution. I like this new approach much more. The is how it needs to be set in `fastlane/.env`:
> 
> ```
> PILOT_BETA_APP_REVIEW_INFO='{
>   "contact_email": "team@company.com",
>   "contact_first_name": "John",
>   "contact_last_name": "Doe",
>   "contact_phone": "+123456789
>   "demo_account_name": "+1234567890",
>   "demo_account_password": "123456"
> }'
> ```
> 
> You can try to just leave out the demo-account related fields if not needed. I didn't try that but it should just work.
> 
> If you run your distribution on a CI you can specify the same environment variable there in the environment section. Again fastlane will just pick up the data and work as expected.
> 
> This implementation by fastlane is just a couple of days ld. So I think it is the reaction of this change by Apple.

For those getting `[!] 'beta_app_review_info' value must be a Hash! Found String instead.`, it took me awhile to realize that the snippet above is missing a `",` after the contact phone value 😅 

Fixed:
```
PILOT_BETA_APP_REVIEW_INFO='{
  "contact_email": "team@company.com",
  "contact_first_name": "John",
  "contact_last_name": "Doe",
  "contact_phone": "+123456789",
  "demo_account_name": "+1234567890",
  "demo_account_password": "123456"
}'```

**Comment by Blackjacx** [comment]
Ooooops sorry for the inconvenience... good catch @rogerluan 👍 I fixed it.
