### ISSUE TITLE
Fastlane match fails to import private key into keychain

### ISSUE THREAD

**Issue by lyf571321556** [fastlane/fastlane#17209]
fastlane 2.154.0

encrypt step:

openssl pkcs12 -nocerts -nodes -out key.pem -in xxxx.p12 -password pass:$MATCH_PASSWORD
openssl aes-256-cbc -k $MATCH_PASSWORD -in key.pem -out $CERT_ID.p12 -a
openssl aes-256-cbc -k $MATCH_PASSWORD -in xxxx.cer -out $CERT_ID.cer -a

fastlane match log:
INFO [2020-09-10 11:24:53.93]: $ security import /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/d20200910-9738-1qngoqg/certs/distribution/WXFCAHFH47.p12 -k '/Users/travis/Library/Keychains/fastlane_tmp_keychain-db' -P '' -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
ERROR [2020-09-10 11:24:53.99]: security: SecKeychainItemImport: Unknown format in import.

**Comment by lyf571321556** [comment]
╰ fastlane env
[✔] 🚀
[19:42:33]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[19:42:36]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.5                                     |
| Ruby                        | 2.4.9                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.9/bin/fastlane         |
| Host                        | Mac OS X 10.15.5 (19F101)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.9/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.6                                        |

**Comment by seeligd** [comment]
I'm encountering the same issue. Here's the important parts of my  `fastlane env` output

```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.7                                          |
| Ruby                        | 2.7.1                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.24.3 (Apple Git-128)               |
| Installation Source         | ~/.rbenv/versions/2.7.1/bin/fastlane             |
| Host                        | Mac OS X 10.15.7 (19H2)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.1/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-12.0.app/Contents/Developer/ |
| Xcode Version               | 12.0                                             |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

# NOTE: removed everything but the critical section

lane :ios_cert_setup_enterprise do
	internalAppIdentifiers = [
		"#{iosInternalBundleIdentifierPrefix}"
	]

	for extensionName in iosExtensionNames
		internalAppIdentifiers.push("#{iosInternalBundleIdentifierPrefix}.#{extensionName}")
	end

	for appIdentifier in internalAppIdentifiers
		match(git_url: "ssh://git@some.hostname:7999/path/apple_certs_profiles.git",
			type: "development",
			app_identifier: appIdentifier,
			username: APPLE_USER_ID,
			team_id: "XXXXXXXXXX",
			force_for_new_devices: true,
			verbose: true,
			readonly: true)
	end
end

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.165.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.2        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| emoji_regex               | 3.0.0        |
| uri                       | 0.10.0       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.19.0       |
| public_suffix             | 4.0.6        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| json                      | 2.3.1        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.3.3        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.0       |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-partitions            | 1.378.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.109.0      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.82.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>


*generated on:* **2020-10-23**
</details>
```

**Comment by xilin** [comment]
Hi @seeligd  :) https://github.com/fastlane/fastlane/issues/12260#issuecomment-379596642 seems to be a manually fix. There is a typo there so I edit here:
```
# decrypt private key
openssl aes-256-cbc -k YOUR-PASSWORD -in certs/distribution/FOOBAR123.p12 -out key.pem -a -d
# decrypt cert
openssl aes-256-cbc -k YOUR-PASSWORD -in certs/distribution/FOOBAR123.cer -out cert.der -a -d
# convert cert from der to pem
openssl x509 -inform der -in cert.der -out cert.pem
# combine private key + cert into p12 (enter password to secure output p12 file)
openssl pkcs12 -export -out cert.p12 -inkey key.pem -in cert.pem
```

However it would be better if we can find the root cause. Maybe a fix openssl version?

**Comment by rogerluan** [comment]
Hey 👋 

This may have been fixed here: https://github.com/fastlane/fastlane/pull/17456

Since that PR was released 16 days ago in https://github.com/fastlane/fastlane/releases/tag/2.164.0, could you update to the latest version of _fastlane_ and try again? 🙏

**Comment by seeligd** [comment]
@rogerluan thanks for the note - I just deleted the key from Keychain Access and tried with fastlane-2.166.0; keys were encrypted with LibreSSL 2.8.3.

Still getting the error:
ERROR [2020-11-04 19:41:41.81]: security: SecKeychainItemImport: Unknown format in import.

**Comment by rogerluan** [comment]
@seeligd Any feedback wrt the solution that @xilin posted above? Does that work for you?
