### ISSUE TITLE
result_bundle: true required to output tests xcresult file

### ISSUE THREAD

**Issue by spitz** [fastlane/fastlane#19866]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Follow on to issue: https://github.com/fastlane/fastlane/issues/19824#issuecomment-1020306518 
@joshdholtz - creating the issue requested

run_tests does not output the required xcresults file that xcov is looking for by default unless we explicitly turn on `result_bundle: true`

##### Command executed

```
run_tests(workspace: "[ProjectName].xcworkspace",
              devices: ["iPhone 11"],
              code_coverage: true,
              output_directory: "test_output/" + target,
              output_types: "html,junit,json-compilation-database",
              scheme: target)

    xcov(workspace: "[ProjectName].xcworkspace",
         scheme: target,
         output_directory: "test_output/" + target + "/coverage")
```

##### Complete output when running fastlane, including the stack trace and command used

Please reference:https://github.com/fastlane/fastlane/issues/19824

### Environment

Please reference:https://github.com/fastlane/fastlane/issues/19824

**Comment by Chesterqa** [comment]
Same issue here and i cant find any solutions

**Comment by joshdholtz** [comment]
@spitz @Chesterqa This should have been fixed in https://github.com/fastlane/fastlane/pull/19845 for you!

- With `result_bundle: false` will keep `.xcresult` in the derived data but `scan` will try to find it
- With `result_bundle: true` the `.xcresult` will be placed in the output directory

The `.xcresult` path can be found with both the cases with...
```rb
scan()
xcresult_path = Actions.lane_context[SharedValues::SCAN_GENERATED_XCRESULT_PATH]
```

This was released in `2.201.2`. Let me know if this still isn't working for you!

**Comment by Emmitt121** [comment]
Seems like i got mine solution thanks for sharing keep it up.

**Comment by onevcat** [comment]
@joshdholtz Thanks for the fix.

It worked for an app target:

```
scan(
  scheme: "MyApp", 
  clean: true,
)
```

But for a local package target, it still fails with the same error:

```
scan(
  package_path: "Packages/MyPackage",
  scheme: "MyLibInPackage",
    device: "iPhone 13",
)
```

I also noticed that in https://github.com/fastlane/fastlane/issues/19841 there is a similar report from @evenoe , maybe he's also in a similar context?

Any ideas?

**Comment by Emmitt121** [comment]
I conflicted with a general kind of issue last time, I am at this point searching for some obvious plan.
[MyBalanceNow](https://www.mybalancenow.tips/)

**Comment by clintmod** [comment]
Wanted to comment the final solution that worked for me:

```ruby
  desc "Run test coverage"
  lane :coverage do
    # A future version of fastlane and xcov will pick this up automatically
    xcresult_path = File.absolute_path(Dir["test_output/*.xcresult"].first)
    xcov(
      xccov_file_direct_path: xcresult_path,
      workspace: "XXX.xcworkspace",
      scheme: "XXX",
      output_directory: "xcov_output"
    )
  end
```
