### ISSUE TITLE
select_team': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by ronpelayo** [fastlane/fastlane#20086]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [`2.205.0`]
- Last working version: [`2.204.3`]

### Regression Description

It crashes once I run select_team

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>

**Spaceship::Tunes.select_team**

Multiple App Store Connect teams found, please enter the number of the team you want to use: 
Note: to automatically choose the team, provide either the App Store Connect Team ID, or the Team Name in your fastlane/Appfile:
Alternatively you can pass the team name or team ID using the `FASTLANE_ITC_TEAM_ID` or `FASTLANE_ITC_TEAM_NAME` environment variable

/Users/xxx/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/fastlane-2.205.0/spaceship/lib/spaceship/tunes/tunes_client.rb:98:in `block in select_team': undefined method `[]' for nil:NilClass (NoMethodError)
from /Users/xxx/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/fastlane-2.205.0/spaceship/lib/spaceship/tunes/tunes_client.rb:91:in `loop'
from /Users/xxx/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/fastlane-2.205.0/spaceship/lib/spaceship/tunes/tunes_client.rb:91:in `select_team'
from /Users/xxx/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/fastlane-2.205.0/spaceship/lib/spaceship/tunes/spaceship.rb:35:in `select_team'
from (irb):12:in `<main>'
from /Users/xxx/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
from /Users/xxx/.rbenv/versions/3.0.2/bin/irb:23:in `load'
from /Users/xxx/.rbenv/versions/3.0.2/bin/irb:23:in `<main>'
</pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.0.1                                      |
| Ruby                        | 3.0.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.30.1 (Apple Git-130)          |
| Installation Source         | ~/.rbenv/versions/3.0.2/bin/fastlane        |
| Host                        | macOS 12.0.1 (21A559)                       |
| Ruby Lib Dir                | ~/.rbenv/versions/3.0.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.1                                        |
| Swift Version               | 5.5.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.205.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.4        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.88.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.22       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.6.0        |
| google-apis-androidpublisher_v3 | 0.13.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.8.0        |
| google-apis-storage_v1          | 0.9.0        |
| rake                            | 13.0.3       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.521.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.121.5      |
| aws-sdk-kms                     | 1.50.0       |
| aws-sdk-s3                      | 1.104.0      |
| tsort                           | 0.1.0        |
| uri                             | 0.10.1       |
| set                             | 1.0.1        |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| openssl                         | 2.2.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| securerandom                    | 0.1.0        |
| digest                          | 3.0.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |
</details>

*generated on:* **2022-03-18**
</details></pre>
</details>

**Comment by h-nomura0504** [comment]
The following PR corrects this problem.
https://github.com/fastlane/fastlane/pull/20088

Temporarily, you can work around this problem by rewriting the fastlane in the Gemfile as follows

```
gem "fastlane", :git => "https://github.com/nomunomu0504/fastlane.git", :branch => "fix-teams-undefined-key"
```

**Comment by nomunomu0504** [comment]
The following PR corrects this problem.
https://github.com/fastlane/fastlane/pull/20088

Temporarily, you can work around this problem by rewriting the fastlane in the Gemfile as follows

```
gem "fastlane", :git => "https://github.com/nomunomu0504/fastlane.git", :branch => "fix-teams-undefined-key"
```

**Comment by felipepalazzo** [comment]
I tried the workaround above, still getting the error:

```
Multiple App Store Connect teams found, please enter the number of the team you want to use:
[09:39:17]: --------------------
[09:39:17]: fastlane init failed
[09:39:17]: --------------------
[09:39:18]: undefined method `[]' for nil:NilClass
```

**Comment by ronpelayo** [comment]
> The following PR corrects this problem. #20088
> 
> Temporarily, you can work around this problem by rewriting the fastlane in the Gemfile as follows
> 
> ```
> gem "fastlane", :git => "https://github.com/nomunomu0504/fastlane.git", :branch => "fix-teams-undefined-key"
> ```

This worked for me using spaceship. Thank you

**Comment by nomunomu0504** [comment]
@felipepalazzo 
Thank you reporting. Could you give us detailed information on how to reproduce this?

**Comment by felipepalazzo** [comment]
@nomunomu0504 To give you some context, I'm using React Native v0.66.4. 

Steps to reproduce:

- inside ios folder, run `fastlane init`
- select option 2, "Automate beta distribution to TestFlight"
- type your Apple ID Username (in my case, I have Admin rights)
- just after that step, I see the error in the terminal

**Comment by nomunomu0504** [comment]
@felipepalazzo 

Thanks for the details. I tried the reproduction method and it did not cause any errors in my environment.

If you have rewritten the gemfile, be sure to run `bundle update`.

If you do not run `bundle update`, the modified library will not be imported and the faulty library will be used.

**Comment by nomunomu0504** [comment]
@seokjeatuiti cc: @felipepalazzo 

I understood. I fixed later :(

**Comment by felipepalazzo** [comment]
same as @seokjeatuiti, even after running `bundle update`, I still get the error.

**Comment by seokjeatuiti** [comment]
@nomunomu0504 
Actually I think it was my mistake and i didn't know how to use the bundler properly.
Instead of `fastlane init`, `bundle exec fastlane init` works fine.
Thanks. 🙇‍♂

**Comment by felipepalazzo** [comment]
@nomunomu0504 `bundle exec fastlane init` worked for me as well

**Comment by nomunomu0504** [comment]
@tymcdowell 
Thanks report.
I tried this code and did not cause any errors in my environment.

- Gemfile
```
source "https://rubygems.org"

gem "fastlane", :git => "https://github.com/nomunomu0504/fastlane.git", :branch => "fix-teams-undefined-key"
```

- test.rb
```
require "bundler/setup"
require "spaceship"

Spaceship::Tunes.login("#{devAcctEmail}")
Spaceship::Tunes.select_team
```

How to run（I using asdf for manage multiple version）
Ruby 2.6.0
```
$ asdf exec bundle install
Fetching https://github.com/nomunomu0504/fastlane.git
Updating files: 100% (2733/2733), done.
Fetching gem metadata from https://rubygems.org/........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
...
Using fastlane 2.205.0 from https://github.com/nomunomu0504/fastlane.git (at fix-teams-undefined-key@4d83d3d)
Bundle complete! 1 Gemfile dependency, 90 gems now installed.
Bundled gems are installed into `./vendor/bundle`

$ asdf exec bundler exec ruby test.rb 
Available session is not valid any more. Continuing with normal login.
Multiple App Store Connect teams found, please enter the number of the team you want to use: 
Note: to automatically choose the team, provide either the App Store Connect Team ID, or the Team Name in your fastlane/Appfile:
Alternatively you can pass the team name or team ID using the `FASTLANE_ITC_TEAM_ID` or `FASTLANE_ITC_TEAM_NAME` environment variable

  itc_team_id "xxxxxxxxxx"

or

  itc_team_name "Org1"

1) "Org1" (xxxxxxxxxx)
2) "Parson1" (yyyyyyy)
3) "Org2" (zzzzzzzz)
```

**Comment by tymcdowell** [comment]
> 
Thank you!! This works. I already had changed my Gemfile, but the key was including 
`  require "bundler/setup"`

> @tymcdowell Thanks report. I tried this code and did not cause any errors in my environment.
> 
> * Gemfile
> 
> ```
> source "https://rubygems.org"
> 
> gem "fastlane", :git => "https://github.com/nomunomu0504/fastlane.git", :branch => "fix-teams-undefined-key"
> ```
> 
> * test.rb
> 
> ```
> require "bundler/setup"
> require "spaceship"
> 
> Spaceship::Tunes.login("#{devAcctEmail}")
> Spaceship::Tunes.select_team
> ```
> 
> How to run（I using asdf for manage multiple version） Ruby 2.6.0
> 
> ```
> $ asdf exec bundle install
> Fetching https://github.com/nomunomu0504/fastlane.git
> Updating files: 100% (2733/2733), done.
> Fetching gem metadata from https://rubygems.org/........
> Fetching gem metadata from https://rubygems.org/.
> Resolving dependencies....
> ...
> Using fastlane 2.205.0 from https://github.com/nomunomu0504/fastlane.git (at fix-teams-undefined-key@4d83d3d)
> Bundle complete! 1 Gemfile dependency, 90 gems now installed.
> Bundled gems are installed into `./vendor/bundle`
> 
> $ asdf exec bundler exec ruby test.rb 
> Available session is not valid any more. Continuing with normal login.
> Multiple App Store Connect teams found, please enter the number of the team you want to use: 
> Note: to automatically choose the team, provide either the App Store Connect Team ID, or the Team Name in your fastlane/Appfile:
> Alternatively you can pass the team name or team ID using the `FASTLANE_ITC_TEAM_ID` or `FASTLANE_ITC_TEAM_NAME` environment variable
> 
>   itc_team_id "xxxxxxxxxx"
> 
> or
> 
>   itc_team_name "Org1"
> 
> 1) "Org1" (xxxxxxxxxx)
> 2) "Parson1" (yyyyyyy)
> 3) "Org2" (zzzzzzzz)
> ```

**Comment by jterhorst** [comment]
We were also encountering this. It appeared to be because we have multiple teams on the account affected. The workaround was to provide `FASTLANE_ITC_TEAM_NAME` when invoking the Fastlane command.

**Comment by jonas-simkus-mw** [comment]
We are still encountering same error, this does not seem to be fixed yet. We can not produce any builds, neither with latest version nor the earlier versions of fastlane.

**Comment by antoinelefebvre17** [comment]
Me too, same error.

**Comment by ccalabro** [comment]
failing for me as well using the latest version

**Comment by shmkane** [comment]
failing for us, even with version 2.205.1

**Comment by bobsmits** [comment]
Same here does not seem to be fixed.

**Comment by vitorverasm** [comment]
failling using 2.205.1

**Comment by jwaldrip** [comment]
Same for us, still borked.

**Comment by jterhorst** [comment]
Fixed for us on 2.205.1. We made sure our WWDR certificates are updated as part of our scripts, as noted in this SO post: https://stackoverflow.com/questions/71850186/invalid-provisioning-profile-signature-state-error-validation-error-90165

**If you are still encountering this error, please first update your WWDR certificates. If after updating those you still encounter it, create a ticket instead of posting here. Thank you!**

**Comment by vitorverasm** [comment]
> Fixed for us on 2.205.1. We made sure our WWDR certificates are updated as part of our scripts, as noted in this SO post: https://stackoverflow.com/questions/71850186/invalid-provisioning-profile-signature-state-error-validation-error-90165
> 
> **If you are still encountering this error, please first update your WWDR certificates. If after updating those you still encounter it, create a ticket instead of posting here. Thank you!**

updating the WWDR certificates and using fastlane 2.205.1 solved for me
