### ISSUE TITLE
Xcode 14: Could not find transporter error

### ISSUE THREAD

**Issue by mzsanford** [fastlane/fastlane#20664]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

After switching to Xcode 14 the `fastlane beta` command I had been using, which calls `upload_to_testflight`, began to fail with the error `[!] Could not find transporter at /Applications/Xcode.app/Contents/Developer/. Please make sure you set the correct path to your Xcode installation.`

##### Command executed

The call in question boils down to:

```
    upload_to_testflight(
      apple_id: team_id,
      changelog: test_notes
    )
```

I'm not at liberty to post the full code and output because it includes content from the codebase I am contracted not to disclose. I checked the installation in question and Xcode 14 does not have the `itms` program that Fastlane is looking for. Perhaps it has been renamed or replaced.

**Comment by freddi-kit** [comment]
This problem is fixed 2.210.0 version. Can you see your fastlane version by `--version`?

**Comment by mzsanford** [comment]
Turns out I had updated when I started investigating the issue and 2.210.0 was released after that. I upgraded and confirmed it fixed the issue.

**Comment by LugonjaAleksandar** [comment]
Did anyone figure out how to setup specific version (2.210.0) on github actions? There is no option provided for it, and the error persists for `maierj/fastlane-action@v2.3.0`

**Comment by SarjuHansaliya** [comment]
> Did anyone figure out how to setup specific version (2.210.0) on github actions? There is no option provided for it, and the error persists for `maierj/fastlane-action@v2.3.0`

You will need to update `Gemfile.lock` file with the version you want so github action can take version from there.

**Comment by LugonjaAleksandar** [comment]
> > Did anyone figure out how to setup specific version (2.210.0) on github actions? There is no option provided for it, and the error persists for `maierj/fastlane-action@v2.3.0`
> 
> You will need to update `Gemfile.lock` file with the version you want so github action can take version from there. You can use `bundle update fastlane` to update fastlane version in `Gemfile.lock`

Yes, that was the issue for me. Once I've added lock file to gitignore, it started using latest version and all worked fine.

**Comment by piotrsmajek** [comment]
Is there any workaround for it? We can't update fastlane from 2.200.0 version due to this issue https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/384

**Comment by walkingbrad** [comment]
I found that this error still comes up (on v2.211.0) when we pass `verify_only: true`, at least in my one test of doing so. Setting it to false allows the action to succeed.
