### ISSUE TITLE
match fails after installing certificates on setting cached_profiles

### ISSUE THREAD

**Issue by vtrikoupis** [fastlane/fastlane#21779]
### New Issue Checklist

- [ X ] Updated fastlane to the latest version
- [ X ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ X ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ X ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`match` fails because of `cached_profiles` being set to `[]`

##### Command executed
`fastlane match development --verbose`

##### Complete output when running fastlane, including the stack trace and command used
```
INFO [2024-01-04 18:15:39.69]: Verifying the certificate is properly installed locally...
INFO [2024-01-04 18:15:39.69]: Successfully installed certificate U38U12345
ERROR [2024-01-04 18:15:41.23]: Error setting value '[]' for option 'cached_profiles'
/opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:250:in `rescue in valid?': [!] cached_profiles parameter must be a non-empty array of Spaceship::ConnectAPI::Profile (FastlaneCore::Interface::FastlaneError)
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:246:in `valid?'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:195:in `verify!'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:87:in `block in verify_value_exists'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:82:in `each'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:82:in `verify_value_exists'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:66:in `initialize'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:36:in `new'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:36:in `create'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/match/lib/match/generator.rb:115:in `generate_provisioning_profile'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/match/lib/match/runner.rb:276:in `fetch_provisioning_profile'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/match/lib/match/runner.rb:106:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/match/lib/match/runner.rb:105:in `loop'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/match/lib/match/runner.rb:105:in `block in run'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/match/lib/match/runner.rb:104:in `each'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/match/lib/match/runner.rb:104:in `run'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/match/lib/match/commands_generator.rb:69:in `block (3 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/match/lib/match/commands_generator.rb:186:in `run'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/match/lib/match/commands_generator.rb:26:in `start'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/bin/fastlane:25:in `<main>'
/opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': cached_profiles parameter must be a non-empty array of Spaceship::ConnectAPI::Profile (FastlaneCore::Interface::FastlaneError)
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/sigh/lib/sigh/options.rb:247:in `block in available_options'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:247:in `valid?'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:195:in `verify!'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:87:in `block in verify_value_exists'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:82:in `each'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:82:in `verify_value_exists'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:66:in `initialize'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:36:in `new'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:36:in `create'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/match/lib/match/generator.rb:115:in `generate_provisioning_profile'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/match/lib/match/runner.rb:276:in `fetch_provisioning_profile'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/match/lib/match/runner.rb:106:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/match/lib/match/runner.rb:105:in `loop'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/match/lib/match/runner.rb:105:in `block in run'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/match/lib/match/runner.rb:104:in `each'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/match/lib/match/runner.rb:104:in `run'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/match/lib/match/commands_generator.rb:69:in `block (3 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/match/lib/match/commands_generator.rb:186:in `run'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/match/lib/match/commands_generator.rb:26:in `start'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/gems/fastlane-2.218.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.218.0/libexec/bin/fastlane:25:in `<main>
```

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 14.1.1                                                     |
| Ruby                        | 3.2.2                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.39.3 (Apple Git-145)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.218.0/libexec/bin/fastlane |
| Host                        | macOS 14.1.1 (23B81)                                       |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.2.2_1/lib                      |
| OpenSSL Version             | OpenSSL 3.1.1 30 May 2023                                  |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 15.1                                                       |
| Swift Version               | 5.9.2                                                      |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

api_key = app_store_connect_api_key(
  key_id: ENV["KEY_ID"],
  issuer_id: ENV["ISSUER_ID"],
  key_content: ENV["API_KEY"],
  # duration: 1200, # Optional (maximum 1200)
  # in_house: false # Optional but may be required if using match/sigh
)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")

    upload_to_testflight(
      api_key: api_key,
      beta_app_feedback_email: "app@mycompany.com",
      app_identifier: "com.mycompany.app",
      demo_account_required: false,
      )
  end
end



```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.mycompany.app") # The bundle identifier of your app
apple_id("app-deployer@mycompany.com") # Your Apple Developer Portal username

itc_team_id("123123123") # App Store Connect Team ID
team_id("ASDASDASD") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.218.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.5.1        |
| did_you_mean                    | 1.6.3        |
| syntax_suggest                  | 1.0.2        |
| public_suffix                   | 5.0.4        |
| addressable                     | 2.8.6        |
| artifactory                     | 3.0.15       |
| jmespath                        | 1.6.2        |
| aws-partitions                  | 1.876.0      |
| aws-eventstream                 | 1.3.0        |
| aws-sigv4                       | 1.8.0        |
| aws-sdk-core                    | 3.190.1      |
| aws-sdk-kms                     | 1.75.0       |
| aws-sdk-s3                      | 1.142.0      |
| babosa                          | 1.0.4        |
| bundler                         | 2.4.10       |
| rexml                           | 3.2.6        |
| CFPropertyList                  | 3.0.6        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.108.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.3.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| faraday_middleware              | 1.2.0        |
| domain_name                     | 0.6.20231109 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.3.0        |
| gh_inspector                    | 1.1.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.5        |
| google-cloud-env                | 2.1.0        |
| jwt                             | 2.7.1        |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.18.0       |
| googleauth                      | 1.9.1        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.8.1        |
| google-apis-core                | 0.11.2       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.1        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.29.0       |
| rake                            | 13.1.0       |
| digest-crc                      | 0.6.5        |
| google-cloud-storage            | 1.45.0       |
| json                            | 2.6.3        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.3.1        |
| plist                           | 3.7.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.5.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.23.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.0.3        |
| forwardable                     | 1.3.3        |
| logger                          | 1.5.3        |
| pathname                        | 0.2.1        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.6        |
| date                            | 3.3.3        |
| timeout                         | 0.3.1        |
| securerandom                    | 0.2.2        |
| uri                             | 0.12.1       |
| openssl                         | 3.1.0        |
| digest                          | 3.1.1        |
| ipaddr                          | 1.2.5        |
| resolv                          | 0.2.2        |
| time                            | 0.2.2        |
| stringio                        | 3.0.4        |
| open-uri                        | 0.3.0        |
| mutex_m                         | 0.1.2        |
| net-http                        | 0.3.2        |
| net-protocol                    | 0.2.1        |
| ostruct                         | 0.5.5        |
| english                         | 0.7.2        |
| erb                             | 4.0.2        |
| abbrev                          | 0.1.1        |
| tempfile                        | 0.1.3        |
| delegate                        | 0.3.0        |
| fileutils                       | 1.7.0        |
| tmpdir                          | 0.1.3        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.2        |
| nkf                             | 0.1.2        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.4.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.1        |
| psych                           | 5.0.1        |
</details>

*generated on:* **2024-01-04**
</details>

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by joshdholtz** [comment]
This should be fixed in `2.219.0` which just went out but let us know if not!

**Comment by alexkater** [comment]
I had to downgrade to 2.217.0 as was still failing on 2.219.0
