### ISSUE TITLE
The provided entity includes an unknown relationship - 'prices' is not a relationship on the resource

### ISSUE THREAD

**Issue by lakshydeep-14** [fastlane/fastlane#21819]
The provided entity includes an unknown attribute - 'availableInNewTerritories' is not an attribute on the resource 'apps' - /data/attributes/availableInNewTerritories
The provided entity includes an unknown relationship - 'prices' is not a relationship on the resource 'apps' - /data/relationships/prices
The provided entity includes an unknown relationship - 'availableTerritories' is not a relationship on the resource 'apps' - /data/relationships/availableTerritories

**Comment by d3r3nic** [comment]
Same Issue here:

 A parameter has an invalid value - 'prices' is not a valid relationship name
bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/3.0.0/bin/fastlane)
/usr/local/lib/ruby/gems/3.0.0/bundler/gems/fastlane-4c9c094ac28d/spaceship/lib/spaceship/connect_api/api_client.rb:204:in `handle_response': \e[31m[!] A parameter has an invalid value - 'prices' is not a valid relationship name\e[0m (Spaceship::UnexpectedResponse)

**Comment by Jinxiansen** [comment]
Hi guys,
We also got this error when upload ipa to AppStore.
Does anyone know the root cause? This is urgent.
```
[14:00:23]: A parameter has an invalid value - 'prices' is not a valid relationship name
```
<img width="1086" alt="image" src="https://github.com/fastlane/fastlane/assets/16829428/4cecfec9-d7bf-4d13-9626-eda25d10ff11">

**Comment by damirstuhec** [comment]
Same here.

**Comment by shashwatkn** [comment]
Same here

**Comment by damirstuhec** [comment]
@Jinxiansen thanks, updating to the latest version of fastlane indeed fixed the issue. 👍

**Comment by y-hakutaku** [comment]
same here

**Comment by abhi-0213** [comment]
Why is this happening, i just wanted to send a build to review and i see this error, is this a bug from Fastlane?

**Comment by abhi-0213** [comment]
> same here but resolved by new version `2.219.0`. thanks @Jinxiansen

how did you update, did you update the Gemfile with the new version or did gem install fastlane?

**Comment by gabma** [comment]
Updating to `2.219.0` didn't solve the `the provided entity includes an unknown attribute - 'availableInNewTerritories'`  issue for us, also mentioned here https://github.com/fastlane/fastlane/issues/21820

**Comment by khvorost-dish** [comment]
2.219.0 works for iOS but I have the following problem on tvOS with `match`:
```
Spaceship::UnexpectedResponse: [!] {
  "errors" : [ {
    "id" : "24207304-974a-43c6-8aab-757bccaf70a9",
    "status" : "400",
    "code" : "PARAMETER_ERROR.INVALID",
    "title" : "A parameter has an invalid value",
    "detail" : "A parameter 'filter[platform]' has an invalid value : 'Empty filter values are not supported.'",
    "source" : {
      "parameter" : "filter[platform]"
    }
  } ]
}
```

**Comment by vveltri-parser** [comment]
Same here.

**Comment by jwaldrip** [comment]
This is not working for me.

**Comment by d3r3nic** [comment]
the issue arose after I accepted the new privacy policies.

I had fastlane in ios Gemfile like this:
gem "fastlane", :git => "https://github.com/freddi-kit/fastlane.git", :branch => "altool-upload"

so i temporarily replaced it with 
gem "fastlane", "2.213.0"

like so
# gem "fastlane", :git => "https://github.com/freddi-kit/fastlane.git", :branch => "altool-upload"
gem "fastlane", "2.213.0"

and this successfully worked

**Comment by isaac-weisberg** [comment]
same

**Comment by mickaeldanslenowhere** [comment]
Get this one too : A parameter has an invalid value - 'prices' is not a valid relationship name
Upgrading didn't fix the issue...

**Comment by marcelojunior7** [comment]
Same here

**Comment by olympus-rajivmanivannan** [comment]
Upgraded to 2.219.0 didn't fix the issue

**Comment by isaac-weisberg** [comment]
2.219.0 did work for me.

**Comment by Foggzie** [comment]
2.219.0 worked for us as well

**Comment by TiBz0u** [comment]
Fixed from 2.214.0
Tested on 2.214.0 & 2.217.0 at my side.
Thanks everyone :)

**Comment by misyobun** [comment]
We also updated it to 2.219.0 and it worked.

**Comment by crsantos** [comment]
`2.119.0` didn't fix this and there's nothing related to this on release notes.

What I can see on the output is:

```shell
App has no prices yet... Enabling all countries in App Store Connect
```

and then:

```shell
The provided entity includes an unknown attribute - 'availableInNewTerritories' is not an attribute on the resource 'apps' - /data/attributes/availableInNewTerritories
The provided entity includes an unknown relationship - 'prices' is not a relationship on the resource 'apps' - /data/relationships/prices
The provided entity includes an unknown relationship - 'availableTerritories' is not a relationship on the resource 'apps' - /data/relationships/availableTerritories
```

I could trace this to this specific log here: https://github.com/fastlane/fastlane/blob/39ed6fed0c3cb8439238c4aec62384c59966931f/deliver/lib/deliver/upload_price_tier.rb#L28


And the error triggered starts here: https://github.com/fastlane/fastlane/blob/39ed6fed0c3cb8439238c4aec62384c59966931f/deliver/lib/deliver/upload_price_tier.rb#L38


Here's a full stacktrace:

```shell
failed to load command: fastlane (user-ruby-path/ruby/3.0.1/bin/fastlane)
user-ruby-path/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/connect_api/api_client.rb:223:in `handle_response': \e[31m[!] The provided entity includes an unknown attribute - 'availableInNewTerritories' is not an attribute on the resource 'apps' - /data/attributes/availableInNewTerritories (Spaceship::UnexpectedResponse)
The provided entity includes an unknown relationship - 'prices' is not a relationship on the resource 'apps' - /data/relationships/prices
The provided entity includes an unknown relationship - 'availableTerritories' is not a relationship on the resource 'apps' - /data/relationships/availableTerritories\e[0m
	from user-ruby-path/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/connect_api/api_client.rb:136:in `patch'
	from user-ruby-path/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:209:in `patch_app'
	from user-ruby-path/ruby/3.0.1/lib/ruby/3.0.0/forwardable.rb:238:in `patch_app'
	from user-ruby-path/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/connect_api/models/app.rb:109:in `update'
	from user-ruby-path/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/deliver/lib/deliver/upload_price_tier.rb:38:in `upload'
	from user-ruby-path/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/deliver/lib/deliver/runner.rb:161:in `upload_metadata'
	from user-ruby-path/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/deliver/lib/deliver/runner.rb:61:in `run'
	from user-ruby-path/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `run'
```

**Comment by bvanderplanck** [comment]
It looks like those fields were already deprecated and they now basically fail.. 
(cf: https://developer.apple.com/documentation/appstoreconnectapi/app/relationships/availableterritories)

<img width="615" alt="Screenshot 2024-01-23 at 10 39 45" src="https://github.com/fastlane/fastlane/assets/17257969/3e4f1ecb-4625-464a-bc60-0fa464aa2301">

**Comment by bvanderplanck** [comment]
So I have run some tests.. I have been able to get my app on the Apple Store using fastlane and modifying the source code as follow:

```
ls ./spaceship/lib/spaceship/connect_api/models/app.rb | head -1 | xargs sed -i -e '109s/app_price_tier_id\: app_price_tier_id/app_price_tier_id\: nil/'
ls ./spaceship/lib/spaceship/connect_api/models/app.rb | head -1 | xargs sed -i -e '109s/territory_ids\: territory_ids/territory_ids\: nil/'
ls ./deliver/lib/deliver/upload_price_tier.rb | head -1 | xargs sed -i -e '30d'
ls ./spaceship/lib/spaceship/connect_api/models/app.rb | head -1 | xargs sed -i -e '50d'
ls ./spaceship/lib/spaceship/connect_api/models/app.rb | head -1 | xargs sed -i -e '57d'
ls ./spaceship/connect_api/models/app.rb | head -1 | xargs sed -i -e '58d'
```

**Comment by qyzdo** [comment]
Looks like release 2.212.2 fixes this problem https://github.com/fastlane/fastlane/releases/tag/2.212.2. https://github.com/fastlane/fastlane/pull/21187
Time to update (for me too 😄)

**Comment by crsantos** [comment]
Small correction to what @qyzdo mentioned:

`2.212.0` doesn't solve the issue **if you have** `price_tier` on your `Deliverfile`.

as @gabma referred here https://github.com/fastlane/fastlane/issues/21820#issuecomment-1906892034, you can simply remove the `price_tier 0` and you're good to go.

**Comment by sunjinshuai** [comment]
Same here.

**Comment by foux** [comment]
Same here. Allready on 2.219.0

**Comment by jesusamaro25** [comment]
Same here, any solution? already on 2.219.0 version

**Comment by foux** [comment]
Absolutely none except removing the price

**Comment by boldijar** [comment]
> Absolutely none except removing the price

What do you mean by removing the price? I have this issue and the app doesn’t have a price, is free. Thank you.

**Comment by owjsub** [comment]
It is possible to submit an app for review as long as you do not specify a `price_tier` attribute on deliver. When `price_tier` is specified, fastlane calls `app.update(attributes: attributes, app_price_tier_id: price_tier, territory_ids: territory_ids)` which returns an error `The provided entity includes an unknown relationship - 'availableTerritories' is not a relationship on the resource 'apps' - /data/relationships/availableTerritories`.

While this workaround will help prevent errors with submitting an app, it's still not possible to manage the available territories through fastlane. As @bvanderplanck mentioned, the ASC API to manage territories were deprecated.

In App Store Connect, when modifying territories interactively, if you inspect the request, you will see a `POST https://appstoreconnect.apple.com/iris/v1/bulkUpdateAppAvailabilities`. In the App Store Connect docs, there appears to be a new way to manage territories, but it appears it's only for preorders? https://developer.apple.com/documentation/appstoreconnectapi/modify_the_territory_availabilty_for_an_app_pre-order

Should we open a new issue to fix the error that occurs when attempting to modify available territories in fastlane?

**Comment by lacostej** [comment]
> So I have run some tests.. I have been able to get my app on the Apple Store using fastlane and modifying the source code as follow:
> 
> ```
> ls ./spaceship/lib/spaceship/connect_api/models/app.rb | head -1 | xargs sed -i -e '109s/app_price_tier_id\: app_price_tier_id/app_price_tier_id\: nil/'
> ls ./spaceship/lib/spaceship/connect_api/models/app.rb | head -1 | xargs sed -i -e '109s/territory_ids\: territory_ids/territory_ids\: nil/'
> ls ./deliver/lib/deliver/upload_price_tier.rb | head -1 | xargs sed -i -e '30d'
> ls ./spaceship/lib/spaceship/connect_api/models/app.rb | head -1 | xargs sed -i -e '50d'
> ls ./spaceship/lib/spaceship/connect_api/models/app.rb | head -1 | xargs sed -i -e '57d'
> ls ./spaceship/connect_api/models/app.rb | head -1 | xargs sed -i -e '58d'
> ```

@bvanderplanck were these changes applied on top of 2.219.0 ? Do you want to send a PR?

**Comment by Stephens64a** [comment]
I'm grateful for your help in finding the solution. Thank you for sharing!

**Comment by trevoriancox** [comment]
This was working fine for me earlier this week. Now the errors cited in this issue are back. Tested with fastlane 2.220 and 2.217.0.

```
The provided entity includes an unknown attribute - 'availableInNewTerritories' is not an attribute on the resource 'apps' - /data/attributes/availableInNewTerritories
The provided entity includes an unknown relationship - 'prices' is not a relationship on the resource 'apps' - /data/relationships/prices
The provided entity includes an unknown relationship - 'availableTerritories' is not a relationship on the resource 'apps' - /data/relationships/availableTerritories
```

**Comment by saifudheenvk** [comment]
Facing the issue again in 2.220

**Comment by azubala** [comment]
In our case we faced error:

```
The provided entity includes an unknown attribute - 'availableInNewTerritories'
```

Removing `price_tier: 0` from `Deliverfile` (as suggested [here](https://github.com/fastlane/fastlane/issues/21820#issuecomment-1906892034)) helped -- it basically relies on the tier you have currently selected in AppStore Connect for your app.

**Comment by gemix95** [comment]
same here

**Comment by pedro380085** [comment]
this issue continues

**Comment by muhammad67uzair** [comment]
I'm trying to update the app availability, through fastlane, but i get

> It is possible to submit an app for review as long as you do not specify a `price_tier` attribute on deliver. When `price_tier` is specified, fastlane calls `app.update(attributes: attributes, app_price_tier_id: price_tier, territory_ids: territory_ids)` which returns an error `The provided entity includes an unknown relationship - 'availableTerritories' is not a relationship on the resource 'apps' - /data/relationships/availableTerritories`.
> 
> While this workaround will help prevent errors with submitting an app, it's still not possible to manage the available territories through fastlane. As @bvanderplanck mentioned, the ASC API to manage territories were deprecated.
> 
> In App Store Connect, when modifying territories interactively, if you inspect the request, you will see a `POST https://appstoreconnect.apple.com/iris/v1/bulkUpdateAppAvailabilities`. In the App Store Connect docs, there appears to be a new way to manage territories, but it appears it's only for preorders? https://developer.apple.com/documentation/appstoreconnectapi/modify_the_territory_availabilty_for_an_app_pre-order
> 
> Should we open a new issue to fix the error that occurs when attempting to modify available territories in fastlane?

is this still not fixed? is there still no way to update the app price tier and/or availability through fastlane?

**Comment by neufeng** [comment]
Same here. 2.212.2 work for me

**Comment by Blackjacx** [comment]
This is stiull a problem for us using `fastlane 2.225.0`

**Comment by florian-agsteiner-caperwhite** [comment]
Getting this in 2.228.

[14:33:17]: App has no prices yet... Enabling all countries in App Store Connect
...
```
[14:33:18]: The provided entity includes an unknown attribute - 'availableInNewTerritories' is not an attribute on the resource 'apps' - /data/attributes/availableInNewTerritories
The provided entity includes an unknown relationship - 'prices' is not a relationship on the resource 'apps' - /data/relationships/prices
The provided entity includes an unknown relationship - 'availableTerritories' is not a relationship on the resource 'apps' - /data/relationships/availableTerritories
The included resource object is not linked - The included resource is not reachable from any relationship linkage. - /included/0

```
