### ISSUE TITLE
Xcode 16 beta 3 tests fail as xcresulttool get object is deprecated

### ISSUE THREAD

**Issue by mikehouse** [fastlane/fastlane#22132]
### New Issue Checklist

- [ yes] Updated fastlane to the latest version
- [ yes] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ yes] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ yes] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

This doesn't work anymore
```bash
/Applications/Xcode-beta-16-v3.app/Contents/Developer/usr/bin/xcresulttool get --format json --path /fastlane/test_output/Test-MyAppTests-2024.07.09_14-57-50-339029-+0700.xcresult        
Error: This command is deprecated and will be removed in a future release, --legacy flag is required to use it.
Usage: xcresulttool get object [--legacy] --path <path> [--id <id>] [--version <version>] [--format <format>]
  See 'xcresulttool get object --help' for more information.
```

Seems quick fix maybe done by adding _--legacy_ flag.

Thank you.

##### Command executed
```ruby
run_tests(...)
```

##### Complete output when running fastlane, including the stack trace and command used

```bash
[15:28:35]: ▸ Test execute Succeeded
Error: This command is deprecated and will be removed in a future release, --legacy flag is required to use it.
Usage: xcresulttool get object [--legacy] --path <path> [--id <id>] [--version <version>] [--format <format>]
  See 'xcresulttool get object --help' for more information.

Failed to execute - xcrun xcresulttool get --format json --path fastlane/test_output/Test-MyAppTests-2024.07.09_15-27-46-331299-+0700.xcresult

vendor/bundle/ruby/3.1.0/gems/fastlane-2.221.1/trainer/lib/trainer/test_parser.rb:196:in `execute_cmd': \e[31m[!] Failed to execute - xcrun xcresulttool get --format json --path fastlane/test_output/Test-MyAppTests-2024.07.09_15-27-46-331299-+0700.xcresult\e[0m (RuntimeError)
    from vendor/bundle/ruby/3.1.0/gems/fastlane-2.221.1/trainer/lib/trainer/test_parser.rb:205:in `parse_xcresult'
    from vendor/bundle/ruby/3.1.0/gems/fastlane-2.221.1/trainer/lib/trainer/test_parser.rb:105:in `initialize'
    from vendor/bundle/ruby/3.1.0/gems/fastlane-2.221.1/trainer/lib/trainer/test_parser.rb:82:in `new'
```

### Environment

Xcode 16 beta 3
MacOS 14.5 (23F79)
Fastlane 2.221.1
ruby 3.1.0

**Comment by giginet** [comment]
Hi there. This issue was resolved by @dokimyj. 🥳 

I'm preparing to release the new version. Please moment.

**Comment by lukeredpath** [comment]
Running into this issue too - I'm happy to test out the new release and report back as I'm working on a branch to get our app ready for Xcode 16.

**Comment by salvatoreboemia** [comment]
In which version is available this fix for Xcode 16 beta 3?

I tried just some minutes ago and the issue is still there

PS: before all do I launch fastlane update and no update is available on the latest runner used

**Comment by dokimyj** [comment]
@salvatoreboemia This feature is not yet released...
If you want to give it a try, you should use `master` version of *fastlane*, which is built with source.
You can install `master` with the Gemfile like below:

```
source 'https://rubygems.org'
# or any other sources if you have gems from private repos

gem 'fastlane', git: 'https://github.com/fastlane/fastlane'
```

**Comment by lukeredpath** [comment]
I can confirm the `main` branch worked for me.

**Comment by Skatox** [comment]
I'm having the same issue with Xcode 16 Release Candidate

**Comment by giginet** [comment]
This issue was already resolved on 2.222.0 https://github.com/fastlane/fastlane/releases/tag/2.222.0

Could you check the version?

**Comment by v86** [comment]
I'm having the same issue with Xcode 16 and fastlane 2.222.0

**Comment by dokimyj** [comment]
@v86 Could you please show us what exactly happens with Xcode 16? I have never seen any errors related to this issue yet after FL 2.222.

**Comment by burhanflobiz** [comment]
I'm having the same issue with Xcode 16 and fastlane 2.222.0
while running  `run_tests` command

**Comment by v86** [comment]
Thanks for reaching out, @dokimyj. Turned out that my xcresult was outdated as well. Mea culpa.

**Comment by dokimyj** [comment]
@burhanflobiz As I said in another comment, I've never faced the same issue since the release of 2.222. Could you drop me the log of fails and your Gemfile.lock used in the `run_tests` job?

**Comment by Skatox** [comment]
Hello, I confirm that it now works under `2.222.0`, but I needed to update Ruby version and bundler to 2.5.20

**Comment by Skatox** [comment]
I confirmed that it was fixed in `2.222.0.` I needed to increase my pipeline hardware to make the tests under the limit. It seems like iOS18 takes more time.
