### ISSUE TITLE
fastlane cannot update project version

### ISSUE THREAD

**Issue by Pr0Ger** [fastlane/fastlane#329]
I tried both `set_build_number_repository` and `increment_version_number` and receive this error:

```
[22:01:18]: [SHELL]: Updating CFBundleVersion in Info.plist(s)...
[22:01:18]: [SHELL]:
[22:01:18]: [SHELL]: $(SRCROOT)/ProjectName/Supporting Files/Info.plist
[22:01:18]: [SHELL]: Cannot find "$(SRCROOT)/ProjectName/Supporting Files/Info.plist"
[22:01:18]: [SHELL]: Updated CFBundleVersion in "ProjectName.xcodeproj/../ProjectName Tests/Info.plist" to 55e9c3d
```

Of course I have plist file on the specified path (./ProjectName/Supporting Files/Info.plist). 

Do you have any idea what causing this issue? I can provide additional info if needed, or try to reproduce this issue on demo project

**Comment by u16suzu** [comment]
Error message said.

```
[22:01:18]: [SHELL]: Cannot find "$(SRCROOT)/ProjectName/Supporting Files/Info.plist"
```

So do you specify the correct path?

**Comment by Pr0Ger** [comment]
As I know $(SRCROOT) points to directory with xcode project, so this path is correct. Also, xcode can find this plist file and successfully build this project

**Comment by u16suzu** [comment]
Could you try to use the real path? 
I mean do not use $(SRCROOT).
I think that ruby try to use the value $(SRCROOT) as string.

**Comment by Pr0Ger** [comment]
Hm, yes, it's works. But I really don't remember when I specify path using this environment variable, probably xcode change path to this after I move Info.plist into to supporting files directory

**Comment by KrauseFx** [comment]
Is this issue still open?

**Comment by Pr0Ger** [comment]
It's up to you. For myself I solved this issue by manually fixing path to plist inside project file.

**Comment by KrauseFx** [comment]
:+1:

**Comment by mtford90** [comment]
Just facing this issue myself - should this really be closed? My team commit the project file and if I hardcode the plist path within project settings this is going to break the project for other members of my team. Why can't fastlane expand environment variables such as $(SRCROOT)?

**Comment by Pr0Ger** [comment]
@mtford90 I still using a relative path to this file, but without using $(SRCROOT) variable. In this case, Xcode and other tools will resolve full path to file from project root directory. This is how my project file looks like (I strip some lines because this parameter is duplicated for all configurations): 
```
cat ProjectName.xcodeproj/project.pbxproj | grep -C 3 INFOPLIST_FILE
					"$(inherited)",
					"RELEASE_ADHOC=1",
				);
				INFOPLIST_FILE = "ProjectName/Supporting Files/Info.plist";
				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
				PRODUCT_NAME = "$(TARGET_NAME)";
				PROVISIONING_PROFILE = "$(PROFILE_UDID)";
```

**Comment by iOSAppMaker** [comment]
Facing the same problem.

**Comment by iOSAppMaker** [comment]
Also, is it possible to update separately for each target separately??

**Comment by KrauseFx** [comment]
@iOSAppMaker the recommended way is to use [match](https://github.com/fastlane/match) which can set the provisioning profile for each target using environment variables.

**Comment by iOSAppMaker** [comment]
Sure. But is there a way to update the version and build number separately for each target??

**Comment by fvisticot** [comment]
Same issue:

Setting version of project test to:
[23:19:24]: ▸ 5.
[23:19:24]: ▸ Also setting CFBundleVersion key (assuming it exists)
[23:19:24]: ▸ Updating CFBundleVersion in Info.plist(s)...
[23:19:24]: ▸ $(SRCROOT)/test/test-Info.plist
[23:19:24]: ▸ Cannot find "$(SRCROOT)/

**Comment by KrauseFx** [comment]
I just pushed a fix for this yesterday, could you try updating? https://github.com/fastlane/fastlane/releases/tag/1.59.0 Let me know if that works for you :+1:

**Comment by fvisticot** [comment]
I'have tried with fastlane 1.59.0
And it seems not fixed :(

The release note message: Fixed $(SRCROOT) in file path for commit_version_bump action

I'm using the increment_build_number and NOT the commit_version_bump action

Tx for your help

The traces:

[16:34:34]: ------------------------------------
[16:34:34]: --- Step: increment_build_number ---
[16:34:34]: ------------------------------------
[16:34:34]: $ cd /Users/fred/Documents/1.GIT-REPO/tibe-ios && agvtool next-version -all
[16:34:35]: ▸ Setting version of project tibe to:
[16:34:35]: ▸ 11.
[16:34:35]: ▸ Also setting CFBundleVersion key (assuming it exists)
[16:34:35]: ▸ Updating CFBundleVersion in Info.plist(s)...
[16:34:35]: ▸ $(SRCROOT)/test/test-Info.plist
[16:34:35]: ▸ Cannot find "$(SRCROOT)/test/test-Info.plist"

**Comment by s0mmer** [comment]
I suddenly started experiencing this issue today as well:
```
[13:09:31]: ▸ Setting version of project Fastlane TestApp to:
[13:09:31]: ▸ 16.02.16.13.09.
[13:09:31]: ▸ Also setting CFBundleVersion key (assuming it exists)
[13:09:31]: ▸ Updating CFBundleVersion in Info.plist(s)...
[13:09:31]: ▸ Cannot find "Fastlane TestApp.xcodeproj/../				<key>INFOPLIST_FILE</key>"
```

**Comment by almsta** [comment]
Experiencing the same issue. Settings absolute paths is not an option :(

**Comment by dugalp** [comment]
increment_build_number also returns the same error for me.  Wondering if $(SRCROOT) can simply be interchanged with ${SRCROOT}

**Comment by MaksimBazarov** [comment]
Stil have this issue on 1.64.0
``` 
Also setting CFBundleVersion key (assuming it exists)
Updating CFBundleVersion in Info.plist(s)...
$(SRCROOT)/Info.plist
```
Is there way to set .plist path manually?

**Comment by vaibhavi-joshi** [comment]
Still facing same issue with latest version, can't give manual path in plist??? is there any other workaround??

**Comment by almsta** [comment]
My current workaround is using the `set_info_plist_value` action with the proper keys and path to he plist.

**Comment by zigdanis** [comment]
I've removed $(SRCROOT) path from my INFOPLIST_FILE variable in Xcode.
And now `increment_build_number` works fine!

**Comment by TKBurner** [comment]
@almsta and @zigdanis Thanks for posting workarounds!

@vaibhavi-joshi Wanted to see if you are still running into this issue. Thanks!

**Comment by marcwebbie** [comment]
Worked the same for me as @zigdanis Just updated `.xcodeproj/project.pbxproj` removing the `$(SRCROOT)`

**Comment by vaibhavi-joshi** [comment]
@TKBurner resolved issue using workaround given by almsta !
Thank you so much for the support!

**Comment by TKBurner** [comment]
Awesome @vaibhavi-joshi! Glad to hear you are up and running. Going to close this issue out 👍

**Comment by cytryn** [comment]
Any updates on this?

I am having the same errors, but I don't feel like using these workarounds...
Anyway, removing $(SRCROOT) from Info.plist File didnt solve =/

**Comment by TKBurner** [comment]
@cytryn Are you running the command from your Fastlane folder or your project Folder? Thanks!

**Comment by cytryn** [comment]
@TKBurner I usually run from my project folder

**Comment by TKBurner** [comment]
Can you try running in the Fastlane folder? Thanks!

**Comment by christianlanz** [comment]
+1

**Comment by sasvarizoli** [comment]
For clarification, you can still use a relative path if you just remove the $(SRCROOT) part.

Make this
```
INFOPLIST_FILE = "$(SRCROOT)/Project/info.plist";
```
into this
```
INFOPLIST_FILE = "Project/info.plist";
```

**Comment by kostiakoval** [comment]
looks like it's an isse in `agvtool` itself. If you try to run ` agvtool next-version -all` you will see the same error.

**Comment by electic** [comment]
If you are having issues with this. It is because your project file has the wrong settings. Basically argvtool does not understand the variable $(SRCROOT).

1. Open your xcworkspace file.
2. Go to Build Settings.
3. Search for Info.plist File.
4. Remove the variable. So if you had $(SRCROOT)/Program/... it would be become Program/...
