### ISSUE TITLE
Scan not working with Xcode 7.3

### ISSUE THREAD

**Issue by raphaelcruzeiro** [fastlane/fastlane#3886]
When running _scan_ after installing Xcode 7.3, the test results always show 0 if the tests run successfully:
`scan --workspace "Project.xcworkspace" --scheme "project" --device "iPhone 6s" --clean --verbose`

```
+--------------------+-------+
|        Test Results        |
+--------------------+-------+
| Number of tests    | 0     |
| Number of failures | 0     |
+--------------------+-------+
```

If I purposely break a test, the scan command will fail with code 65:

```
** TEST FAILED **
ERROR [2016-03-22 20:16:31.24]: Exit status: 65
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'd42bc744e9cdd2c0ece054f74b3ec3e1'
The crash report has been stored locally '/tmp/sentry_d42bc744e9cdd2c0ece054f74b3ec3e1.json'
/Library/Ruby/Gems/2.0.0/gems/scan-0.5.2/lib/scan/error_handler.rb:32:in `handle_build_error': [!] Error building/testing the application - see the log above (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.5.2/lib/scan/runner.rb:31:in `block in test_app'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.39.0/lib/fastlane_core/command_executor.rb:85:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.39.0/lib/fastlane_core/command_executor.rb:85:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.5.2/lib/scan/runner.rb:23:in `test_app'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.5.2/lib/scan/runner.rb:9:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.5.2/lib/scan/manager.rb:10:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.5.2/lib/scan/commands_generator.rb:41:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.39.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.5.2/lib/scan/commands_generator.rb:60:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.5.2/lib/scan/commands_generator.rb:14:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.5.2/bin/scan:6:in `<top (required)>'
	from /usr/local/bin/scan:23:in `load'
	from /usr/local/bin/scan:23:in `<main>'
```

fastlane 1.67.0
scan 0.5.2

Could it be that something broke with the new XCode or is this issue on my side?

Thanks,

**Comment by TKBurner** [comment]
Hi @raphaelcruzeiro! If you create a blank xCode project do the 2 default tests run for that? I'm trying to figure out if this is project specific, system specific, or a widespread issue.

Thanks!

**Comment by raphaelcruzeiro** [comment]
@TKBurner I created an empty project with just a few tests and Scan ran fine. So this is a project specific issue. Something broke during the update.

The issue happens on this project no matter the development machine (happens on our CI server as well). Any ideas on how I could best approach this issue, where to start looking etc?

thanks

**Comment by TKBurner** [comment]
Thanks for following up. Are you able to run your tests manually rather than through Fastlane? It's now important to see if this is an issue with your testing setup or an issue with Fastlane. The way we run our commands suggests this is an issue with the testing configuration on your app. Can you send me the full output of scan?

Thanks! :grinning:

**Comment by raphaelcruzeiro** [comment]
Yes, I can run them manually just fine. Scan also runs the tests but it seems to crash while trying to make sense of the output. Scan reports 0 tests executed for a successful test run and fails with code 65 if any of the tests break.

**Comment by TKBurner** [comment]
Thanks @raphaelcruzeiro. Can you send me the full output of scan?

**Comment by raphaelcruzeiro** [comment]
There you go @TKBurner [ScanOutput.txt](https://github.com/fastlane/fastlane/files/186524/ScanOutput.txt)

**Comment by TKBurner** [comment]
Hi @raphaelcruzeiro, is the report at /Users/raphaelcruzeiro/Projects/h19-iphone-v2/fastlane/test_output/report.html also blank?

Thanks!

**Comment by raphaelcruzeiro** [comment]
@TKBurner it reports 0 tests.

**Comment by TKBurner** [comment]
@raphaelcruzeiro Thanks! Going to look into this over here. I'll be back with you soon :+1:

**Comment by raven** [comment]
Just for some more info, this isn't isolated to 'scan'. Mention of changes to XCTest in Xcode 7.3 have affected xcpretty / console output. 
https://github.com/Quick/Quick/issues/494#issuecomment-200286238

**Comment by nrako** [comment]
The issue is way up in the chain https://github.com/facebook/xctool/issues/674#issuecomment-200655653

**Comment by TKBurner** [comment]
@nrako Thanks for following up! We are looking into this over here :+1:

**Comment by K76154** [comment]
This is not project specific, because I also have the same problem. I believe this is a widespread issue.

**Comment by erdemPinch** [comment]
Hy,

Same here, I also have the problem.

Thanks for looking into it :)

**Comment by i2amsam** [comment]
Looks like xctool make a fix upstream per @nrako's comment above, has anyone tried that fix?  Looks like it has not been shipped with a new release yet.

**Comment by esetnik** [comment]
I can confirm i'm experiencing the same behavior. Thanks!

**Comment by peterturza** [comment]
Same issue here. Passing tests reports 
```
+--------------------+-------+
|        Test Results        |
+--------------------+-------+
| Number of tests    | 0     |
| Number of failures | 0     |
+--------------------+-------+
```
Also the report is empty
And failing tests 
```
Failing tests:
-[ArrayExtensionTests _unique__picks_only_unique_members()]
** TEST FAILED **
[14:19:43]: Exit status: 65
[14:19:43]: Variable Dump:
[14:19:43]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"test"}
[14:19:43]: Error building/testing the application - see the log above
```

**Comment by TKBurner** [comment]
@esetnik @peterturza Thanks for reaching out about this. Have you tried pulling in the xctool update mentioned in @nrako's comment? It hasn't been pulled into their master branch yet.

**Comment by tomburns** [comment]
scan doesn't use xctool, right? i don't understand the connection there.

**Comment by raphaelcruzeiro** [comment]
@tomburns: As far as I understood, xctool's problem has the same root as the problem we are facing and that's the only connection.

About our problem, I believe that the root cause is Nimble as vanila tests work seamlessly with scan (someone correct me if I'm wrong).

**Comment by leonardowistuba** [comment]
@raphaelcruzeiro I'm facing the same problem with vanilla tests. XCode 7.3 and scan 0.5.2

**Comment by i2amsam** [comment]
Sorry for adding confusion, yes, I think the root cause is the same but we have not been able to reproduce in our testing.

**Comment by tomburns** [comment]
Yes, none of our tests are being reported to stdout (which i assume is the mechanism scan uses to detect them), so we end up reporting 0/0 "successes" even though the tests run.

**Comment by TKBurner** [comment]
If anyone has full repro steps it'd help a lot on our side. Let me know. Thanks!

**Comment by hartbit** [comment]
Something similar is happening to us, but I don't know if it's related: our tests (`scan`) fail with `Exit status: 65` about one times out of two.

**Comment by TKBurner** [comment]
@hartbit Thanks for reaching out. Can you send over the full output? Also, do the tests pass but then show 0 tests 0 failures as above?

Thanks!

**Comment by hartbit** [comment]
@TKBurner No, they do not show 0 tests 0 failures, that's why I think it may not be related: but it fails without any reason:

https://gist.github.com/hartbit/40b8fc327c12a657510a015ac2876f98

**Comment by hartbit** [comment]
@TKBurner I re-read the output and saw that it's running tests twice O_O. Here's my Fastfile if it can help:

```
update_fastlane
fastlane_version '1.68.0'
default_platform :ios

platform :ios do
  before_all do |lane|
    setup_jenkins # works for all CI

    if is_ci? then
      check_env_keys(['SLACK_URL'])
    end

    lane_context['VERSION_NUMBER'] = `/usr/libexec/plistbuddy -c Print:CFBundleShortVersionString '../Geranium/Geranium-Info.plist'`.strip
    repo = `git config --get remote.origin.url`
    lane_context['REPO_NAME'] = /(?:\/|:)([^:\/]*)(?:.git)$/.match(repo)[1]
    lane_context['REPO_URL'] = "https://" + /@(.*)(?:.git)$/.match(repo)[1]
  end

  desc 'Run unit-tests'
  lane :test do
    match(
      type: "development",
      readonly: true
    )
    
    scan(
      scheme: "Geranium QUAL",
      configuration: 'Debug',
      destination: 'platform=iOS Simulator,name=iPad Air,OS=latest',
      clean: true,
      skip_build: true,
      slack_only_on_failure: true
    )
  end
  
  def check_env_keys(keys)
    keys.each { |key| raise "Environment variable '#{key}' missing" unless ENV[key] }
  end

  error do |lane, exception|
    slack(
      message: "#{exception.message} #{lane_context['REPO_URL']}/builds/#{ENV['CI_BUILD_ID']}",
      success: false
    ) if is_ci? && ENV['SLACK_URL']
  end
end
```

And I don't know what I did but it now prints this before failing:

```
[17:27:14]: ▸ Testing failed:
[17:27:14]: ▸ Command builtin-rm failed with exit code 513
[17:27:14]: ▸ ** TEST FAILED **
```

**Comment by TKBurner** [comment]
Hi @hartbit! Thanks for reaching out. Can you let me know if you are getting exit code 513 or exit code 65? Your original report mentioned 65.

Thansk!

**Comment by hartbit** [comment]
@TKBurner It's very weird, I am getting different errors, but more often code 65. For info, this only happens on the CI server. On the local machine, it works fine.

**Comment by hartbit** [comment]
Here's another output with Error 65 this time:

https://gist.github.com/hartbit/943d5a4e565e881e6561d0f85b416c75

**Comment by khantthulinn** [comment]
I got the same error if I use jenkin. If I run manually from terminal, it is okay. 
    from /Library/Ruby/Gems/2.0.0/gems/scan-0.5.2/lib/scan/runner.rb:31:in `block in test_app'

I got  Exit status: 70. 

https://gist.github.com/khantthulinn/dcabeb68ee50abf20637b683a8a8306f

**Comment by TKBurner** [comment]
@khantthulinn and @hartbit Thanks for following up. We are still looking into this. The info you sent over is really helpful 👍

**Comment by leonardowf** [comment]
We were having this problem in one machine and everything was ok in another one.
With Xcode 7.2.1 scan was perfect in both machines.

After trying so many times with different ruby versions, fastlane and scan updated we decided to run scan's xcodebuild to see what was going on.

Our error 65 problem was related to the iOS Simulator in version 8.4.
Running xcodebuild with a 9.3 simulator solved the problem.

Running scan with --device using "iPhone 6 9.3" solved the problem too.

Maybe this can help someone.

**Comment by TKBurner** [comment]
@leonardowf Thanks for sharing! @khantthulinn and @hartbit can you try this workaround? We are still investigating on our end and will follow up. Thanks! 👍

**Comment by hartbit** [comment]
@TKBurner I was using a clean install of the CI server, so it only have 9.3 simulators and I am using:

```
SCAN_DESTINATION=platform=iOS Simulator,name=iPad Air,OS=latest
```

Changing it to:

```
SCAN_DESTINATION=platform=iOS Simulator,name=iPad Air,OS=9.3
```

Did not change anything.

**Comment by khantthulinn** [comment]
@TKBurner I still got same error after I change like this (Exit status: 70)

`    scan(
      configuration: "Debug",
      scheme: "DevelopmentTest",
      device: "iPhone 6 9.3",)`

https://gist.github.com/khantthulinn/e2bd441d234053d876bc54f1a5c49ca0

**Comment by TKBurner** [comment]
@khantthulinn and @hartbit Thanks for following up. We are going to investigate this a little more over here and circle back 👍

**Comment by khantthulinn** [comment]
For me, I think it is because of Jenkins. I need to set up Jenkins like this to run GUI application like Simulator. 
http://www.cimgf.com/2015/05/26/setting-up-jenkins-ci-on-a-mac-2/ 
After I do that, everything is okay already.

**Comment by hartbit** [comment]
@TKBurner ok, I fixed my problem by Resetting the Simulator. That's weird.

**Comment by jgafni** [comment]
@TKBurner , I have tried a bunch of suggestions. The one that resolved it was from @bencollier [here](https://github.com/fastlane/fastlane/issues/4059) that the spaces in **all** scheme names be removed, not just the active scheme.  When I changed something like `MySchemeName - MyTests` to `MySchemeName-MyTests`, I stopped receiving the failure.  This wasn't an issue when running fastlane locally, but running it remotely on CircleCI failed constantly.

**Comment by TKBurner** [comment]
@jgafni Glad to hear you got up and running. We are still looking into the root cause of this, but this seems like a viable workaround.

**Comment by m1357l** [comment]
@TKBurner any breakthrough on this issue? I'm am also seeing this issue, but don't know what I can do to work around it.

**Comment by Lcrnice** [comment]
Occasionally happen the similar issue, I only create a empty project, but **Test execution failed. Exit status: 65** appear when UI test running

**Comment by TKBurner** [comment]
@m1357l Thanks for following up. Can you let me know if you are able to get this working when you don't have multiple targets within a scheme? Thanks!

**Comment by tsmith1024** [comment]
I've been watching this issue for a while, as I've been seeing the same problem, but more focused on Snapshot use. Tests were failing with status: 65 and preventing all the screenshot magic from finishing. When I have only one test target in my scheme, everything appears to work as expected. Hope this helps figure out the real cause of things, and thanks for all the info so far!

**Comment by TKBurner** [comment]
@tsmith1024 Thanks for following up. This seems to fit into the pattern other users have reported. We are still looking into this and will update on this thread. Thanks!

**Comment by mfurtak** [comment]
Hi folks!

We still want to get to the bottom of this. Here's my system setup:

```
Mac OS X: 10.11.4
xcodebuild: Xcode 7.3, Build version 7D175
snapshot: 1.12.1
scan 0.6.0
```

So far no combination of:

* Schemes with spaces in the names
* Targets with spaces in the names
* Multiple targets per scheme
* Specifying a particular simulator

has been able to help us reproduce the problem. 😞 

What would be really _really_ helpful would be if someone was able to **share a small test project and associated command** that exhibits this problem with either `scan` or `snapshot` that we can pull down and use.

I'm going to mark this as `help wanted` to indicate that this would be a great place for people to contribute as well.

Thanks for your patience!

**Comment by hartbit** [comment]
Have you done your tests through a CI build server?

**Comment by sgsabbage** [comment]
I also have this problem, and found that running xcodebuild with the same settings, I had no 'Test case:' output for anything to pick up on.

I'm using KIF for my tests, however, and found this pull request, which may be related for some people? https://github.com/kif-framework/KIF/pull/819

**Comment by mfurtak** [comment]
Hi folks - I've released [`scan` 0.6.1](https://github.com/fastlane/fastlane/releases/tag/scan%2F0.6.1).

This ticket has wound up collecting a lot of different kinds of problem reports, but if you're having trouble with simulators that fail to boot, could you please upgrade your `scan` with:

```bash
gem update scan
```

and then try running:

```bash
FASTLANE_EXPLICIT_OPEN_SIMULATOR=1 scan
```

or

```bash
FASTLANE_EXPLICIT_OPEN_SIMULATOR=1 fastlane your_lane
```

depending on how you run `scan`, and let me know if allows your test runs to succeed? Thanks! 🚀

**Comment by hartbit** [comment]
It seems to have fixed the problem for me! :D So happy. Will keep this issue updated if the problem re-appears.

**Comment by pjechris** [comment]
Still not working for me.
Runned xcpretty manually:

```shell
xcodebuild
-workspace **.xcworkspace \
-scheme "**" \
-sdk iphonesimulator \
-destination 'platform=iOS Simulator,name=iPad Air' \
test | xcpretty -c -r html --output reports/xcpretty
```
and got an empty html report, so I guess issue is on xcpretty side?

**Comment by TKBurner** [comment]
Hi @pjechris! Thanks for following up. What error are you getting with Scan? I want to take a look 👍

**Comment by pbrobst23** [comment]
I am still seeing errors on both Travis CI and Circle CI after setting FASTLANE_EXPLICIT_OPEN_SIMULATOR=1. 
Everything is running fine on our various development machines.

Travis regularly times out looking for a UI element within a long running UI test I have, so I suspect that is the simulator dying unexpectedly.

My short running UI test scheme fails intermittently with this error 65 while trying to switch over to testing:
`▸ Generating 'UITests.xctest.dSYM'
▸ Copying InfoPlist.strings
▸ Running script 'Copy Pods Resources'
▸ Running script 'Embed Pods Frameworks'
▸ Touching UITests.xctest
** TEST FAILED **
[00:52:48]: Exit status: 65
[00:52:48]: Variable Dump:
[00:52:48]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test"}
[00:52:48]: Error building/testing the application - see the log above`

On Circle CI I see failures on both Unit/UI test targets with the same pattern of Touching UITests.xctest or Touching UnitTests.xctest followed by Exit status: 65.

As far as system setup I have:
`Mac OS X: 10.11.4
xcodebuild: Xcode 7.3, Build version 7D175
fastlane 1.89.0
scan 0.6.1`
and I am updating both CI services to the current versions of fastlane and scan on each run.

For test frameworks we're using:
`KIF: 3.4.2 for UITest targets
 Kiwi :2.4.0 for UnitTest targets`

**Comment by TKBurner** [comment]
Hi @pbrobst23! Sorry to hear that you are running into this issue. Can you file a new issue and use the issue template? I'm not sure this is related and I want to make sure we solve both of your issues. Thanks! 👍

**Comment by pbrobst23** [comment]
Sure thing, sorry for the hijack! I thought they might be similar enough.

**Comment by pjechris** [comment]
@TKBurner I have no error, just 0 test reported.
What I found fout is that xcodebuild is not printing runned tests into logs so xcpretty (and scan) report a count of 0. On some other library everything is OK.

This is `xcodebuild test` output for my project:
```shell
10:50:52.024 iBee[4208:87455] _XCT_testBundleReadyWithProtocolVersion:minimumVersion: reply received
10:50:52.030 iBee[4208:87560] _IDE_startExecutingTestPlanWithProtocolVersion:16
** TEST SUCCEEDED **
```
This is xcodebuild test` output of one library:
```shell
10:48:05.292 xctest[2964:47961] _XCT_testBundleReadyWithProtocolVersion:minimumVersion: reply received
10:48:05.300 xctest[2964:47961] _IDE_startExecutingTestPlanWithProtocolVersion:16
Test Suite 'All tests' started at 2016-05-19 10:48:05.416
Test Suite 'Quick.framework' started at 2016-05-19 10:48:05.418
Test Suite 'Quick.framework' passed at 2016-05-19 10:48:05.418.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.001) seconds
Test Suite 'GaikanTests.xctest' started at 2016-05-19 10:48:05.419
[...]
Test Suite 'UIViewSpec' passed at 2016-05-19 10:48:06.152.
	 Executed 4 tests, with 0 failures (0 unexpected) in 0.004 (0.007) seconds
Test Suite 'GaikanTests.xctest' passed at 2016-05-19 10:48:06.153.
	 Executed 26 tests, with 0 failures (0 unexpected) in 0.696 (0.734) seconds
Test Suite 'All tests' passed at 2016-05-19 10:48:06.153.
	 Executed 26 tests, with 0 failures (0 unexpected) in 0.696 (0.737) seconds
** TEST SUCCEEDED **
```

**Comment by TKBurner** [comment]
@pjechris Thanks for following up. Can you share your full output of running scan --verbose?

Thanks!

**Comment by dcvz** [comment]
My tests which were previously getting this error have now started passing on Travis 🎉 no changes on my part but looks like it's now using scan 0.6.0 instead of 0.6.1

**Comment by TKBurner** [comment]
@dcvz Awesome! Really glad to hear you got up and running. Hope you have a great weekend 👍

**Comment by ferusinfo** [comment]
Ok, I've found the solution to the problem, and for those of you that still might be in trouble, here is the solution.
I've run some tests to see what is the root cause - the problem isn't with scan at all.
The problem is tied to the `xcpretty` library, and to be more precise, to the way how XCTests have changed in xCode 7.3. With a bug that is not letting custom observers to observe for tests until they are inside the `dispatch_async` blocks, libraries like KIF were not functioning.

Bumping the version of KIF to the latest (after looking in some of the closed issues) has **finally solved the problem**.

Hope that will help someone in need.

Help sources:
https://github.com/kif-framework/KIF/pull/819
https://github.com/Quick/Nimble/pull/271
https://github.com/Quick/Nimble/pull/271/commits/6a50a930ff7d6ba783fcac823a1fc306a55d0f7e
https://books.google.pl/books?id=9lQnCgAAQBAJ&pg=PA173#v=onepage&q&f=false (nice book btw, explaining the command line tools and xcpretty pretty well)

**Comment by joeljeske** [comment]
Thank you much! Scan wasn't running my tests; after an upgrade of Nimble, everything now works correctly!

**Comment by TKBurner** [comment]
@ferusinfo Thanks so much for sharing your solution! Really happy to have you as part of our community 👍 

@joeljeske Thanks for testing and updating us. Really glad to hear you got up and running.

I'm going to close this out for the time being until we get another report 👍
