### ISSUE TITLE
Match: Regenerate Profile if Profile is Invalid or Expired

### ISSUE THREAD

**Issue by ram0287** [fastlane/fastlane#5379]
Hi,

     Cert and Profile been synced to Git Repo using Match ( Started from scratch after nuke )

     After that Generated a new Push Certificate for an existing App Id using pem ( Enable Push Services )
     Existing Provisioning Profile became invalid. 

     When i run match without force
         It is not regenerating the Profile - But it says Profile is valid

     When i run match with force
        Ideally a new Provisioning profile is created and synced to the git repo

     To me it looks like When we run match 
       We need to Check whether the Profile is Invalid or Expired
       If so - need to re generate the Profile and Update the Git repo
       
    Any thoughts on this?
 
Thanks in advance.
Ram.

**Comment by ram0287** [comment]
Any Update on this ?

**Comment by TKBurner** [comment]
Hi @ram0287 Thanks for reaching out. It looks like you might need to run `match nuke distribution` to clear this up. If that isn't a viable option can you share your full output when you run `match --force` thanks!

**Comment by ram0287** [comment]
@TKBurner Thanks for your response

I started with Match nuke 

Developer Account is Clean. No Certs / Profiles

Created a New Cert / Profile using match

Generated a new Push Certificate for the App Id using pem ( Enable Push Services )

Existing Provisioning Profile became invalid. 

If I run match with force
   A new Provisioning profile is created and synced to the git repo

If I run match without force
     It is not regenerating the Profile - But it says Profile is valid

My Suggestion is 
When we run match 
   We need to Check whether the Profile is Invalid or Expired
   If so - need to re generate the Profile and Update the Git repo accordingly.

Kindly let me know your thoughts. Please

**Comment by ram0287** [comment]
@TKBurner - Any Update on this ?

**Comment by krodak** [comment]
Exactly same issue as @ram0287 
I don't want to use `force` every time and regenerate certificates, but `match` should regenerate new certs when old are invalid.

My use case:
- have valid provisioning profiles I'm able to use `match`
- added `Associated Domains`, so my PP are invalid
- running match without `force` - I get an error, should be regenerated

**Comment by ram0287** [comment]
@TKBurner - Did you get a chance to have a look at this ?

**Comment by TKBurner** [comment]
Hi @ram0287 Thanks for following up. It seems to make sense that when the provisioning profiles become invalid we should prompt you to regenerate or not. Because match needs to be able to be run unattended we chose the behavior of non-destructive unless force is on. Let me know if that makes sense.

Thanks!

**Comment by papauschek** [comment]
@TKBurner regarding unattended:

As a default behavior, why not simply check whether the certificates are valid, and replace them if they are invalid?

It says it verifies validity:
```
Verifying that the certificate and profile are still valid on the Dev Portal...
```

But in fact the step completes successfully if the profile exists, but is marked invalid on the dev portal. By checking actual validity this could be automated. Or am I missing something?

**Comment by TKBurner** [comment]
@papauschek I just reached out to the core team about this. Thanks!

**Comment by KrauseFx** [comment]
_match_ should check if the certificates and profiles are still valid and if they are not, it should automatically repair them. If that doesn't work, that's something we need to fix. Do you have steps to reproduce this?

**Comment by ram0287** [comment]
@KrauseFx Please find below the steps to reproduce

Created a New Dist Cert / Provisioning Profile using match

Generated a new Push Certificate for the App Id using pem ( Enable Push Services )

Existing Provisioning Profile became invalid.

If I run match with force
A new Provisioning profile is created and synced to the git repo

If I run match without force
It is not regenerating the Profile - But it says Profile is valid

My Suggestion is 
When we run match 
We need to Check whether the Profile is Invalid or Expired
If so - need to re generate the Profile and Update the Git repo accordingly.

Kindly let me know your thoughts. Please

**Comment by krodak** [comment]
@KrauseFx exactly same reproduction as @ram0287 but set `Associated Domains` as enabled

**Comment by TKBurner** [comment]
@ram0287 @krodak Just looped back with the core team. We'll work with you here. Thanks so much for helping us get to the bottom of this.

**Comment by PitchLabsAsh** [comment]
I was just looking at this and was wondering about the case where pem refreshes the push cert as its about to expire.

My lane starts like this..

```
pem(app_identifier: "com.autologic.vinsupport.dev")     
match(app_identifier: "com.autologic.vinsupport.dev", type: "adhoc", force_for_new_devices: true)
```

In this case if pem refreshes the push cert and match does create a new profile due to a new device being added then push notifications wont work.

I realise pem has a callback block that can be used to indicate if the cert was refreshed, but it seems match is unaware it was done?

As a work around for the issue on this thread could we not make the script set an local var to indicate if it was refreshed and then use this to conditionally set match force the refresh?

**Comment by TKBurner** [comment]
@PitchLabsAsh Do you have a sample project this is duplicatable on? Is force: true working? Would you be interested in working on a PR?

**Comment by hdoria** [comment]
I have the same problem. Clean repository, clean account on developer portal:

```
$ match nuke development
$ match nuke distribution
$ match development
$ match adhoc
```

Everything is fine on developer portal.

```
$ pem --development
$ pem
```

Existing Provisioning Profile became invalid in the developer portal. If I use match again, it creates a new provisioning, it does not fixed the existing one. Also, if I fix the provisioning profile by going to the dev portal , match can't find the provisioning profile anymore.

**Comment by KrauseFx** [comment]
_match_ shouldn't be related to _push_ in any way, those are separate certificates. Are you sure the 2 things are related?

**Comment by pahnev** [comment]
I always thought `force_for_new_devices: true` would do this, but was surprised it didn't.

To add my 2cents. 
I had bunch of development Provisioning profiles created and valid. I enabled an app group in them on developer.apple.com, which marked them as invalid. 
![screen shot 2016-10-10 at 12 16 50](https://cloud.githubusercontent.com/assets/2078494/19231594/89e14b94-8ee3-11e6-9802-e21c67311e1a.png)

Running my match lane, just re-downloaded all these profiles and `force_for_new_devices` had no effect. The solution would be `force: true`. However that creates new profile for some reason.

```
[12:20:28]: Successfully logged in
[12:20:28]: Fetching profiles...
[12:20:29]: Provisioning Profile 'match Development com.myapp.dev' is not valid, skipping this one...
[12:20:29]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[12:20:33]: The name 'match Development com.myapp.dev' is already taken, using another one.
[12:20:33]: Creating new provisioning profile for 'com.myapp.dev' with name 'match Development com.myapp.dev 1476091233'
```

Which is obviously not we would like. So now I have to delete all those profiles first and then run my match command with `force:true` because otherwise it would fail on pushing to git.

**Comment by KrauseFx** [comment]
@pahnev thanks for the report, that makes sense, by invalidating an existing profile, you need to re-generate. _match_ doesn't seem to do a great job doing that currently, so that's something that should be fixed

**Comment by hdoria** [comment]
@KrauseFx the problems seem to be with pem. When we use the "pem" command it invalidates all provisioning profile. When we run match again, it does not fix these provisioning profile.

**Comment by KrauseFx** [comment]
@hdoria That doesn't sound right. Can you post a screenshot of your provisioning profile list before running _pem_ and then after running _pem_?

**Comment by pascalhuynh** [comment]
@KrauseFx: I noticed the same issue - "the problems seem to be with pem. When we use the "pem" command it invalidates all provisioning profile. When we run match again, it does not fix these provisioning profile."

**Comment by TKBurner** [comment]
@pascalhuynh Thanks for following up. I looped in the core team so we can take another look 👍

**Comment by lemonkey** [comment]
I'm also seeing what @pahnev is seeing (https://github.com/fastlane/fastlane/issues/5379#issuecomment-252570741), except for normal provisioning profiles (not apns related). 

Instead of regenerating invalid profiles, new duplicate profiles with a randomish number is appended to the profile name when force=true. Sometimes I'm seeing dupes being created even if the original profiles aren't invalid and it's pretty annoying.

**Comment by KrauseFx** [comment]
Thanks @pahnev, I can reproduce the issue, and will work on a fix 👍

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/fastlane/pull/6703, which implements an auto-repair system for profiles. 
I'll now look into why provisioning profiles are invalidated when creating a push certificate.

**Comment by KrauseFx** [comment]
I just checked, generating a push notification profile on the Apple Developer Portal manually also invalidated all associated provisioning profiles. I'll submit a radar for this.

**Comment by KrauseFx** [comment]
I filed a radar for Apple that push notifications invalidate certificates: https://openradar.appspot.com/radar?id=4956030156931072, feel free to dupe.

The next _match_ release should be able to automatically repair invalidated provisioning profiles 👍 

Thanks everybody for your help on this, and providing the information on how to reproduce the problem.

**Comment by lemonkey** [comment]
Thanks for the work on this.

**Comment by pascalhuynh** [comment]
Thanks for the good job !
—

	
Pascal HUYNH

Co-Founder & Software Engineer

	
+33 6 26 43 30 03

	
pascal.beyowi

	
75 quai de la Seine, 75019 Paris

	
http://www.beyowi.com <http://www.beyowi.com/>

**Comment by johnboiles** [comment]
@KrauseFx: Is there a similar fix in the works for `sigh` as well? I just ran `sigh` (from my Fastfile) on some distribution and ad-hoc profiles that had been invalidated, and duplicate profiles got created (instead of having the invalid profiles repaired).

```
> fastlane --version
fastlane 1.109.0
> sigh --version
sigh 1.11.2
```

**Comment by TKBurner** [comment]
Hi @johnboiles Thanks for following up. I'm not sure there is active work toward this. Is there a reason why you can't use match?

**Comment by johnboiles** [comment]
We use Enterprise distribution frequently. From the match README.md

> Because of the potentially dangerous nature of In-House profiles we decided to not allow the use of match with enterprise accounts.
