### ISSUE TITLE
Unable to find a destination matching the provided destination specifier

### ISSUE THREAD

**Issue by giacgbj** [fastlane/fastlane#5731]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

This issue happens since fastlane 1.000.0. 

The same error happens if I remove "destination".

##### Complete output when running fastlane, including the stack trace and command used

```
ijhack:uPen jhack$ fastlane ios jSonar
[10:48:54]: -------------------------------------------------
[10:48:54]: --- Step: Verifying required fastlane version ---
[10:48:54]: -------------------------------------------------
[10:48:54]: fastlane version valid
[10:48:54]: ------------------------------
[10:48:54]: --- Step: default_platform ---
[10:48:54]: ------------------------------
[10:48:54]: Driving the lane 'ios jSonar' 🚀
[10:48:54]: ------------------
[10:48:54]: --- Step: scan ---
[10:48:54]: ------------------
[10:48:54]: xcodebuild -list -workspace uPen.xcworkspace
[10:49:17]: It's not recommended to set the `destination` value directly
[10:49:17]: Instead use the other options available in `scan --help`
[10:49:17]: Using your value 'platform=iOS Simulator,name=iPad Air,OS=9.3' for now
[10:49:17]: because I trust you know what you're doing...
[10:49:17]: xcodebuild -list -workspace uPen.xcworkspace

+-----------------------+---------------------+
|           Summary for scan 0.11.2           |
+-----------------------+---------------------+
| workspace             | uPen.xcworkspace    |
| scheme                | uPen                |
| configuration         | Debug               |
| derived_data_path     | reports/DerivedData |
| code_coverage         | true                |
| output_directory      | reports             |
| clean                 | false               |
| address_sanitizer     | false               |
| skip_build            | false               |
| output_types          | html,junit          |
| buildlog_path         | ~/Library/Logs/scan |
| open_report           | false               |
| skip_slack            | false               |
| slack_only_on_failure | false               |
| use_clang_report_name | false               |
| fail_build            | true                |
+-----------------------+---------------------+

[10:49:22]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace uPen.xcworkspace -scheme uPen -configuration 'Debug' -destination 'platform=iOS Simulator,id=1326E607-F5A0-493C-8F94-49181D96FA89' -derivedDataPath 'reports/DerivedData' -enableCodeCoverage YES build test | tee '/Users/jhack/Library/Logs/scan/uPen-uPen.log' | xcpretty 
[10:49:22]: ▸ Loading...
[10:49:24]: ▸ xcodebuild: error: Unable to find a destination matching the provided destination specifier:
[10:49:24]: ▸ { platform:iOS Simulator, id:1326E607-F5A0-493C-8F94-49181D96FA89 }
[10:49:24]: ▸ Available destinations for the "uPen" scheme:
[10:49:24]: ▸ { platform:iOS Simulator, id:0E23F1C7-B9C2-44A0-9D2D-2D0E4D6CBE23, OS:8.1, name:iPad 2 }
[10:49:24]: ▸ { platform:iOS Simulator, id:28FD7625-E137-4345-A1CE-C40D9872BAEB, OS:8.2, name:iPad 2 }
[10:49:24]: ▸ { platform:iOS Simulator, id:9DE50730-2C57-4DCA-8C05-793218A6A3E3, OS:8.3, name:iPad 2 }
[10:49:24]: ▸ { platform:iOS Simulator, id:4A60E65D-4848-4031-9EBD-9949B026823C, OS:8.4, name:iPad 2 }
[10:49:24]: ▸ { platform:iOS Simulator, id:46E4770C-5ACA-49EB-9D96-FC5BD42D4779, OS:9.0, name:iPad 2 }
[10:49:24]: ▸ { platform:iOS Simulator, id:212A3145-FFDA-4A8E-8ECA-B669CE0E8783, OS:9.1, name:iPad 2 }
[10:49:24]: ▸ { platform:iOS Simulator, id:D6FD2D19-58F5-4325-B410-E697082D9879, OS:9.2, name:iPad 2 }
[10:49:24]: ▸ { platform:iOS Simulator, id:C34BDD49-0B94-4F46-A78A-CF52C5BF1185, OS:9.3, name:iPad 2 }
[10:49:24]: ▸ { platform:iOS Simulator, id:6A04E3B0-F37E-4348-9551-8F80A403238A, OS:8.1, name:iPad Air }
[10:49:24]: ▸ { platform:iOS Simulator, id:1DCFFA10-AE8F-4E47-B864-72DB96E21533, OS:8.2, name:iPad Air }
[10:49:24]: ▸ { platform:iOS Simulator, id:4EE5A080-B782-4477-BC3F-128738E4A8C9, OS:8.3, name:iPad Air }
[10:49:24]: ▸ { platform:iOS Simulator, id:DB490ABF-1F2E-45FB-AD7E-A8B27EE404FE, OS:8.4, name:iPad Air }
[10:49:24]: ▸ { platform:iOS Simulator, id:E8812F40-7875-4994-B9BB-D7CD18953276, OS:9.0, name:iPad Air }
[10:49:24]: ▸ { platform:iOS Simulator, id:D45C7864-1543-4259-8201-45B7AE82623C, OS:9.1, name:iPad Air }
[10:49:24]: ▸ { platform:iOS Simulator, id:24D4422A-C6FB-43CE-9110-FA2A6791C691, OS:9.2, name:iPad Air }
[10:49:24]: ▸ { platform:iOS Simulator, id:6B4107BA-2E1C-44C1-9180-52DEAA244A4C, OS:9.3, name:iPad Air }
[10:49:24]: ▸ { platform:iOS Simulator, id:104C78F6-3625-4D23-809D-A3B90F140668, OS:9.0, name:iPad Air 2 }
[10:49:24]: ▸ { platform:iOS Simulator, id:1EC88DEA-BB9F-4D4F-B900-1BFB899C2CCA, OS:9.1, name:iPad Air 2 }
[10:49:24]: ▸ { platform:iOS Simulator, id:D2FAB216-F3D5-49B8-A728-AA1E1554C97B, OS:9.2, name:iPad Air 2 }
[10:49:24]: ▸ { platform:iOS Simulator, id:5E464F0D-F70E-406C-B825-12F33F4C3433, OS:9.3, name:iPad Air 2 }
[10:49:24]: ▸ { platform:iOS Simulator, id:F83C5AA4-B875-4D14-AA3C-6FD55A7BC900, OS:9.1, name:iPad Pro }
[10:49:24]: ▸ { platform:iOS Simulator, id:2A741F57-4715-4EEB-BAE5-C9FC3F169661, OS:9.2, name:iPad Pro }
[10:49:24]: ▸ { platform:iOS Simulator, id:A5B3BC14-C3F2-41CA-BF7D-A78201A00B7F, OS:9.3, name:iPad Pro }
[10:49:24]: ▸ { platform:iOS Simulator, id:CA9540C7-2DD8-4304-BC0C-896C6A8F4024, OS:8.1, name:iPad Retina }
[10:49:24]: ▸ { platform:iOS Simulator, id:0565D034-D0C1-45E7-A640-31916BC7FF7C, OS:8.2, name:iPad Retina }
[10:49:24]: ▸ { platform:iOS Simulator, id:B43471C7-3091-4F45-80B0-8CF84CEA4793, OS:8.3, name:iPad Retina }
[10:49:24]: ▸ { platform:iOS Simulator, id:D6F7B05D-F12E-42AD-BA49-2B12C097C551, OS:8.4, name:iPad Retina }
[10:49:24]: ▸ { platform:iOS Simulator, id:CE160ACC-8DF1-46BC-8F35-DD60B70DC776, OS:9.0, name:iPad Retina }
[10:49:24]: ▸ { platform:iOS Simulator, id:2FD51DEE-6C02-4F14-87BD-2B8D669301EE, OS:9.1, name:iPad Retina }
[10:49:24]: ▸ { platform:iOS Simulator, id:0BFBED20-886A-4B91-B8FD-C44D7CD8870C, OS:9.2, name:iPad Retina }
[10:49:24]: ▸ { platform:iOS Simulator, id:7B024B6A-BDF5-493E-85A1-267EB5A2CE70, OS:9.3, name:iPad Retina }
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
{ platform:iOS Simulator, id:1326E607-F5A0-493C-8F94-49181D96FA89 }

Available destinations for the "uPen" scheme:
{ platform:iOS Simulator, id:0E23F1C7-B9C2-44A0-9D2D-2D0E4D6CBE23, OS:8.1, name:iPad 2 }
{ platform:iOS Simulator, id:28FD7625-E137-4345-A1CE-C40D9872BAEB, OS:8.2, name:iPad 2 }
{ platform:iOS Simulator, id:9DE50730-2C57-4DCA-8C05-793218A6A3E3, OS:8.3, name:iPad 2 }
{ platform:iOS Simulator, id:4A60E65D-4848-4031-9EBD-9949B026823C, OS:8.4, name:iPad 2 }
{ platform:iOS Simulator, id:46E4770C-5ACA-49EB-9D96-FC5BD42D4779, OS:9.0, name:iPad 2 }
{ platform:iOS Simulator, id:212A3145-FFDA-4A8E-8ECA-B669CE0E8783, OS:9.1, name:iPad 2 }
{ platform:iOS Simulator, id:D6FD2D19-58F5-4325-B410-E697082D9879, OS:9.2, name:iPad 2 }
{ platform:iOS Simulator, id:C34BDD49-0B94-4F46-A78A-CF52C5BF1185, OS:9.3, name:iPad 2 }
{ platform:iOS Simulator, id:6A04E3B0-F37E-4348-9551-8F80A403238A, OS:8.1, name:iPad Air }
{ platform:iOS Simulator, id:1DCFFA10-AE8F-4E47-B864-72DB96E21533, OS:8.2, name:iPad Air }
{ platform:iOS Simulator, id:4EE5A080-B782-4477-BC3F-128738E4A8C9, OS:8.3, name:iPad Air }
{ platform:iOS Simulator, id:DB490ABF-1F2E-45FB-AD7E-A8B27EE404FE, OS:8.4, name:iPad Air }
{ platform:iOS Simulator, id:E8812F40-7875-4994-B9BB-D7CD18953276, OS:9.0, name:iPad Air }
{ platform:iOS Simulator, id:D45C7864-1543-4259-8201-45B7AE82623C, OS:9.1, name:iPad Air }
{ platform:iOS Simulator, id:24D4422A-C6FB-43CE-9110-FA2A6791C691, OS:9.2, name:iPad Air }
{ platform:iOS Simulator, id:6B4107BA-2E1C-44C1-9180-52DEAA244A4C, OS:9.3, name:iPad Air }
{ platform:iOS Simulator, id:104C78F6-3625-4D23-809D-A3B90F140668, OS:9.0, name:iPad Air 2 }
{ platform:iOS Simulator, id:1EC88DEA-BB9F-4D4F-B900-1BFB899C2CCA, OS:9.1, name:iPad Air 2 }
{ platform:iOS Simulator, id:D2FAB216-F3D5-49B8-A728-AA1E1554C97B, OS:9.2, name:iPad Air 2 }
{ platform:iOS Simulator, id:5E464F0D-F70E-406C-B825-12F33F4C3433, OS:9.3, name:iPad Air 2 }
{ platform:iOS Simulator, id:F83C5AA4-B875-4D14-AA3C-6FD55A7BC900, OS:9.1, name:iPad Pro }
{ platform:iOS Simulator, id:2A741F57-4715-4EEB-BAE5-C9FC3F169661, OS:9.2, name:iPad Pro }
{ platform:iOS Simulator, id:A5B3BC14-C3F2-41CA-BF7D-A78201A00B7F, OS:9.3, name:iPad Pro }
{ platform:iOS Simulator, id:CA9540C7-2DD8-4304-BC0C-896C6A8F4024, OS:8.1, name:iPad Retina }
{ platform:iOS Simulator, id:0565D034-D0C1-45E7-A640-31916BC7FF7C, OS:8.2, name:iPad Retina }
{ platform:iOS Simulator, id:B43471C7-3091-4F45-80B0-8CF84CEA4793, OS:8.3, name:iPad Retina }
{ platform:iOS Simulator, id:D6F7B05D-F12E-42AD-BA49-2B12C097C551, OS:8.4, name:iPad Retina }
{ platform:iOS Simulator, id:CE160ACC-8DF1-46BC-8F35-DD60B70DC776, OS:9.0, name:iPad Retina }
{ platform:iOS Simulator, id:2FD51DEE-6C02-4F14-87BD-2B8D669301EE, OS:9.1, name:iPad Retina }
{ platform:iOS Simulator, id:0BFBED20-886A-4B91-B8FD-C44D7CD8870C, OS:9.2, name:iPad Retina }
{ platform:iOS Simulator, id:7B024B6A-BDF5-493E-85A1-267EB5A2CE70, OS:9.3, name:iPad Retina }
[10:49:24]: Exit status: 70
[10:49:24]: Variable Dump:
[10:49:24]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios jSonar", :SCAN_DERIVED_DATA_PATH=>"reports/DerivedData", :SCAN_GENERATED_PLIST_FILE=>nil}
[10:49:24]: Error building/testing the application - see the log above

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | scan                                | 29          |
+------+-------------------------------------+-------------+

[10:49:24]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Error building the application: xcodebuild error SDK "iphoneos9.2" cannot be located.
   https://github.com/fastlane/fastlane/issues/4162 [open] 20 💬
   3 days ago

➡️  Detect whether snapshot is running in build phase script
   https://github.com/fastlane/fastlane/issues/4356 [open] 4 💬
   29 Apr 2016

➡️  Snapshot run fails not finded libraries installed via pods
   https://github.com/fastlane/fastlane/issues/4423 [open] 28 💬
   23 Jun 2016

and 24 more at: https://github.com/fastlane/fastlane/search?q=Error%20building/testing%20the%20application%20-%20see%20the%20log%20above&type=Issues&utf8=✓

[!] Error building/testing the application - see the log above

```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile (relevant part):
```ruby
    scan(
      workspace: "uPen.xcworkspace",
      scheme: "uPen", 
      configuration: "Debug",

      derived_data_path: "reports/DerivedData", 
      
      destination: "platform=iOS Simulator,name=iPad Air,OS=9.3",      
      
      code_coverage: true,      

      output_directory: "reports"
    )
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.100.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No.

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv.

**Comment by TKBurner** [comment]
@giacgbj Thanks for reaching out! Can you let me know what happens if you reset the simulator before running scan? Also, what happens if you run it when Xcode is closed? Thanks!

**Comment by giacgbj** [comment]
I've already tried those combinations with or without "destination" with the same results.

I still don't understand:
* where does `-destination 'platform=iOS Simulator,id=1326E607-F5A0-493C-8F94-49181D96FA89' `come from;
* why that destination is not found when "instruments -s" founds it (iPhone 5s (8.1) [1326E607-F5A0-493C-8F94-49181D96FA89] (Simulator));
* how should I avoid the the destination parameter ("It's not recommended to set the `destination` value directly. Instead use the other options available in `scan --help`"). Which other option(s)? How should I exactly use it/them?

**Comment by TKBurner** [comment]
Hi @giacgbj Thanks for followin gup. What happens if you run the `reset_simulators` action prior to running scan? Thanks!

**Comment by giacgbj** [comment]
@TKBurner Same error.

**Comment by KrauseFx** [comment]
Fixed with https://github.com/fastlane/fastlane/pull/5744, I'm preparing a new release right now. Sorry for introducing the issue

**Comment by giacgbj** [comment]
@KrauseFx If I just need to update the scan component to the version 0.11.3, as I did, I still experience the bug.

**Comment by bartoszj** [comment]
@giacgbj 
Bug was introduced and fixed in the `Fastlane` not in the `Scan`. As I can see the bug fix was not yet released.

**Comment by giacgbj** [comment]
I close this issue: it seems to have been solved by Fastlane 1.101.0.

**Comment by postmechanical** [comment]
Not for me @giacgbj 

```
gem update fastlane
Updating installed gems
Updating fastlane
Fetching: scan-0.11.3.gem (100%)
Successfully installed scan-0.11.3
Fetching: fastlane-1.101.0.gem (100%)
Successfully installed fastlane-1.101.0
Parsing documentation for fastlane-1.101.0
Installing ri documentation for fastlane-1.101.0
Installing darkfish documentation for fastlane-1.101.0
Parsing documentation for scan-0.11.3
Installing ri documentation for scan-0.11.3
Installing darkfish documentation for scan-0.11.3
Gems updated: fastlane scan
scan --scheme Foobar --device "iPhone 6s"
[11:49:55]: xcodebuild -list -workspace ./Foobar.xcworkspace
[11:50:07]: Ignoring 'iPhone 6s', couldn't find matching simulator
[11:50:07]: Couldn't find any matching simulators for '["iPhone 6s"]' - falling back to default simulator
```

**Comment by hons82** [comment]
You've to remain on scan 0.11.0 which seems to be the last working version till now

**Comment by giacgbj** [comment]
@postmechanical It seems you are using a different configuration than mine. I specify a destination.

@hons82 I'm using scan 0.11.3.

**Comment by postmechanical** [comment]
I get this warning when using `destination`:

```
[12:54:39]: xcodebuild -list -workspace ./Foobar.xcworkspace
[12:54:47]: It's not recommended to set the `destination` value directly
[12:54:47]: Instead use the other options available in `scan --help`
[12:54:47]: Using your value 'device=iPhone 6s' for now
[12:54:47]: because I trust you know what you're doing...
```

**Comment by giacgbj** [comment]
@postmechanical I know, but I've never found other ways to avoid `destination`, mostly because of `other options available in `scan --help`` is not extremely clear.

**Comment by hons82** [comment]
I let it run directly on my CI server with such a command

scan --workspace ${WS}.xcworkspace --scheme ${SCHEME} --devices "iPad Air 2" --derived_data_path ${DERRIVED_DATA_DIR} --clean --code_coverage true --output_types junit --output_directory ${DERRIVED_DATA_DIR}/test-reports

Which is working on 0.11.0 but later it says that it cannot find the destination specified

**Comment by giacgbj** [comment]
@hons So you should follow the ticket #5742 (created by @postmechanical), which you and @postmechanical are confirming is not related to this one, closed by the latest release.

**Comment by postmechanical** [comment]
@giacgbj Sorry, did not notice I was posting to wrong issue.

**Comment by hons82** [comment]
Ups... Mi too.
Sorry
