### ISSUE TITLE
[Sigh] recreating provision profiles even with valid certificate

### ISSUE THREAD

**Issue by maschall** [fastlane/fastlane#6137]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
##### Complete output when running fastlane, including the stack trace and command used

```
sigh -a [app id] -b [team id] -u [username]

[15:10:16]: Starting login with user [username]
[15:10:18]: Successfully logged in
[15:10:18]: Fetching profiles...
[15:10:19]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[15:10:19]: Found more than one code signing identity. Choosing the first one. Check out `sigh --help` to see all available options.
[15:10:19]: Available Code Signing Identities for current filters:
[15:10:19]:     - Name: [REDACTED]
[15:10:19]:     - Name: [REDACTED]
[15:10:20]: The name '[REDACTED] InHouse' is already taken, using another one.
[15:10:20]: Creating new provisioning profile for [REDACTED] with name '[REDACTED] InHouse 1473966620'
[15:10:21]: Downloading provisioning profile...
[15:10:22]: Successfully downloaded provisioning profile...
[15:10:22]: Installing provisioning profile...
[REDACTED]
[15:10:22]: Setting Provisioning Profile type to 'enterprise'
```

sigh version (run `fastlane -v`): 1.10.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rvm

Additionally, when debugging sigh I see the following in the profiles

```
[<Spaceship::Portal::ProvisioningProfile::InHouse 
    id="[REDACTED]", 
    uuid="[REDACTED]", 
    expires=#<DateTime: 2017-09-15T19:12:19+00:00 ((2458012j,69139s,0n),+0s,2299161j)>, 
    distribution_method="inhouse", 
    name="[REDACTED] InHouse 1473966738", 
    status="Active", 
    type="iOS UniversalDistribution", 
    version="2", 
    platform="ios", 
    managing_app=nil, 
    app=<Spaceship::Portal::App 
        app_id="[REDACTED]", 
        name="[REDACTED]", 
        platform="ios", 
        prefix="[REDACTED]", 
        bundle_id="[REDACTED]", 
        is_wildcard=false, 
        features={"push"=>true, "iCloud"=>false, "inAppPurchase"=>true, "gameCenter"=>true, "LPLF93JG7M"=>false, "passbook"=>false, "IAD53UNK2F"=>false, "V66P55NK2I"=>false, "dataProtection"=>"untilfirstauth", "SKC3T5S89Y"=>false, "APG3427HIY"=>false, "HK421J6T7P"=>false, "homeKit"=>false, "WC421J6T7P"=>false, "cloudKitVersion"=>1}, 
        enabled_features=["gameCenter", "dataProtection", "inAppPurchase", "push"], 
        dev_push_enabled=false, 
        prod_push_enabled=false, 
        app_groups_count=nil, 
        cloud_containers_count=nil, 
        identifiers_count=nil>, 
    certificates=[], 
    devices=[]>
```

As you can see the certificates is empty as well as devices.

When I login to the portal, the certificate is set and valid with devices.  Also I have the valid certificate downloaded on my machine.

**Comment by maschall** [comment]
Verified with Charles, that the certificateIds is returning an empty array

**Comment by tehnoir** [comment]
Confirmed here as well. Adding a device to a profile an updating results in a new profile being generated that only contains that single device.

**Comment by harshabonthu** [comment]
I am facing a similar issue as well. I was getting multiple profiles created when ever new device is added so did some testing and noticed as below.

I did `'match nuke distribution'` and then `'match adhoc'`

If I run `'sigh download_all'` I see a message ```Skipping invalid/expired profile 'match AdHoc com.appname' ``` even though the profile is still valid on portal.

I see multiple provisioning profiles created when I do the following steps
I did `'match nuke distribution'` and then `'match adhoc'`
and now if I run `match adhoc --force_for_new_devices` this generates another profile with timestamp.

**Comment by CraigSiemens** [comment]
Running into the same issue as well. 

`sigh download_all` reports that all provisioning profiled are invalid/expired but developer.apple.com shows them all as being active.

**Comment by stevenbaker** [comment]
Seeing same thing as @CraigSiemens and @maschall above.  

I'm not a fastlane developer, so my hunches may be off, but I have a strong suspicion that `developerservices2.apple.com` is returning bad data.  Somebody please double check my work here.  :-)

At the commandline, I performed the following:

```
$ VERBOSE=1 bundle exec sigh download_all
```

Within the logger output, I see ...

```
... "devices"=>[], "deviceIds"=>[], "certificates"=>[], "certificateIds"=>[] ...
```

Crazy thing is, when I open this _same exact provisioning profile_ in the web UI at  developer.apple.com, I see five certificates and twenty devices on the profile.  (It's a dev profile.) 

Note that the "missing data" scenario above is confirmed by doing the same `sigh download_all` attempt, but this time proxying via Charles:

```
$ DEBUG=1 bundle exec sigh download_all
```

In Charles, we see:
```
...
<key>devices</key>
<array />
<key>deviceIds</key>
<array />
<key>certificates</key>
<array />
<key>certificateIds</key>
<array />
...
```

Yeesh.  At this point, it seems like there's not much that spaceship + sigh can do.  When downloading profiles, sigh does a check to see if the profile is valid, and it returns false if the `certificates` array is empty.

So, even if the provisioning profiles are valid within the web UI at developer.apple.com, since Apple appears to be returning incorrect data via their API at `developerservices2.apple.com` ... it's impossible for sigh to know that the profiles are valid and will therefore report them as invalid.  

But again, I'd love to be wrong here ...

**Comment by KrauseFx** [comment]
Thanks for the reports everybody, we're looking into the issue right now 👍

**Comment by KrauseFx** [comment]
Could you try running sigh using
```ruby
  sigh(skip_certificate_verification: true, ...)
```
or 
```
sigh --skip_certificate_verification
```

and see if that works for you? Still working on a fix, I'm trying to find the spot in _sigh_ that's causing the problem 👍

**Comment by maschall** [comment]
It still has the issue, because the problem is on this [line](https://github.com/fastlane/fastlane/blob/master/sigh/lib/sigh/runner.rb#L68) and the check for skip_certificate_verification is below that.

I was going to try removing the `certificate_valid?` call [here](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/provisioning_profile.rb#L382) and see if it works with the --skip_certificate_verification.

I feel like Apple only marks profiles as "Active" when the certificates are valid, but I'm sure I could be wrong.

Additionally, if we still wanted to make the certificate_valid? check, we could do so unless skip_certificate_verification is true.

**Comment by KrauseFx** [comment]
Alright, thanks, I noticed the error is somewhere else, so please ignore my last question

**Comment by KrauseFx** [comment]
I have prepared https://github.com/fastlane/fastlane/pull/6143, which will access a separate API to get the list of certificates for a provisioning profile to detect if it's valid. If you have a minute, please try installing it and let me know if it works for you 👍

**Comment by stevenbaker** [comment]
@krausefx @maschall Works for me!

```
$ git pull
$ git checkout fix-spaceship
$ git log --pretty=oneline | head -n 1
c819a8a50e22f6289d7951d002f38f8b065af93f Add support for 2-level provisioning profile API
$ bundle exec rake install
$ bundle exec sigh download_all
[...]
[19:13:35]: Successfully logged in
[19:13:36]: Downloading profile 'com.***.***** Development'...
[19:13:37]: Installing provisioning profile...
[19:13:37]: Downloading profile 'com.***.***** AppStore'...
[19:13:37]: Installing provisioning profile...
```

Thanks so much!  Great work.

:shipit:

**Comment by KrauseFx** [comment]
Thanks everybody, I just pushed https://github.com/fastlane-old/sigh/releases/tag/1.10.3, let me know if that works for you 🚀

**Comment by romanr** [comment]
After this update ```sigh download_all``` works.
But the problem with endless regeneration of profiles still there, on each run sigh generates newer profile with new timestamp:

```
$sigh --adhoc --app_identifier <app>

+-------------------------------------+--------------------------+
|                    Summary for sigh 1.10.3                     |
+-------------------------------------+--------------------------+
| adhoc                               | true                     |
| app_identifier                      | <app>          |
| skip_install                        | false                    |
| development                         | false                    |
| force                               | false                    |
...
[15:41:30]: Successfully logged in
[15:41:30]: Fetching profiles...
[15:41:30]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[15:41:35]: The name '<app> AdHoc' is already taken, using another one.
[15:41:35]: Creating new provisioning profile for '<app>' with name '<app> AdHoc 1474029695'
[15:41:40]: Downloading provisioning profile...
[15:41:42]: Successfully downloaded provisioning profile...
[15:41:42]: Installing provisioning profile...

$sigh --adhoc --app_identifier <app>
...
[15:41:48]: Fetching profiles...
[15:41:48]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[15:41:53]: The name '<app> AdHoc' is already taken, using another one.
[15:41:53]: Creating new provisioning profile for '<app>' with name '<app> AdHoc 1474029713'
[15:41:57]: Downloading provisioning profile...
```
On each run it generates newer profile with new timestamp: ```Creating new provisioning profile for '<app>' with name '<app> AdHoc 1474029713'```

**Comment by tehnoir** [comment]
After updating sigh, spaceship, and fastlane, I'm still seeing the same symptoms when using Spaceship to add devices to profiles. When selecting a profile by name with `"Spaceship.provisioning_profile.all.find { |p| p.name == "Nick Fastlane Test" }"` it reports devices as an empty array: `devices=[]`.

If I push a new device to that profile and do an update, the profile will only contain that single device, not all devices that were previously on it.

Let me know if this should be opened as a separate bug.

**Comment by KrauseFx** [comment]
Thanks @tehnoir @romanr I'm looking into this. Looks like I only fixed the `valid?` problem, looking into devices right now 🚀

**Comment by KrauseFx** [comment]
I was doing more research

https://twitter.com/KrauseFx/status/776881915366219777
https://twitter.com/KrauseFx/status/776882447132745728
https://twitter.com/KrauseFx/status/776883600604004352

I tried to avoid downloading the profile for performance reasons
since we now have to send one request for each profile, just to detect its type
and we can’t do a lazy loading, since we need the class type
not an issue, I found a fast API endpoint
however thinking about countries with slower internet, they will feel the difference
but  updated both their API endpoints to not include the devices and certificates any more
I’ll do my best to keep the number of requests on a minimum

**Comment by KrauseFx** [comment]
And more discoveries https://twitter.com/KrauseFx/status/776887607456178177

**Comment by KrauseFx** [comment]
@tehnoir I just pushed https://github.com/fastlane/fastlane/pull/6155 which should fix the device issue you mentioned. Could you give it a try?

**Comment by KrauseFx** [comment]
@romanr I couldn't reproduce your issue, do you think you can find a way to send me some steps to reproduce?

**Comment by tehnoir** [comment]
@KrauseFx I can confirm that fixes my issue. Now when finding a profile by name, the device list is no longer empty. Also, when adding a new device to a profile and updating the profile, it now adds the new device while preserving all existing devices on the profile.

**Comment by KrauseFx** [comment]
I just added some final touches to https://github.com/fastlane/fastlane/pull/6155, @tehnoir I'd appreciate if you could give it one more try, just to make sure this is working before we push a new version 👍

**Comment by owurman** [comment]
I'm experiencing this and happy to try the fix, but I'm brain farting and can't figure out how to apply the patch? I'm synced up to the latest gem.

**Comment by KrauseFx** [comment]
@owurman are you using bundler? 
If not, please clone the repo, check out the `fix-spaceship-again` branch, and run `cd spaceship; bundle install && rake install`

You might have to run `[sudo] gem install bundler` first

**Comment by owurman** [comment]
Have not been using bundler to my knowledge. I'll install it and clone the repo, and let you know. Anything I need to specify in my environment to run the cloned version rather than the gem-installed version, or should explicitly running the cloned version of fastlane be enough?

**Comment by KrauseFx** [comment]
@owurman you should be fine, follow the instructions above, clone the repo, check out the branch, and run the command I sent you 👍

**Comment by owurman** [comment]
Unfortunately, didn't go so smooth. fastlane now crashes:
/Library/Ruby/Gems/2.0.0/gems/bundler-1.13.1/lib/bundler/rubygems_ext.rb:45:in `full_gem_path': uninitialized constant Bundler::Plugin::API::Source (NameError)
...


I think something screwed up in my setup when I ran the installation.

**Comment by owurman** [comment]
Oh OK, I shouldn't have run rake install with sudo, I think, but it fails without it:
spaceship 0.32.3 built to pkg/spaceship-0.32.3.gem.
rake aborted!
Couldn't install gem, run `gem install /Users/oded/fastlane/spaceship/pkg/spaceship-0.32.3.gem' for more detailed output

Running the gem install manually (without sudo) gives me
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory

**Comment by KrauseFx** [comment]
We just pushed the new release: https://twitter.com/FastlaneTools/status/776920815522553856, let us know if that fixes the issue for you 👍

**Comment by owurman** [comment]
Unfortunately, whatever I did with bundle/rake isn't fixed by a gem update. I have to figure it out and clean it up.

**Comment by tehnoir** [comment]
@KrauseFx Sorry for the belated response. Just did another pass with the latest push, and all is still working well for me. Thanks for the quick fix.

**Comment by owurman** [comment]
OK, the issue is actually with bundler v1.13.1 which I installed, assuming I didn't have bundler at all. I rolled back to 1.12.5 and everything is fine now. The fix seems to work but I'll verify on another app in a moment.

**Comment by owurman** [comment]
Confirmed, works on the other app, too.

**Comment by carlosefonseca** [comment]
I saw that @KrauseFx was concerned about the number of requests to Apple endpoints but could it be possible to optimize something on the simple case of fetching a profile?

For instance, I call `sigh -a com.company.example` or `sigh(app_identifier:com.company.example)` on my scripts/fastfile and I get this

```
[19:44:44]: Successfully logged in
[19:44:44]: Fetching profiles...
[19:51:14]: Found 1 matching profile(s)```

It now takes more than 6 minutes to do what used to be very fast.
I have many many apps on this account.
I'm just asking if, for this case where I specify the app id, could `sigh` be performing useless requests?

Usually I try to look into the source code but I don't have much time right now. Sorry about that.

Many thanks!

**Comment by KrauseFx** [comment]
@carlosefonseca Thanks for letting us know, we're aware of the issue and we're trying to figure out a better approach, however it doesn't seem to be an easy fix
