### ISSUE TITLE
Lane fails when trying to perform sigh step

### ISSUE THREAD

**Issue by natanrolnik** [fastlane/fastlane#707]
(I wasn't sure if I should open the issue in the fastlane, Sigh, or Spaceship repo, so I'm opening here):

Starting 2 days ago, sigh is failing in my lanes - both locally and in CircleCI. 
I enabled the new feature - crash reporting - and I got the id `7dbd93125998c44a140a0494b4fbbd26`

This is the response I get:

```
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Before enabling the crash reporting, it showed `(Spaceship::Client::UnexpectedResponse)`

**Comment by KrauseFx** [comment]
Thank you so much for attaching the crash report, this helped me a lot:

Please update your gems as I pushed a fix yesterday:

```
sudo gem update fastlane
```

or just `sudo gem update spaceship`

**Comment by KrauseFx** [comment]
If you have a `Gemfile` and `Gemfile.lock` make sure to run `bundle update`

**Comment by natanrolnik** [comment]
Thank you @KrauseFx
According to the CI logs, the gem versions are:

spaceship-0.12.1
sigh-1.0.0
fastlane-1.33.3

**Comment by KrauseFx** [comment]
According to the crash report your CI is using outdated versions. Could you describe your setup on how you install the gems? Do you use a `Gemfile`?

**Comment by revile** [comment]
I'm getting a sigh failing in my builds as well:
```
[16:44:08]: Starting login with user 'emailmobile@trademe.co.nz'
[16:44:11]: Successfully logged in
[16:44:11]: Fetching profiles...
unable to load certificate
17420:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:/SourceCache/OpenSSL098/OpenSSL098-52.30.1/src/crypto/asn1/tasn_dec.c:1341:
17420:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:/SourceCache/OpenSSL098/OpenSSL098-52.30.1/src/crypto/asn1/tasn_dec.c:385:Type=X509
```

Crash report: 22644bde1cc6e37d9e2a8ca93c684ad9

**Comment by KrauseFx** [comment]
@revile Could you try updating to the latest spaceship/fastlane as well? This is caused by a  server change and I had to update the tools :+1:

**Comment by realf** [comment]
It seems this issue has a similar nature to https://github.com/fastlane/spaceship/issues/129

**Comment by natanrolnik** [comment]
Updating the Gemfile to 
```
gem 'fastlane', '~> 1.33'
```
did the trick. But it's strange that the previous logs mentioned the most up to date (back then) fastlane. Anyway, I'm glad it's fixed.

Thanks again, @KrauseFx !

**Comment by realf** [comment]
I am on version 1.33.4 and sometimes I'm still getting this error:
```
unable to load certificate
45002:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:/SourceCache/OpenSSL098/OpenSSL098-52.40.1/src/crypto/asn1/tasn_dec.c:1341:
45002:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:/SourceCache/OpenSSL098/OpenSSL098-52.40.1/src/crypto/asn1/tasn_dec.c:385:Type=X509
[18:24:34]: 
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.24.0/lib/fastlane_core/cert_checker.rb:43:in `rescue in sha1_fingerprint': Error parsing certificate '/var/folders/9y/1myb2dnd2l1f1mxp2tscg_1h0000gq/T/cert20151019-44998-1fr9kj6' (RuntimeError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.24.0/lib/fastlane_core/cert_checker.rb:37:in `sha1_fingerprint'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.24.0/lib/fastlane_core/cert_checker.rb:8:in `installed?'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sigh-1.0.0/lib/sigh/runner.rb:94:in `block (2 levels) in fetch_profiles'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sigh-1.0.0/lib/sigh/runner.rb:90:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sigh-1.0.0/lib/sigh/runner.rb:90:in `block in fetch_profiles'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sigh-1.0.0/lib/sigh/runner.rb:87:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sigh-1.0.0/lib/sigh/runner.rb:87:in `find_all'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sigh-1.0.0/lib/sigh/runner.rb:87:in `fetch_profiles'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sigh-1.0.0/lib/sigh/runner.rb:20:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sigh-1.0.0/lib/sigh/manager.rb:7:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sigh-1.0.0/bin/sigh:34:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sigh-1.0.0/bin/sigh:86:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sigh-1.0.0/bin/sigh:92:in `<top (required)>'
	from /usr/local/bin/sigh:23:in `load'
	from /usr/local/bin/sigh:23:in `<main>'
```

I don't think we should close this issue yet.

**Comment by natanrolnik** [comment]
Although it was fixed in the CI, I'm getting now another error in the sigh step:

```
18:39:15]: Starting login with user 'myuser@email.com'
[18:39:17]: Successfully logged in
[18:39:17]: Fetching profiles...
sh: openssl: command not found
```

Crash report: `37e6d6333e1130a929775d721b1a5b4d`

**Comment by realf** [comment]
One more crash report: `a73b5ecd1e31514f61840ab6f67b0238`

**Comment by nklausni** [comment]
Problem still alive with the latest Fastlane version: e4975840c476c8980f764efc6406353c

**Comment by nklausni** [comment]
Now it works. Seems to be a weird problem o.O

**Comment by natanrolnik** [comment]
For me it's weird also, it's an inconsistent bug.
In my CI it started failing again. @KrauseFx I enabled crash reporting also in the CI, and this is the crash report id: `39602e56769bc864b1f2bd4cee84f6f2 `

**Comment by gfpacheco** [comment]
For me this is a consistent problem, it's happening every time I run a lane with sigh it crashes with the "302 Found" error. This is my last report sent: `8370640736b17a8e131e4fa08836df27`.

**Comment by jeffremer** [comment]
Also having the same problem with v1.33.6, see `275aa826310d025b3c769d950899a8f7`.

**Comment by ohwutup** [comment]
Hi everyone! I am going to close this issue for now as it's probably been taken care of in a newer version of the tools! If you are still having these issues, please try to update the versions and don't hesitate at all to reopen the issue! :icecream:
