### ISSUE TITLE
fastlane beta error: `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)

### ISSUE THREAD

**Issue by fnazarios** [fastlane/fastlane#745]
I'm getting this error when i try run `fastlane beta`. 

Full stack:
```
/Users/fnazarios/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
	from /Users/fnazarios/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
	from /Users/fnazarios/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/fnazarios/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect'
	from /Users/fnazarios/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/fnazarios/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /Users/fnazarios/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/fnazarios/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1133:in `get'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.12.3/lib/spaceship/portal/portal_client.rb:22:in `api_key'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.12.3/lib/spaceship/portal/portal_client.rb:37:in `send_login_request'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.12.3/lib/spaceship/client.rb:157:in `login'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.12.3/lib/spaceship/client.rb:51:in `login'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.12.3/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.12.3/lib/spaceship/portal/spaceship.rb:77:in `login'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/sigh-1.1.0/lib/sigh/runner.rb:15:in `run'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/sigh-1.1.0/lib/sigh/manager.rb:7:in `start'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/gems/fastlane-1.35.0/lib/fastlane/actions/sigh.rb:20:in `run'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/gems/fastlane-1.35.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/gems/fastlane-1.35.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/gems/fastlane-1.35.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/gems/fastlane-1.35.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/gems/fastlane-1.35.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/gems/fastlane-1.35.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:36:in `block (2 levels) in parsing_binding'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/gems/fastlane-1.35.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/gems/fastlane-1.35.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/gems/fastlane-1.35.0/lib/fastlane/runner.rb:51:in `block in execute'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/gems/fastlane-1.35.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/gems/fastlane-1.35.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/gems/fastlane-1.35.0/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/gems/fastlane-1.35.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/gems/fastlane-1.35.0/bin/fastlane:35:in `block (2 levels) in run'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/gems/fastlane-1.35.0/bin/fastlane:152:in `run'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/gems/fastlane-1.35.0/bin/fastlane:158:in `<top (required)>'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `load'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `<main>'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by xfreebird** [comment]
@fnazarios does that happen each time ? Or just in some cases ?

**Comment by fnazarios** [comment]
this erro happen when the `fastlane` tries connect to iTunes connect i
think. When i run `pilot` occurs the same error.

2015-10-27 11:07 GMT-02:00 Nicolae Ghimbovschi <notifications@github.com>:

> @fnazarios <https://github.com/fnazarios> does that happen each time ? Or
> just in some cases ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fastlane/fastlane/issues/745#issuecomment-151489161>.
>



-- 

Abs,
Fernando Nazario
Cel.: +55 (11) 9-
​6779-2121

Twitter: http://twitter.com/fnazarios
--------------------------------------------------



*"A grandiosa Revolução Humana de uma única pessoairá um dia impulsionar a
mudança total do destino de umpaís e além disso, será capaz de transformar
o destino detoda a humanidade." *

**Comment by fnazarios** [comment]
this erro happen when the `fastlane` tries connect to iTunes connect i think. When i run `pilot` occurs the same error.

**Comment by fnazarios** [comment]
Error when i run `pilot list` @xfreebird 
```
$ pilot list
[11:28:50]: Login to iTunes Connect (fernando.sousa@moip.com.br)
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
/Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.12.3/lib/spaceship/tunes/tunes_client.rb:58:in `rescue in login_url': Could not fetch the login URL from iTunes Connect, the server might be down (RuntimeError)
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.12.3/lib/spaceship/tunes/tunes_client.rb:50:in `login_url'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.12.3/lib/spaceship/tunes/tunes_client.rb:63:in `send_login_request'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.12.3/lib/spaceship/client.rb:157:in `login'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.12.3/lib/spaceship/client.rb:51:in `login'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.12.3/lib/spaceship/tunes/spaceship.rb:22:in `login'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/pilot-1.0.0/lib/pilot/manager.rb:15:in `login'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/pilot-1.0.0/lib/pilot/manager.rb:8:in `start'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/pilot-1.0.0/lib/pilot/tester_manager.rb:67:in `list_testers'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/pilot-1.0.0/lib/pilot/commands_generator.rb:76:in `block (2 levels) in run'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/pilot-1.0.0/lib/pilot/commands_generator.rb:120:in `run'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/pilot-1.0.0/lib/pilot/commands_generator.rb:17:in `start'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1@global/gems/pilot-1.0.0/bin/pilot:6:in `<top (required)>'
	from /Users/fnazarios/.rvm/rubies/ruby-2.2.1/bin/pilot:23:in `load'
	from /Users/fnazarios/.rvm/rubies/ruby-2.2.1/bin/pilot:23:in `<main>'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/fnazarios/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by xfreebird** [comment]
Does it work if you login from web browser ? http://itunesconnect.apple.com ?

**Comment by fnazarios** [comment]
@xfreebird Works.

**Comment by xfreebird** [comment]
It looks more like a Ruby problem. see https://gist.github.com/mislav/5026283 and  https://gist.github.com/luislavena/f064211759ee0f806c88 

Have you tried updating your Ruby gems ? Or even a different Ruby version ?

```
gem update -p
```

You could try reinstalling your Ruby env, 
or try the suggested workaround:

```bash
curl -fsSL curl.haxx.se/ca/cacert.pem \
  -o "$(ruby -ropenssl -e 'puts OpenSSL::X509::DEFAULT_CERT_FILE')"
```

**Comment by fnazarios** [comment]
Maybe because i'm using `rvm`?

**Comment by xfreebird** [comment]
@fnazarios I don't know, I'm using ```rbenv```. Have you tried with the system Ruby ? Do you get similar errors ?

**Comment by fnazarios** [comment]
@xfreebird F***. Running with system ruby (2.2.x), the error does not happen. Thank's for help man! ;)

**Comment by KrauseFx** [comment]
Thanks @xfreebird :+1:

**Comment by colinta** [comment]
Had this error using Ruby 2.1 (which I installed to get past #804), and fixed it by installing Ruby 2.2 (again using rvm).  My system Ruby version is 2.0.

**Comment by pbernery** [comment]
Note that this is a common error with RVM. The regular way to fix it is:
- make sure OpenSSL is installed with Homebrew: `brew install openssl`
- tell RVM to use your Homebrew OpenSSL: `rvm reinstall ruby-2.2.3 --with-openssl-dir=/usr/local`

**Comment by jmorford** [comment]
This issue occurs on the xcode7.2 Travis CI image, but works ok with the xcode7.1 image. Are you working with Travis on this?

**Comment by cotsog** [comment]
@jmorford: there is a workaround [here](https://github.com/travis-ci/travis-ci/issues/5274#issuecomment-164320944). We are trying to provide a better fix but we don't have an ETA right now. Sorry for the inconvenience.

**Comment by ChristopherDrum** [comment]
@jmorford TravisCI and Xcode7.2 user here. Same issue. Using fastlane with Travis is starting to prove to be unwieldy, given I need to update fastlane every time I run an automated build (1.47 is just old enough to not include a command I need), and I believe that submissions to the iTunes Connect must be built with the latest Xcode, no? So, now I'll need to include this workaround as well, it seems. These mandatory installs for every time I want to do a continuous release build is getting to be a drag...

Can the Travis cache system be used to my advantage in these cases? (fastlane at 1.50 and ssl certs workaround)

**Comment by cotsog** [comment]
This should now be fixed on Travis CI's side.

Can someone confirm? @jmorford? @ChristopherDrum?

Thanks!

**Comment by the-scott-davis** [comment]
pbernery's comment resolve the issue for me. I did have to re-install fastlane once that was done, but otherwise i was good to go!

**Comment by marcomorain** [comment]
@cotsog this is still an issue on Travis I'm afraid (using the xcode 7.2 image)

**Comment by cotsog** [comment]
@marcomorain: Thanks for reporting and sorry for the issue.

Could you send a build log showing the error at support (at) travis-ci (dot) com?

Thanks!

**Comment by reach2seo** [comment]
I wish to collect links of business listed on https://trustedpros.ca/members_search_for_contractor_results_new.asp?job_sub_cat=58&postal=Toronto+&searchpage=1&miles=30&sort_by=30&province=Ontario&searchworddisplay=Painting&offset=10 and so on from all pages. When i run following given code i am facing error of

2.2.0/net/http.rb:923: in connect' ssl_connect returned=1 errno=0 state=sslv3 read certificate

Can anyone please guide step by step because i am fresher to this technology. I am running ruby on windows 7.

require 'nokogiri'
require 'open-uri'
require 'csv'
require 'openssl'
require 'net/http'

i=10
data_array=[]

while i<420

main='https://trustedpros.ca/members_search_for_contractor_results_new.asp?job_sub_cat=58&postal=Toronto+&searchpage=1&miles=30&sort_by=30&province=Ontario&searchworddisplay=Painting&offset='

url= main + (i).to_s

nokogiri_object = Nokogiri::HTML(open(url).read)
parse = nokogiri_object.xpath("//div[@class='left-det']/a[1]/@href")

parse.each do |a|
post_name = a.text
data_array.push(post_name)
end

CSV.open('yp.csv', 'w', {:col_sep => "\n"}) do |csv|
csv << data_array
end
i +=10
end

Can anyone give me better solution please?
