### ISSUE TITLE
gym just builds instead of archive

### ISSUE THREAD

**Issue by jjrebollo** [fastlane/fastlane#7494]
### New Issue Checklist

- [YES ] Updated fastlane to the latest version
- [ YES] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

gym is building my project but not archiving. This is the command that gym is running:

[17:23:58]: $ set -o pipefail && xcodebuild -workspace ./ASD\ PEC.xcworkspace -scheme SCHEME -configuration Release -destination 'generic/platform=iOS' -archivePath /Users/Juan/Library/Developer/Xcode/Archives/2016-12-14/App\ 2016-12-14\ 17.23.58.xcarchive **_build_** | tee /Users/Juan/Library/Logs/gym/China-AppStore-LR-China-AppStore-LR.log | xcpretty

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[17:26:06]: ▸ Running script '📦 Embed Pods Frameworks'
[17:26:06]: ▸ Running script '📦 Copy Pods Resources'
[17:26:06]: ▸ Touching SCHEME.app
[17:26:10]: ▸ Signing /Users/Juan/Library/Developer/Xcode/DerivedData/ASD-eqjeyrqbntnxlpgkqkixpkprrsrc/Build/Products/Release-iphoneos/SCHEME.app
[17:26:11]: ▸ Build Succeeded
[17:26:11]: Exporting Files:
[17:26:13]: 	 ▸ SCHEME.app
[17:26:13]: 	 ▸ SCHEME.app.dSYM
[17:26:13]: 	 ▸ HockeySDK
....

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.4                                     |
| Ruby                | 2.2.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.7.4 (Apple Git-66)            |
| Installation Source | ~/.rbenv/versions/2.2.3/bin/fastlane        |
| Host                | Mac OS X 10.11.4 (15E65)                    |
| Ruby Lib Dir        | ~/.rbenv/versions/2.2.3/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2f  28 Jan 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 7.3.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

## fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.60.0  | ✅ Up-To-Date  |
| spaceship           | 0.39.0  | ✅ Up-To-Date  |
| deliver             | 1.16.2  | ✅ Up-To-Date  |
| snapshot            | 1.17.0  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.1   | ✅ Up-To-Date  |
| cert                | 1.4.5   | ✅ Up-To-Date  |
| sigh                | 1.12.1  | ✅ Up-To-Date  |
| produce             | 1.4.0   | ✅ Up-To-Date  |
| gym                 | 1.13.0  | ✅ Up-To-Date  |
| pilot               | 1.13.1  | ✅ Up-To-Date  |
| scan                | 0.14.2  | ✅ Up-To-Date  |
| supply              | 0.8.0   | ✅ Up-To-Date  |
| match               | 0.11.1  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| fastlane            | 1.111.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| highline                  | 1.7.8        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.1        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.0        |
| net-ssh                   | 3.0.2        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.10.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| addressable               | 2.3.8        |
| xcode-install             | 2.0.9        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.11.2       |
| colored                   | 1.2          |
| commander                 | 4.4.0        |
| excon                     | 0.45.4       |
| gh_inspector              | 1.0.2        |
| credentials_manager       | 0.16.2       |
| fastlane_core             | 0.60.0       |
| bundler                   | 1.12.5       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160128 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| babosa                    | 1.0.2        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0221  |
| mime-types                | 3.0          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.0.0        |
| jwt                       | 1.5.2        |
| memoist                   | 0.14.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.2        |
| googleauth                | 0.5.1        |
| thor                      | 0.19.1       |
| httpclient                | 2.7.1        |
| google-api-client         | 0.9.2        |
| claide                    | 1.0.0        |
| xcodeproj                 | 1.0.0        |
</details>

**Comment by jjrebollo** [comment]
I'm using sigh for code signing and I've checked that is downloading the right provisioning profiles. Still the same issue :S

**Comment by zemelenda** [comment]
I'm seeing the same thing after updating from gym 1.12.1 to gym 1.13.0 in the last 24 hours.

**Comment by jjrebollo** [comment]
Same here. I just updated today and am having this issue.

**Comment by johnknapprs** [comment]
What version of Xcode is everyone running?  I had a similar issue with Gym yesterday on an Xcode 8.2 build machine.

**Comment by jjrebollo** [comment]
I'm using Xcode 7.3 so it doesn't seem to be about the Xcode version.

**Comment by mattiacantalu** [comment]
I opened same issue here https://github.com/fastlane/fastlane/issues/7485.

The problem seems to be gym 1.13.0, but i've not found a solution to force 1.12.1

**Comment by jjrebollo** [comment]
I just figured a workaround out to use gym v1.12.1:

```
gem install gym -v "=1.12.1"
gem uninstall gym -v "=1.13.0"
```

After this, the latest gym version you are going to have in your machine will be 1.12.1, so this will be the one used.

This version is working for me just fine.

As said before, this is just a workaround. Looking forward to getting new releases that fix this issue.

**Comment by zemelenda** [comment]
I used the same workaround as @mattiacantalu  and @jjrebollo yesterday (downgrading gym to 1.12.1). Not ideal, but it's keeping my build system up and running. I'm running both Xcode 7.3.1 and 8.2 on our build server but I only recall the issue affecting Xcode 8.2 builds.

**Comment by mattiacantalu** [comment]
yep.. it's not a solution, but a workaround!

**Comment by KrauseFx** [comment]
Thanks for reporting this, it seems to be a serious issue, so I'll reopen it and look into it

**Comment by KrauseFx** [comment]
I just pushed a PR, we're trying to get a release out as soon as possible: https://github.com/fastlane/fastlane/issues/7526

**Comment by mattiacantalu** [comment]
Hi @KrauseFx i'm trying to update fastlane... seems gym is not a dependencies anymore, but integrated in fastlane package, am i right?

After removing gym 1.12.1, `gem update gym` shows me: "No gem update".

**Comment by donatima** [comment]
Same here: apparently, gym 1.4.0 still shows the issue.
Furthermore, _gem install fastlane -v 1.111.0_ does not install v1.111.0 but v2.0.3, which is a mono gem and doesn't allow to downgrade gym, so the only current solution for us seems to be a temporary removal of Fastlane.

Any suggestion on a workaround would be greatly appreciated...

**Comment by KrauseFx** [comment]
We just released fastlane 2.0.4, please update to the new release, it will work :🚀

**Comment by dallamat** [comment]
Hi @KrauseFx we just updated fastlane to 2.1.1 and we still have the same problem as reported by @mattiacantalu
