### ISSUE TITLE
Gym now fails shortly after archiving

### ISSUE THREAD

**Issue by xtreme-shane-lattanzio** [fastlane/fastlane#7541]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Running my fastfile now causes the gym command to fail shortly after archiving. It seems to be looking for an ipa file that does not exist. The following is what I see after gym runs:

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

...
[12:17:46]: ▸ ** BUILD SUCCEEDED **

+------------------+---------------+
|           Lane Context           |
+------------------+---------------+
| DEFAULT_PLATFORM | ios           |
| PLATFORM_NAME    | ios           |
| LANE_NAME        | ios build_ipa |
+------------------+---------------+
[12:17:46]: File /var/folders/6t/syyk38954f1cqyrf246fmh3w0000gp/T/gym_output20161216-31661-11ombz3/APP-20161216-Staging-Internal.ipa not found

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | default_platform                                              | 0           |
| 2    |  ../scripts/reset_environment.sh && ../ | 18          |
| 3    | /usr/libexec/PlistBuddy ../../app/app-common/In | 0           |
| 4    | /usr/libexec/PlistBuddy ../../app/app-common/In | 0           |
| 5    | date +"%Y%m%d" | tr -d "\n"                                   | 0           |
| 💥   | gym                                                           | 87          |
+------+---------------------------------------------------------------+-------------+

[12:17:46]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
Zip::Error: [!] File /var/folders/6t/syyk38954f1cqyrf246fmh3w0000gp/T/gym_output20161216-31661-11ombz3/APP-20161216-Staging-Internal.ipa not found
  /Library/Ruby/Gems/2.0.0/gems/rubyzip-1.2.0/lib/zip/file.rb:85:in `initialize'
  /Library/Ruby/Gems/2.0.0/gems/rubyzip-1.2.0/lib/zip/file.rb:99:in `new'
  /Library/Ruby/Gems/2.0.0/gems/rubyzip-1.2.0/lib/zip/file.rb:99:in `open'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/gym/lib/gym/xcodebuild_fixes/swift_fix.rb:90:in `zip_entries_matching'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/gym/lib/gym/xcodebuild_fixes/swift_fix.rb:82:in `check_for_swift'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/gym/lib/gym/xcodebuild_fixes/swift_fix.rb:15:in `swift_library_fix'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/gym/lib/gym/runner.rb:94:in `fix_package'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/gym/lib/gym/runner.rb:20:in `run'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/gym/lib/gym/manager.rb:14:in `work'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/fastlane/lib/fastlane/actions/gym.rb:21:in `run'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/fastlane/lib/fastlane/runner.rb:225:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/fastlane/lib/fastlane/runner.rb:210:in `block in execute_action'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/fastlane/lib/fastlane/runner.rb:209:in `chdir'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/fastlane/lib/fastlane/runner.rb:209:in `execute_action'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/fastlane/lib/fastlane/runner.rb:131:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:152:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/fastlane/lib/fastlane/commands_generator.rb:96:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.0.0/gems/commander-4.4.1/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.0.0/gems/commander-4.4.1/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.0.0/gems/commander-4.4.1/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.0.0/gems/commander-4.4.1/lib/commander/runner.rb:444:in `run_active_command'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /Library/Ruby/Gems/2.0.0/gems/commander-4.4.1/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/fastlane/lib/fastlane/commands_generator.rb:293:in `run'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/fastlane/lib/fastlane/commands_generator.rb:36:in `start'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/fastlane/lib/fastlane/cli_tools_distributor.rb:60:in `take_off'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.0.3/bin/fastlane:5:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.11.6                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.9.3 (Apple Git-75)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.11.6 (15G1004)                                     |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.1                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby 

default_platform :ios

ENV["LANG"] = "en_US.UTF-8"
ENV["LANGUAGE"] = "en_US.UTF-8"
ENV["LC_ALL"] = "en_US.UTF-8"

platform :ios do
  lane :build_ipa do |options|

 #   increment_build_number

      gym(
        workspace: EDITED,
        scheme: EDITED,
        clean: true,
        configuration: "Staging",
        output_directory: "../builds",
        output_name: STAGING_BUILDNAME,
        use_legacy_build_api: true,
        disable_xcpretty: true
        )
  end
end
```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier "" # The bundle identifier of your app
apple_id "yaaay" # Your Apple email address

team_id "[[DEV_PORTAL_TEAM_ID]]"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.39.0  | ✅ Up-To-Date  |
| fastlane            | 2.0.3   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.1        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.6.0        |
| faraday                   | 0.10.0       |
| faraday_middleware        | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| babosa                    | 1.0.2        |
| xcode-install             | 2.0.9        |
| word_wrap                 | 1.0.0        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| rubyzip                   | 1.2.0        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| json                      | 1.8.3        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
</details>

*generated on:* **2016-12-16**
</details>

**Comment by milch** [comment]
Hi @xtreme-shane-lattanzio, thanks for submitting your issue! 

This was fixed in https://github.com/fastlane/fastlane/pull/7526. I've just released fastlane [`2.0.4`](https://github.com/fastlane/fastlane/releases/tag/fastlane/2.0.4) which includes this fix. If you update to that version, your issue should be resolved!

I'm going to close this for now. Let me know if you still experience issues, then we'll reopen this!

**Comment by xtreme-shane-lattanzio** [comment]
@milch Thanks for your reply! Unfortunately I am still getting the same error. Here is my new environment output:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.11.6                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.9.3 (Apple Git-75)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.11.6 (15G1004)                                     |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.1                                                            |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# Options to run this script
# internal - Only staging and QA to ETT
# internal and prod = Staging QA Prod to ETT
# release - Staging and QA to Ford
# release and prod - Staging QA Prod to Ford
# internal and release and prod - Staging QA Prod to ETT and Ford

# Note: Running internal and release will only cut for release
#       Running prod alone does nothing       

default_platform :ios

ENV["LANG"] = "en_US.UTF-8"
ENV["LANGUAGE"] = "en_US.UTF-8"
ENV["LC_ALL"] = "en_US.UTF-8"

platform :ios do
  lane :build_ipa do |options|

 #   increment_build_number

    if options[:internal]

      gym(
        workspace: "workspace",
        scheme: "app",
        clean: true,
        configuration: "Staging",
        output_directory: "../builds",
        output_name: STAGING_BUILDNAME,
        use_legacy_build_api: true,
        disable_xcpretty: true
        )
end
```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier "" # The bundle identifier of your app
apple_id "yaaay" # Your Apple email address

team_id "[[DEV_PORTAL_TEAM_ID]]"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.39.0  | ✅ Up-To-Date  |
| fastlane            | 2.0.4   | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.1        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.6.0        |
| faraday                   | 0.10.0       |
| faraday_middleware        | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| babosa                    | 1.0.2        |
| xcode-install             | 2.0.9        |
| word_wrap                 | 1.0.0        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| json                      | 1.8.3        |
| rubyzip                   | 1.2.0        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
</details>


*generated on:* **2016-12-16**
</details>

**Comment by xtreme-shane-lattanzio** [comment]
@milch When looking at the error more closely it actually looks like the directory is and old one that I had previously deleted yet it did create a new one. Now it looks like it is actually looking in the wrong spot. Is there a cache I need to clear?

**Comment by milch** [comment]
@xtreme-shane-lattanzio There's no cache, you can clear, sorry. However, I see that credentials_manager and spaceship are loaded. They are not needed anymore since they are integrated into fastlane now, try uninstalling both using `gem uninstall`.

**Comment by shammatime** [comment]
We are having the same issue as well with the new version.

**Comment by xtreme-shane-lattanzio** [comment]
@milch When I uninstall those I get the following when trying to run

bundle exec fastlane build_ipa internal:true
Bundler could not find compatible versions for gem "spaceship":
  In Gemfile:
    fastlane was resolved to 2.0.4, which depends on
      xcode-install (~> 2.0.0) was resolved to 2.0.9, which depends on
        spaceship (< 1.0.0, >= 0.25.1)

Could not find gem 'spaceship (< 1.0.0, >= 0.25.1)', which is required by gem 'xcode-install (~> 2.0.0)', in any of the sources.

**Comment by kskrishnan** [comment]
@milch - Even I get this error, ipa not found. I tried uninstalling credentials_manager and spaceship, but still the error persists. Any help here would be great.

**Comment by shammatime** [comment]
@milch @KrauseFx  Any update on this issue. With the recent problems with gems being removed for older version of fastlane we seem to be having issues with stability with older versions as well as the latest versions.

**Comment by milch** [comment]
@shammatime Sorry about that, we just shipped another update tonight: https://github.com/fastlane/fastlane/pull/7596
