### ISSUE TITLE
Error updating fastlane using the installer

### ISSUE THREAD

**Issue by carlosefonseca** [fastlane/fastlane#7691]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Was having some issues with the `json` gem so I tried to use the all-in-one installer package thing for fastlane. Seemed to install fine. Tried to update it didn't go well.

```
❯❯❯ fastlane update_fastlane
Updating installed gems
Updating fastlane
Fetching: tzinfo-0.3.52.gem (100%)
Successfully installed tzinfo-0.3.52
Fetching: minitest-4.7.5.gem (100%)
Successfully installed minitest-4.7.5
Fetching: activesupport-4.0.13.gem (100%)
Successfully installed activesupport-4.0.13
Building native extensions.  This could take a while...
Gems updated: tzinfo minitest activesupport jsonERROR:  Error installing fastlane:

	ERROR: Failed to build gem native extension.

    current directory: /Users/carlos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.0.2/ext/json/ext/generator
/Users/carlos/.fastlane/bin/bundle/bin/ruby -r ./siteconf20161228-55568-1v3kflw.rb extconf.rb
creating Makefile

current directory: /Users/carlos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.0.2/ext/json/ext/generator
Gems already up-to-date: fastlane pilot spaceship produce deliver frameit pem snapshot screengrab supply cert sigh match scan gym fastlane_core credentials_manager
make "DESTDIR=" clean

current directory: /Users/carlos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.0.2/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk'
In file included from generator.c:1:
In file included from ./../fbuffer/fbuffer.h:5:
In file included from /Users/carlos/.fastlane/bin/bundle/include/ruby-2.2.0/ruby.h:33:
In file included from /Users/carlos/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/ruby.h:29:
/Users/carlos/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/defines.h:26:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/carlos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.0.2 for inspection.
Results logged to /Users/carlos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/json-2.0.2/gem_make.out
Cleaning up installed gems...
Attempting to uninstall activesupport-4.0.13
Successfully uninstalled activesupport-4.0.13
Attempting to uninstall tzinfo-0.3.52
Successfully uninstalled tzinfo-0.3.52
Attempting to uninstall minitest-4.7.5
Successfully uninstalled minitest-4.7.5
Clean Up Complete
❯❯❯
```

The problem seems with this:
```
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk'
```
which I tried to install but ultimately failed telling me to install the command line tools, even after I did that… now I'm trying to replace my Xcode 8 with Xcode 7… 

By the way, my regular bundler install was failing with json problems too, either `ensure_xcode_version` failed with incompatible library (xcversion seems to require json v1.8)
```
[14:20:03]: --- Step: ensure_xcode_version ---
[14:20:03]: ----------------------------------
[14:20:03]: $ xcversion selected
[14:20:04]: ▸ /Users/carlos/.gems/gems/json-2.0.2/lib/json/ext.rb:7:in `require': incompatible library version - /Users/carlos/.gems/gems/json-2.0.2/lib/json/ext/parser.bundle (fatal)
[14:20:04]: ▸ from /Users/carlos/.gems/gems/json-2.0.2/lib/json/ext.rb:7:in `<module:Ext>'
[14:20:04]: ▸ from /Users/carlos/.gems/gems/json-2.0.2/lib/json/ext.rb:6:in `<module:JSON>'
[14:20:04]: ▸ from /Users/carlos/.gems/gems/json-2.0.2/lib/json/ext.rb:3:in `<top (required)>'
[14:20:04]: ▸ from /Users/carlos/.gems/gems/json-2.0.2/lib/json.rb:59:in `require'
[14:20:04]: ▸ from /Users/carlos/.gems/gems/json-2.0.2/lib/json.rb:59:in `<module:JSON>'
[14:20:04]: ▸ from /Users/carlos/.gems/gems/json-2.0.2/lib/json.rb:55:in `<top (required)>'
[14:20:04]: ▸ from /Users/carlos/.gems/gems/xcode-install-2.1.0/lib/xcode/install.rb:5:in `require'
[14:20:04]: ▸ from /Users/carlos/.gems/gems/xcode-install-2.1.0/lib/xcode/install.rb:5:in `<top (required)>'
[14:20:04]: ▸ from /Users/carlos/.gems/gems/xcode-install-2.1.0/bin/xcversion:10:in `require'
[14:20:04]: ▸ from /Users/carlos/.gems/gems/xcode-install-2.1.0/bin/xcversion:10:in `<top (required)>'
[14:20:04]: ▸ from /Users/carlos/.gems/bin/xcversion:22:in `load'
[14:20:04]: ▸ from /Users/carlos/.gems/bin/xcversion:22:in `<main>'
```

Other times I got a seg fault from ruby.
```
/Users/carlos/.gems/gems/json-2.0.2/lib/json/ext/parser.bundle: [BUG] Segmentation fault
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
```

I'm going bonkers with this…

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

This is the all-in-one:

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                         |
| ------------------- | --------------------------------------------- |
| OS                  | 10.12.1                                       |
| Ruby                | 2.2.4                                         |
| Bundler?            | false                                         |
| Git                 | git version 2.7.4 (Apple Git-66)              |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane           |
| Host                | Mac OS X 10.12.1 (16B2555)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                    |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                    |
| Is contained        | false                                         |
| Xcode Path          | /Volumes/Small/Xcode7.app/Contents/Developer/ |
| Xcode Version       | 7.3.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.100.0"

default_platform :ios

platform :ios do
  before_all do
    Actions.verify_gem!('xcode-install')
    Actions.verify_gem!('badge')
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/XXXXX"
    ensure_xcode_version(version: "8.2.1")
    # ensure_git_status_clean
    setup
    setup_jenkins(result_bundle: false) if Helper.is_ci?
  end

  … stuff …

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md

app_identifier "XXXX" # The bundle identifier of your app
apple_id "XXX" # Your Apple email address

team_id "XXX"  # Developer Portal Team ID
```
</details>

### fastlane gems

| Gem      | Version | Update-Status       |
| -------- | ------- | ------------------- |
| fastlane | 2.3.0   | 🚫 Update availaible |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
</details>

*generated on:* **2016-12-28**
</details>

This is my bundler:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                         |
| ------------------- | --------------------------------------------- |
| OS                  | 10.12.1                                       |
| Ruby                | 2.3.1                                         |
| Bundler?            | false                                         |
| Git                 | git version 2.7.4 (Apple Git-66)              |
| Installation Source | ~/.gems/bin/fastlane                          |
| Host                | Mac OS X 10.12.1 (16B2555)                    |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib            |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                   |
| Is contained        | false                                         |
| Xcode Path          | /Volumes/Small/Xcode7.app/Contents/Developer/ |
| Xcode Version       | 7.3.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.100.0"

default_platform :ios

platform :ios do
  before_all do
    Actions.verify_gem!('xcode-install')
    Actions.verify_gem!('badge')
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/XXXX"
    ensure_xcode_version(version: "8.2.1")
    # ensure_git_status_clean
    setup
    setup_jenkins(result_bundle: false) if Helper.is_ci?
  end


  … stuff …


  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md

app_identifier "XXXXX" # The bundle identifier of your app
apple_id "XXXXX" # Your Apple email address

team_id "XXXXXXXX"  # Developer Portal Team ID
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.3.1   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.2        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.5       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.5        |
| rubyzip                   | 1.2.0        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
</details>

*generated on:* **2016-12-28**
</details>

**Comment by KrauseFx** [comment]
Do you know the best way for us to reproduce the error?

**Comment by carlosefonseca** [comment]
One way I get to the problem is trying to update the all-in-one fastlane using `fastlane update_fastlane`…


```~/G/b2c-android ❯❯❯ fastlane update_fastlane
Fastlane update available
Please run `brew cask reinstall fastlane`
Updating installed gems
Updating fastlane
Fetching: tzinfo-0.3.52.gem (100%)
Successfully installed tzinfo-0.3.52
Fetching: minitest-4.7.5.gem (100%)
Successfully installed minitest-4.7.5
Fetching: activesupport-4.0.13.gem (100%)
Successfully installed activesupport-4.0.13
Building native extensions.  This could take a while...
ERROR:  Error installing fastlane:
Gems updated: tzinfo minitest activesupport json
	ERROR: Failed to build gem native extension.

    current directory: /Users/carlos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.0.2/ext/json/ext/generator
/Users/carlos/.fastlane/bin/bundle/bin/ruby -r ./siteconf20161228-78054-13n61sq.rb extconf.rb
creating Makefile

current directory: /Users/carlos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.0.2/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /Users/carlos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.0.2/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk'
Gems already up-to-date: fastlane pilot spaceship produce deliver frameit pem snapshot screengrab supply cert sigh match scan gym fastlane_core credentials_managerIn file included from generator.c:1:

In file included from ./../fbuffer/fbuffer.h:5:
In file included from /Users/carlos/.fastlane/bin/bundle/include/ruby-2.2.0/ruby.h:33:
In file included from /Users/carlos/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/ruby.h:29:
/Users/carlos/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/defines.h:26:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/carlos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.0.2 for inspection.
Results logged to /Users/carlos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/json-2.0.2/gem_make.out
Fastlane update available
Please run `brew cask reinstall fastlane`
Cleaning up installed gems...
Attempting to uninstall activesupport-4.0.13
Successfully uninstalled activesupport-4.0.13
Attempting to uninstall tzinfo-0.3.52
Successfully uninstalled tzinfo-0.3.52
Attempting to uninstall minitest-4.7.5
Successfully uninstalled minitest-4.7.5
Clean Up Complete
```

Here's the related stack:
### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


This is using all built in stuff (system ruby is a different version for instance) but fails to compile the json gem…


I tried a `brew cask reinstall fastlane` just before this but did nothing special and didn't update…
<details><summary>here's the log of that</summary>

```
~/G/b2c-android ❯❯❯ brew cask reinstall fastlane
==> Running uninstall process for fastlane; your password may be necessary
==> Running uninstall script /opt/homebrew-cask/Caskroom/fastlane/1.0/uninstall
==>
==> You can now remove fastlane from your search path by editing your ~/.zshrc file.
==> fastlane was uninstalled successfully!
==> Downloading https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/bundle-1.0.zip
Already downloaded: /opt/boxen/cache/homebrew/Cask/fastlane--1.0.zip
==> Verifying checksum for Cask fastlane
==> Running installer script /opt/homebrew-cask/Caskroom/fastlane/1.0/install
==>
==> Installing fastlane to /Users/carlos/.fastlane/bin... this might take a few seconds
==>
==> Successfully copied fastlane to /Users/carlos/.fastlane/bin
==>
==> Fastlane update available
==> Please run `brew cask reinstall fastlane`
==> Updating installed gems
==> Updating cert
==> Successfully installed fastlane-2.3.0
==> Please use `fastlane cert` instead of `cert` from now on.
==> Successfully installed cert-2.0.0
==> Updating credentials_manager
==> Please use `fastlane credentials_manager` instead of `credentials_manager` from now on.
==> Successfully installed credentials_manager-1.0.0
==> Updating deliver
==> Please use `fastlane deliver` instead of `deliver` from now on.
==> Successfully installed deliver-2.0.1
==> Updating fastlane_core
==> Successfully installed fastlane_core-1.0.0
==> Updating frameit
==> Please use `fastlane frameit` instead of `frameit` from now on.
==> Successfully installed frameit-4.0.0
==> Updating gym
==> Please use `fastlane gym` instead of `gym` from now on.
==> Successfully installed gym-2.0.0
==> Updating match
==> Please use `fastlane match` instead of `match` from now on.
==> Successfully installed match-1.0.0
==> Updating pem
==> Please use `fastlane pem` instead of `pem` from now on.
==> Successfully installed pem-2.0.0
==> Updating pilot
==> Please use `fastlane pilot` instead of `pilot` from now on.
==> Successfully installed pilot-2.0.0
==> Updating produce
==> Please use `fastlane produce` instead of `produce` from now on.
==> Successfully installed produce-2.0.0
==> Updating scan
==> Please use `fastlane scan` instead of `scan` from now on.
==> Successfully installed scan-1.0.0
==> Updating screengrab
==> Please use `fastlane screengrab` instead of `screengrab` from now on.
==> Successfully installed screengrab-1.0.0
==> Updating sigh
==> Please use `fastlane sigh` instead of `sigh` from now on.
==> Successfully installed sigh-2.0.1
==> Updating snapshot
==> Please use `fastlane snapshot` instead of `snapshot` from now on.
==> Successfully installed snapshot-2.0.0
==> Updating spaceship
==> Please use `fastlane spaceship` instead of `spaceship` from now on.
==> Successfully installed spaceship-1.0.0
==> Updating supply
==> Please use `fastlane supply` instead of `supply` from now on.
==> Successfully installed supply-1.0.0
==> Gems updated: cert fastlane credentials_manager deliver fastlane_core frameit gym match pem pilot produce scan screengrab sigh snapshot spaceship supply
==> Fastlane update available
==> Please run `brew cask reinstall fastlane`
==> Cleaning up installed gems...
==> Attempting to uninstall libxml-ruby-2.6.0
==> Successfully uninstalled libxml-ruby-2.6.0
==> Attempting to uninstall fastlane-1.109.0
==> Executables and scripts will remain installed.
==> Successfully uninstalled fastlane-1.109.0
==> Attempting to uninstall CFPropertyList-2.2.8
==> Successfully uninstalled CFPropertyList-2.2.8
==> Attempting to uninstall supply-0.7.1
==> Successfully uninstalled supply-0.7.1
==> Attempting to uninstall snapshot-1.16.3
==> Successfully uninstalled snapshot-1.16.3
==> Attempting to uninstall screengrab-0.5.6
==> Successfully uninstalled screengrab-0.5.6
==> Attempting to uninstall scan-0.14.1
==> Successfully uninstalled scan-0.14.1
==> Attempting to uninstall produce-1.3.0
==> Successfully uninstalled produce-1.3.0
==> Attempting to uninstall pilot-1.12.1
==> Successfully uninstalled pilot-1.12.1
==> Attempting to uninstall pem-1.4.0
==> Successfully uninstalled pem-1.4.0
==> Attempting to uninstall match-0.11.0
==> Successfully uninstalled match-0.11.0
==> Attempting to uninstall gym-1.12.0
==> Successfully uninstalled gym-1.12.0
==> Attempting to uninstall frameit-3.0.0
==> Successfully uninstalled frameit-3.0.0
==> Attempting to uninstall deliver-1.15.1
==> Successfully uninstalled deliver-1.15.1
==> Attempting to uninstall sigh-1.11.2
==> Successfully uninstalled sigh-1.11.2
==> Attempting to uninstall cert-1.4.4
==> Successfully uninstalled cert-1.4.4
==> Attempting to uninstall fastlane_core-0.56.0
==> Successfully uninstalled fastlane_core-0.56.0
==> Attempting to uninstall credentials_manager-0.16.2
==> Successfully uninstalled credentials_manager-0.16.2
==> Clean Up Complete
==> Detected shell config file at path '~/.zshrc'
==> Please add the following line to your bash profile:
==>
==> export PATH="$HOME/.fastlane/bin:$PATH"
==>
==> After doing so close the terminal session and restart it to start using fastlane 🚀
🍺  fastlane was successfully installed!
```

```
~/G/b2c-android ❯❯❯ export PATH="$HOME/.fastlane/bin:$PATH"
~/G/b2c-android ❯❯❯ which fastlane
/Users/carlos/.fastlane/bin/fastlane
~/G/b2c-android ❯❯❯ fastlane
Fastlane update available
Please run `brew cask reinstall fastlane`
[19:11:22]: Installing Ruby gem 'fastlane-plugin-ftp'...
Fetching: fastlane-plugin-ftp-0.1.3.gem (100%)
[19:11:34]: Successfully installed 'fastlane-plugin-ftp'
+---------------------+---------+--------+
|              Used plugins              |
+---------------------+---------+--------+
| Plugin              | Version | Action |
+---------------------+---------+--------+
| fastlane-plugin-ftp | 0.1.3   | ftp    |
+---------------------+---------+--------+

[19:11:34]: -------------------------------------------------
[19:11:34]: --- Step: Verifying required fastlane version ---
[19:11:34]: -------------------------------------------------
[19:11:34]: Your fastlane version 2.3.0 matches the minimum requirement of 1.67.0  ✅
[19:11:34]: ------------------------------
[19:11:34]: --- Step: default_platform ---
[19:11:34]: ------------------------------
[19:11:34]: Welcome to fastlane! Here's what your app is setup to do:
+--------+---------------------------+-------------------------------------------------------------------------------------------------------------+
|                                                              Available lanes to run                                                              |
+--------+---------------------------+-------------------------------------------------------------------------------------------------------------+
| Number | Lane Name                 | Description                                                                                                 |
+--------+---------------------------+-------------------------------------------------------------------------------------------------------------+
| 1      | android predeploy         | Does the stuff before a deploy.                                                                             |
|        |                           | Generates a changelog, bumps the build number, commits the bump.                                            |
| 2      | android bump              | Automatically increment version code                                                                        |
| 3      | android major_bump        | Automatically increment major version number (1.2.3 > 2.0.0)                                                |
| 4      | android minor_bump        | Automatically increment minor version number (1.2.3 > 1.3.0)                                                |
| 5      | android patch_bump        | Automatically increment patch version number  (1.2.3 > 1.2.4)                                               |
…
| 0      | cancel                    | No selection, exit fastlane!                                                                                |
+--------+---------------------------+-------------------------------------------------------------------------------------------------------------+
Which number would you like run?
0

[!] Run `fastlane` the next time you need to build, test or release your app 🚀

#######################################################################
# fastlane 2.3.1 is available. You are on 2.3.0.
# It is recommended to use the latest version.
# Please update using `sudo gem update fastlane`.
#######################################################################

2.3.1 Ruby 2.4 and more
- Add support for Ruby 2.4
- Improve error message when Xcode isn't installed
- Fix an optional property in _deliver_
- Improve documentation
- Add prefix index with zeroes for JUnit reports

Please update using `sudo gem update fastlane`
~/G/b2c-android ❯❯❯ fastlane update_fastlane
Fastlane update available
Please run `brew cask reinstall fastlane`
Updating installed gems
Updating fastlane
Fetching: tzinfo-0.3.52.gem (100%)
Successfully installed tzinfo-0.3.52
Fetching: minitest-4.7.5.gem (100%)
Successfully installed minitest-4.7.5
Fetching: activesupport-4.0.13.gem (100%)
Successfully installed activesupport-4.0.13
Fetching: json-2.0.2.gem (100%)
Building native extensions.  This could take a while...
Gems updated: tzinfo minitest activesupport jsonERROR:  Error installing fastlane:

	ERROR: Failed to build gem native extension.

    current directory: /Users/carlos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.0.2/ext/json/ext/generator
/Users/carlos/.fastlane/bin/bundle/bin/ruby -r ./siteconf20161228-77188-p7onmi.rb extconf.rb
creating Makefile

current directory: /Users/carlos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.0.2/ext/json/ext/generator
Gems already up-to-date: fastlane pilot spaceship produce deliver frameit pem snapshot screengrab supply cert sigh match scan gym fastlane_core credentials_managermake "DESTDIR=" clean


current directory: /Users/carlos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.0.2/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk'
In file included from generator.c:1:
In file included from ./../fbuffer/fbuffer.h:5:
In file included from /Users/carlos/.fastlane/bin/bundle/include/ruby-2.2.0/ruby.h:33:
In file included from /Users/carlos/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/ruby.h:29:
/Users/carlos/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/defines.h:26:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/carlos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.0.2 for inspection.
Results logged to /Users/carlos/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/json-2.0.2/gem_make.out
Fastlane update available
Please run `brew cask reinstall fastlane`
Cleaning up installed gems...
Attempting to uninstall activesupport-4.0.13
Successfully uninstalled activesupport-4.0.13
Attempting to uninstall tzinfo-0.3.52
Successfully uninstalled tzinfo-0.3.52
Attempting to uninstall minitest-4.7.5
Successfully uninstalled minitest-4.7.5
Clean Up Complete
```
</details>

**Comment by krokofant** [comment]
I've also gotten this error first time installing fastlane.
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.11.0                          |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.11.6 (15G1212)                  |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status       |
| -------- | ------- | ------------------- |
| fastlane | 2.1.3   | 🚫 Update availaible |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.2        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
</details>


*generated on:* **2016-12-29**
</details>

**Comment by uenitest** [comment]
Same problem here. I've tried to update, reinstall and remove + clean install. It crashes always

**Comment by moralez** [comment]
I was experiencing this same issue. Found this GitHub issue #6006 that said to run 
`fastlane run update_fastlane`
After running this command, it said it successfully updated and I was able to run normal fastlane commands again.
```
[jmo@xyz ~]$ fastlane run update_fastlane
[13:41:42]: -----------------------------
[13:41:42]: --- Step: update_fastlane ---
[13:41:42]: -----------------------------
[13:41:42]: Looking for updates for fastlane...
[13:41:51]: Updating fastlane from 2.1.3 to 2.3.1 ... 🚀
[13:42:56]: Finished updating fastlane
[13:42:56]: Cleaning up old versions...
[13:42:56]: fastlane.tools successfully updated! I will now restart myself... 😴
[13:42:57]: -----------------------------
[13:42:57]: --- Step: update_fastlane ---
[13:42:57]: -----------------------------
```

**Comment by uenitest** [comment]
After running `fastlane run update_fastlane` I get this:

```
[10:31:22]: -----------------------------
[10:31:22]: --- Step: update_fastlane ---
[10:31:22]: -----------------------------
[10:31:22]: Looking for updates for cert, credentials_manager, deliver, fastlane, fastlane_core, frameit, gym, match, pem, pilot, produce, scan, screengrab, sigh, snapshot, spaceship, supply...
[10:31:25]: Updating cert from 1.4.4 to 2.0.0 ... 🚀
[10:31:25]: Finished updating cert
[10:31:25]: Updating credentials_manager from 0.16.4 to 1.0.0 ... 🚀
[10:31:26]: Finished updating credentials_manager
[10:31:26]: Updating deliver from 1.16.1 to 2.0.1 ... 🚀
[10:31:27]: Finished updating deliver
[10:31:27]: Updating fastlane from 1.111.0 to 2.3.1 ... 🚀
[10:31:41]: Finished updating fastlane
[10:31:41]: Updating fastlane_core from 0.59.0 to 1.0.0 ... 🚀
[10:31:44]: Finished updating fastlane_core
[10:31:44]: Updating frameit from 3.0.0 to 4.0.0 ... 🚀
[10:31:45]: Finished updating frameit
[10:31:46]: Updating gym from 1.12.1 to 2.0.0 ... 🚀
[10:31:46]: Finished updating gym
[10:31:46]: Updating match from 0.11.1 to 1.0.0 ... 🚀
[10:31:48]: Finished updating match
[10:31:48]: Updating pem from 1.4.1 to 2.0.0 ... 🚀
[10:31:49]: Finished updating pem
[10:31:49]: Updating pilot from 1.12.1 to 2.0.0 ... 🚀
[10:31:49]: Finished updating pilot
[10:31:49]: Updating produce from 1.3.2 to 2.0.0 ... 🚀
[10:31:50]: Finished updating produce
[10:31:50]: Updating scan from 0.14.2 to 1.0.0 ... 🚀
[10:31:51]: Finished updating scan
[10:31:51]: Updating screengrab from 0.5.6 to 1.0.0 ... 🚀
[10:31:52]: Finished updating screengrab
[10:31:52]: Updating sigh from 1.12.1 to 2.0.1 ... 🚀
[10:31:53]: Finished updating sigh
[10:31:53]: Updating snapshot from 1.16.4 to 2.0.0 ... 🚀
[10:31:54]: Finished updating snapshot
[10:31:54]: Updating spaceship from 0.39.0 to 1.0.0 ... 🚀
[10:31:58]: Finished updating spaceship
[10:31:58]: Updating supply from 0.8.0 to 1.0.0 ... 🚀
[10:32:00]: Finished updating supply
[10:32:00]: All fastlane tools are up-to-date!
[10:32:00]: Result: true

#######################################################################
# fastlane 2.3.1 is available. You are on 1.111.0.
# It is recommended to use the latest version.
# Please update using `sudo gem update fastlane`.
#######################################################################

2.3.1 Ruby 2.4 and more
- Add support for Ruby 2.4
- Improve error message when Xcode isn't installed
- Fix an optional property in _deliver_
- Improve documentation
- Add prefix index with zeroes for JUnit reports

2.3.0 Improvements
* Removed redundant check in reset_git_repo, fixes #7650 (#7649)
* Allow commit_version_bump to find the Settings.bundle in the project (#6997)
* Updates credential manager docs for execution with monogem (#7640)
* Fix broken docs links in ToolsAndDebugging.md (#7637)
* Updated test path for post-monogem times (#7638)
* [docs] Update Jenkins integration link to link to new docs page (#7566)
* Update Jenkins integration link in fastlane sub-dir (#7567)
* [docs] Improve docs around how to test code (#7553)
* [snapshot] Add xcargs option to pass additional parameters to xcodebuild, fixes #7255 (#7261)
* [docs] More diagnostics & docs on the DEBUG env during testing (#7560)
* [README] spaceauth - adopt to monogem changes (#7615)
* [deliver] support metdata update of live_version (#7172)
* Remove imagemagick check, fixes #6904 (#6905)
* Jenkins doc improvements (#7608)
* Use Dir.mktmpdir internal cleanup mechanism to remove tmp folder (#7635)
* Update CORE_CONTRIBUTOR.md (#7634)
* Preventing actions called from another action to show in summary (#6322)

2.2.0 Add mailgun options, more iPad options for snapshot, bugfixes & more...
* [gym] Revert library support, fixes #7630 (#7631)
* [spaceship] Fix path to referenced fastfile (#7604)
* [fastlane action] Support mailgun reply_to (#7605)
* [fastlane] Anonymize sensitive options for captured_output (#7335)
* [snapshot] Add additional ipad classifiers. (#7570)

To see all new releases, open https://github.com/fastlane/fastlane/releases

Please update using `sudo gem update fastlane`

```

Some stuff seems to be updated buy I'm still on 1.111.0. So I run `sudo gem update fastlane`.
Aaaaand, perfect, I'm finally on 2.3.1

**Comment by larryonoff** [comment]
I had the same issue and `fastlane run update_fastlane` solved my problem.

**Comment by jocax** [comment]
I can also confirm that `fastlane run update_fastlane` solved my problem with the error `/Users/carlos/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/defines.h:26:10: fatal error: 'stdio.h' file not found
#include <stdio.h>` if you just execute `fastlane update_fastlane`

**Comment by larryonoff** [comment]
Just noticed that I'm unable updating fastlane to the latest version from 2.3.0 to 2.3.1 with `fastlane run update_fastlane`, when `fastlane update_fastlane` still throws an error.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                            |
| ------------------- | ------------------------------------------------ |
| OS                  | 10.12.2                                          |
| Ruby                | 2.2.4                                            |
| Bundler?            | false                                            |
| Git                 | git version 2.11.0                               |
| Installation Source | ~/.fastlane/bin/fastlane_lib/bundle/bin/fastlane |
| Host                | Mac OS X 10.12.2 (16C67)                         |
| Ruby Lib Dir        | ~/.fastlane/bin/fastlane_lib/bundle/lib          |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                       |
| Is contained        | true                                             |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/      |
| Xcode Version       | 8.2.1                                            |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status       |
| -------- | ------- | ------------------- |
| fastlane | 2.3.0   | 🚫 Update availaible |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.4        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.13.6       |
| claide                    | 1.0.1        |
| cocoapods                 | 1.1.1        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| commander                 | 4.4.2        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.1        |
| escape                    | 0.0.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 2.0.1        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.2        |
| google-api-client         | 0.9.20       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.4        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| netrc                     | 0.7.8        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.4        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.12       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.2        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2017-01-01**
</details>

**Comment by jocax** [comment]
I am facing the same problem as @larryonoff. After I run `fastlane run update_fastlane`  I can not updating fastlane  to the latest version from 2.3.0 to 2.3.1.  The problem`fatal error: 'stdio.h' file not found
#include <stdio.h>
`  still exists.

**Comment by samuelbeek** [comment]
I have exactly the sane problem `fastlane run update_fastlane` will only get me to `2.3.0`. If there's anything I can do to help, let me know!

**Comment by ohwutup** [comment]
Hey everyone! Thank you for reporting the issues! We are currently working on a fix and will get this thread updated as soon as possible. 🚀 🐙

**Comment by KrauseFx** [comment]
Hey everyone, we just pushed [fastlane 2.4.0](https://github.com/fastlane/fastlane/releases/tag/2.4.0) which fixes the bundled _fastlane_, just run `fastlane update_fastlane` to get the latest release 🚀

However this release breaks support for Ruby 2.4.0 for now, which we should be able to add again soon. For now, please downgrade to an older version of Ruby, or use the bundled _fastlane_ from [download.fastlane.tools](https://download.fastlane.tools)

Please let us know if that works for you 👍

**Comment by Reyske** [comment]
Still the same problem here.. Fastlane tools bundle v2.14.2 and Xcode 8.1 on El Capitan

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory: /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-1.8.6/ext/json/ext/generator
/Users/me/.fastlane/bin/bundle/bin/ruby -r ./siteconf20170210-45432-sj89c7.rb extconf.rb
creating Makefile

current directory: /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-1.8.6/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-1.8.6/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
clang: warning: no such sysroot directory:
'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk'
In file included from generator.c:1:
In file included from ./../fbuffer/fbuffer.h:5:
In file included from /Users/me/.fastlane/bin/bundle/include/ruby-2.2.0/ruby.h:33:
In file included from /Users/me/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/ruby.h:29:
/Users/me/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/defines.h:26:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2
```

**Comment by michaek** [comment]
If I run `gem install` in my project directory, it installs the dependencies without errors and I'm able to use the fastlane CLI. The error messages kind of look like the install script is trying to use the "wrong" Ruby, but I don't know what's going on under the hood.

**Comment by ohwutup** [comment]
Hey @Reyske thanks for raising the issue! Could you share some more of your command line output? Also, what is the command that you are running to generate this problem?

**Comment by Reyske** [comment]
Before running fastlane, the CI executes the following commands:
`fastlane update_fastlane
fastlane update_plugins`

And this is the output: 
`21-Feb-2017 08:28:07	Updating installed gems
21-Feb-2017 08:28:07	Nothing to update
21-Feb-2017 08:28:09	Cleaning up installed gems...
21-Feb-2017 08:28:09	Clean Up Complete
21-Feb-2017 08:28:12	Updating plugin dependencies...
21-Feb-2017 08:28:25	Errno::EPERM: Operation not permitted @ chmod_internal -
21-Feb-2017 08:28:25	/Users/qompium/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-1.8.6/tests/test_json.rb
21-Feb-2017 08:28:25	An error occurred while installing json (1.8.6), and Bundler cannot continue.
21-Feb-2017 08:28:25	Make sure that `gem install json -v '1.8.6'` succeeds before bundling.`

**Comment by ohayon** [comment]
@Reyske, thanks for sharing that info! Would you mind sharing which fastlane plugins you are using? I also have a one more question to try to shed some more light on whats going on here: Do you manage your own CI box, or are you using a service such as Travis or Circle?

**Comment by pmpandit04** [comment]
I am still getting this error when I run the command 

fastlane add_plugin update_project_codesigning

I am running Xcode 8.2, fastlane and version fastlane 2.18.3. I will really appreciate someone's help on this problem.

**Comment by ohayon** [comment]
Hey @pmpandit04! Would love to help out with this, would you mind sharing the output in your terminal to give a bit more context? Thanks!! 🐙

**Comment by pmpandit04** [comment]
Hi ohayan,

Thanks so much for replying. Here is the output of my error

`current directory: /Users/ppandit/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.0.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk'
In file included from generator.c:1:
In file included from ./../fbuffer/fbuffer.h:5:
In file included from /Users/ppandit/.fastlane/bin/bundle/include/ruby-2.2.0/ruby.h:33:
In file included from /Users/ppandit/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/ruby.h:29:
/Users/ppandit/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/defines.h:26:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
make: *** [generator.o] Error 1`

**Comment by hjanuschka** [comment]
@pmpandit04 looks like you are missing the commandline tools from xcode.

could you try running the following command (once):

```
xcode-select --install
```

**Comment by pmpandit04** [comment]
hjanuschka,

When I run `xcode-select --install`, I get the message `xcode-select: error: command line tools are already installed, use "Software Update" to install updates`. 

Seems like I have command line tools installed. I also verified by typing `gcc. I get the output `clang:` error: no input files`.

I am running Xcode 8.2 on El Capitan (OS X version 10.11.6).

**Comment by jrmybrault** [comment]
Any update on this ?

**Comment by powtac** [comment]
When running `fastlane add_plugin xcake` I do get a very similar to @carlosefonseca  error message:

<details>

```
current directory: /Users/a/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.1.0/ext/json/ext$
/Users/a/.fastlane/bin/bundle/bin/ruby -r ./siteconf20170730-1636-i2lshh.rb extconf.rb
creating Makefile

current directory: /Users/a/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.1.0/ext/json/ext$
make "DESTDIR=" clean

current directory: /Users/a/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.1.0/ext/json/ext$
make "DESTDIR="
compiling generator.c
clang: warning: no such sysroot directory: '/Applications/Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.$
In file included from generator.c:1:
In file included from ./../fbuffer/fbuffer.h:5:
In file included from /Users/a/.fastlane/bin/bundle/include/ruby-2.2.0/ruby.h:33:
In file included from /Users/a/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/ruby.h:29:
/Users/a/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/defines.h:26:10: fatal error: 'stdio.h' fil$
#include <stdio.h>
         ^
1 error generated.
make: *** [generator.o] Error 1
```
</details>

I think the relevant line is 

`clang: warning: no such sysroot directory: '/Applications/Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.$`

Although I do have Xcode 8.3.3 and the latest command line tools installed.

Output of `gcc --version`: 
<details>

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
</details>

**Comment by ohayon** [comment]
Hey @powtac - apologies for the issue. Would you mind sharing the output of `fastlane env`? Would be great to know some more context about your _fastlane_ configuration. Thanks! 🐙

**Comment by powtac** [comment]
@ohayon I updated fastlane to `2.50.0` and ran `fastlane env` and added the output to my original comment. 

Some History: I have played around with fastlane since the beginning. Every some month I updated my installation. But did not used it heavily or some month not at all. Some weeks ago I installed the prepacked OS X installation package. But I'm sure the old installation is still somewhere active on my computer. So in my case it could be that some kind of upgrade path was not meet because there where so long delays in my upgrades.

**Comment by ohayon** [comment]
Ah! Thanks for that info @powtac ! That definitely makes sense. We have been having some issues with plugins in the installation package, so if it isn't a problem for you, I think your fastest route to having a working installation of fastlane with plugins is going to be to just do a `rm -rf ~/.fastlane` and then run `gem update fastlane` followed by installing your plugins. Let me know if that makes sense! 🚀

**Comment by powtac** [comment]
Did the `rm` but then with `gem update fastlane` I get: 

```
Updating installed gems
Updating fastlane
Fetching: fastlane-2.50.0.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
```

The I tried with `sudo` and got 

```
Updating installed gems
Updating fastlane
Fetching: fastlane-2.50.0.gem (100%)
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/bin-proxy
```


Before that I tried to install fastlane via the prepacked package. It was successfully installed. But after running my `add_plugin` command the "no such sysroot directory" error occured again with this error msg:

<details>

```
$ fastlane add_plugin xcake
[20:17:03]: Installing Ruby gem 'fastlane-plugin-appicon'...
Fetching: fastlane-plugin-appicon-0.7.0.gem (100%)
[20:17:27]: Successfully installed 'fastlane-plugin-appicon'
[20:17:27]: Installing Ruby gem 'fastlane-plugin-xcake'...
Fetching: cork-0.3.0.gem (100%)
Fetching: hooks-0.4.1.gem (100%)
Fetching: i18n-0.8.6.gem (100%)
Fetching: thread_safe-0.3.6.gem (100%)
Fetching: tzinfo-1.2.3.gem (100%)
Fetching: activesupport-4.2.9.gem (100%)
Fetching: xcake-0.8.9.gem (100%)
Fetching: fastlane-plugin-xcake-0.1.0.gem (100%)
[20:17:49]: Successfully installed 'fastlane-plugin-xcake'
+------------------------+---------+------------------+
|                    Used plugins                     |
+------------------------+---------+------------------+
| Plugin                 | Version | Action           |
+------------------------+---------+------------------+
| fastlane-plugin-appic  | 0.7.0   | android_appicon  |
| on                     |         | appicon          |
| fastlane-plugin-xcake  | 0.1.0   | xcake            |
+------------------------+---------+------------------+

[20:17:49]: Make sure to commit your Gemfile, Gemfile.lock and Pluginfile to version control
Installing plugin dependencies...
^[[A^[[AGem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/simonbruechner/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.1.0/ext/json/ext/generator
/Users/simonbruechner/.fastlane/bin/bundle/bin/ruby -r ./siteconf20170801-727-1y4wthw.rb
extconf.rb
creating Makefile

current directory:
/Users/simonbruechner/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR=" clean

current directory:
/Users/simonbruechner/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
clang: warning: no such sysroot directory:
'/Applications/Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk'
[-Wmissing-sysroot]
In file included from generator.c:1:
In file included from ./../fbuffer/fbuffer.h:5:
In file included from
/Users/simonbruechner/.fastlane/bin/bundle/include/ruby-2.2.0/ruby.h:33:
In file included from
/Users/simonbruechner/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/ruby.h:29:
/Users/simonbruechner/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/defines.h:26:10: fatal
error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in
/Users/simonbruechner/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.1.0 for
inspection.
Results logged to
/Users/simonbruechner/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/json-2.1.0/gem_make.out

An error occurred while installing json (2.1.0), and Bundler cannot continue.
Make sure that `gem install json -v '2.1.0'` succeeds before bundling.
```
</details>

<br />

Another thing I tried: not calling `add_plugin` which then starts to "Installing plugin dependencies..." and then crashes with the mentioned "json..." error. But simply calling `fastlane` after installation results in 

```
[20:36:30]: Installing Ruby gem 'fastlane-plugin-appicon'...
Fetching: fastlane-plugin-appicon-0.7.0.gem (100%)
[20:36:53]: Successfully installed 'fastlane-plugin-appicon'
[20:36:53]: Installing Ruby gem 'fastlane-plugin-xcake'...
Fetching: cork-0.3.0.gem (100%)
Fetching: hooks-0.4.1.gem (100%)
Fetching: i18n-0.8.6.gem (100%)
Fetching: thread_safe-0.3.6.gem (100%)
Fetching: tzinfo-1.2.3.gem (100%)
Fetching: activesupport-4.2.9.gem (100%)
Fetching: xcake-0.8.9.gem (100%)
Fetching: fastlane-plugin-xcake-0.1.0.gem (100%)
[20:37:16]: Successfully installed 'fastlane-plugin-xcake'
+------------------------+---------+------------------+
|                    Used plugins                     |
+------------------------+---------+------------------+
| Plugin                 | Version | Action           |
+------------------------+---------+------------------+
| fastlane-plugin-appic  | 0.7.0   | android_appicon  |
| on                     |         | appicon          |
| fastlane-plugin-xcake  | 0.1.0   | xcake            |
+------------------------+---------+------------------+

[20:37:16]: -------------------------------------------------
[20:37:16]: --- Step: Verifying required fastlane version ---
[20:37:16]: -------------------------------------------------
[20:37:16]: Your fastlane version 2.50.0 matches the minimum requirement of 1.87.0  ✅
[20:37:16]: ------------------------------
[20:37:16]: --- Step: default_platform ---
[20:37:16]: ------------------------------
[20:37:16]: Name of the lane 'appstore' is already taken by the action named 'appstore'
[20:37:16]: Welcome to fastlane! Here's what your app is setup to do:
+--------+---------------------+-----------------------+
|                Available lanes to run                |
+--------+---------------------+-----------------------+
| Number | Lane Name           | Description           |
+--------+---------------------+-----------------------+
| 1      | ios test            | Runs all the tests    |
| 2      | ios verify          | Verify Xcode          |
| 3      | ios                 | Do several updates    |
|        | third_party_updates |                       |
| 4      | ios clean_up        | Clean up, derivate    |
|        |                     | data, ...             |
| 5      | ios beta            | Submit a new Beta     |
|        |                     | Build to Apple        |
|        |                     | TestFlight This will  |
|        |                     | also make sure the    |
|        |                     | profile is up to date |
| 6      | ios appstore        | Deploy a new version  |
|        |                     | to the App Store      |
| 0      | cancel              | No selection, exit    |
|        |                     | fastlane!             |
+--------+---------------------+-----------------------+
[20:37:16]: Which number would you like run?
0
[20:37:22]: Sending crash report...
[20:37:22]: The stacktrace is sanitized so no personal information is sent.
[20:37:22]: To see what we are sending, look here: /Users/simonbruechner/.fastlane/latest_crash.json
[20:37:22]: Learn more at https://github.com/fastlane/fastlane#crash-reporting
[20:37:22]: You can disable crash reporting by adding `opt_out_crash_reporting` at the top of your Fastfile

[!] Run `fastlane` the next time you need to build, test or release your app 🚀
```

... which looks fine so far. BUT then calling `add_plugin xcake` leads to the mentioned crash again. :-(

**Comment by ohayon** [comment]
Hmmm @powtac - it seems like something could be wrong with your permissions on your machine, running `sudo gem update fastlane` should work with no problem. Are you familiar with [`rbenv`](https://github.com/rbenv/rbenv) or [`rvm`](https://rvm.io/)? I would recommend installing `rbenv` to manage your ruby versions and then you should be able to install fastlane into that ruby with no problem at all. Again, apologies for the issues you are having! Let us know if you have more questions!

**Comment by jamesjara** [comment]
same issue here, this is my output

`
[12:41:58]: Make sure to commit your Gemfile, Gemfile.lock and Pluginfile to version control
Installing plugin dependencies...
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.1.0/ext/json/ext/generator
/Users/xxx/.fastlane/bin/bundle/bin/ruby -r ./siteconf20170813-78509-1iqc4qc.rb extconf.rb
creating Makefile

current directory: /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /Users/xxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
clang: warning: no such sysroot directory: '/Applications/Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk' [-Wmissing-sysroot]
In file included from generator.c:1:
In file included from ./../fbuffer/fbuffer.h:5:
In file included from /Users/xxxx/.fastlane/bin/bundle/include/ruby-2.2.0/ruby.h:33:
In file included from /Users/xxxx/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/ruby.h:29:
/Users/xxxx/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/defines.h:26:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/xxxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.1.0 for inspection.
Results logged to /Users/xxxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/json-2.1.0/gem_make.out

An error occurred while installing json (2.1.0), and Bundler cannot continue.
Make sure that `gem install json -v '2.1.0'` succeeds before bundling.

`

**Comment by frey1esm** [comment]
Any update on this?

**Comment by hyperh** [comment]
Same issue +1

**Comment by dbarros** [comment]
Any news on this? I'm also still seeing this error.

**Comment by RishabhTayal** [comment]
Any update on this?

**Comment by ppamorim** [comment]
Any update?

**Comment by cpetzel** [comment]
Any update??

**Comment by Damnum** [comment]
If that happens when adding a plugin, try `bundle exec fastlane add_plugin <my_plugin>`
