### ISSUE TITLE
[Regression] JSON-dependency change in 2.3.1 causes sudden incompatibilities

### ISSUE THREAD

**Issue by sirlantis** [fastlane/fastlane#7700]
(contd. of #7695)

The change #7674 in 2.3.1 forced a downgrade of `activesupport` from 4.2.7.1 to 4.0.13. Reason: fastlane depends on `< 5` and the latest 4.2.7.1 depends on `json ~> 1.7`. To solve that conflict `gem` reverts to an earlier version that didn't specify `json` as a dependency.

While I have this issue, others are running into this as well already: See #7696

We have to make a choice:

1. Support `system` and `2.4`
2. Support `system` and a more complex user `Gemfile`
   - Existing projects
   - Projects with plugins

I personally think the #7674 change should be reverted to keep users in 2.0 to 2.3 world happy and updated until we find a better solution.

A workaround for 2.4 users would be to do `gem install json -v "2.0.1"` before installing `fastlane`.

---

The two dependencies that are the contradicting forces here are:

- `spec.add_dependency 'activesupport', '< 5'`
  - Transitive dependency through `xcodeproj`
  - Needed to support `system` Ruby since `gem` is stupid and would try to install 5 which requires Ruby 2.2
  - Prevents users from upgrading to newer `activesupport` version.
- `spec.add_dependency 'json', '>= 2.0.1', '< 3.0.0'`
  - Transitive dependency through `activesupport` in later `4.x` releases
  - Needed to support `2.4` since `gem` will try to install `1.8.3` which is not compatible with Ruby 2.0.

**Comment by jinjorge** [comment]
yup, running into this same error too.

```
/Users/secretariat/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2284:in `raise_if_conflicts': Unable to activate activesupport-4.2.6, because json-2.0.2 conflicts with json (>= 1.7.7, ~> 1.7) (Gem::ConflictError)
	from /Users/secretariat/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1407:in `activate'
	from /Users/secretariat/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1441:in `block in activate_dependencies'
	from /Users/secretariat/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1427:in `each'
	from /Users/secretariat/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1427:in `activate_dependencies'
	from /Users/secretariat/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1409:in `activate'
	from /Users/secretariat/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:68:in `block in gem'
	from /Users/secretariat/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:67:in `synchronize'
	from /Users/secretariat/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:67:in `gem'
	from /Users/secretariat/.rvm/gems/ruby-2.3.0/bin/fastlane:22:in `<main>'
	from /Users/secretariat/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/secretariat/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by freboursier-ez** [comment]
Exact same issue here:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts': Unable to activate activesupport-4.2.3, because json-2.0.1 conflicts with json (>= 1.7.7, ~> 1.7) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1212:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:48:in `gem'
	from /usr/local/bin/fastlane:22:in `<main>'
```

**Comment by Mactub07** [comment]
the same

**Comment by kohtenko** [comment]
Rollback to release 2.3.0 of `fastlane` is temporary workaround.
```
sudo gem uninstall fastlane
sudo gem install fastlane --version 2.3.0
```

**Comment by jonlambert** [comment]
The rollback doesn't fix a slightly different json dependancy issue for me when trying to use the S3 action: 

```
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2284:in `raise_if_conflicts': Unable to activate aws-sdk-v1-1.66.0, because json-2.0.2 conflicts with json (~> 1.4) (Gem::ConflictError)
```

**Comment by hartbit** [comment]
Got the same problem here.

**Comment by waltermvp** [comment]
+1

**Comment by zhouhesheng** [comment]
I installed json-2.0.1, but:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts': Unable to activate activesupport-4.2.6, because json-2.0.1 conflicts with json (>= 1.7.7, ~> 1.7) (Gem::LoadError)

**Comment by hjanuschka** [comment]
hey folks can you try curent fastlane version, i think the json issues have been resolved.

**Comment by jinjorge** [comment]
@hjanuschka yes, this is resolved.

**Comment by damirjuretic** [comment]
@hjanuschka for the current fastlane version(2.18.3)  this issue is still not resolved: /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate aws-sdk-v1-1.66.0, because json-2.0.2 conflicts with json (~> 1.4)

**Comment by sirlantis** [comment]
@hjanuschka Looks good to me, too.
