### ISSUE TITLE
error: uninitialized constant Shenzhen::Plugins::S3::Client::AWS

### ISSUE THREAD

**Issue by 7mllm7** [fastlane/fastlane#780]
'Driving' a lane that used to work before fails with:
`error: uninitialized constant Shenzhen::Plugins::S3::Client::AWS`

potentially after upgrading to Fastlane version fastlane 1.36.4.

According to:
http://stackoverflow.com/questions/22826432/uninitialized-constant-aws-nameerror, AND
http://ruby.awsblog.com/post/TxFKSK2QJE6RPZ/Upcoming-Stable-Release-of-AWS-SDK-for-Ruby-Version-2
I think my `aws-sdk` got updated to version 2, where the AWS constant is `Aws` and not `AWS`.

Can anyone confirm that?
If it is the case, then I assume we need to either `require 'aws-sdk-v1'`, or use `s3_client = Aws::S3.new` in `s3.rb`.

**Comment by 7mllm7** [comment]
Ok so it appears that `fastlane` 1.36.4 with the commit https://github.com/fastlane/fastlane/commit/a74c80b20361fe1c832536d066ce2a8a44e6bac0 that updated dependency to `krausefx-shenzhen` 0.14.6 with the commit https://github.com/fastlane/shenzhen/commit/ffea35a1121ffa56f71fc1e517386e158957712c made it not work.

To solve it I rolled back `fastlane` to 1.36.1 `krausefx-shenzhen` to 0.14.15.
Should we start referring `s3.rb` to `::Aws` from now on?

**Comment by KrauseFx** [comment]
Can you share the complete output + stack trace and your `Fastfile`?

**Comment by 7mllm7** [comment]
Odd, after updating to 1.37.0 the problem was resolved, even though the changes had nothing to do with that particular problem.
WEIRD, but I'll take it for now. I'll reopen if I see a reason again.
BTW, amazing job you're doing here!
Thanks

**Comment by KrauseFx** [comment]
:+1:

**Comment by chinnawatp** [comment]
Just want to confirm that this error will occur if you have aws-sdk v2.0+ installed on your mac . Since aws-sdk v2.0+ ,AWS constant is "Aws" and not "AWS".

**Comment by 7mllm7** [comment]
Indeed, I'll try to work on a fix for that

**Comment by 7mllm7** [comment]
I submitted a pull request to krausefx-shenzhen, this is where the problem seems to be...

**Comment by kreeger** [comment]
Not 100% sure if this is related but it _seems_ to be. This is the crashing output of our lane.

```
[23:16:23]: ----------------
[23:16:23]: --- Step: s3 ---
[23:16:23]: ----------------
[23:16:23]: krausefx-ipa distribute:s3 -f "/path/to/our/binary.ipa" -d "/path/to/our/binary.app.dSYM.zip" -a "<S3_KEY_REDACTED>" -s "<S3_SECRET_REDACTED>" -b "<S3_BUCKET>" -P "v3.0.4/"
[23:16:23]: [SHELL COMMAND]: krausefx-ipa distribute:s3 -f "/path/to/our/binary.ipa" -d "/path/to/our/binary.app.dSYM.zip" -a "<S3_KEY_REDACTED>" -s "<S3_SECRET_REDACTED>" -b "<S3_BUCKET>" -P "v3.0.4/"
[23:16:24]: [SHELL]: invalid option: -f
[23:16:24]: [SHELL]: /Users/ben/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/krausefx-shenzhen-0.14.6/lib/shenzhen/plugins/s3.rb:1:in `require': cannot load such file -- aws-sdk (LoadError)
[23:16:24]: [SHELL]: from /Users/ben/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/krausefx-shenzhen-0.14.6/lib/shenzhen/plugins/s3.rb:1:in `<top (required)>'
[23:16:24]: [SHELL]: from /Users/ben/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/krausefx-shenzhen-0.14.6/lib/shenzhen/commands.rb:9:in `require'
[23:16:24]: [SHELL]: from /Users/ben/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/krausefx-shenzhen-0.14.6/lib/shenzhen/commands.rb:9:in `<top (required)>'
[23:16:24]: [SHELL]: from /Users/ben/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/krausefx-shenzhen-0.14.6/bin/krausefx-ipa:25:in `require'
[23:16:24]: [SHELL]: from /Users/ben/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/krausefx-shenzhen-0.14.6/bin/krausefx-ipa:25:in `<top (required)>'
[23:16:24]: [SHELL]: from /Users/ben/.rbenv/versions/2.2.0/bin/krausefx-ipa:23:in `load'
[23:16:24]: [SHELL]: from /Users/ben/.rbenv/versions/2.2.0/bin/krausefx-ipa:23:in `<main>'
[23:16:24]: [SHELL]: from /Users/ben/.rbenv/versions/2.2.0/bin/ruby_executable_hooks:15:in `eval'
[23:16:24]: [SHELL]: from /Users/ben/.rbenv/versions/2.2.0/bin/ruby_executable_hooks:15:in `<main>'
[23:16:24]: Variable Dump:
[23:16:24]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios release_build", :IPA_OUTPUT_PATH=>"/path/to/our/binary.ipa", :DSYM_OUTPUT_PATH=>"/path/to/our/binary.app.dSYM.zip"}
[23:16:24]: Exit status of command 'krausefx-ipa distribute:s3 -f "/path/to/our/binary.ipa" -d "/path/to/our/binary.app.dSYM.zip" -a "<S3_KEY_REDACTED>" -s "<S3_SECRET_REDACTED>" -b "<S3_BUCKET>" -P "v3.0.4/"' was 1 instead of 0.
invalid option: -f
/Users/ben/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/krausefx-shenzhen-0.14.6/lib/shenzhen/plugins/s3.rb:1:in `require': cannot load such file -- aws-sdk (LoadError)
    from /Users/ben/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/krausefx-shenzhen-0.14.6/lib/shenzhen/plugins/s3.rb:1:in `<top (required)>'
    from /Users/ben/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/krausefx-shenzhen-0.14.6/lib/shenzhen/commands.rb:9:in `require'
    from /Users/ben/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/krausefx-shenzhen-0.14.6/lib/shenzhen/commands.rb:9:in `<top (required)>'
    from /Users/ben/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/krausefx-shenzhen-0.14.6/bin/krausefx-ipa:25:in `require'
    from /Users/ben/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/krausefx-shenzhen-0.14.6/bin/krausefx-ipa:25:in `<top (required)>'
    from /Users/ben/.rbenv/versions/2.2.0/bin/krausefx-ipa:23:in `load'
    from /Users/ben/.rbenv/versions/2.2.0/bin/krausefx-ipa:23:in `<main>'
    from /Users/ben/.rbenv/versions/2.2.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/ben/.rbenv/versions/2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

And our Fastfile:

```
platform :ios do
  desc "Generate a production build and upload to Amazon S3."
  lane :release_build do
    if !ENV["S3_SECRET_ACCESS_KEY"]
      puts "FATAL ERROR: Must have S3_ACCESS_KEY and S3_SECRET_ACCESS_KEY available in ENV."
      puts "Exiting."
      exit
    end

    template_dir = File.join(Dir.pwd, "templates")
    puts "Using template dir #{template_dir}"

    gym(workspace: "NameOfApp.xcworkspace",
        configuration: "Release",
        scheme: "NameOfApp-Production",
        output_name: "NameOfApp.ipa",
        use_legacy_build_api: true,
        clean: true)

    bucket_name = "<S3_BUCKET>"
    released_version = "v#{version_number}"
    s3(access_key: ENV['S3_ACCESS_KEY'],
       secret_access_key: ENV['S3_SECRET_ACCESS_KEY'],
       bucket: bucket_name,
       path: "#{released_version}/",
       version_template_path: File.join(template_dir, "s3_version_template.json.erb"),
       version_file_name: "#{released_version}/version.json",
       html_template_path: File.join(template_dir, "s3_html_template.html.erb"),
       html_file_name: "#{released_version}/index.html")

    # ... a few notification bits, too
  end
end
```

That said, rolling back to v1.36.0 of `fastlane` still doesn't help.

**Comment by frobichaud** [comment]
+1, we're getting invalid parameter -f like @kreeger above since we upgraded to fastlane 1.4.1

**Comment by truth3** [comment]
@7mllm7 Many thanks for sharing.. I built fastlane and shenzhen with your changes and added the region parameter to the `s3` line in my Fastfile. I am back in business with pushing enterprise builds to S3 using latest fastlane relase :+1:

**Comment by truth3** [comment]
@kreeger @frobichaud If you want to get on the latest code and still have S3 work, you should be able to uninstall fastlane and krausefx-shenzhen, fork each and then make the changes @7mllm7 suggested. Once you build both gems post changes and install them, you will need to add `region` as a parameter in your fastfile and you should be all set.

Hope that helps

**Comment by Damien-B** [comment]
@KrauseFx Getting same error as @kreeger, solution is to implement @7mllm7 fix ? Is it going to be added in Fastlane at some point ?

**Comment by lynxluna** [comment]
Do we strictly need `krausefx-shenzhen` to upload to S3? I've written a pretty rough replacement only for `s3` action. If you don't mind I'll open PR once I clean the code up to meet fastlane's standard.

**Comment by dbachrach** [comment]
@KrauseFx Any resolution on this one? This broke our S3 builds, and since fastlane pins to '>= 0.14.6', we can't manually override to 0.14.5.

Thanks

**Comment by 7mllm7** [comment]
FWIW, the changes in my pull request should solve it. What do we need to do to merge it?

**Comment by va3093** [comment]
Hey guys, any progress on this issue. I downgraded my aws to 1.x and am still getting this error?

**Comment by chinnawatp** [comment]
FYI, what i did and this problem gone is "$ gem install shenzhen".

**Comment by HarrisonJackson** [comment]
Thanks @chinnawatp - fixed for me as well - that was quite a headbanger till I found this issue.

**Comment by 7mllm7** [comment]
But @chinnawatp, woun't your solution break something, as `fastlane` requires `krausefx-shenzhen` and not the original `shenzhen`?

What I found to solve it was like said before, keeping `aws-sdk` in version 1. If you already updated to version 2, then you should:
 1. `gem list aws-sdk`, you should see `aws-sdk (2.2.8)` or some other version 2.
 1. `gem uninstall aws-sdk` will remove it.
 1. `gem install aws-sdk -v 1.66.0` will install version 1.

So although this solves it for me, I'm still curious what will be when `aws-sdk 1.66.0` will be deprecated or we need some version 2 functionality, then I guess [my PR](https://github.com/fastlane/fastlane/pull/810) that tries to fix it will be useful.

**Comment by jaroslavas** [comment]
I have the same error with aws-sdk version 2. Log number is: `119bf1751a0a2ad04a182ff92bc87958`

Running `gem uninstall aws-sdk` and selecting version 2 (a have version 1 also installed) fixes the issue. But it reappear after every `gem update`.

**Comment by siong1987** [comment]
this will be helpful: https://github.com/fastlane/shenzhen/pull/6 - if we specifically pick `aws-1.0` for the `shenzhen` gem, it won't mess with `gem update`.

**Comment by tettoffensive** [comment]
I just updated fastlane today and this stopped working for me. Any idea why?

```
/Library/Ruby/Gems/2.0.0/gems/krausefx-shenzhen-0.14.7/lib/shenzhen/plugins/s3.rb:7:in `initialize': uninitialized constant Shenzhen::Plugins::S3::Client::AWS (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/krausefx-shenzhen-0.14.7/lib/shenzhen/plugins/s3.rb:104:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/krausefx-shenzhen-0.14.7/lib/shenzhen/plugins/s3.rb:104:in `block (2 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'
```

```
$ gem list aws-sdk

*** LOCAL GEMS ***

aws-sdk (2.3.4, 1.64.0)
aws-sdk-core (2.3.4)
aws-sdk-resources (2.3.4)
aws-sdk-v1 (1.66.0, 1.64.0)

$ gem list krausefx-shenzhen

*** LOCAL GEMS ***

krausefx-shenzhen (0.14.7)

$ gem list fastlane

*** LOCAL GEMS ***

fastlane (1.89.0, 1.81.0, 1.68.0, 1.60.0, 1.59.0, 1.49.0)
fastlane_core (0.43.5, 0.41.2, 0.39.0, 0.36.5, 0.36.4, 0.32.0)
```

```
s3(
        # All of these are used to make Shenzhen's `ipa distribute:s3` command
        access_key: ENV['S3_ACCESS_KEY'],               # Required from user.
        secret_access_key: ENV['S3_SECRET_ACCESS_KEY'], # Required from user.
        region: 'us-west-2',
        bucket: 'mybucket',
        ipa: 'MyApp.ipa',
        dsym: 'MyApp.app.dSYM.zip',
        upload_metadata: 'true'                         # Upload .plist
       )
```

**Comment by 7mllm7** [comment]
@tettoffensive, try what I suggested in a previous commend:
Uninstall `aws-sdk` altogether (version 2 AND 1, including `aws-sdk-v1`), and then `gem install aws-sdk -v 1.66.0`.
Basically you need `aws-sdk` version 1 installed and only it (unless you have dependencies in other projects / you know what you're doing with ruby environments).

**Comment by TKBurner** [comment]
@tettoffensive, Can you let me know if @7mllm7 help cleared up things for you? Thanks!

@7mllm7 Thanks for helping! 👍
