### ISSUE TITLE
Launch arguments not working in Snapshot

### ISSUE THREAD

**Issue by Sjoerdjanssenen** [fastlane/fastlane#8768]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I included one launch argument in my snapfile, but the app doesn't see it. When I launch the app from Xcode with the same launch argument everything works as expected. And below you can see my snapfile:

    # Uncomment the lines below you want to change by removing the # in the beginning

    # A list of devices you want to take the screenshots from
    devices([
       "iPhone 6",
       "iPhone 6 Plus",
       "iPhone 5",
       "iPad Pro (9.7 inch)",
       "iPad Pro (12.9 inch)"
    ])

    languages([
      "en-US",
      "nl-NL",
      "de-DE"
    ])

    # clear_previous_screenshots true

    # Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
    launch_arguments(["-is_demo"])

    # The name of the scheme which contains the UI Tests
    scheme "Pods-myappUITests"

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

    /Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
    invalid option: --capture_output

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.4                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.4 (16E195)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3                                                            |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.96.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods

  end

  desc "Take screenshots"
  lane :screenshot do
    snapshot(
       devices: [
          "iPhone 7",
          "iPhone 7 Plus",
          "iPhone 5",
          "iPad Pro (9.7 inch)",
          "iPad Pro (12.9 inch)"
       ],
       launch_arguments: ["-app_uitests websitescreenshots"],
       output_directory: "./screenshotsweb"
     )
	    frameit
	     deliver
  end


  desc "Runs all the tests"
  lane :test do
    scan(
      scheme: "myapp"
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "myapp") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "myapp") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.company.app" # The bundle identifier of your app
apple_id "my@appleid.com" # Your Apple email address

team_id "123456"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.25.0  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.0.1     |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| i18n                      | 0.8.1        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.6        |
| activesupport             | 4.2.8        |
| json                      | 2.0.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.3        |
</details>

*generated on:* **2017-04-04**
</details>

**Comment by hjanuschka** [comment]
can you try uninstalling fastimage, and then reinstall fastlane?

or even better - choose another installation method here: https://docs.fastlane.tools/#choose-your-installation-method (brew, rvm/rbenv, single-download) - looks like you are using apple-system-ruby which is quiet outdated, and you probably run into other problems once that is fixed.

**Comment by ohayon** [comment]
Hey @Sjoerdjanssenen, could you try setting up a `Snapfile` in the same directory as your `Fastfile`? Before we go in and try to make a fix for this, I'm curious if your launch arguments will get correctly passed through if you define them in a `Snapfile` as in this related issue from last year: https://github.com/fastlane/fastlane/issues/4202.

Let us know if this works out for you! Thanks! 🐙

**Comment by Sjoerdjanssenen** [comment]
Hey @ohayon, I already included my snapfile which is indeed located in the same folder as my fastfile.

**Comment by ohayon** [comment]
Ah, my apologies, I missed that! Could you add a value to the `-is_demo` launch argument? Maybe change that to say `-is_demo true`?

**Comment by Sjoerdjanssenen** [comment]
Thanks for the reply. I tried this, but it didn't solve it. 😞

**Comment by Wojcik** [comment]
I have the similar problem. No languages and no launch arguments. Swift helper can't read files to get those
This is an output from test session logs:

```
-path prefix (/Users/XXX/Library/Caches/tools.fastlane)

Couldn't detect/set language...
Couldn't detect/set locale...
Couldn't detect/set launch_arguments...
```

**Comment by Sjoerdjanssenen** [comment]
Good that you managed to fix it. What steps did you take?

**Comment by Wojcik** [comment]
Just wrapped simulatorHostHome in pathPrefix function
`guard let homeDirUrl = URL(string: "file://\(simulatorHostHome)") else {`

**Comment by wryphonedev** [comment]
I have a PR open for this issue as I discovered it earlier tofay

**Comment by KrauseFx** [comment]
This issue is now resolved with the most recent release, right?

**Comment by deepumukundan** [comment]
Getting this same warning with Ruby 2.4.1 and Fastlane 2.45.0. Not blocking out lanes from running but would like to understand/fix this if possible

**Comment by evilDave** [comment]
Same here (as @deepumukundan) - ```ruby 2.0.0p648``` which I guess is the system installed one...
```brew install ruby``` gives me ```ruby 2.4.1p111```, but the problem is still there.
```sudo gem install fastlane``` moves fastlane to ```/usr/local/lib/ruby/gems/2.4.0``` and the error is gone.

**Comment by bradvandyk** [comment]
@evilDave this fixed for me too and lots of other issues I was having...thank you!
