### ISSUE TITLE
Two Factor Authentication - token always expired

### ISSUE THREAD

**Issue by shiroganee** [fastlane/fastlane#9044]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Because of Two Factor Authentication I run through spaceauth to get the token which later is included in FASTLANE_SESSION. Eventho I did what is written in docs the message that is below is still present after running it on the CI server. If I will "break" value on purpose it will get me a different message that something is not valid etc. so it seems that it is read by the process.
> Two Factor Authentication for account 'kamil@xxx.com' is enabled
> Your session cookie has been expired.
> Please enter the 6 digit code: +------------------+----------+

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.12.2                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.7  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.0.1     |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types                | 1.25.1       |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.0.2        |
| openssl                   | 2.0.3        |
| io-console                | 0.4.6        |
</details>

]

**Comment by KrauseFx** [comment]
Hey @shiroganee, thanks for submitting this issue. What CI system do you use? Can it be that it's related to the environment variable being somehow escaped, and therefore not properly used?

**Comment by KrauseFx** [comment]
Do you mind sharing how the problem was solved, so others can learn from it too? 👍

**Comment by shiroganee** [comment]
https://discuss.bitrise.io/t/two-factor-authentication-for-apple-id-itunes-connect-testflight-deploy/1180/14 

This link has whole discussion (as I find it more useful to actually copy the link rather than long discussion). Big kudos to Viktor for really quick responses.

but tl;dr for anyone having same problem: it is better to copy FASTLANE_SESSION directly in Bitrise.yml rather than use the UI editor.

**Comment by shiroganee** [comment]
and for clarying the problem still occurs @KrauseFx  but this one is only related to 

> Your session cookie has been expired.
> Please enter the 6 digit code: +------------------+----------+

And it seems like it is Fastlane related / 2FA related.

**Comment by lucamaraschi** [comment]
@shiroganee I never even got to the session expired message but it looks like the ```FASTLANE_SESSION``` is ignored by fastlane...

**Comment by shiroganee** [comment]
@lucamaraschi I dunno if that is the case. I would believe that
> FASTLANE_SESSION 

if ignored would give a different message - I gave it a try, when i didn't include FASTLANE_SESSION it simply asked me about auth code.

Though I created a new account, without 2FA and it worked straight away. So I can asume that it is something with Apple being Apple rather than with Fastlane. To be honest, I truly have no idea what could be a reason for that odd message, probably somewhere something needed to be clicked on Apple portal? Truly no idea.

**Comment by KrauseFx** [comment]
Okay cool, is it ok to close this issue?

**Comment by shiroganee** [comment]
ya go ahead @KrauseFx  as this is pretty much unknown how and where the problem lied. probably something with Apple

**Comment by KrauseFx** [comment]
Actually we worked on this, which should help https://github.com/fastlane/fastlane/pull/9266
