### ISSUE TITLE
Fastlane supply fails with undefined method `timeout_sec='

### ISSUE THREAD

**Issue by Buuhuu** [fastlane/fastlane#9501]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm trying to send a build and signed apk file to google play.

##### Complete output when running fastlane, including the stack trace and command used
```
Running shell script
+ LANG=en_US.UTF-8
+ LANGUAGE=en_US.UTF-8
+ LC_ALL=en_US.UTF-8
+ ANDROID_HOME=/Users/jenkins/Software/AndroidSDK/
+ FOR_ENV=TEST
+ fastlane supply --json_key **** --track alpha --apk build/CUSTOMER_APP.apk --package_name someapppackagename
/Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here

+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                           [32mSummary for supply 2.39.0[0m                                                                                           |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| json_key                | **** |
| track                   | alpha                                                                                                                                                                               |
| apk                     | build/CUSTOMER_APP.apk                                                                                                                                                         |
| package_name            | ch.someapppackagename                                                                                                                                                             |
| rollout                 | 0.1                                                                                                                                                                                 |
| skip_upload_apk         | false                                                                                                                                                                               |
| skip_upload_metadata    | false                                                                                                                                                                               |
| skip_upload_images      | false                                                                                                                                                                               |
| skip_upload_screenshots | false                                                                                                                                                                               |
| validate_only           | false                                                                                                                                                                               |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+


Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new

/Library/Ruby/Gems/2.0.0/gems/fastlane-2.39.0/supply/lib/supply/client.rb:71:in `initialize': [31m[!] undefined method `timeout_sec=' for #<Google::Apis::RequestOptions:0x007fcd53548648>[0m (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.39.0/supply/lib/supply/client.rb:36:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.39.0/supply/lib/supply/client.rb:36:in `make_from_config'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.39.0/supply/lib/supply/uploader.rb:174:in `client'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.39.0/supply/lib/supply/uploader.rb:6:in `perform_upload'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.39.0/supply/lib/supply/commands_generator.rb:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.39.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:39:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.39.0/supply/lib/supply/commands_generator.rb:59:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.39.0/supply/lib/supply/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.39.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.39.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```
### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.5                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.5 (16F73)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3.3                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.39.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| multi_json                | 1.12.1       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| excon                     | 0.56.0       |
| plist                     | 3.3.0        |
| faraday                   | 0.12.1       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| bundler                   | 1.15.1       |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.2.1        |
</details>

*generated on:* **2017-06-16**
</details>

**Comment by ohayon** [comment]
Hey @Buuhuu, apologies for the inconvenience! We are about to push out a release with a fix!

**Comment by erchenger** [comment]
I feel like I may be having the same problem. The beginning of the stack trace isn't the same but it fails in the same place for me.
```
/Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
/Library/Ruby/Gems/2.0.0/gems/bundler-1.13.1/lib/bundler/rubygems_ext.rb:45:in `full_gem_path': uninitialized constant Bundler::Plugin::API::Source (NameError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1391:in `contains_requirable_file?'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `block in require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:823:in `block in each'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `find'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `require'
        from /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.1/lib/bundler/plugin/api/source.rb:2:in `<top (required)>'
        from /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.1/lib/bundler/rubygems_ext.rb:45:in `full_gem_path'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1391:in `contains_requirable_file?'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `block in require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:823:in `block in each'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `find'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `require'
        from /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.1/lib/bundler.rb:11:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.39.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:5:in `<class:PluginManager>'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.39.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:4:in `<module:Fastlane>'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.39.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:3:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.39.0/fastlane/lib/fastlane/plugins/plugins.rb:9:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.39.0/fastlane/lib/fastlane.rb:22:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.39.0/fastlane/lib/fastlane/cli_tools_distributor.rb:18:in `take_off'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.39.0/bin/fastlane:20:in `<top (required)>'
        from /usr/local/bin/fastlane:23:in `load'
        from /usr/local/bin/fastlane:23:in `<main>'
```

Am I wrong that they are similar?

**Comment by ohayon** [comment]
Hey @erchenger we just pushed 2.39.1, would you mind checking to see if that fixed your issue too?

**Comment by erchenger** [comment]
@ohayon totally fixed it. In other news I have updated ruby on my machine and yet it still shows as old version. (╯°□°）╯︵ ┻━┻

What was the fix if you don't mind me asking?

**Comment by vdelricco** [comment]
Had this same issue, and re-testing with 2.39.1 fixed the problem. Thanks @ohayon!

**Comment by ohayon** [comment]
Glad you all are back to working states! @erchenger looks like it was some API renaming https://github.com/fastlane/fastlane/pull/9499.

I am going to close this issue for now, but please feel free to continue conversation, and if there are other problems we can reopen it if necessary! 🚀
