### ISSUE TITLE
Google Api Error: multiApkShadowedActiveApk: Version 4145 of this app can not be downloaded...

### ISSUE THREAD

**Issue by GeoffreyPlitt** [fastlane/fastlane#9574]
Our deploys were working fine for a long time and suddenly started failing with this error. I don't understand what's wrong, or how to fix.

```
fastlane supply --apk ./android/app/build/outputs/apk/app-release.apk --json_key ./creds_android/playstore_jsonkey.json --track beta --package_name com.stardust

+-------------------------+-------------------------------------------------+
|                         Summary for supply 2.41.0                         |
+-------------------------+-------------------------------------------------+
| apk                     | ./android/app/build/outputs/apk/app-release.apk |
| json_key                | ./creds_android/playstore_jsonkey.json          |
| track                   | beta                                            |
| package_name            | com.stardust                                    |
| rollout                 | 0.1                                             |
| skip_upload_apk         | false                                           |
| skip_upload_metadata    | false                                           |
| skip_upload_images      | false                                           |
| skip_upload_screenshots | false                                           |
| validate_only           | false                                           |
| check_superseded_tracks | false                                           |
+-------------------------+-------------------------------------------------+

[15:01:06]: Preparing apk at path './android/app/build/outputs/apk/app-release.apk' for upload...
[15:01:10]: Updating track 'beta'...
[15:01:10]: Uploading all changes to Google Play...
[15:01:13]: Sending crash report...
[15:01:13]: The stacktrace is sanitized so no personal information is sent.
[15:01:13]: To see what we are sending, look here: /Users/distiller/.fastlane/latest_crash.json
[15:01:13]: Learn more at https://github.com/fastlane/fastlane#crash-reporting
[15:01:13]: You can disable crash reporting by adding `opt_out_crash_reporting` at the top of your Fastfile

[!] Google Api Error: multiApkShadowedActiveApk: Version 4145 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.

fastlane supply --apk ./android/app/build/outputs/apk/app-release.apk --json_key ./creds_android/playstore_jsonkey.json --track beta --package_name com.stardust returned exit code 1

Action failed: fastlane supply --apk ./android/app/build/outputs/apk/app-release.apk --json_key ./creds_android/playstore_jsonkey.json --track beta --package_name com.stardust
```

**Comment by GeoffreyPlitt** [comment]
Sorry, I thought the above was enough. Here it is:
```
distiller-build-59:~ distiller$ fastlane env
[15:19:06]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                           |
| ------------------- | ----------------------------------------------- |
| OS                  | 10.11.6                                         |
| Ruby                | 2.3.1                                           |
| Bundler?            | false                                           |
| Git                 | git version 2.10.2                              |
| Installation Source | /opt/rubies/ruby-2.3.1/bin/fastlane             |
| Host                | Mac OS X 10.11.6 (15G1108)                      |
| Ruby Lib Dir        | /opt/rubies/ruby-2.3.1/lib                      |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                     |
| Is contained        | false                                           |
| Xcode Path          | /Applications/Xcode-8.2.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                           |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | 🚫 Update availaible |
| spaceship           | 0.38.1  | 🚫 Update availaible |
| fastlane_core       | 0.57.1  | 🚫 Update availaible |
| deliver             | 1.16.0  | 🚫 Update availaible |
| snapshot            | 1.16.4  | 🚫 Update availaible |
| frameit             | 3.0.0   | 🚫 Update availaible |
| pem                 | 1.4.0   | 🚫 Update availaible |
| cert                | 1.4.4   | 🚫 Update availaible |
| sigh                | 1.11.2  | 🚫 Update availaible |
| produce             | 1.3.1   | 🚫 Update availaible |
| gym                 | 1.12.1  | 🚫 Update availaible |
| pilot               | 1.12.1  | 🚫 Update availaible |
| scan                | 0.14.2  | 🚫 Update availaible |
| supply              | 0.8.0   | 🚫 Update availaible |
| match               | 0.11.0  | 🚫 Update availaible |
| screengrab          | 0.5.6   | 🚫 Update availaible |
| fastlane            | 1.110.0 | 🚫 Update availaible |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| faraday                   | 0.10.0       |
| faraday_middleware        | 0.10.1       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| xcode-install             | 2.0.9        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| rubyzip                   | 1.1.7        |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.57.1       |
| bundler                   | 1.13.6       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| io-console                | 0.4.6        |
| plist                     | 3.2.0        |
</details>


*generated on:* **2017-06-23**
</details>
[15:19:18]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

#######################################################################
# fastlane 2.41.0 is available. You are on 1.110.0.
# It is recommended to use the latest version.
# Please update using `sudo gem update fastlane`.
#######################################################################

2.41.0 snapshot support for Xcode 9
* [snapshot] Add support for Xcode 9 (#9559) via David Ohayon
* Add calculating of fastlane plugin scores and nice rendering on docs page (#9511) via Felix Krause
* Pilot: Allow '~' in ipa path (#9481) via Nick
* Pass app_identifier through to precheck (#9566) via Joshua Liebowitz
* support Xcode 9 new export options when using sigh (#9449) via igor-makarov

2.40.0 Introducing fastlane precheck
* New: _fastlane precheck_: Check your app's metadata before submitting to App Review
* Allow to skip updating of an app version under 'Prepare for submission' (#9469) via Victor Ronin
* Apk check superseded tracks (#9459) via Marcelo Oliveira
* Fixed issue where deliver would not print appropriate error messages after failing to upload metadata (#9515) via Colin McDonnell

2.39.2 Improvements
* [increment_build_number] Fix issue when incrementing versions and specifying a `xcodeproj` value (#9508) via Hawken Rives
* [supply] Mask json_key_data in summary table (#9507) via Stanislav Shakirov
* [snapshot] Show message that Xcode 9 isn't supported yet (#9468) via Felix Krause

To see all new releases, open https://github.com/fastlane/fastlane/releases

Please update using `sudo gem update fastlane`
distiller-build-59:~ distiller$ 
```

We are not on the latest, since upgrading in the past led to instabilities.

**Comment by capyvara** [comment]
Dupe of #6791 and it has been fixed on 2.40.0 (Apk check superseded tracks #9459), you also have to use --check_superseded_tracks to allow the feature to work.

**Comment by keplersj** [comment]
I'm running 2.42.0 and I'm still getting this error while using `check_superseded_tracks`.  Any tips?

**Comment by capyvara** [comment]
I think is better to open a new issue with the log so I can help diagnose it.

**Comment by owurman** [comment]
@keplersj Did you figure this out or open a new issue? I'm also running 2.55 with check_superseded_tracks:true and hitting this when I have a beta version out.

**Comment by corneliu-serediuc** [comment]
Also getting this error with the following parameters:

```
  # Deploy build to the Alpha Channel
  supply(
    json_key: GOOGLE_PLAY_JSON_KEY,
    package_name: ANDROID_APPLICAITON_IDENTIFIER,
    apk: apk,
    track: "alpha",
    # metadata_path: "metadata/google-play",
    skip_upload_metadata: true,
    skip_upload_images: true,
    skip_upload_screenshots: true,
    check_superseded_tracks: true,
    validate_only: false
  )
```
Also the error:

`[!] Google Api Error: multiApkDowngradedDevice: Devices with version 355826070 of this app would be downgraded to version 29 if they met the following criteria: [(API_LEVEL in range 21-0 AND RELEASE_TRACK containing any of each of [[ALPHA]] AND SCREENS containing any of each of [[small, normal, large, xlarge]] AND NATIVE_PLATFORM containing any of each of [[armeabi-v7a]] AND GL_ES_VERSION in range 131072-0 AND FEATURES containing all of [android.hardware.FAKETOUCH, android.hardware.LOCATION, android.hardware.CAMERA, android.hardware.camera.FLASH])].`

**Comment by corneliu-serediuc** [comment]
Why was this issue closed if it was never adressed?

**Comment by capyvara** [comment]
You error multiApkDowngradedDevice is not the same error as multiApkShadowedActiveApk that the --check_superseded_tracks is trying to avoid.

**Comment by corneliu-serediuc** [comment]
Thank you @capyvara. You are right.

**Comment by andreyslyusar** [comment]
I am running `fastlane 2.63.0` and getting 
```
Google Api Error: multiApkShadowedActiveApk: Version 106 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.
``` 
with next supply configuration:
```
+-------------------------+---------------------------------------+
|                    [32mSummary for supply 2.63.0[0m                    |
+-------------------------+---------------------------------------+
| track                   | beta                                  |
| package_name            | *******                    |
| json_key_data           | ********                              |
| check_superseded_tracks | true                                  |
| apk                     | app/build/outputs/apk/app-release.apk |
| skip_upload_apk         | false                                 |
| skip_upload_metadata    | false                                 |
| skip_upload_images      | false                                 |
| skip_upload_screenshots | false                                 |
| validate_only           | false                                 |
+-------------------------+---------------------------------------+
```

Am I missing something? Thanks in advance.

**Comment by andreyslyusar** [comment]
@capyvara any ideas?

**Comment by capyvara** [comment]
@andreyslyusar Can we have the full log?

**Comment by andreyslyusar** [comment]
@capyvara 

```
...
[13:11:19]: ▸ [35mBUILD SUCCESSFUL[0m
[13:11:19]: ▸ [35mTotal time: 8 mins 1.229 secs[0m
[13:11:19]: Cruising back to lane 'android deploy' 🚘
[13:11:19]: [32m--------------------[0m
[13:11:19]: [32m--- Step: supply ---[0m
[13:11:19]: [32m--------------------[0m

+-------------------------+---------------------------------------+
|                    [32mSummary for supply 2.63.0[0m                    |
+-------------------------+---------------------------------------+
| track                   | beta                                  |
| package_name            | xxx                    |
| json_key_data           | ********                              |
| check_superseded_tracks | true                                  |
| apk                     | app/build/outputs/apk/app-release.apk |
| skip_upload_apk         | false                                 |
| skip_upload_metadata    | false                                 |
| skip_upload_images      | false                                 |
| skip_upload_screenshots | false                                 |
| validate_only           | false                                 |
+-------------------------+---------------------------------------+

[13:11:22]: Preparing apk at path 'app/build/outputs/apk/app-release.apk' for upload...
[13:11:28]: Updating track 'beta'...
[13:11:28]: Checking superseded tracks...
[13:11:29]: Uploading all changes to Google Play...
[13:11:36]: [32m----------------------------[0m
[13:11:36]: [32m--- Step: reset_git_repo ---[0m
[13:11:36]: [32m----------------------------[0m
[13:11:36]: [36m$ git reset --hard HEAD[0m
[13:11:36]: ▸ [35mHEAD is now at 1bbf992 Merge pull request #103 in FNX/app-react-native from feature/APP-300 to develop[0m
[13:11:36]: [36m$ git clean -qfdx[0m
[13:11:36]: [32mGit repo was reset and cleaned back to a pristine state.[0m
+-----------------------------+--------------------------------------------------------------------------------------------------+
|                                                          [33mLane Context[0m                                                          |
+-----------------------------+--------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM            | android                                                                                          |
| PLATFORM_NAME               | android                                                                                          |
| LANE_NAME                   | android deploy                                                                                   |
| GIT_REPO_WAS_CLEAN_ON_START | true                                                                                             |
| GRADLE_ALL_APK_OUTPUT_PATHS | ["/Users/utv/workspace/mobile-app/deploy/android/app/build/outputs/apk/app-release.apk"] |
| GRADLE_APK_OUTPUT_PATH      | /Users/utv/workspace/mobile-app/deploy/android/app/build/outputs/apk/app-release.apk     |
+-----------------------------+--------------------------------------------------------------------------------------------------+
[13:11:36]: [31mGoogle Api Error: multiApkShadowedActiveApk: Version 106 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | ensure_git_status_clean             | 0           |
| 4    | Switch to android build_app lane    | 0           |
| 5    | gradle                              | 482         |
| 💥   | [31msupply[0m                              | 15          |
| 7    | reset_git_repo                      | 0           |
+------+-------------------------------------+-------------+

[13:11:36]: [31mfastlane finished with errors[0m
[31m
[!] Google Api Error: multiApkShadowedActiveApk: Version 106 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.[0m

[32m#######################################################################[0m
[32m# fastlane 2.64.0 is available. You are on 2.63.0.[0m
[32m# You should use the latest version.[0m
[32m# Please update using `bundle update fastlane`.[0m
[32m#######################################################################[0m

[32m2.64.0 iPhone X support and more[0m
* Support App Preview for iPhone X (#10799) via Fumiya Nakamura
* Add auto_release_date option to deliver (#10768) via Joshua Liebowitz
* Support for iPhone X in frameit (#10533) via Alfredo Delli Bovi
* Snapshot - fix String character count deprecation warning in SnapshotHelper (#10761) via xta
* Commit version bump enhancements (#9483) via Jimmy Dee
* [Deliver] Fix uses idfa limits tracking (#10715) via Jorge
* Allow snapshots on older iOS versions when no specified/latest found (see #10211) (#10755) via Ely Alvarado
* In two-stage Hockey action, do not set the status to 2 (downloadable) until after the app is uploaded (#10706) via Steve Rubin
* Fix colon styling in SnapshotHelper (#10736) via Sampsa Kuronen
* Fixes image reference in pilot's README. (#10804) via Péter Krassay
* Fixed instruction for update plugin (#10809) via Rishabh Tayal
* Fix mismatched <th> tags in docs_generator (#10797) via David Vanoni
* Allow in app purchases check to be disabled via deliver (#10758) via Iulian Onofrei
* Remove redundant let declaration for a discardable result (#10762) via Sampsa Kuronen
* Update AppfileTemplate (#10759) via Aaron Brager
* Added is_string: false to active_days_limit config entry (#10763) via vspac
* issue template fix (#10673) via Rishabh Tayal

[32mPlease update using `bundle update fastlane`[0m
error Command failed with exit code 1.
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
```

Are there `verbose` flag for `supply`?

**Comment by capyvara** [comment]
I'll add some verbosity to the command and post a PR later.

For now can you use the google_play_track_version_codes action and show me the apk versions on all the tracks? production, rollout, beta, alpha?

**Comment by aegis123** [comment]
I'm having the same issue with with uploading from my CI, the APK that is being uploaded to production has an higher versionCode the the one released in Alpha. When uploading through the dashboard everything works fine and the Alpha release gets closed automatically when uploading directly to production.

**Comment by andreyslyusar** [comment]
@capyvara Sorry for long response. I do not have direct access to JSON key, so I cannot fetch track version codes.

**Comment by janpio** [comment]
The PR #10927 is now merged and will be included in the next release.

**Comment by KrauseFx** [comment]
🚀
