### ISSUE TITLE
Unable to upload symbols (macOS High Sierra)

### ISSUE THREAD

**Issue by c-st** [fastlane/fastlane#9840]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I am running Fastlane v2.48 under macOS High Sierra. When attempting to submit my dSYMs to Crashlytics via `upload_symbols_to_crashlytics` it fails:

```
❯ fastlane beta --capture_output
[00:16:45]: For more information, check out https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2017-07-25 00:16:48.27]: Checking if there are any plugins that should be loaded...
INFO [2017-07-25 00:16:48.40]: -------------------------------------------------
INFO [2017-07-25 00:16:48.40]: --- Step: Verifying required fastlane version ---
INFO [2017-07-25 00:16:48.40]: -------------------------------------------------
INFO [2017-07-25 00:16:48.40]: Your fastlane version 2.48.0 matches the minimum requirement of 2.48  ✅
INFO [2017-07-25 00:16:48.41]: ------------------------------
INFO [2017-07-25 00:16:48.41]: --- Step: default_platform ---
INFO [2017-07-25 00:16:48.41]: ------------------------------
INFO [2017-07-25 00:16:48.41]: Driving the lane 'ios beta' 🚀
INFO [2017-07-25 00:16:48.41]: -------------------------------------------
INFO [2017-07-25 00:16:48.41]: --- Step: upload_symbols_to_crashlytics ---
INFO [2017-07-25 00:16:48.41]: -------------------------------------------
INFO [2017-07-25 00:16:48.57]: Extracting '/Users/chris/Development/TheApp/TheApp/TheApp .app.dSYM.zip'...
INFO [2017-07-25 00:16:48.57]: $ unzip -qo /Users/chris/Development/TheApp/TheApp/TheApp .app.dSYM.zip
INFO [2017-07-25 00:16:49.37]: Uploading 'RealmSwift.framework.dSYM'...
ERROR [2017-07-25 00:16:49.42]: Shell command exited with exit status 8 instead of 0.
INFO [2017-07-25 00:16:49.42]: Uploading '34DB257B-AC09-337D-8211-B3AD89434965.dSYM'...
INFO [2017-07-25 00:16:49.44]: Uploading 'TheApp App.app.dSYM'...
ERROR [2017-07-25 00:16:49.47]: Shell command exited with exit status 8 instead of 0.
INFO [2017-07-25 00:16:49.47]: Uploading 'A9390D36-9311-3B62-ADE3-CE5114A4E81B.dSYM'...
INFO [2017-07-25 00:16:49.49]: Uploading 'Realm.framework.dSYM'...
ERROR [2017-07-25 00:16:49.52]: Shell command exited with exit status 8 instead of 0.
INFO [2017-07-25 00:16:49.52]: Uploading 'RxRealm.framework.dSYM'...
ERROR [2017-07-25 00:16:49.55]: Shell command exited with exit status 8 instead of 0.
INFO [2017-07-25 00:16:49.55]: Uploading 'BCF641D7-95C1-39E1-A365-9B42228DD9E6.dSYM'...
ERROR [2017-07-25 00:16:49.57]: Shell command exited with exit status 8 instead of 0.
INFO [2017-07-25 00:16:49.57]: Uploading '2B21C48D-EDA1-32FC-B9E4-B72656D1CF37.dSYM'...
INFO [2017-07-25 00:16:49.59]: Uploading 'C34DEC2C-8460-389D-986C-A12BE222F1A8.dSYM'...
ERROR [2017-07-25 00:16:49.62]: Shell command exited with exit status 8 instead of 0.
INFO [2017-07-25 00:16:49.62]: Uploading 'F5181BD7-0514-3AC4-8686-C001063C6916.dSYM'...
INFO [2017-07-25 00:16:49.64]: Uploading '92CE0534-D3D2-3583-8C1B-791135BF7E30.dSYM'...
INFO [2017-07-25 00:16:49.66]: Uploading '02008136-312A-324B-8C51-761246106355.dSYM'...
INFO [2017-07-25 00:16:49.68]: Uploading '7D2E62B7-41C3-37C5-AF59-A5C3883CC591.dSYM'...
ERROR [2017-07-25 00:16:49.71]: Shell command exited with exit status 8 instead of 0.
INFO [2017-07-25 00:16:49.71]: Uploading 'E013AC6D-E8BB-38C0-A1E6-E17BF5213D96.dSYM'...
ERROR [2017-07-25 00:16:49.73]: Shell command exited with exit status 8 instead of 0.
INFO [2017-07-25 00:16:49.73]: Uploading 'RxCocoa.framework.dSYM'...
ERROR [2017-07-25 00:16:49.76]: Shell command exited with exit status 8 instead of 0.
INFO [2017-07-25 00:16:49.76]: Uploading 'AC2370A2-4DF8-33C3-A895-E337874866CF.dSYM'...
INFO [2017-07-25 00:16:49.78]: Uploading 'Result.framework.dSYM'...
ERROR [2017-07-25 00:16:49.81]: Shell command exited with exit status 8 instead of 0.
INFO [2017-07-25 00:16:49.81]: Uploading 'RxSwift.framework.dSYM'...
ERROR [2017-07-25 00:16:49.84]: Shell command exited with exit status 8 instead of 0.
INFO [2017-07-25 00:16:49.84]: Uploading '7709165A-CC16-3C9E-B346-793510D5230A.dSYM'...
ERROR [2017-07-25 00:16:49.86]: Shell command exited with exit status 8 instead of 0.
INFO [2017-07-25 00:16:49.86]: Uploading '77C4C26D-11AB-3C22-9DB4-B9D03E949C42.dSYM'...
INFO [2017-07-25 00:16:49.88]: Uploading '3F25E349-8B21-3DB2-8A90-8E863EEB0667.dSYM'...
INFO [2017-07-25 00:16:49.90]: Uploading 'BE89E2F8-3546-34C8-9773-2FA22C47A7B8.dSYM'...
INFO [2017-07-25 00:16:49.92]: Uploading '0C8F8B1B-BFE5-30A2-A0EA-2ED0A0218418.dSYM'...
ERROR [2017-07-25 00:16:49.95]: Shell command exited with exit status 8 instead of 0.
INFO [2017-07-25 00:16:49.95]: Uploading 'RxAlamofire.framework.dSYM'...
ERROR [2017-07-25 00:16:49.98]: Shell command exited with exit status 8 instead of 0.
INFO [2017-07-25 00:16:49.98]: Uploading '606EC5F9-0045-3D87-8D2C-EC16E8F2A3F3.dSYM'...
ERROR [2017-07-25 00:16:50.00]: Shell command exited with exit status 8 instead of 0.
INFO [2017-07-25 00:16:50.00]: Uploading '63645414-13D9-36AE-B3E8-FD97F00455BA.dSYM'...
ERROR [2017-07-25 00:16:50.03]: Shell command exited with exit status 8 instead of 0.
INFO [2017-07-25 00:16:50.03]: Uploading 'Alamofire.framework.dSYM'...
ERROR [2017-07-25 00:16:50.06]: Shell command exited with exit status 8 instead of 0.
INFO [2017-07-25 00:16:50.06]: Uploading '1D54EDA7-BFAC-3DE9-AE8D-57AAB3A410B9.dSYM'...
INFO [2017-07-25 00:16:50.08]: Uploading '69195E75-4280-326F-9B03-91DE00C344CE.dSYM'...
ERROR [2017-07-25 00:16:50.11]: Shell command exited with exit status 8 instead of 0.
INFO [2017-07-25 00:16:50.17]: Successfully uploaded dSYM files to Crashlytics 💯
INFO [2017-07-25 00:16:50.17]: Successfully generated documentation at path '/Users/chris/Development/TheApp/TheApp/fastlane/README.md'
INFO [2017-07-25 00:16:50.18]: fastlane.tools finished successfully 🎉
WARN [2017-07-25 00:16:50.20]: Generating fastlane environment output, this might take a few seconds...
DEBUG [2017-07-25 00:16:50.61]: Checking if there are any plugins that should be loaded...
```

When running `upload-symbols` directly I am getting the following error message:
```
❯ ./Pods/Fabric/upload-symbols -a xxxx -p ios /Users/chris/Development/TheApp/TheApp/The App.app.dSYM.zip
error: could not complete submission of dSYM at /var/folders/by/3r67nxd94rl9ynq051t7f9t40000gp/T///Users/chris/Development/TheApp/TheApp/The App.app.dSYM.zip.unzipped/RealmSwift.framework.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
```

Any help would be appreciated.

### Captured Output

Command Used: `beta`
<details><summary>Output/Log</summary>

```


+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | Verifying required     | 0           |
|      | fastlane version       |             |
| 2    | default_platform       | 0           |
| 3    | upload_symbols_to_cra  | 1           |
|      | shlytics               |             |
+------+------------------------+-------------+



```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.13                                            |
| Ruby                        | 2.2.4                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.13.3                               |
| Installation Source         | /usr/local/lib/fastlane_lib/bundle/bin/fastlane  |
| Host                        | Mac OS X 10.13 (17A315i)                         |
| Ruby Lib Dir                | /usr/local/lib/fastlane_lib/bundle/lib           |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                       |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | true                                             |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/ |
| Xcode Version               | 9.0                                              |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.48"

default_platform :ios

platform :ios do
  lane :beta do |values|
    gym(scheme: 'The App', export_method: 'development')
    upload_symbols_to_crashlytics
  end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.48.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.2       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.3       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-07-25**
</details>

**Comment by mpirri** [comment]
This problem seems to be tied to the dSYM for RealmSwift - it appears that all other dSYMs were able to be uploaded properly.

Was the RealmSwift.framework built with Xcode 9 or a different version? I.e., are you using the open-sourced version of RealmSwift or a pre-built version?

Thanks for writing in! 🚀

**Comment by c-st** [comment]
Thanks for looking into it. 

I'm using the CocoaPods version of RealmSwift, so it's compiled from source for Xcode 9. 
Why do think the issue is only related to RealmSwift? The output of the single `upload-symbols` call was only an example. I get this error for every other dSYM. 

I just upgraded to fastlane 2.49.0. The issue still remains.

```
[20:59:49]: Uploading 'RealmSwift.framework.dSYM'...
[20:59:49]: Shell command exited with exit status 8 instead of 0.
[20:59:49]: Uploading '34DB257B-AC09-337D-8211-B3AD89434965.dSYM'...
[20:59:49]: Uploading 'The App.app.dSYM'...
[20:59:50]: Shell command exited with exit status 8 instead of 0.
[20:59:50]: Uploading 'A9390D36-9311-3B62-ADE3-CE5114A4E81B.dSYM'...
[20:59:50]: Uploading 'Realm.framework.dSYM'...
[20:59:50]: Shell command exited with exit status 8 instead of 0.
[20:59:50]: Uploading 'RxRealm.framework.dSYM'...
[20:59:50]: Shell command exited with exit status 8 instead of 0.
[20:59:50]: Uploading 'BCF641D7-95C1-39E1-A365-9B42228DD9E6.dSYM'...
[20:59:50]: Shell command exited with exit status 8 instead of 0.
[20:59:50]: Uploading '2B21C48D-EDA1-32FC-B9E4-B72656D1CF37.dSYM'...
[20:59:50]: Uploading 'C34DEC2C-8460-389D-986C-A12BE222F1A8.dSYM'...
[20:59:50]: Shell command exited with exit status 8 instead of 0.
[20:59:50]: Uploading 'F5181BD7-0514-3AC4-8686-C001063C6916.dSYM'...
[20:59:50]: Uploading '92CE0534-D3D2-3583-8C1B-791135BF7E30.dSYM'...
[20:59:50]: Uploading '02008136-312A-324B-8C51-761246106355.dSYM'...
[20:59:50]: Uploading '7D2E62B7-41C3-37C5-AF59-A5C3883CC591.dSYM'...
[20:59:50]: Shell command exited with exit status 8 instead of 0.
[20:59:50]: Uploading 'E013AC6D-E8BB-38C0-A1E6-E17BF5213D96.dSYM'...
[20:59:50]: Shell command exited with exit status 8 instead of 0.
[20:59:50]: Uploading 'RxCocoa.framework.dSYM'...
[20:59:50]: Shell command exited with exit status 8 instead of 0.
[20:59:50]: Uploading 'AC2370A2-4DF8-33C3-A895-E337874866CF.dSYM'...
[20:59:50]: Uploading 'C3ED3924-3362-3C6B-B573-6669EDFFDD56.dSYM'...
[20:59:50]: Uploading 'Result.framework.dSYM'...
[20:59:50]: Shell command exited with exit status 8 instead of 0.
[20:59:50]: Uploading 'RxSwift.framework.dSYM'...
[20:59:50]: Shell command exited with exit status 8 instead of 0.
[20:59:50]: Uploading 'B9A39A7F-CA6C-3898-A750-CC62EFAFEA8F.dSYM'...
[20:59:50]: Uploading '7709165A-CC16-3C9E-B346-793510D5230A.dSYM'...
[20:59:50]: Shell command exited with exit status 8 instead of 0.
[20:59:50]: Uploading '77C4C26D-11AB-3C22-9DB4-B9D03E949C42.dSYM'...
[20:59:50]: Uploading '3F25E349-8B21-3DB2-8A90-8E863EEB0667.dSYM'...
[20:59:50]: Uploading '597034BA-764F-34D3-B3A4-5401B67AFA91.dSYM'...
[20:59:50]: Shell command exited with exit status 8 instead of 0.
[20:59:50]: Uploading '9501F1A8-4516-3321-A120-32971444B705.dSYM'...
[20:59:50]: Shell command exited with exit status 8 instead of 0.
[20:59:50]: Uploading 'BE89E2F8-3546-34C8-9773-2FA22C47A7B8.dSYM'...
[20:59:50]: Uploading '0C8F8B1B-BFE5-30A2-A0EA-2ED0A0218418.dSYM'...
[20:59:50]: Shell command exited with exit status 8 instead of 0.
[20:59:50]: Uploading 'RxAlamofire.framework.dSYM'...
[20:59:50]: Shell command exited with exit status 8 instead of 0.
[20:59:50]: Uploading '606EC5F9-0045-3D87-8D2C-EC16E8F2A3F3.dSYM'...
[20:59:50]: Shell command exited with exit status 8 instead of 0.
[20:59:50]: Uploading '63645414-13D9-36AE-B3E8-FD97F00455BA.dSYM'...
[20:59:50]: Shell command exited with exit status 8 instead of 0.
[20:59:50]: Uploading '394B255C-464E-375F-B7B9-FDE01726DDB2.dSYM'...
[20:59:50]: Shell command exited with exit status 8 instead of 0.
[20:59:50]: Uploading 'Alamofire.framework.dSYM'...
[20:59:50]: Shell command exited with exit status 8 instead of 0.
[20:59:50]: Uploading '1D54EDA7-BFAC-3DE9-AE8D-57AAB3A410B9.dSYM'...
[20:59:50]: Uploading '69195E75-4280-326F-9B03-91DE00C344CE.dSYM'...
[20:59:50]: Shell command exited with exit status 8 instead of 0.
[20:59:50]: Successfully uploaded dSYM files to Crashlytics 💯
```

**Comment by mpirri** [comment]
Ah, sorry for the confusion! 🐙 

Does it seem like this could be an issue with `upload-symbols` itself?  I mean, for sure, _fastlane_ shouldn't be saying everything is 💯 when all those exist status 8's came back. Do you still have the original Crashlytics run script build phase for your project? What happens if you invoke that directly?

**Comment by c-st** [comment]
No worries 😃 

I agree regarding error reporting. This error should fail the build step.

I always used Fabric to integrate Crashlytics into my project so I don't have that script. However I believe that it's executing `upload-symbols` with the extracted dSYMs. When I attempt to do that manually I get the following errors:

`➜  ~/D/C/AppName (master) ✗ find ./dSYM -name "*.dSYM" | xargs -I \{\} ./Pods/Fabric/upload-symbols -a api-key -p ios \{\}`

```
error: could not complete submission of dSYM at ./dSYM/RealmSwift.framework.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
warning: skipping Apple dSYM: ./dSYM/34DB257B-AC09-337D-8211-B3AD89434965.dSYM
error: could not complete submission of dSYM at ./dSYM/AppName App.app.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
warning: skipping Apple dSYM: ./dSYM/A9390D36-9311-3B62-ADE3-CE5114A4E81B.dSYM
error: could not complete submission of dSYM at ./dSYM/Realm.framework.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
error: could not complete submission of dSYM at ./dSYM/F4DDB802-AC29-3A71-8FA3-1B7C76F83B2B.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
error: could not complete submission of dSYM at ./dSYM/RxRealm.framework.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
error: could not complete submission of dSYM at ./dSYM/BCF641D7-95C1-39E1-A365-9B42228DD9E6.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
warning: skipping Apple dSYM: ./dSYM/2B21C48D-EDA1-32FC-B9E4-B72656D1CF37.dSYM
error: could not complete submission of dSYM at ./dSYM/C34DEC2C-8460-389D-986C-A12BE222F1A8.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
warning: skipping Apple dSYM: ./dSYM/F5181BD7-0514-3AC4-8686-C001063C6916.dSYM
warning: skipping Apple dSYM: ./dSYM/92CE0534-D3D2-3583-8C1B-791135BF7E30.dSYM
warning: skipping Apple dSYM: ./dSYM/02008136-312A-324B-8C51-761246106355.dSYM
error: could not complete submission of dSYM at ./dSYM/7D2E62B7-41C3-37C5-AF59-A5C3883CC591.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
error: could not complete submission of dSYM at ./dSYM/E013AC6D-E8BB-38C0-A1E6-E17BF5213D96.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
error: could not complete submission of dSYM at ./dSYM/RxCocoa.framework.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
warning: skipping Apple dSYM: ./dSYM/AC2370A2-4DF8-33C3-A895-E337874866CF.dSYM
warning: skipping Apple dSYM: ./dSYM/C3ED3924-3362-3C6B-B573-6669EDFFDD56.dSYM
error: could not complete submission of dSYM at ./dSYM/Result.framework.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
error: could not complete submission of dSYM at ./dSYM/RxSwift.framework.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
warning: skipping Apple dSYM: ./dSYM/B9A39A7F-CA6C-3898-A750-CC62EFAFEA8F.dSYM
error: could not complete submission of dSYM at ./dSYM/7709165A-CC16-3C9E-B346-793510D5230A.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
warning: skipping Apple dSYM: ./dSYM/77C4C26D-11AB-3C22-9DB4-B9D03E949C42.dSYM
warning: skipping Apple dSYM: ./dSYM/3F25E349-8B21-3DB2-8A90-8E863EEB0667.dSYM
error: could not complete submission of dSYM at ./dSYM/597034BA-764F-34D3-B3A4-5401B67AFA91.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
error: could not complete submission of dSYM at ./dSYM/CA7FF707-F71B-3CFB-859F-204A47DB9E15.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
error: could not complete submission of dSYM at ./dSYM/9501F1A8-4516-3321-A120-32971444B705.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
warning: skipping Apple dSYM: ./dSYM/BE89E2F8-3546-34C8-9773-2FA22C47A7B8.dSYM
error: could not complete submission of dSYM at ./dSYM/0C8F8B1B-BFE5-30A2-A0EA-2ED0A0218418.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
error: could not complete submission of dSYM at ./dSYM/RxAlamofire.framework.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
error: could not complete submission of dSYM at ./dSYM/606EC5F9-0045-3D87-8D2C-EC16E8F2A3F3.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
error: could not complete submission of dSYM at ./dSYM/63645414-13D9-36AE-B3E8-FD97F00455BA.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
error: could not complete submission of dSYM at ./dSYM/394B255C-464E-375F-B7B9-FDE01726DDB2.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
error: could not complete submission of dSYM at ./dSYM/Alamofire.framework.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
warning: skipping Apple dSYM: ./dSYM/1D54EDA7-BFAC-3DE9-AE8D-57AAB3A410B9.dSYM
error: could not complete submission of dSYM at ./dSYM/3C4A2F26-7E4E-3BC6-9496-5C553ABFD8DA.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
error: could not complete submission of dSYM at ./dSYM/69195E75-4280-326F-9B03-91DE00C344CE.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
```

To me it looks like an incompability between macOS High Sierra and the `upload-symbols` binary. Do you know if I can find the source of `upload-symbols` somewhere? Can anyone reproduce this with High Sierra?

**Comment by taquitos** [comment]
@c-st yeah, that's a known issue right now with FabricBase, we'll need to release a new version that supports macOS High Sierra.

**Comment by edmonston** [comment]
@taquitos do i see that support for High Sierra was added earlier this month in 1.6.13? I am unable to upload dsym with the same errors that this person is having

**Comment by taquitos** [comment]
@edmonston, could you confirm you are using the latest Fabric frameworks?

**Comment by edmonston** [comment]
hey @taquitos thanks for your reply, i am using version 1.6.13 of the Fabric pod which I believe is the latest. However, it looks like `upload_symbols_to_crashlytics.rb` first checks for a binary in the Applications folder, and although I just grabbed the latest Mac OS app, it seems to have a different version of upload-symbols (see below). Is there something I can do to get more diagnostics?

```
> cd Pods/Fabric/
> ./upload-symbols --v
upload-symbols 1.2.2 build 8
> cd /Applications/Fabric.app/Contents/MacOS/
> ./upload-symbols -v
upload-symbols Optional("1.2.1") build Optional("7")
```

**Comment by taquitos** [comment]
Really great sleuthing there. I've passed the info along and they are taking a look. Thank you!

**Comment by taquitos** [comment]
Alright, this should be fixed @edmonston. We just released a new version of the app with the updated binary.

**Comment by edmonston** [comment]
Wow that was fast! 

Unfortunately... I still get the same errors when running `upload_symbols_to_crashlytics` as part of a fastlane script on my local machine. (Unlike before, the version of `upload-symbols` in both locations, Applications and Pods, now seems to be 1.2.2 build 8, which is good.)

Probably unrelated, but I do see other errors:

```
[16:49:34]: -------------------------------------------
[16:49:34]: --- Step: upload_symbols_to_crashlytics ---
[16:49:34]: -------------------------------------------
[16:49:34]: invalid byte sequence in UTF-8
[16:49:34]: Unable to find plist file at '/<redacted>/Pods/Crashlytics/iOS/Crashlytics.framework/Info.plist'
[16:49:34]: invalid byte sequence in UTF-8
[16:49:34]: Unable to find plist file at '<redacted>/Pods/Fabric/iOS/Fabric.framework/Info.plist'
[16:49:34]: invalid byte sequence in UTF-8
[...]
```

The script seems to be looking for a plist as part of `find_api_token`, but I believe it succeeds because I do not see the error `Please provide an api_token using api_token`

In the end, I still just get a big list of errors like this:

```
[16:49:38]: Shell command exited with exit status 3 instead of 0.
[16:49:38]: Uploading '04360A21-6166-3625-A4F0-A676B420E66A.dSYM'...
[16:49:38]: Shell command exited with exit status 3 instead of 0.
[16:49:38]: Uploading '043820E2-4369-373F-8BA9-994E6D24D439.dSYM'...
[16:49:38]: Shell command exited with exit status 3 instead of 0.
[16:49:38]: Uploading '04FD7742-B9DB-3E6D-AC33-F83E9DF498E2.dSYM'...
[16:49:38]: Shell command exited with exit status 3 instead of 0.
[16:49:38]: Uploading '05F2ADF4-7447-3261-9D5A-9EC4BA45DC60.dSYM'...
```

**Comment by taquitos** [comment]
Yeah, exist status indicates invalid API code, so I bet fastlane is providing just `" "` for an `api_token`

One thing you could do in the mean time, you can add your `crashlytics api token` by passing it with the `api_token` param to the `upload_symbols_to_crashlytics` action

Also, instead of continuing in this issue, it would be great if you could open a new _fastlane_ issue with this information, along with the info that the new issue template provides. I think we should be able to repro after that.

**Comment by RomanVolkov** [comment]
@taquitos where I can get api_token now in case Crashlytics is a part of Firebase now?

**Comment by aminbenarieb** [comment]
Still getting `shell command exited with exit status 8 instead of 0.` on `upload_symbols_to_crashlytics`. OS: `macOS 10.13.2 (17C88)`
```
### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.78.0  | ✅ Up-To-Date  |
```

**Comment by aminbenarieb** [comment]
hey @taquitos, i've done the same thing that @edmonston did in checking upload-symbols versions. Here what i got:
```
$ ./Pods/Fabric/upload-symbols -v
upload-symbols 1.2.1 build 7
$ /Applications/Fabric.app/Contents/MacOS/upload-symbols -v
upload-symbols 1.5.0 build 11
```
Then i updated my Fabric pod (to `Fabric 1.6.13`) and now upload-symbols version is  `1.2.2 build 8`.

**Comment by aminbenarieb** [comment]
Updating Fabric pod fixes the issue in my case 🎉.

**Comment by RomanVolkov** [comment]
Temporary I'm using this commands to upload symbols. Previously dSYMs are downloaded via fastlane, then this.
```
/Users/romanvolkov/Coding/project/Pods/Fabric/upload-symbols -gsp /Users/romanvolkov/Coding/project/Rolls-Royce\ Whispers/GoogleService-Info.plist -p ios .
rm /Users/romanvolkov/Coding/project/*.dSYM.zip
```
